export default [
  {"id":1,"text":"🍥🦊👦","options":["Bleach","Naruto","One Piece","Dragon Ball"],"correct":1,"hint":"Hidden Leaf ninja","level":1},
  {"id":2,"text":"🏴‍☠️🍖👒","options":["One Piece","Fairy Tail","Black Clover","Bleach"],"correct":0,"hint":"Pirate King dream","level":1},
  {"id":3,"text":"🐉💥🟠","options":["Jujutsu Kaisen","Dragon Ball","Demon Slayer","Attack on Titan"],"correct":1,"hint":"Saiyan warrior","level":1},
  {"id":4,"text":"👹⚔️🎴","options":["Bleach","Demon Slayer","Naruto","Tokyo Ghoul"],"correct":1,"hint":"Breathing styles","level":1},
  {"id":5,"text":"👒⚓🌊","options":["One Piece","Blue Lock","Haikyuu","Black Clover"],"correct":0,"hint":"Grand Line adventure","level":1},
  {"id":6,"text":"⚔️👻🧡","options":["Bleach","Naruto","Death Note","Chainsaw Man"],"correct":0,"hint":"Soul Reapers","level":1},
  {"id":7,"text":"📓🍎💀","options":["Tokyo Ghoul","Death Note","Parasyte","Another"],"correct":1,"hint":"Shinigami notebook","level":1},
  {"id":8,"text":"🏐🧡🖤","options":["Slam Dunk","Blue Lock","Haikyuu","Kuroko no Basket"],"correct":2,"hint":"Volleyball anime","level":1},
  {"id":9,"text":"⚽🔵🔥","options":["Blue Lock","Inazuma Eleven","Captain Tsubasa","Ao Ashi"],"correct":0,"hint":"Ego striker project","level":1},
  {"id":10,"text":"🧹🪄⚫","options":["Black Clover","Mashle","Fairy Tail","Hunter x Hunter"],"correct":1,"hint":"Muscles in magic world","level":1},
  {"id":51,"text":"⚡🍜🟡","options":["One Punch Man","Naruto","Mob Psycho 100","Dragon Ball"],"correct":1,"hint":"Loves ramen","level":1},
  {"id":52,"text":"👊🦸🧑‍🦲","options":["One Punch Man","My Hero Academia","Tiger & Bunny","Mob Psycho 100"],"correct":0,"hint":"Bald hero","level":1},
  {"id":53,"text":"🦸💥🏫","options":["Fire Force","Blue Exorcist","My Hero Academia","Soul Eater"],"correct":2,"hint":"UA High School","level":1},
  {"id":54,"text":"🐉👆🔥","options":["Fairy Tail","Black Clover","Seven Deadly Sins","Magi"],"correct":0,"hint":"Guild wizards","level":1},
  {"id":55,"text":"🍖⚔️🐗","options":["Vinland Saga","Demon Slayer","Dororo","Berserk"],"correct":1,"hint":"Beast breathing","level":1},
  {"id":56,"text":"🐈📦😺","options":["The Cat Returns","Doraemon","Chi's Sweet Home","My Neighbor Totoro"],"correct":1,"hint":"Robotic cat","level":1},
  {"id":57,"text":"👹🔥👶","options":["Blue Exorcist","Beelzebub","Nurarihyon no Mago","Devilman Crybaby"],"correct":1,"hint":"Demon baby","level":1},
  {"id":58,"text":"🏀🟥🟦","options":["Slam Dunk","Kuroko no Basket","Ahiru no Sora","Blue Lock"],"correct":1,"hint":"Phantom sixth man","level":1},
  {"id":59,"text":"🧛🩸🔫","options":["Hellsing","Vampire Knight","Seraph of the End","Trinity Blood"],"correct":0,"hint":"Alucard","level":1},
  {"id":60,"text":"🐯🐉🏫","options":["Toradora","Clannad","Horimiya","Golden Time"],"correct":0,"hint":"Tiger-like tsundere","level":1},
  {"id":101,"text":"🍙⚔️👹","options":["Inuyasha","Naruto","Demon Slayer","Bleach"],"correct":0,"hint":"Feudal Japan demon","level":1},
  {"id":102,"text":"🧙‍♂️🔥🐉","options":["Fairy Tail","Black Clover","Magi","Blue Exorcist"],"correct":0,"hint":"Fire Dragon Slayer","level":1},
  {"id":103,"text":"👊💯👻","options":["Mob Psycho 100","One Punch Man","Bleach","Noragami"],"correct":0,"hint":"Psychic explosion","level":1},
  {"id":104,"text":"⚔️🧛🌹","options":["Vampire Knight","Hellsing","Seraph of the End","Trinity Blood"],"correct":0,"hint":"Vampire school","level":1},
  {"id":105,"text":"🐲⚔️7️⃣","options":["Seven Deadly Sins","Fairy Tail","Black Clover","Dragon Ball"],"correct":0,"hint":"Meliodas","level":1},
  {"id":106,"text":"🎤⭐👶","options":["Oshi no Ko","Love Live!","Idolmaster","Zombieland Saga"],"correct":0,"hint":"Idol twins","level":1},
  {"id":107,"text":"👨‍🍳🍞😋","options":["Food Wars","Yakitate!! Japan","Toriko","Campfire Cooking"],"correct":0,"hint":"Cooking battles","level":1},
  {"id":108,"text":"🏫❤️📚","options":["Horimiya","Kaguya-sama","Toradora","Clannad"],"correct":1,"hint":"Love is war","level":1},
  {"id":109,"text":"🐺👧🌧️","options":["Wolf Children","Spice and Wolf","Princess Mononoke","Beastars"],"correct":0,"hint":"Half-wolf siblings","level":1},
  {"id":110,"text":"🏀🔥👓","options":["Slam Dunk","Ahiru no Sora","Kuroko no Basket","Blue Lock"],"correct":0,"hint":"Red-haired delinquent","level":1},
  {"id":151,"text":"🐱🚌🌳","options":["Kiki's Delivery Service","Spirited Away","My Neighbor Totoro","The Cat Returns"],"correct":2,"hint":"Giant forest spirit","level":1},
  {"id":152,"text":"🧹🐈‍⬛🍞","options":["Little Witch Academia","Kiki's Delivery Service","Flying Witch","Mary and the Witch's Flower"],"correct":1,"hint":"Young delivery witch","level":1},
  {"id":153,"text":"🚂👻🏯","options":["Spirited Away","Howl's Moving Castle","Princess Mononoke","Ponyo"],"correct":0,"hint":"Bathhouse spirits","level":1},
  {"id":154,"text":"🐟👧🌊","options":["Children of the Sea","Ponyo","Lu Over the Wall","Ride Your Wave"],"correct":1,"hint":"Goldfish girl","level":1},
  {"id":155,"text":"⚔️👑🦁","options":["Black Clover","Magi","The Seven Deadly Sins","Arslan Senki"],"correct":1,"hint":"Djinn powers","level":1},
  {"id":156,"text":"👦⚡🐈","options":["Blue Exorcist","Pokémon","Digimon","Beyblade"],"correct":1,"hint":"Electric mouse","level":1},
  {"id":157,"text":"🌀🧿🥷","options":["Naruto","Jujutsu Kaisen","Bleach","Basilisk"],"correct":0,"hint":"Sharingan rivalry","level":1},
  {"id":158,"text":"👧📚✨","options":["Cardcaptor Sakura","Sailor Moon","Madoka Magica","Tokyo Mew Mew"],"correct":0,"hint":"Clow Cards","level":1},
  {"id":159,"text":"🌙👭✨","options":["Pretty Cure","Sailor Moon","Wedding Peach","Magic Knight Rayearth"],"correct":1,"hint":"Moon prism power","level":1},
  {"id":160,"text":"🚗💨⛰️","options":["Initial D","Wangan Midnight","Capeta","Redline"],"correct":0,"hint":"Tofu delivery racer","level":1},
  {"id":201,"text":"🧽⭐🌊","options":["SpongeBob SquarePants","Ponyo","Bubblegum Crisis","Mermaid Melody"],"correct":1,"hint":"Ocean magic girl","level":1},
  {"id":202,"text":"🧑‍🚀🌍🚀","options":["Dr. Stone","Astra Lost in Space","Space Brothers","Edens Zero"],"correct":1,"hint":"Lost in space","level":1},
  {"id":203,"text":"👧🎸😶","options":["K-On!","Nana","Bocchi the Rock!","Beck"],"correct":2,"hint":"Social anxiety guitarist","level":1},
  {"id":204,"text":"⚔️🐉👑","options":["Record of Lodoss War","Fairy Tail","Dragon Quest: Dai","Slayers"],"correct":2,"hint":"Hero from Dragon Quest","level":1},
  {"id":205,"text":"👦🐉💫","options":["Beyblade","Digimon","Bakugan","Yu-Gi-Oh!"],"correct":0,"hint":"Let it rip","level":1},
  {"id":206,"text":"👓📔❤️","options":["Horimiya","My Little Monster","Komi Can't Communicate","Toradora"],"correct":2,"hint":"Communication disorder","level":1},
  {"id":207,"text":"🧹🏫✨","options":["Little Witch Academia","Kiki's Delivery Service","Cardcaptor Sakura","Flying Witch"],"correct":0,"hint":"Magic academy","level":1},
  {"id":208,"text":"⚽🦅🔥","options":["Blue Lock","Captain Tsubasa","Ao Ashi","Inazuma Eleven"],"correct":2,"hint":"Football tactics anime","level":1},
  {"id":209,"text":"🐈🍜😺","options":["Nyan Koi!","The Masterful Cat Is Depressed Again Today","Chi's Sweet Home","Bananya"],"correct":1,"hint":"Giant smart cat","level":1},
  {"id":210,"text":"🛸👽😂","options":["Gintama","Space Dandy","Urusei Yatsura","Dandadan"],"correct":0,"hint":"Alien comedy samurai","level":1},
];
