export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/2/284121.jpg", options: ["Naruto Uzumaki", "Goku", "Luffy", "Ichigo"], correct: 0, hint: "Believes in becoming Hokage", level: 1 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/5/309397.jpg", options: ["Tanjiro Kamado", "Zenitsu", "Inosuke", "Giyu"], correct: 0, hint: "Water breathing demon slayer", level: 1 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/9/72533.jpg", options: ["Edward Elric", "Alphonse Elric", "Roy Mustang", "Scar"], correct: 0, hint: "Fullmetal Alchemist", level: 1 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/7/284129.jpg", options: ["Sasuke Uchiha", "Naruto Uzumaki", "Kakashi Hatake", "Itachi Uchiha"], correct: 0, hint: "Avenger of the Uchiha clan", level: 1 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/9/310307.jpg", options: ["Goku", "Vegeta", "Gohan", "Trunks"], correct: 0, hint: "Super Saiyan from Planet Vegeta", level: 1 },
  { id: 6, image: "https://cdn.myanimelist.net/images/characters/11/294389.jpg", options: ["Saitama", "Genos", "King", "Mumen Rider"], correct: 0, hint: "One punch is all he needs", level: 1 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/6/240275.jpg", options: ["Levi Ackerman", "Eren Yeager", "Mikasa Ackerman", "Erwin Smith"], correct: 0, hint: "Humanity's strongest soldier", level: 1 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/15/422168.jpg", options: ["Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "All Might"], correct: 0, hint: "Inheritor of One For All", level: 1 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/2/60801.jpg", options: ["Monkey D. Luffy", "Roronoa Zoro", "Sanji", "Ace"], correct: 0, hint: "Rubber pirate with a straw hat", level: 1 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/10/216895.jpg", options: ["Light Yagami", "L Lawliet", "Misa Amane", "Near"], correct: 0, hint: "Notebook of death owner", level: 1 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/8/222105.jpg", options: ["Roronoa Zoro", "Monkey D. Luffy", "Shanks", "Mihawk"], correct: 0, hint: "Three sword style master", level: 1 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/13/251027.jpg", options: ["Eren Yeager", "Levi Ackerman", "Armin Arlert", "Reiner Braun"], correct: 0, hint: "Freedom-seeking titan shifter", level: 1 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/2/81607.jpg", options: ["Natsu Dragneel", "Gray Fullbuster", "Erza Scarlet", "Lucy Heartfilia"], correct: 0, hint: "Fire dragon slayer wizard", level: 1 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/15/384228.jpg", options: ["Satoru Gojo", "Yuji Itadori", "Megumi Fushiguro", "Sukuna"], correct: 0, hint: "Strongest modern sorcerer", level: 1 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/7/204821.jpg", options: ["Killua Zoldyck", "Gon Freecss", "Hisoka", "Kurapika"], correct: 0, hint: "Assassin kid with lightning", level: 1 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/11/174517.jpg", options: ["Vegeta", "Goku", "Broly", "Frieza"], correct: 0, hint: "Prince of all Saiyans", level: 1 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/2/80755.jpg", options: ["Kakashi Hatake", "Naruto Uzumaki", "Obito Uchiha", "Minato Namikaze"], correct: 0, hint: "Copy ninja with one Sharingan", level: 1 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/9/226647.jpg", options: ["Ichigo Kurosaki", "Rukia Kuchiki", "Uryu Ishida", "Renji Abarai"], correct: 0, hint: "Substitute Soul Reaper", level: 1 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/3/369837.jpg", options: ["Nezuko Kamado", "Tanjiro Kamado", "Shinobu Kocho", "Mitsuri Kanroji"], correct: 0, hint: "Demon sister in a box", level: 1 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/6/350538.jpg", options: ["Katsuki Bakugo", "Izuku Midoriya", "Shoto Todoroki", "Eijiro Kirishima"], correct: 0, hint: "Explosion quirk rival", level: 1 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/16/292185.jpg", options: ["Gon Freecss", "Killua Zoldyck", "Leorio", "Kurapika"], correct: 0, hint: "Kid hunter looking for his dad", level: 1 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/2/362799.jpg", options: ["Shoto Todoroki", "Izuku Midoriya", "Katsuki Bakugo", "Endeavor"], correct: 0, hint: "Half cold half hot quirk", level: 1 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/4/310779.jpg", options: ["Zenitsu Agatsuma", "Tanjiro Kamado", "Inosuke", "Rengoku"], correct: 0, hint: "Thunder breathing coward", level: 1 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/6/349615.jpg", options: ["All Might", "Izuku Midoriya", "Endeavor", "Gran Torino"], correct: 0, hint: "Symbol of Peace hero", level: 1 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/5/54265.jpg", options: ["Sanji", "Luffy", "Zoro", "Usopp"], correct: 0, hint: "Straw Hat cook who only kicks", level: 1 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/3/72459.jpg", options: ["L Lawliet", "Light Yagami", "Near", "Mello"], correct: 0, hint: "Greatest detective hunts Kira", level: 1 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/15/350357.jpg", options: ["Mikasa Ackerman", "Eren Yeager", "Annie Leonhart", "Historia Reiss"], correct: 0, hint: "Devoted soldier with red scarf", level: 1 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/16/264541.jpg", options: ["Genos", "Saitama", "Metal Bat", "Garou"], correct: 0, hint: "Cyborg disciple of the strongest", level: 1 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/4/310781.jpg", options: ["Inosuke Hashibira", "Tanjiro Kamado", "Zenitsu", "Giyu Tomioka"], correct: 0, hint: "Boar mask beast breathing", level: 1 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/9/131317.jpg", options: ["Erza Scarlet", "Lucy Heartfilia", "Natsu Dragneel", "Gray Fullbuster"], correct: 0, hint: "Titania the fairy queen knight", level: 1 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/12/289220.jpg", options: ["Inuyasha", "Sesshomaru", "Miroku", "Koga"], correct: 0, hint: "Half-demon with dog ears", level: 1 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/9/305236.jpg", options: ["Giyu Tomioka", "Tanjiro Kamado", "Rengoku", "Sanemi"], correct: 0, hint: "Water Hashira always calm", level: 1 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/16/299440.jpg", options: ["Asta", "Yuno", "Noelle Silva", "Yami Sukehiro"], correct: 0, hint: "Anti-magic swords, no magic born", level: 1 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/3/324093.jpg", options: ["Yuji Itadori", "Megumi Fushiguro", "Gojo Satoru", "Todo Aoi"], correct: 0, hint: "Vessel of the King of Curses", level: 1 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/7/76378.jpg", options: ["Nami", "Robin", "Vivi", "Hancock"], correct: 0, hint: "Navigator who loves tangerines", level: 1 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/2/82701.jpg", options: ["Tony Tony Chopper", "Luffy", "Usopp", "Brook"], correct: 0, hint: "Tiny reindeer doctor", level: 1 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/16/360930.jpg", options: ["Jiraiya", "Naruto", "Orochimaru", "Tsunade"], correct: 0, hint: "Pervy sage and legendary Sannin", level: 1 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/5/123558.jpg", options: ["Rock Lee", "Naruto", "Might Guy", "Neji Hyuga"], correct: 0, hint: "Green jumpsuit taijutsu master", level: 1 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/3/324069.jpg", options: ["Megumi Fushiguro", "Yuji Itadori", "Gojo Satoru", "Toge Inumaki"], correct: 0, hint: "Ten Shadows technique user", level: 1 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/12/229839.jpg", options: ["Hinata Shoyo", "Kageyama Tobio", "Nishinoya", "Tanaka"], correct: 0, hint: "Short volleyball player who flies", level: 1 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/6/79611.jpg", options: ["Gray Fullbuster", "Natsu Dragneel", "Laxus", "Gajeel"], correct: 0, hint: "Ice-make mage who strips", level: 1 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/4/297550.jpg", options: ["Gaara", "Naruto", "Sasuke", "Rock Lee"], correct: 0, hint: "Sand ninja became Kazekage", level: 1 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/2/82495.jpg", options: ["Usopp", "Luffy", "Sanji", "Franky"], correct: 0, hint: "Long-nose sniper of Straw Hats", level: 1 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/5/279197.jpg", options: ["Hisoka", "Chrollo", "Killua", "Illumi"], correct: 0, hint: "Magician obsessed with fighting", level: 1 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/5/348643.jpg", options: ["Kyojuro Rengoku", "Tanjiro", "Giyu Tomioka", "Tengen Uzui"], correct: 0, hint: "Flame Hashira set heart ablaze", level: 1 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/16/335986.jpg", options: ["Sakura Haruno", "Hinata Hyuga", "Ino Yamanaka", "Tsunade"], correct: 0, hint: "Medical ninja with super strength", level: 1 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/8/88745.jpg", options: ["Nico Robin", "Nami", "Vivi", "Hancock"], correct: 0, hint: "Archaeologist who reads Poneglyphs", level: 1 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/2/226971.jpg", options: ["Kuroko Tetsuya", "Kagami Taiga", "Kise", "Aomine"], correct: 0, hint: "Phantom sixth man of basketball", level: 1 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/11/232611.jpg", options: ["Kaneki Ken", "Touka", "Hide", "Tsukiyama"], correct: 0, hint: "Half-ghoul with white hair", level: 1 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/6/366669.jpg", options: ["Sukuna", "Gojo Satoru", "Yuji Itadori", "Mahito"], correct: 0, hint: "King of Curses with four arms", level: 1 },
];
