// To switch to local images: change image field to "/shadows/l3_Y.jpg"
export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/6/232649.jpg", options: ["Muzan Kibutsuji", "Akaza", "Kokushibo", "Doma"], correct: 0, hint: "Demon King who created all demons", level: 3 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/8/372906.jpg", options: ["Akaza", "Muzan", "Kokushibo", "Gyutaro"], correct: 0, hint: "Upper Moon 3 martial arts demon", level: 3 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/4/378853.jpg", options: ["Kokushibo", "Yoriichi", "Muzan", "Akaza"], correct: 0, hint: "Upper Moon 1 six-eyed swordsman", level: 3 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/6/378851.jpg", options: ["Doma", "Akaza", "Muzan", "Kokushibo"], correct: 0, hint: "Upper Moon 2 fan-wielding cult leader", level: 3 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/4/179555.jpg", options: ["Madara Uchiha", "Hashirama", "Obito", "Itachi"], correct: 0, hint: "Ghost of the Uchiha legendary founder", level: 3 },
  { id: 6, image: "https://cdn.myanimelist.net/images/characters/6/182159.jpg", options: ["Hashirama Senju", "Madara", "Tobirama", "Minato"], correct: 0, hint: "First Hokage God of Shinobi wood style", level: 3 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/16/292447.jpg", options: ["Lelouch Lamperouge", "Light Yagami", "Suzaku", "C.C."], correct: 0, hint: "Geass user who commands absolute obedience", level: 3 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/16/264199.jpg", options: ["Kirito", "Asuna", "Klein", "Eugeo"], correct: 0, hint: "Black swordsman trapped in virtual worlds", level: 3 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/15/264197.jpg", options: ["Asuna", "Kirito", "Sinon", "Leafa"], correct: 0, hint: "Lightning Flash rapier wielder of SAO", level: 3 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/12/334745.jpg", options: ["Rintaro Okabe", "Kurisu", "Daru", "Mayuri"], correct: 0, hint: "Mad scientist Hououin Kyouma time traveler", level: 3 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/3/334747.jpg", options: ["Kurisu Makise", "Okabe", "Mayuri", "Moeka"], correct: 0, hint: "Genius neuroscientist assistant Christina", level: 3 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/8/211413.jpg", options: ["Deidara", "Sasori", "Itachi", "Hidan"], correct: 0, hint: "Art is an explosion clay bomber", level: 3 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/11/211415.jpg", options: ["Sasori", "Deidara", "Kakuzu", "Pain"], correct: 0, hint: "Red scorpion puppet master of Akatsuki", level: 3 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/5/211421.jpg", options: ["Kisame", "Zabuza", "Suigetsu", "Hidan"], correct: 0, hint: "Monster of the Mist with Samehada", level: 3 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/7/211419.jpg", options: ["Hidan", "Kakuzu", "Deidara", "Kisame"], correct: 0, hint: "Immortal Jashinist scythe wielder", level: 3 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/14/211417.jpg", options: ["Kakuzu", "Hidan", "Sasori", "Pain"], correct: 0, hint: "Five hearts bounty hunter of Akatsuki", level: 3 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/14/235219.jpg", options: ["Konan", "Pain", "Tsunade", "Temari"], correct: 0, hint: "Paper angel origami user of Rain village", level: 3 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/10/367475.jpg", options: ["Suguru Geto", "Gojo", "Kenjaku", "Mahito"], correct: 0, hint: "Curse manipulator turned worst enemy", level: 3 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/3/232417.jpg", options: ["Kaneki Ken", "Touka", "Ayato", "Tsukiyama"], correct: 0, hint: "One-eyed ghoul finger cracking bookworm", level: 3 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/15/232421.jpg", options: ["Touka Kirishima", "Kaneki", "Hinami", "Rize"], correct: 0, hint: "Rabbit kagune ghoul barista of Anteiku", level: 3 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/9/380475.jpg", options: ["Yoriichi Tsugikuni", "Kokushibo", "Tanjiro", "Muzan"], correct: 0, hint: "Original Sun Breathing creator strongest slayer", level: 3 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/12/378849.jpg", options: ["Gyutaro", "Daki", "Akaza", "Doma"], correct: 0, hint: "Upper Moon 6 sickle-wielding jealous demon", level: 3 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/3/70153.jpg", options: ["King Bradley", "Father", "Greed", "Envy"], correct: 0, hint: "Fuhrer who is the homunculus Wrath", level: 3 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/14/72187.jpg", options: ["Father", "Hohenheim", "Pride", "King Bradley"], correct: 0, hint: "Dwarf in the flask mastermind of FMA", level: 3 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/5/70155.jpg", options: ["Greed", "Ling", "Father", "Envy"], correct: 0, hint: "Ultimate Shield homunculus who wants everything", level: 3 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/8/70157.jpg", options: ["Envy", "Lust", "Greed", "Gluttony"], correct: 0, hint: "Shape-shifting homunculus full of jealousy", level: 3 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/12/128899.jpg", options: ["Sesshomaru", "Inuyasha", "Naraku", "Miroku"], correct: 0, hint: "Full demon lord cold older brother", level: 3 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/3/259703.jpg", options: ["Chrollo Lucilfer", "Hisoka", "Feitan", "Illumi"], correct: 0, hint: "Phantom Troupe leader Skill Hunter", level: 3 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/4/293835.jpg", options: ["Neferpitou", "Meruem", "Pouf", "Youpi"], correct: 0, hint: "Royal Guard cat chimera ant with Nen", level: 3 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/7/237179.jpg", options: ["Doflamingo", "Crocodile", "Law", "Luffy"], correct: 0, hint: "String puppet master Heavenly Demon", level: 3 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/9/381399.jpg", options: ["Kaido", "Big Mom", "Whitebeard", "Blackbeard"], correct: 0, hint: "King of Beasts strongest creature dragon", level: 3 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/2/263765.jpg", options: ["Sosuke Aizen", "Ichigo", "Gin", "Urahara"], correct: 0, hint: "Since when were you under the impression", level: 3 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/12/226303.jpg", options: ["Ulquiorra", "Grimmjow", "Aizen", "Ichigo"], correct: 0, hint: "Cuatro Espada nihilistic bat hollow", level: 3 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/9/226305.jpg", options: ["Grimmjow", "Ulquiorra", "Nnoitra", "Starrk"], correct: 0, hint: "Sexta Espada panther king of destruction", level: 3 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/8/52195.jpg", options: ["Frieza", "Cell", "Buu", "Vegeta"], correct: 0, hint: "Galactic emperor who destroyed Planet Vegeta", level: 3 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/6/366055.jpg", options: ["Blackbeard", "Kaido", "Akainu", "Shanks"], correct: 0, hint: "Two devil fruit pirate Yami Yami user", level: 3 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/14/389047.jpg", options: ["Mahito", "Geto", "Sukuna", "Jogo"], correct: 0, hint: "Cursed spirit who reshapes souls with Idle Transfiguration", level: 3 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/8/128897.jpg", options: ["Naraku", "Sesshomaru", "Inuyasha", "Kikyo"], correct: 0, hint: "Spider demon mastermind of Inuyasha", level: 3 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/14/361765.jpg", options: ["Garou", "Saitama", "Boros", "Genos"], correct: 0, hint: "Hero hunter who becomes cosmic threat", level: 3 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/3/380547.jpg", options: ["Overhaul", "Shigaraki", "Dabi", "All For One"], correct: 0, hint: "Plague mask yakuza who destroys with touch", level: 3 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/7/380549.jpg", options: ["Shigaraki", "All For One", "Dabi", "Overhaul"], correct: 0, hint: "Decay quirk villain successor hand face", level: 3 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/5/380551.jpg", options: ["Dabi", "Todoroki", "Endeavor", "Hawks"], correct: 0, hint: "Blue flame villain with burned skin", level: 3 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/11/70151.jpg", options: ["Lust", "Envy", "Gluttony", "Sloth"], correct: 0, hint: "Ultimate Spear seductive homunculus", level: 3 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/16/389049.jpg", options: ["Kenjaku", "Geto", "Sukuna", "Mahito"], correct: 0, hint: "Ancient sorcerer controlling Geto's body", level: 3 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/7/259705.jpg", options: ["Feitan", "Chrollo", "Phinks", "Hisoka"], correct: 0, hint: "Phantom Troupe speed demon Pain Packer", level: 3 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/16/232175.jpg", options: ["Hange Zoe", "Levi", "Erwin", "Mike"], correct: 0, hint: "Titan researcher eccentric Survey Corps", level: 3 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/15/72191.jpg", options: ["Scar", "Ed", "Mustang", "Greed"], correct: 0, hint: "Ishvalan warrior monk seeking vengeance", level: 3 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/11/128901.jpg", options: ["Kagura", "Naraku", "Sesshomaru", "Kikyo"], correct: 0, hint: "Wind sorceress seeking freedom from Naraku", level: 3 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/4/366053.jpg", options: ["Akainu", "Blackbeard", "Kizaru", "Garp"], correct: 0, hint: "Magma fist fleet admiral absolute justice", level: 3 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/11/380553.jpg", options: ["All For One", "Shigaraki", "Dabi", "Overhaul"], correct: 0, hint: "Symbol of Evil who steals quirks", level: 3 },
];
