export default [
  { level: 2, silhouette: '🕶️', hints: ['Uses genjutsu', 'Tragic backstory involving his clan', 'Belongs to Uchiha clan'], answer: 'Itachi Uchiha', anime: 'Naruto' },
  { level: 2, silhouette: '🎭', hints: ['Wears an orange spiral mask', 'Claims to be Madara', 'Was once thought dead'], answer: 'Obito Uchiha', anime: 'Naruto' },
  { level: 2, silhouette: '🌑', hints: ['Has a cursed seal', 'Left the village for power', 'Last member of his clan alive'], answer: 'Sasuke Uchiha', anime: 'Naruto' },
  { level: 2, silhouette: '💜', hints: ['Blue-haired maid', 'Twin sister is Ram', 'Many fans ask Who is she?'], answer: 'Rem', anime: 'Re:Zero' },
  { level: 2, silhouette: '🎪', hints: ['Rubber powers awakened', 'Gear transformations', 'Joy Boy reincarnation theory'], answer: 'Monkey D. Luffy', anime: 'One Piece' },
  { level: 2, silhouette: '🔮', hints: ['Fortune teller abilities', 'From Phantom Troupe', 'Chain user who hunts spiders'], answer: 'Kurapika', anime: 'Hunter x Hunter' },
  { level: 2, silhouette: '💊', hints: ['Surgeon of Death', 'Has a polar bear companion', 'Uses Room ability'], answer: 'Trafalgar Law', anime: 'One Piece' },
  { level: 2, silhouette: '🎸', hints: ['Lazy samurai in Edo', 'Loves strawberry milk', 'Wooden sword fighter'], answer: 'Gintoki Sakata', anime: 'Gintama' },
  { level: 2, silhouette: '🌺', hints: ['Hyuga clan heiress', 'Shy and gentle', 'Loved Naruto since childhood'], answer: 'Hinata Hyuga', anime: 'Naruto' },
  { level: 2, silhouette: '🏖️', hints: ['Sand manipulation', 'Has love kanji on forehead', 'Became Kazekage'], answer: 'Gaara', anime: 'Naruto' },
  { level: 2, silhouette: '🦅', hints: ['Has a hawk summon', 'Rinnegan user', 'Wanted to change the world through pain'], answer: 'Nagato/Pain', anime: 'Naruto' },
  { level: 2, silhouette: '🎶', hints: ['Plays a flute made of bone', 'One of Sound Four', 'Actually a she disguised as he'], answer: 'Tayuya', anime: 'Naruto' },
  { level: 2, silhouette: '🖤', hints: ['Anti-magic swords', 'Has a five-leaf clover grimoire', 'Born without any magic'], answer: 'Asta', anime: 'Black Clover' },
  { level: 2, silhouette: '👿', hints: ['Son of Satan', 'Blue flames', 'Attends an exorcist school'], answer: 'Rin Okumura', anime: 'Blue Exorcist' },
  { level: 2, silhouette: '🌟', hints: ['Celestial spirit mage', 'Blonde hair with keys', 'Joined Fairy Tail guild'], answer: 'Lucy Heartfilia', anime: 'Fairy Tail' },
  { level: 2, silhouette: '🐺', hints: ['Transforms into a titan', 'Seeks freedom above all', 'Started the Rumbling'], answer: 'Eren Yeager', anime: 'Attack on Titan' },
  { level: 2, silhouette: '🧣', hints: ['Wears a red scarf', 'Incredibly skilled soldier', 'Devoted to Eren'], answer: 'Mikasa Ackerman', anime: 'Attack on Titan' },
  { level: 2, silhouette: '📚', hints: ['Brilliant strategist', 'Blonde commander', 'Sacrificed himself for humanity'], answer: 'Erwin Smith', anime: 'Attack on Titan' },
  { level: 2, silhouette: '🥔', hints: ['Loves food especially potatoes', 'From a small village', 'Scout Regiment member'], answer: 'Sasha Blouse', anime: 'Attack on Titan' },
  { level: 2, silhouette: '🔩', hints: ['Cyborg shipwright', 'Cola-powered', 'Built the Thousand Sunny'], answer: 'Franky', anime: 'One Piece' },
  { level: 2, silhouette: '🍖', hints: ['Captain of Straw Hat crew', 'Always hungry', 'Scar under left eye'], answer: 'Monkey D. Luffy', anime: 'One Piece' },
  { level: 2, silhouette: '🃏', hints: ['Magician and fighter', 'Schwing!', 'Obsessed with fighting strong opponents'], answer: 'Hisoka Morow', anime: 'Hunter x Hunter' },
  { level: 2, silhouette: '🐜', hints: ['Chimera Ant King', 'Played Gungi with a blind girl', 'Most powerful creature born'], answer: 'Meruem', anime: 'Hunter x Hunter' },
  { level: 2, silhouette: '💎', hints: ['Uses diamond-hard skin', 'Third division commander', 'Whitebeard pirate'], answer: 'Jozu', anime: 'One Piece' },
  { level: 2, silhouette: '🌊', hints: ['Ice-wielding admiral', 'Lazy and laidback', 'Left the Marines'], answer: 'Aokiji/Kuzan', anime: 'One Piece' },
  { level: 2, silhouette: '☀️', hints: ['Fire fist user', 'Luffy\'s older brother', 'Died at Marineford'], answer: 'Portgas D. Ace', anime: 'One Piece' },
  { level: 2, silhouette: '🎵', hints: ['Soul musician', 'Black Blood weapon', 'Partner to Maka'], answer: 'Soul Evans', anime: 'Soul Eater' },
  { level: 2, silhouette: '📕', hints: ['Scythe wielder', 'Daughter of a Death Scythe', 'Meister at DWMA'], answer: 'Maka Albarn', anime: 'Soul Eater' },
  { level: 2, silhouette: '🎃', hints: ['Death\'s son', 'Obsessed with symmetry', 'Wields twin pistols'], answer: 'Death the Kid', anime: 'Soul Eater' },
  { level: 2, silhouette: '💉', hints: ['Mad scientist', 'Stitched up face', 'Strongest meister ever'], answer: 'Franken Stein', anime: 'Soul Eater' },
  { level: 2, silhouette: '🗝️', hints: ['Gate Keeper alchemist', 'Flame Alchemist', 'Wants to become Fuhrer'], answer: 'Roy Mustang', anime: 'Fullmetal Alchemist' },
  { level: 2, silhouette: '💪', hints: ['Muscular alchemist', 'Armstrong family legacy', 'Artistic combat style'], answer: 'Alex Louis Armstrong', anime: 'Fullmetal Alchemist' },
  { level: 2, silhouette: '🐕', hints: ['Loyal military dog', 'Best friend was Hughes', 'Lieutenant to Mustang'], answer: 'Riza Hawkeye', anime: 'Fullmetal Alchemist' },
  { level: 2, silhouette: '👻', hints: ['Homunculus of greed', 'Ultimate shield ability', 'Became an ally later'], answer: 'Greed/Ling', anime: 'Fullmetal Alchemist' },
  { level: 2, silhouette: '🎯', hints: ['Uses finger guns', 'Vessel for the King of Curses', 'Eats cursed objects'], answer: 'Yuji Itadori', anime: 'Jujutsu Kaisen' },
  { level: 2, silhouette: '🐕‍🦺', hints: ['Ten Shadows technique', 'Summons shikigami', 'From the Zenin clan'], answer: 'Megumi Fushiguro', anime: 'Jujutsu Kaisen' },
  { level: 2, silhouette: '🌹', hints: ['Cursed speech user', 'Can only say rice ball ingredients', 'From Jujutsu High'], answer: 'Toge Inumaki', anime: 'Jujutsu Kaisen' },
  { level: 2, silhouette: '🐼', hints: ['Huge cursed energy', 'Friendly giant', 'Second-year at Jujutsu High'], answer: 'Panda', anime: 'Jujutsu Kaisen' },
  { level: 2, silhouette: '⭐', hints: ['Star Platinum Stand', 'Yare yare daze', 'Grandson of Jonathan'], answer: 'Jotaro Kujo', anime: "JoJo's Bizarre Adventure" },
  { level: 2, silhouette: '💛', hints: ['Crazy Diamond Stand', 'Lives in Morioh', 'Illegitimate son of Joseph'], answer: 'Josuke Higashikata', anime: "JoJo's Bizarre Adventure" },
  { level: 2, silhouette: '🐞', hints: ['Gold Experience Stand', 'Son of DIO', 'Wants to be a Gang-Star'], answer: 'Giorno Giovanna', anime: "JoJo's Bizarre Adventure" },
  { level: 2, silhouette: '🧛', hints: ['Vampire who rejected humanity', 'The World Stand', 'Main villain for generations'], answer: 'DIO', anime: "JoJo's Bizarre Adventure" },
  { level: 2, silhouette: '🌸', hints: ['Medical ninja', 'Super strength', 'Teammate of Naruto and Sasuke'], answer: 'Sakura Haruno', anime: 'Naruto' },
  { level: 2, silhouette: '🦊', hints: ['Nine-tailed fox spirit', 'Sealed inside Naruto', 'Eventually became an ally'], answer: 'Kurama', anime: 'Naruto' },
  { level: 2, silhouette: '🎭', hints: ['Wears a mask over mouth', 'Known as the Demon of the Mist', 'Wielded Kubikiribocho'], answer: 'Zabuza Momochi', anime: 'Naruto' },
  { level: 2, silhouette: '❄️', hints: ['Ice mirror technique', 'Looked like a girl', 'Served Zabuza loyally'], answer: 'Haku', anime: 'Naruto' },
  { level: 2, silhouette: '🦁', hints: ['Flame Hashira', 'Set his heart ablaze', 'Died protecting the Mugen Train'], answer: 'Kyojuro Rengoku', anime: 'Demon Slayer' },
  { level: 2, silhouette: '🎶', hints: ['Sound Hashira', 'Flamboyant and flashy', 'Uses explosive nunchucks'], answer: 'Tengen Uzui', anime: 'Demon Slayer' },
  { level: 2, silhouette: '🌫️', hints: ['Mist Hashira', 'Youngest Hashira', 'Descendant of a legendary swordsman'], answer: 'Muichiro Tokito', anime: 'Demon Slayer' },
  { level: 2, silhouette: '🐍', hints: ['Serpent Hashira', 'Has a white snake', 'Striped haori'], answer: 'Obanai Iguro', anime: 'Demon Slayer' },
];
