export default [
  { level: 1, silhouette: '🗡️', hints: ['Carries a special sword', 'From a shonen series', 'Known for his spiky orange hair'], answer: 'Ichigo Kurosaki', anime: 'Bleach' },
  { level: 1, silhouette: '⚡', hints: ['Has lightning powers', 'Wears a headband', 'His rival became his best friend'], answer: 'Sasuke Uchiha', anime: 'Naruto' },
  { level: 1, silhouette: '🔱', hints: ['Wears a straw hat', 'Can stretch like rubber', 'Wants to be King of the Pirates'], answer: 'Monkey D. Luffy', anime: 'One Piece' },
  { level: 1, silhouette: '⚙️', hints: ['Uses alchemy', 'Has a metal arm', 'Travels with his armored brother'], answer: 'Edward Elric', anime: 'Fullmetal Alchemist' },
  { level: 1, silhouette: '🌸', hints: ['Demon slayer', 'Uses water breathing', 'Has a sister who is a demon'], answer: 'Tanjiro Kamado', anime: 'Demon Slayer' },
  { level: 1, silhouette: '🦊', hints: ['Has a fox demon inside him', 'Wears an orange jumpsuit', 'Dreams of becoming Hokage'], answer: 'Naruto Uzumaki', anime: 'Naruto' },
  { level: 1, silhouette: '🐉', hints: ['Super Saiyan warrior', 'Alien from Planet Vegeta', 'Always looking for a strong opponent'], answer: 'Goku', anime: 'Dragon Ball' },
  { level: 1, silhouette: '💀', hints: ['Has a death notebook', 'High school genius', 'Wants to become god of the new world'], answer: 'Light Yagami', anime: 'Death Note' },
  { level: 1, silhouette: '🧊', hints: ['Half cold half hot', 'Has a scar on his face', 'Father is the number one hero'], answer: 'Shoto Todoroki', anime: 'My Hero Academia' },
  { level: 1, silhouette: '👊', hints: ['Bald hero', 'Defeats everything in one punch', 'Trained so hard he lost his hair'], answer: 'Saitama', anime: 'One Punch Man' },
  { level: 1, silhouette: '🌀', hints: ['Uses Rasengan', 'Mentor was a pervy sage', 'Son of the Fourth Hokage'], answer: 'Naruto Uzumaki', anime: 'Naruto' },
  { level: 1, silhouette: '⚔️', hints: ['Three-sword style', 'Gets lost easily', 'Green-haired swordsman'], answer: 'Roronoa Zoro', anime: 'One Piece' },
  { level: 1, silhouette: '🔥', hints: ['Pink-haired dragon slayer', 'From a wizard guild', 'Raised by a fire dragon'], answer: 'Natsu Dragneel', anime: 'Fairy Tail' },
  { level: 1, silhouette: '👁️', hints: ['Has special eyes', 'The strongest sorcerer', 'Always blindfolded'], answer: 'Satoru Gojo', anime: 'Jujutsu Kaisen' },
  { level: 1, silhouette: '🎭', hints: ['Wears a mask', 'Always late', 'Copy ninja with one Sharingan'], answer: 'Kakashi Hatake', anime: 'Naruto' },
  { level: 1, silhouette: '💚', hints: ['Inheritor of One For All', 'Breaks his bones when using power', 'A quirkless boy who became a hero'], answer: 'Izuku Midoriya', anime: 'My Hero Academia' },
  { level: 1, silhouette: '🗡️', hints: ['Humanity strongest soldier', 'Very short', 'Captain of Survey Corps'], answer: 'Levi Ackerman', anime: 'Attack on Titan' },
  { level: 1, silhouette: '⚡', hints: ['White-haired assassin kid', 'From a family of killers', 'Best friend is Gon'], answer: 'Killua Zoldyck', anime: 'Hunter x Hunter' },
  { level: 1, silhouette: '🎣', hints: ['Carries a fishing rod', 'Looking for his dad', 'Took the Hunter Exam as a kid'], answer: 'Gon Freecss', anime: 'Hunter x Hunter' },
  { level: 1, silhouette: '🌊', hints: ['Water Hashira', 'Always calm and gentle', 'Has a haori with wave patterns'], answer: 'Giyu Tomioka', anime: 'Demon Slayer' },
  { level: 1, silhouette: '💛', hints: ['Thunder breathing user', 'Falls asleep to fight', 'Extremely cowardly when awake'], answer: 'Zenitsu Agatsuma', anime: 'Demon Slayer' },
  { level: 1, silhouette: '🐷', hints: ['Wears a boar head mask', 'Dual-wielding swordsman', 'Raised in the mountains'], answer: 'Inosuke Hashibira', anime: 'Demon Slayer' },
  { level: 1, silhouette: '👑', hints: ['Prince of all Saiyans', 'Rivals with Goku', 'Proud warrior with spiky hair'], answer: 'Vegeta', anime: 'Dragon Ball' },
  { level: 1, silhouette: '🎩', hints: ['Phantom Troupe leader', 'Uses Bungee Gum', 'A magician-like fighter'], answer: 'Hisoka', anime: 'Hunter x Hunter' },
  { level: 1, silhouette: '🦁', hints: ['King of curses', 'Has four arms in true form', 'Shares a body with a high schooler'], answer: 'Ryomen Sukuna', anime: 'Jujutsu Kaisen' },
  { level: 1, silhouette: '🍜', hints: ['Cook of the Straw Hats', 'Only kicks in battle', 'Loves all women'], answer: 'Sanji', anime: 'One Piece' },
  { level: 1, silhouette: '🌹', hints: ['Red-haired pirate captain', 'Missing one arm', 'Gave his straw hat to Luffy'], answer: 'Shanks', anime: 'One Piece' },
  { level: 1, silhouette: '📖', hints: ['Archaeologist of Straw Hats', 'Can sprout body parts anywhere', 'Reads ancient Poneglyphs'], answer: 'Nico Robin', anime: 'One Piece' },
  { level: 1, silhouette: '🎯', hints: ['Sniper of the Straw Hats', 'Tells tall tales', 'Has a long nose'], answer: 'Usopp', anime: 'One Piece' },
  { level: 1, silhouette: '🧡', hints: ['Navigator of the Straw Hats', 'Loves money and tangerines', 'Expert in weather'], answer: 'Nami', anime: 'One Piece' },
  { level: 1, silhouette: '💣', hints: ['Explosive personality', 'Rival to Deku', 'Quirk creates explosions from his palms'], answer: 'Katsuki Bakugo', anime: 'My Hero Academia' },
  { level: 1, silhouette: '🧬', hints: ['Symbol of Peace', 'Muscular hero form', 'Passed his quirk to a student'], answer: 'All Might', anime: 'My Hero Academia' },
  { level: 1, silhouette: '🐍', hints: ['One of three legendary Sannin', 'Obsessed with immortality', 'Has snake abilities'], answer: 'Orochimaru', anime: 'Naruto' },
  { level: 1, silhouette: '🐸', hints: ['Pervy Sage', 'Naruto\'s teacher', 'One of the legendary Sannin'], answer: 'Jiraiya', anime: 'Naruto' },
  { level: 1, silhouette: '🏋️', hints: ['Wears a green jumpsuit', 'Master of taijutsu', 'Cannot use ninjutsu or genjutsu'], answer: 'Rock Lee', anime: 'Naruto' },
  { level: 1, silhouette: '🐶', hints: ['Has a giant dog companion', 'From the Inuzuka clan', 'Wild and feral fighting style'], answer: 'Kiba Inuzuka', anime: 'Naruto' },
  { level: 1, silhouette: '🦋', hints: ['Insect Hashira', 'Always smiling', 'Uses poison in combat'], answer: 'Shinobu Kocho', anime: 'Demon Slayer' },
  { level: 1, silhouette: '🔴', hints: ['Red-haired swordswoman', 'S-class mage', 'Known as Titania'], answer: 'Erza Scarlet', anime: 'Fairy Tail' },
  { level: 1, silhouette: '❄️', hints: ['Ice-make mage', 'Strips unconsciously', 'Rival to Natsu'], answer: 'Gray Fullbuster', anime: 'Fairy Tail' },
  { level: 1, silhouette: '🐱', hints: ['Blue flying cat', 'Says Aye sir!', 'Partner to a dragon slayer'], answer: 'Happy', anime: 'Fairy Tail' },
  { level: 1, silhouette: '🎀', hints: ['Pink-haired demon sister', 'Sleeps in a box', 'Was turned into a demon'], answer: 'Nezuko Kamado', anime: 'Demon Slayer' },
  { level: 1, silhouette: '🌙', hints: ['Half-demon with dog ears', 'Wields Tessaiga', 'Loves ramen from the future'], answer: 'Inuyasha', anime: 'Inuyasha' },
  { level: 1, silhouette: '🏀', hints: ['Phantom sixth man', 'Almost invisible presence', 'Specializes in misdirection'], answer: 'Tetsuya Kuroko', anime: "Kuroko's Basketball" },
  { level: 1, silhouette: '🏐', hints: ['Short but can jump incredibly high', 'Orange-haired', 'Plays volleyball at Karasuno'], answer: 'Shoyo Hinata', anime: 'Haikyuu!!' },
  { level: 1, silhouette: '🎹', hints: ['Pianist who cannot hear his own music', 'Wears glasses', 'Met a violinist who changed his world'], answer: 'Kousei Arima', anime: 'Your Lie in April' },
  { level: 1, silhouette: '🤖', hints: ['Cyborg disciple', 'Full metal body', 'Seeks the villain who destroyed his town'], answer: 'Genos', anime: 'One Punch Man' },
  { level: 1, silhouette: '☠️', hints: ['Skeleton musician', 'Brook of the Straw Hats', 'Ate the Revive-Revive Fruit'], answer: 'Brook', anime: 'One Piece' },
  { level: 1, silhouette: '🦌', hints: ['Tiny reindeer doctor', 'Can transform into different forms', 'Loves cotton candy'], answer: 'Tony Tony Chopper', anime: 'One Piece' },
  { level: 1, silhouette: '🗡️', hints: ['Wielder of Nichirin blade', 'Has a scar on his forehead', 'Kind-hearted protagonist'], answer: 'Tanjiro Kamado', anime: 'Demon Slayer' },
  { level: 1, silhouette: '🐻', hints: ['Giant armored brother', 'Soul bound to a suit of armor', 'Loves cats'], answer: 'Alphonse Elric', anime: 'Fullmetal Alchemist' },
];
