// To switch to local images: change image field to "/shadows/l5_Y.jpg"
export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/11/174515.jpg", options: ["Johan Liebert", "Tenma", "Lunge", "Roberto"], correct: 0, hint: "Nameless monster perfect manipulator", level: 5 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/4/174513.jpg", options: ["Kenzo Tenma", "Johan", "Lunge", "Grimmer"], correct: 0, hint: "Brain surgeon who saved a monster", level: 5 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/16/234697.jpg", options: ["Motoko Kusanagi", "Revy", "Lain", "Batou"], correct: 0, hint: "Section 9 cyborg major ghost in shell", level: 5 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/12/349923.jpg", options: ["Griffith", "Guts", "Casca", "Void"], correct: 0, hint: "White hawk turned God Hand betrayer", level: 5 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/3/349921.jpg", options: ["Guts", "Griffith", "Skull Knight", "Zodd"], correct: 0, hint: "Black swordsman branded struggler Dragonslayer", level: 5 },
  { id: 6, image: "https://cdn.myanimelist.net/images/characters/9/180569.jpg", options: ["Lain Iwakura", "Homura", "Rei", "Kusanagi"], correct: 0, hint: "Wired existence blurring digital reality", level: 5 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/14/148275.jpg", options: ["Nausicaa", "San", "Kiki", "Sophie"], correct: 0, hint: "Valley of the Wind princess loves Ohmu", level: 5 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/16/148277.jpg", options: ["San", "Nausicaa", "Chihiro", "Kaguya"], correct: 0, hint: "Wolf princess raised by Moro of the forest", level: 5 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/3/188815.jpg", options: ["Howl", "Haku", "Calcifer", "Turnip"], correct: 0, hint: "Vain wizard of the moving castle", level: 5 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/5/188817.jpg", options: ["Sophie Hatter", "Howl", "Witch", "Lettie"], correct: 0, hint: "Cursed old hat maker who found courage", level: 5 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/4/137355.jpg", options: ["Chihiro", "Haku", "No-Face", "Yubaba"], correct: 0, hint: "Spirited away girl who worked in bathhouse", level: 5 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/6/137357.jpg", options: ["Haku", "Chihiro", "No-Face", "Zeniba"], correct: 0, hint: "River spirit dragon boy who forgot his name", level: 5 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/8/137359.jpg", options: ["No-Face", "Haku", "Yubaba", "Calcifer"], correct: 0, hint: "Masked spirit that consumes and mimics", level: 5 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/6/249595.jpg", options: ["Homura Akemi", "Madoka", "Sayaka", "Mami"], correct: 0, hint: "Time-looping magical girl who did nothing wrong", level: 5 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/2/249593.jpg", options: ["Madoka Kaname", "Homura", "Sayaka", "Kyoko"], correct: 0, hint: "Pink-haired girl who became hope itself", level: 5 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/7/148279.jpg", options: ["Porco Rosso", "Howl", "Lupin", "Spike"], correct: 0, hint: "Cursed pilot pig bounty hunter of Adriatic", level: 5 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/9/137361.jpg", options: ["Totoro", "Catbus", "Soot Sprite", "Kodama"], correct: 0, hint: "Giant forest spirit only children can see", level: 5 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/11/148281.jpg", options: ["Kiki", "Nausicaa", "Sophie", "Chihiro"], correct: 0, hint: "Young witch delivery service with black cat", level: 5 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/3/204575.jpg", options: ["Revy", "Kusanagi", "Balalaika", "Roberta"], correct: 0, hint: "Two-handed gunslinger of the Black Lagoon", level: 5 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/5/230177.jpg", options: ["Mugen", "Jin", "Spike", "Kenshin"], correct: 0, hint: "Wild breakdancing swordsman of Champloo", level: 5 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/14/345231.jpg", options: ["Phosphophyllite", "Diamond", "Cinnabar", "Bort"], correct: 0, hint: "Fragile gem who keeps breaking and changing", level: 5 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/12/326563.jpg", options: ["Mob", "Reigen", "Dimple", "Teru"], correct: 0, hint: "Psychic boy reaching 100 percent explosion", level: 5 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/14/326565.jpg", options: ["Reigen Arataka", "Mob", "Dimple", "Serizawa"], correct: 0, hint: "Self-proclaimed greatest psychic con man", level: 5 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/3/363305.jpg", options: ["Tohru", "Kobayashi", "Kanna", "Elma"], correct: 0, hint: "Chaos dragon maid in love with her master", level: 5 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/5/363307.jpg", options: ["Kobayashi", "Tohru", "Kanna", "Fafnir"], correct: 0, hint: "Tired programmer who befriended a dragon", level: 5 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/7/249597.jpg", options: ["Kyubey", "Madoka", "Homura", "Mami"], correct: 0, hint: "Cute alien incubator contract creature", level: 5 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/6/242813.jpg", options: ["Vash the Stampede", "Wolfwood", "Spike", "Kenshin"], correct: 0, hint: "Sixty billion double dollar man love and peace", level: 5 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/14/334749.jpg", options: ["Hououin Kyouma", "Daru", "Kurisu", "Mayuri"], correct: 0, hint: "It's the choice of Steins Gate El Psy Kongroo", level: 5 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/9/204577.jpg", options: ["Edward Wong", "Spike", "Faye", "Jet"], correct: 0, hint: "Eccentric hacker kid of the Bebop crew", level: 5 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/4/330983.jpg", options: ["Thorfinn", "Askeladd", "Canute", "Thorkell"], correct: 0, hint: "Son of Thors seeking true warrior path", level: 5 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/11/330981.jpg", options: ["Askeladd", "Thorfinn", "Canute", "Bjorn"], correct: 0, hint: "Cunning Welsh mercenary leader complex villain", level: 5 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/13/137363.jpg", options: ["Yubaba", "Zeniba", "No-Face", "Haku"], correct: 0, hint: "Greedy bathhouse witch with giant head", level: 5 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/12/399423.jpg", options: ["Anya Forger", "Yor", "Loid", "Becky"], correct: 0, hint: "Telepathic child waku waku peanuts", level: 5 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/14/399425.jpg", options: ["Yor Forger", "Anya", "Loid", "Fiona"], correct: 0, hint: "Thorn Princess assassin pretend wife", level: 5 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/7/399421.jpg", options: ["Loid Forger", "Yor", "Anya", "Franky"], correct: 0, hint: "Spy master of disguise Twilight father", level: 5 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/11/316505.jpg", options: ["Saber Alter", "Saber", "Gilgamesh", "Rin"], correct: 0, hint: "Dark corrupted King Arthur black armor", level: 5 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/5/404819.jpg", options: ["Sung Jin-Woo", "Igris", "Iron", "Beru"], correct: 0, hint: "Shadow monarch weakest to strongest hunter", level: 5 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/13/316507.jpg", options: ["Archer", "Shirou", "Gilgamesh", "Lancer"], correct: 0, hint: "Counter Guardian future Emiya Unlimited Blade Works", level: 5 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/2/378155.jpg", options: ["Kaguya Shinomiya", "Miyuki", "Chika", "Miko"], correct: 0, hint: "Vice president ice princess love war", level: 5 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/4/378157.jpg", options: ["Miyuki Shirogane", "Kaguya", "Ishigami", "Chika"], correct: 0, hint: "Student council president studying monster", level: 5 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/6/355117.jpg", options: ["Osamu Dazai", "Atsushi", "Chuuya", "Ranpo"], correct: 0, hint: "Suicidal detective with No Longer Human ability", level: 5 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/8/355119.jpg", options: ["Atsushi Nakajima", "Dazai", "Akutagawa", "Kunikida"], correct: 0, hint: "White tiger weretiger orphan detective", level: 5 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/10/277403.jpg", options: ["Izaya Orihara", "Shizuo", "Celty", "Mikado"], correct: 0, hint: "Information broker who loves humans Ikebukuro", level: 5 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/12/277405.jpg", options: ["Shizuo Heiwajima", "Izaya", "Celty", "Simon"], correct: 0, hint: "Bartender outfit superhuman strength vending machines", level: 5 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/3/403215.jpg", options: ["Marin Kitagawa", "Gojo", "Juju", "Sajuna"], correct: 0, hint: "Cosplay-loving gyaru dress-up darling", level: 5 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/8/292449.jpg", options: ["C.C.", "Lelouch", "Kallen", "Suzaku"], correct: 0, hint: "Immortal green-haired pizza-loving witch", level: 5 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/11/394421.jpg", options: ["Pochita", "Denji", "Power", "Makima"], correct: 0, hint: "Chainsaw Devil dog form loyal companion", level: 5 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/9/204579.jpg", options: ["Spike Spiegel", "Jet", "Vicious", "Faye"], correct: 0, hint: "See you space cowboy Jeet Kune Do", level: 5 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/6/411055.jpg", options: ["Stark", "Frieren", "Fern", "Eisen"], correct: 0, hint: "Cowardly warrior apprentice of Eisen", level: 5 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/14/213567.jpg", options: ["Clare", "Teresa", "Raki", "Priscilla"], correct: 0, hint: "Silver-eyed half-yoma warrior number 47", level: 5 },
];
