export default [
  { text: "What is Naruto’s surname?", options: ["Senju", "Uzumaki", "Uchiha", "Hyuga"], correct: 1 },
  { text: "Who is Luffy’s swordsman?", options: ["Sanji", "Usopp", "Zoro", "Law"], correct: 2 },
  { text: "Which anime has Titans?", options: ["Bleach", "Naruto", "Attack on Titan", "Fairy Tail"], correct: 2 },
  { text: "What is Goku’s race?", options: ["Human", "Saiyan", "Namekian", "Android"], correct: 1 },
  { text: "Who is Tanjiro’s sister?", options: ["Mitsuri", "Shinobu", "Nezuko", "Kanao"], correct: 2 },
  { text: "What sport is played in Haikyuu!!?", options: ["Football", "Basketball", "Tennis", "Volleyball"], correct: 3 },
  { text: "Who uses the Death Note?", options: ["L", "Light Yagami", "Ryuk", "Near"], correct: 1 },
  { text: "What is Naruto’s dream?", options: ["Pirate King", "Wizard King", "Hokage", "Hero"], correct: 2 },
  { text: "Which anime features Soul Reapers?", options: ["Bleach", "One Piece", "Black Clover", "JoJo"], correct: 0 },
  { text: "What is Ash’s main Pokémon?", options: ["Charizard", "Pikachu", "Bulbasaur", "Squirtle"], correct: 1 },
  { text: "Who is Deku?", options: ["Bakugo", "Todoroki", "Midoriya", "Kirishima"], correct: 2 },
  { text: "Which anime has Dragon Balls?", options: ["Naruto", "Dragon Ball", "Bleach", "Fairy Tail"], correct: 1 },
  { text: "What is Luffy searching for?", options: ["Hokage title", "Dragon Balls", "One Piece", "Death Note"], correct: 2 },
  { text: "Who is Naruto’s rival?", options: ["Kakashi", "Sasuke", "Gaara", "Lee"], correct: 1 },
  { text: "What color is Goku’s outfit?", options: ["Blue", "Black", "Orange", "Green"], correct: 2 },
  { text: "Which anime features alchemy?", options: ["Demon Slayer", "Fullmetal Alchemist", "Jujutsu Kaisen", "One Punch Man"], correct: 1 },
  { text: "What animal is Happy in Fairy Tail?", options: ["Dog", "Cat", "Bird", "Fox"], correct: 1 },
  { text: "Who is the Flame Hashira?", options: ["Giyu", "Sanemi", "Rengoku", "Tengen"], correct: 2 },
  { text: "What is Gojo’s clan technique famous for?", options: ["Fire", "Ice", "Six Eyes", "Sand"], correct: 2 },
  { text: "Which anime features Saitama?", options: ["Mob Psycho", "One Punch Man", "Bleach", "Naruto"], correct: 1 },
  { text: "What village is Naruto from?", options: ["Sand", "Mist", "Stone", "Leaf"], correct: 3 },
  { text: "Who is Eren’s adoptive sister?", options: ["Historia", "Annie", "Mikasa", "Sasha"], correct: 2 },
  { text: "Which anime has the Akatsuki?", options: ["Naruto", "Bleach", "One Piece", "Dragon Ball"], correct: 0 },
  { text: "Who is Gon’s best friend?", options: ["Kurapika", "Leorio", "Killua", "Hisoka"], correct: 2 },
  { text: "What is Vegeta’s title?", options: ["Pirate Prince", "Prince of Saiyans", "Hokage", "Hero King"], correct: 1 },
  { text: "Which anime has Titans and ODM gear?", options: ["Vinland Saga", "Attack on Titan", "Berserk", "Black Clover"], correct: 1 },
  { text: "What is Tanjiro’s weapon?", options: ["Axe", "Bow", "Sword", "Spear"], correct: 2 },
  { text: "What is Ichigo’s power called?", options: ["Nen", "Chakra", "Bankai", "Haki"], correct: 2 },
  { text: "Who trained Naruto during Shippuden?", options: ["Kakashi", "Jiraiya", "Iruka", "Yamato"], correct: 1 },
  { text: "Which anime features Ryuk?", options: ["Death Note", "Bleach", "Naruto", "One Piece"], correct: 0 },
  { text: "Who is the captain of the Straw Hats?", options: ["Zoro", "Law", "Luffy", "Ace"], correct: 2 },
  { text: "What is Inosuke known for wearing?", options: ["Fox Mask", "Boar Mask", "Bird Mask", "Cat Mask"], correct: 1 },
  { text: "Which anime features Titans eating humans?", options: ["Demon Slayer", "One Piece", "Attack on Titan", "Fairy Tail"], correct: 2 },
  { text: "What is Goku’s wife’s name?", options: ["Bulma", "Chi-Chi", "Android 18", "Videl"], correct: 1 },
  { text: "Who is the Symbol of Peace?", options: ["Endeavor", "Hawks", "All Might", "Deku"], correct: 2 },
  { text: "Which anime features Edward Elric?", options: ["Bleach", "Fullmetal Alchemist", "Naruto", "JoJo"], correct: 1 },
  { text: "What is Nezuko?", options: ["Human", "Demon", "Titan", "Spirit"], correct: 1 },
  { text: "Who is Naruto’s father?", options: ["Hashirama", "Minato", "Tobirama", "Fugaku"], correct: 1 },
  { text: "Which anime has Spirit Bomb?", options: ["Naruto", "Bleach", "Dragon Ball", "Fairy Tail"], correct: 2 },
  { text: "What is the name of L’s rival?", options: ["Light", "Ryuk", "Near", "Mello"], correct: 0 },
  { text: "Which anime has Fairy Tail guild?", options: ["Fairy Tail", "Bleach", "Black Clover", "Naruto"], correct: 0 },
  { text: "Who uses Thunder Breathing?", options: ["Tanjiro", "Zenitsu", "Giyu", "Muichiro"], correct: 1 },
  { text: "Which anime features Sukuna?", options: ["Jujutsu Kaisen", "Naruto", "Bleach", "Tokyo Ghoul"], correct: 0 },
  { text: "What is Levi famous for fighting?", options: ["Demons", "Hollows", "Titans", "Pirates"], correct: 2 },
  { text: "Which anime has Hokages?", options: ["Bleach", "Naruto", "One Piece", "Dragon Ball"], correct: 1 },
  { text: "What is the name of Luffy’s crew?", options: ["Red Hair Pirates", "Heart Pirates", "Straw Hat Pirates", "Beast Pirates"], correct: 2 },
  { text: "Who is Goku’s strongest rival?", options: ["Krillin", "Vegeta", "Yamcha", "Piccolo"], correct: 1 },
  { text: "Which anime features Gojo Satoru?", options: ["Bleach", "One Piece", "Jujutsu Kaisen", "Black Clover"], correct: 2 }
];