// To switch to local images: change image field to "/shadows/l4_Y.jpg"
export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/7/204573.jpg", options: ["Spike Spiegel", "Mugen", "Vash", "Revy"], correct: 0, hint: "Bounty hunter cowboy in space with jazz", level: 4 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/4/230175.jpg", options: ["Kenshin Himura", "Mugen", "Gintoki", "Zoro"], correct: 0, hint: "Wandering samurai with cross-shaped scar", level: 4 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/8/349451.jpg", options: ["Violet Evergarden", "Saber", "Fate", "Ais"], correct: 0, hint: "Auto Memory Doll learning emotions", level: 4 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/8/305944.jpg", options: ["Ainz Ooal Gown", "Albedo", "Shalltear", "Demiurge"], correct: 0, hint: "Skeleton overlord ruler of Nazarick", level: 4 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/3/305945.jpg", options: ["Albedo", "Ainz", "Shalltear", "Narberal"], correct: 0, hint: "Succubus guardian overseer loves Ainz", level: 4 },
  { id: 6, image: "https://cdn.myanimelist.net/images/characters/2/354371.jpg", options: ["Emilia", "Rem", "Ram", "Beatrice"], correct: 0, hint: "Half-elf silver-haired royal candidate", level: 4 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/3/354373.jpg", options: ["Subaru Natsuki", "Kazuma", "Naofumi", "Rimuru"], correct: 0, hint: "Return by Death tracksuit isekai boy", level: 4 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/7/282179.jpg", options: ["Sebastian Michaelis", "Ciel", "Grell", "Claude"], correct: 0, hint: "One hell of a butler demon servant", level: 4 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/4/282181.jpg", options: ["Ciel Phantomhive", "Sebastian", "Alois", "Elizabeth"], correct: 0, hint: "Young earl with eye patch contract", level: 4 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/4/260693.jpg", options: ["Kisuke Urahara", "Aizen", "Ichigo", "Yoruichi"], correct: 0, hint: "Shady shopkeeper genius former captain", level: 4 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/6/260695.jpg", options: ["Yoruichi", "Urahara", "Soi Fon", "Rukia"], correct: 0, hint: "Flash goddess cat-form Shinigami", level: 4 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/3/263767.jpg", options: ["Toshiro Hitsugaya", "Byakuya", "Ichigo", "Rangiku"], correct: 0, hint: "Ice dragon child prodigy captain", level: 4 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/5/263769.jpg", options: ["Byakuya Kuchiki", "Toshiro", "Aizen", "Renji"], correct: 0, hint: "Noble cherry blossom Senbonzakura captain", level: 4 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/11/52197.jpg", options: ["Cell", "Frieza", "Buu", "Android 17"], correct: 0, hint: "Perfect form bio-android absorber", level: 4 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/7/52199.jpg", options: ["Majin Buu", "Cell", "Frieza", "Broly"], correct: 0, hint: "Pink candy-loving ancient destructive blob", level: 4 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/14/366057.jpg", options: ["Big Mom", "Kaido", "Blackbeard", "Shanks"], correct: 0, hint: "Soul-stealing emperor who loves sweets", level: 4 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/10/366059.jpg", options: ["Katakuri", "Luffy", "Doflamingo", "Cracker"], correct: 0, hint: "Mochi man perfect observation haki", level: 4 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/4/265801.jpg", options: ["Whitebeard", "Roger", "Kaido", "Shanks"], correct: 0, hint: "Strongest man quake fruit old era emperor", level: 4 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/8/389051.jpg", options: ["Hawks", "Endeavor", "Dabi", "Mirko"], correct: 0, hint: "Number two winged hero double agent", level: 4 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/5/389053.jpg", options: ["Endeavor", "Hawks", "All Might", "Todoroki"], correct: 0, hint: "Flame hero number one abusive father", level: 4 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/6/370483.jpg", options: ["Yami Sukehiro", "Asta", "Yuno", "Julius"], correct: 0, hint: "Dark magic captain surpass your limits", level: 4 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/8/370485.jpg", options: ["Yuno", "Asta", "Yami", "Noelle"], correct: 0, hint: "Wind spirit magic golden dawn prodigy", level: 4 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/10/389055.jpg", options: ["Maki Zenin", "Nobara", "Mai", "Toge"], correct: 0, hint: "Non-cursed energy warrior heavenly restriction", level: 4 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/12/389057.jpg", options: ["Nobara Kugisaki", "Maki", "Yuji", "Megumi"], correct: 0, hint: "Straw doll hammer nails sorcerer", level: 4 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/14/389059.jpg", options: ["Yuta Okkotsu", "Gojo", "Yuji", "Megumi"], correct: 0, hint: "Special grade with cursed queen Rika", level: 4 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/6/286651.jpg", options: ["Netero", "Meruem", "Ging", "Zeno"], correct: 0, hint: "Chairman with 100-type Guanyin Bodhisattva", level: 4 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/8/286653.jpg", options: ["Ging Freecss", "Gon", "Kite", "Netero"], correct: 0, hint: "Legendary hunter deadbeat dad", level: 4 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/7/253407.jpg", options: ["Armin Arlert", "Eren", "Erwin", "Levi"], correct: 0, hint: "Colossal inheritor tactician of scouts", level: 4 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/12/310309.jpg", options: ["Broly", "Goku", "Vegeta", "Jiren"], correct: 0, hint: "Legendary Super Saiyan berserker", level: 4 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/2/366061.jpg", options: ["Gol D. Roger", "Whitebeard", "Shanks", "Rayleigh"], correct: 0, hint: "Pirate King who started the great era", level: 4 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/7/354375.jpg", options: ["Petelgeuse", "Subaru", "Emilia", "Roswaal"], correct: 0, hint: "Sloth Archbishop desu brain trembling", level: 4 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/4/258271.jpg", options: ["Holo", "Spice", "Wolf", "Raphtalia"], correct: 0, hint: "Wise wolf harvest deity of economics", level: 4 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/7/394413.jpg", options: ["Power", "Denji", "Makima", "Aki"], correct: 0, hint: "Blood fiend Nobel Prize horns chaotic", level: 4 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/5/394415.jpg", options: ["Denji", "Power", "Aki", "Makima"], correct: 0, hint: "Chainsaw man poor devil hybrid boy", level: 4 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/3/394417.jpg", options: ["Makima", "Power", "Denji", "Reze"], correct: 0, hint: "Control devil manipulative red-haired boss", level: 4 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/9/394419.jpg", options: ["Aki Hayakawa", "Denji", "Power", "Angel"], correct: 0, hint: "Future devil contract topknot hunter", level: 4 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/10/397305.jpg", options: ["Senku Ishigami", "Chrome", "Tsukasa", "Gen"], correct: 0, hint: "Ten billion percent science revival genius", level: 4 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/4/411051.jpg", options: ["Frieren", "Fern", "Himmel", "Stark"], correct: 0, hint: "Thousand-year elf mage mourning hero", level: 4 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/11/316501.jpg", options: ["Gilgamesh", "Saber", "Archer", "Lancer"], correct: 0, hint: "King of Heroes Gate of Babylon", level: 4 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/9/316503.jpg", options: ["Saber", "Gilgamesh", "Rin", "Shirou"], correct: 0, hint: "King Arthur holy sword Excalibur", level: 4 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/7/351649.jpg", options: ["Rimuru Tempest", "Ainz", "Subaru", "Naofumi"], correct: 0, hint: "Slime isekai ruler of Jura Tempest", level: 4 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/6/293837.jpg", options: ["Komugi", "Meruem", "Neferpitou", "Pouf"], correct: 0, hint: "Blind Gungi champion who touched a king", level: 4 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/8/411053.jpg", options: ["Fern", "Frieren", "Stark", "Serie"], correct: 0, hint: "Frieren's apprentice talented young mage", level: 4 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/11/349453.jpg", options: ["Naofumi Iwatani", "Raphtalia", "Filo", "Ren"], correct: 0, hint: "Shield Hero wrongly accused isekai", level: 4 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/3/307607.jpg", options: ["Goblin Slayer", "Naofumi", "Guts", "Kirito"], correct: 0, hint: "Helmet never off only slays goblins", level: 4 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/13/349455.jpg", options: ["Raphtalia", "Naofumi", "Filo", "Melty"], correct: 0, hint: "Raccoon demi-human sword wielder companion", level: 4 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/4/301735.jpg", options: ["Shinji Ikari", "Asuka", "Rei", "Kaworu"], correct: 0, hint: "Get in the robot reluctant Eva pilot", level: 4 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/6/301737.jpg", options: ["Asuka Langley", "Rei", "Shinji", "Misato"], correct: 0, hint: "Fiery redhead Eva Unit 02 pilot", level: 4 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/8/301739.jpg", options: ["Rei Ayanami", "Asuka", "Shinji", "Kaworu"], correct: 0, hint: "Blue-haired mysterious clone pilot", level: 4 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/10/263771.jpg", options: ["Kenpachi Zaraki", "Ichigo", "Byakuya", "Yamamoto"], correct: 0, hint: "Battle-crazed captain lives for fighting", level: 4 },
];
