export default [
  { level: 3, silhouette: '🎭', hints: ['Wears a white mask', 'Leader of Akatsuki secretly', 'Manipulated the ninja world'], answer: 'Obito Uchiha', anime: 'Naruto' },
  { level: 3, silhouette: '🦇', hints: ['Upper Moon demon', 'King of Demons', 'Created all other demons'], answer: 'Muzan Kibutsuji', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🌕', hints: ['Upper Moon Three', 'Strongest Upper Moon', 'Has multiple fighting forms'], answer: 'Akaza', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🎻', hints: ['Played violin beautifully', 'Brought color to a pianist\'s world', 'Passed away young'], answer: 'Kaori Miyazono', anime: 'Your Lie in April' },
  { level: 3, silhouette: '📱', hints: ['Mad scientist', 'Sends texts to the past', 'El Psy Kongroo'], answer: 'Rintaro Okabe', anime: 'Steins;Gate' },
  { level: 3, silhouette: '🧪', hints: ['Lab coat wearing girl', 'Assistant to Okabe', 'Tuturu!'], answer: 'Mayuri Shiina', anime: 'Steins;Gate' },
  { level: 3, silhouette: '💻', hints: ['Super hacker', 'Christina nickname she hates', 'Time travel researcher'], answer: 'Kurisu Makise', anime: 'Steins;Gate' },
  { level: 3, silhouette: '🗡️', hints: ['Black swordsman', 'Trapped in a death game', 'Dual-wielding player'], answer: 'Kirito', anime: 'Sword Art Online' },
  { level: 3, silhouette: '🧚', hints: ['Flash user in SAO', 'Lightning fast rapier', 'Sub-leader of Knights of Blood'], answer: 'Asuna', anime: 'Sword Art Online' },
  { level: 3, silhouette: '👑', hints: ['Prince who became emperor', 'Geass power in left eye', 'Created Zero identity'], answer: 'Lelouch Lamperouge', anime: 'Code Geass' },
  { level: 3, silhouette: '🦿', hints: ['Knightmare pilot', 'Best friend turned enemy', 'Japanese honorary Britannian'], answer: 'Suzaku Kururugi', anime: 'Code Geass' },
  { level: 3, silhouette: '🐍', hints: ['Controls snakes', 'Has a split personality', 'Green-haired witch'], answer: 'Medusa Gorgon', anime: 'Soul Eater' },
  { level: 3, silhouette: '🌙', hints: ['Moonlight sword technique', 'Upper Moon One', 'Brother to a legend'], answer: 'Kokushibo', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🎪', hints: ['Ringmaster of chaos', 'Cursed spirit user', 'Patchwork face villain'], answer: 'Suguru Geto', anime: 'Jujutsu Kaisen' },
  { level: 3, silhouette: '🧠', hints: ['Genius tactician', 'Plays shogi', 'Lazy but deadly smart'], answer: 'Shikamaru Nara', anime: 'Naruto' },
  { level: 3, silhouette: '🦋', hints: ['Uses paper jutsu', 'Angel of Hidden Rain', 'Member of original Akatsuki'], answer: 'Konan', anime: 'Naruto' },
  { level: 3, silhouette: '🎭', hints: ['Art is an explosion', 'Uses clay bombs', 'Akatsuki member from Iwagakure'], answer: 'Deidara', anime: 'Naruto' },
  { level: 3, silhouette: '🪡', hints: ['Puppet master', 'Turned himself into a puppet', 'Akatsuki partner to Deidara'], answer: 'Sasori', anime: 'Naruto' },
  { level: 3, silhouette: '💰', hints: ['Immortal bounty hunter', 'Worships Jashin', 'Rituals require blood'], answer: 'Hidan', anime: 'Naruto' },
  { level: 3, silhouette: '💵', hints: ['Five hearts', 'Akatsuki treasurer', 'Oldest human member'], answer: 'Kakuzu', anime: 'Naruto' },
  { level: 3, silhouette: '🦈', hints: ['Blue-skinned swordsman', 'Wields Samehada', 'Former Seven Swordsmen member'], answer: 'Kisame Hoshigaki', anime: 'Naruto' },
  { level: 3, silhouette: '🌿', hints: ['Half black half white', 'Plant-like appearance', 'Spy for Akatsuki'], answer: 'Zetsu', anime: 'Naruto' },
  { level: 3, silhouette: '☁️', hints: ['Cloud nine attitude', 'Female titan shifter', 'Trained with Eren'], answer: 'Annie Leonhart', anime: 'Attack on Titan' },
  { level: 3, silhouette: '🐎', hints: ['Armored Titan', 'Betrayed his comrades', 'Warrior from Marley'], answer: 'Reiner Braun', anime: 'Attack on Titan' },
  { level: 3, silhouette: '🦍', hints: ['Beast Titan', 'Throws rocks with precision', 'Eren\'s half-brother'], answer: 'Zeke Yeager', anime: 'Attack on Titan' },
  { level: 3, silhouette: '🐦', hints: ['Doves are his symbol', 'White-haired investigator', 'Turned half-ghoul'], answer: 'Ken Kaneki', anime: 'Tokyo Ghoul' },
  { level: 3, silhouette: '☕', hints: ['Runs a coffee shop', 'SSS-rated ghoul', 'The One-Eyed Owl father'], answer: 'Yoshimura', anime: 'Tokyo Ghoul' },
  { level: 3, silhouette: '🐰', hints: ['Rabbit mask', 'Fights for ghoul rights', 'Blue-haired waitress'], answer: 'Touka Kirishima', anime: 'Tokyo Ghoul' },
  { level: 3, silhouette: '⚗️', hints: ['Human transmutation attempt', 'Father of homunculi', 'Dwarf in the flask'], answer: 'Father', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '😈', hints: ['Homunculus of Lust', 'Ultimate spear fingers', 'Seductive and deadly'], answer: 'Lust', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '😤', hints: ['Homunculus of Wrath', 'King Bradley', 'Fuhrer of Amestris'], answer: 'King Bradley', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '😏', hints: ['Homunculus of Envy', 'Shape-shifter', 'Started the Ishval war'], answer: 'Envy', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '🗡️', hints: ['Wielder of Tessaiga', 'Half-demon dog', 'Sealed to a tree for 50 years'], answer: 'Inuyasha', anime: 'Inuyasha' },
  { level: 3, silhouette: '🏹', hints: ['Priestess reincarnation', 'Time-traveling schoolgirl', 'Can sense jewel shards'], answer: 'Kagome Higurashi', anime: 'Inuyasha' },
  { level: 3, silhouette: '🌀', hints: ['Wind tunnel in his hand', 'Cursed by Naraku', 'Monk with wandering hands'], answer: 'Miroku', anime: 'Inuyasha' },
  { level: 3, silhouette: '🦴', hints: ['Demon slayer warrior', 'Giant boomerang weapon', 'Brother was controlled'], answer: 'Sango', anime: 'Inuyasha' },
  { level: 3, silhouette: '🎭', hints: ['Gourmet ghoul', 'Obsessed with Kaneki', 'From a wealthy family'], answer: 'Shuu Tsukiyama', anime: 'Tokyo Ghoul' },
  { level: 3, silhouette: '🍽️', hints: ['Homunculus of Gluttony', 'Eats anything', 'Childlike but deadly'], answer: 'Gluttony', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '😴', hints: ['Homunculus of Sloth', 'Incredibly fast despite laziness', 'Tunneled under the country'], answer: 'Sloth', anime: 'Fullmetal Alchemist' },
  { level: 3, silhouette: '🎭', hints: ['War Hammer Titan', 'Noble family from Marley', 'Crystal-based powers'], answer: 'Lara Tybur', anime: 'Attack on Titan' },
  { level: 3, silhouette: '🐉', hints: ['Full demon lord brother', 'Wields Bakusaiga', 'Travels with a human girl'], answer: 'Sesshomaru', anime: 'Inuyasha' },
  { level: 3, silhouette: '🕷️', hints: ['Main villain of Inuyasha', 'Created from human desires', 'Half-demon shapeshifter'], answer: 'Naraku', anime: 'Inuyasha' },
  { level: 3, silhouette: '🪭', hints: ['Wind sorceress', 'Created by Naraku', 'Desires freedom'], answer: 'Kagura', anime: 'Inuyasha' },
  { level: 3, silhouette: '🪞', hints: ['Void demon child', 'Controls a mirror', 'Created by Naraku'], answer: 'Kanna', anime: 'Inuyasha' },
  { level: 3, silhouette: '🗡️', hints: ['Legendary swordsmith ancestor', 'Created special blades', 'Demon Slayer Corps founder'], answer: 'Yoriichi Tsugikuni', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🎭', hints: ['Upper Moon Two', 'Rainbow-eyed demon', 'Cult leader personality'], answer: 'Doma', anime: 'Demon Slayer' },
  { level: 3, silhouette: '💔', hints: ['Upper Moon Six pair', 'Brother and sister demons', 'Tragic backstory'], answer: 'Gyutaro & Daki', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🔥', hints: ['Flame Hashira', 'Set his heart ablaze', 'Died on the Mugen Train'], answer: 'Kyojuro Rengoku', anime: 'Demon Slayer' },
  { level: 3, silhouette: '💜', hints: ['Love Hashira', 'Unique muscle composition', 'Cherry blossom mochi hair'], answer: 'Mitsuri Kanroji', anime: 'Demon Slayer' },
  { level: 3, silhouette: '🌬️', hints: ['Wind Hashira', 'Scarred face', 'Hot-tempered and aggressive'], answer: 'Sanemi Shinazugawa', anime: 'Demon Slayer' },
];
