export default [
  { level: 4, silhouette: '🎭', hints: ['Wears a plague doctor mask', 'From a chaotic world', 'Searches for his original face'], answer: 'Caiman', anime: 'Dorohedoro' },
  { level: 4, silhouette: '🧵', hints: ['Controls threads', 'Wears a flamingo coat', 'King of Dressrosa'], answer: 'Donquixote Doflamingo', anime: 'One Piece' },
  { level: 4, silhouette: '⚓', hints: ['Strongest man in the world', 'Earthquake powers', 'Father to his crew'], answer: 'Edward Newgate/Whitebeard', anime: 'One Piece' },
  { level: 4, silhouette: '🎩', hints: ['Gravity fruit user', 'Admiral of Marines', 'Wears a purple outfit'], answer: 'Fujitora/Issho', anime: 'One Piece' },
  { level: 4, silhouette: '🌋', hints: ['Magma fist user', 'Killed Ace', 'Became Fleet Admiral'], answer: 'Sakazuki/Akainu', anime: 'One Piece' },
  { level: 4, silhouette: '💫', hints: ['Light-speed kicks', 'Admiral Kizaru', 'Always seems relaxed'], answer: 'Borsalino/Kizaru', anime: 'One Piece' },
  { level: 4, silhouette: '🐊', hints: ['Sand-sand fruit user', 'Warlord of the Sea', 'Tried to take over Alabasta'], answer: 'Crocodile', anime: 'One Piece' },
  { level: 4, silhouette: '🦩', hints: ['Transforms into a phoenix', 'First division commander', 'Whitebeard Pirate'], answer: 'Marco', anime: 'One Piece' },
  { level: 4, silhouette: '🎻', hints: ['Plays deadly music', 'Curse technique uses sound', 'Jujutsu Kaisen villain'], answer: 'Jogo', anime: 'Jujutsu Kaisen' },
  { level: 4, silhouette: '🌊', hints: ['Ocean curse spirit', 'Domain Expansion user', 'Fought Gojo'], answer: 'Dagon', anime: 'Jujutsu Kaisen' },
  { level: 4, silhouette: '🌺', hints: ['Curse of the forest', 'Flower-like appearance', 'Special grade curse'], answer: 'Hanami', anime: 'Jujutsu Kaisen' },
  { level: 4, silhouette: '🧵', hints: ['Heavenly Restriction', 'No cursed energy', 'Peak physical abilities'], answer: 'Toji Fushiguro', anime: 'Jujutsu Kaisen' },
  { level: 4, silhouette: '🎭', hints: ['Anime director persona', 'Brain swap villain', 'Took over a sorcerer body'], answer: 'Kenjaku', anime: 'Jujutsu Kaisen' },

  { level: 4, silhouette: '🗡️', hints: ['Wandering swordsman', 'Cross-shaped scar', 'Former assassin who vowed never to kill'], answer: 'Kenshin Himura', anime: 'Rurouni Kenshin' },
  { level: 4, silhouette: '🎵', hints: ['Jazz-loving bounty hunter', 'See you space cowboy', 'Jeet Kune Do fighter'], answer: 'Spike Spiegel', anime: 'Cowboy Bebop' },
  { level: 4, silhouette: '🔧', hints: ['Former cop turned bounty hunter', 'Has a prosthetic arm', 'Pilots the Bebop ship'], answer: 'Jet Black', anime: 'Cowboy Bebop' },
  { level: 4, silhouette: '🐕', hints: ['Data dog', 'Welsh Corgi', 'Smartest crew member on Bebop'], answer: 'Ein', anime: 'Cowboy Bebop' },
  { level: 4, silhouette: '🍄', hints: ['Eccentric mushroom lover', 'Radical Edward', 'Hacker prodigy on the Bebop'], answer: 'Edward Wong', anime: 'Cowboy Bebop' },
  { level: 4, silhouette: '🔫', hints: ['Female bounty hunter', 'Amnesiac past', 'Uses a Glock on the Bebop'], answer: 'Faye Valentine', anime: 'Cowboy Bebop' },
  { level: 4, silhouette: '🎭', hints: ['Serial killer artist', 'Loves darkness', 'Phantom Troupe member #4'], answer: 'Feitan', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '🕷️', hints: ['Leader of Phantom Troupe', 'Spider tattoo', 'Specialist Nen user'], answer: 'Chrollo Lucilfer', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '💪', hints: ['Enhancement Nen user', 'Strongest in physical combat', 'Troupe member who arm wrestles'], answer: 'Uvogin', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '🎯', hints: ['Gungi champion', 'Blind girl', 'Taught Meruem compassion'], answer: 'Komugi', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '🐈', hints: ['Cat Chimera Ant', 'Royal Guard', 'Shapeshifts using memories'], answer: 'Neferpitou', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '🛡️', hints: ['Royal Guard of the King', 'Centaur-like form', 'Most loyal to Meruem'], answer: 'Shaiapouf', anime: 'Hunter x Hunter' },
  { level: 4, silhouette: '🌿', hints: ['Mushi Master', 'Wanders helping people', 'One functioning eye'], answer: 'Ginko', anime: 'Mushishi' },
  { level: 4, silhouette: '📝', hints: ['Auto Memory Doll', 'Former soldier', 'Has prosthetic metal hands'], answer: 'Violet Evergarden', anime: 'Violet Evergarden' },
  { level: 4, silhouette: '🎪', hints: ['Circus performer background', 'Wields twin blades', 'Black Butler demon servant'], answer: 'Sebastian Michaelis', anime: 'Black Butler' },
  { level: 4, silhouette: '👁️', hints: ['Contract with a demon', 'Eye patch wearing noble', 'Queen\'s watchdog'], answer: 'Ciel Phantomhive', anime: 'Black Butler' },
  { level: 4, silhouette: '🐺', hints: ['Wise wolf deity', 'Takes human form', 'Travels with a merchant'], answer: 'Holo', anime: 'Spice and Wolf' },
  { level: 4, silhouette: '📦', hints: ['Traveling merchant', 'Deals in economics', 'Partner to a wolf goddess'], answer: 'Kraft Lawrence', anime: 'Spice and Wolf' },
  { level: 4, silhouette: '🌸', hints: ['Spirit seer', 'Returns names from a book', 'Lives with a cat spirit'], answer: 'Takashi Natsume', anime: "Natsume's Book of Friends" },
  { level: 4, silhouette: '🐱', hints: ['Lucky cat spirit', 'Bodyguard role', 'Drinks sake and is round'], answer: 'Madara/Nyanko-sensei', anime: "Natsume's Book of Friends" },
  { level: 4, silhouette: '💀', hints: ['Overlord of Nazarick', 'Skeleton mage', 'Trapped in a game as his character'], answer: 'Ainz Ooal Gown', anime: 'Overlord' },
  { level: 4, silhouette: '😈', hints: ['Floor Guardian', 'Succubus demon', 'Obsessed with her master'], answer: 'Albedo', anime: 'Overlord' },
  { level: 4, silhouette: '🐛', hints: ['Floor Guardian insect', 'Battle maid commander', 'Cocytus-like warrior'], answer: 'Cocytus', anime: 'Overlord' },
  { level: 4, silhouette: '🎭', hints: ['Dark elf twins Floor Guardian', 'Prankster personality', 'Aura and Mare'], answer: 'Aura Bella Fiora', anime: 'Overlord' },
  { level: 4, silhouette: '🧊', hints: ['Vampire Floor Guardian', 'True vampire', 'Shalltear Bloodfallen'], answer: 'Shalltear Bloodfallen', anime: 'Overlord' },
  { level: 4, silhouette: '🌙', hints: ['Half-elf', 'Silver-haired spirit user', 'Candidate to be ruler'], answer: 'Emilia', anime: 'Re:Zero' },
  { level: 4, silhouette: '🐈‍⬛', hints: ['Spirit companion', 'Can be tiny or huge', 'Protects Emilia'], answer: 'Puck', anime: 'Re:Zero' },

  { level: 4, silhouette: '🤡', hints: ['Sin Archbishop of Sloth', 'Truly slothful', 'Betelgeuse is his name'], answer: 'Petelgeuse Romanee-Conti', anime: 'Re:Zero' },
  { level: 4, silhouette: '📦', hints: ['Subaru from another world', 'Return by Death power', 'Track suit wearing protagonist'], answer: 'Subaru Natsuki', anime: 'Re:Zero' },
  { level: 4, silhouette: '🌸', hints: ['Cherry blossom theme', 'Captain of Squad 6', 'Noble family head'], answer: 'Byakuya Kuchiki', anime: 'Bleach' },
  { level: 4, silhouette: '🐱', hints: ['Cat-like transformation', 'Squad 2 captain', 'Flash goddess'], answer: 'Yoruichi Shihoin', anime: 'Bleach' },
  { level: 4, silhouette: '🎭', hints: ['Shopkeeper with a hat', 'Former captain', 'Created the Hogyoku'], answer: 'Kisuke Urahara', anime: 'Bleach' },
  { level: 4, silhouette: '🦋', hints: ['Betrayed Soul Society', 'Achieved god-like form', 'Master of illusions'], answer: 'Sosuke Aizen', anime: 'Bleach' },
  { level: 4, silhouette: '☠️', hints: ['Espada number 4', 'Ulquiorra', 'Nihilistic and cold'], answer: 'Ulquiorra Cifer', anime: 'Bleach' },
  { level: 4, silhouette: '🔵', hints: ['Espada number 6', 'Grimmjow', 'Blue hair panther king'], answer: 'Grimmjow Jaegerjaquez', anime: 'Bleach' },
  { level: 4, silhouette: '🐺', hints: ['Captain of Squad 10', 'Ice dragon bankai', 'Youngest captain ever'], answer: 'Toshiro Hitsugaya', anime: 'Bleach' },
  { level: 4, silhouette: '🎭', hints: ['Captain of Squad 12', 'Mad scientist', 'Painted face'], answer: 'Mayuri Kurotsuchi', anime: 'Bleach' },
];
