export default [
  { text: "Which Sternritter was known as “The Visionary”?", options: ["Jugram", "Lille", "Gremmy", "Askin"], correct: 2 },
  { text: "Which Hashira officially had the fastest running speed?", options: ["Sanemi", "Giyu", "Tengen", "Muichiro"], correct: 2 },
  { text: "Which chapter first mentioned Joy Boy by name?", options: ["628", "700", "800", "1044"], correct: 0 },
  { text: "Which Bleach arc introduced Fullbringers?", options: ["Soul Society", "Arrancar", "Lost Agent", "TYBW"], correct: 2 },
  { text: "Which JoJo Stand manipulates weather unconsciously?", options: ["Whitesnake", "Weather Report", "Made in Heaven", "King Crimson"], correct: 1 },
  { text: "Which chapter revealed Itachi’s illness?", options: ["390", "395", "401", "410"], correct: 2 },
  { text: "What is the release command for Kyoka Suigetsu?", options: ["Bloom", "Fly", "Scatter", "Shatter"], correct: 3 },
  { text: "Which One Piece SBS confirmed Zoro’s real-world nationality?", options: ["SBS 40", "SBS 56", "SBS 70", "SBS 90"], correct: 1 },
  { text: "Which JoJo arc introduced the Spin power system?", options: ["Stardust Crusaders", "Stone Ocean", "Steel Ball Run", "JoJolion"], correct: 2 },
  { text: "Which Bleach captain used Konjiki Ashisogi Jizo?", options: ["Gin", "Byakuya", "Mayuri", "Komamura"], correct: 2 },
  { text: "Which Demon Slayer Hashira had the weakest physical strength officially?", options: ["Shinobu", "Mitsuri", "Muichiro", "Obanai"], correct: 0 },
  { text: "Which Naruto databook confirmed Minato’s mission totals?", options: ["Databook 1", "Databook 2", "Databook 3", "Databook 4"], correct: 3 },
  { text: "Which Hunter x Hunter volume introduced Beyond Netero?", options: ["30", "31", "32", "33"], correct: 2 },
  { text: "Which One Piece island changes climate every season?", options: ["Zou", "Punk Hazard", "Little Garden", "Elbaf"], correct: 2 },
  { text: "Which JoJo protagonist never directly defeated the final villain?", options: ["Jotaro", "Jonathan", "Giorno", "Josuke"], correct: 1 },
  { text: "Which Bleach Espada used Respira?", options: ["Grimmjow", "Ulquiorra", "Baraggan", "Stark"], correct: 2 },
  { text: "Which Naruto opening featured “Sign”?", options: ["Opening 4", "Opening 5", "Opening 6", "Opening 7"], correct: 2 },
  { text: "Which JoJo Stand evolved into C-Moon?", options: ["Star Platinum", "Whitesnake", "Killer Queen", "Stone Free"], correct: 1 },
  { text: "Which Titan can inherit future memories?", options: ["Founding Titan", "Attack Titan", "Jaw Titan", "Beast Titan"], correct: 1 },
  { text: "Which anime features the Sibyl System?", options: ["Ergo Proxy", "Monster", "Psycho-Pass", "Pluto"], correct: 2 },
  { text: "Which Fullmetal Alchemist opening was by L’Arc-en-Ciel?", options: ["Again", "Rewrite", "Ready Steady Go", "Rain"], correct: 2 },
  { text: "Which JoJo villain reset the universe?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 3 },
  { text: "Which One Piece chapter revealed Gear 5?", options: ["1040", "1042", "1044", "1046"], correct: 2 },
  { text: "Which Naruto character naturally awakened the Rinnegan?", options: ["Sasuke", "Obito", "Madara", "Nagato"], correct: 2 },
  { text: "Which Bleach captain became a Visored leader?", options: ["Rose", "Kensei", "Love", "Shinji"], correct: 3 },
  { text: "Which Demon Slayer Upper Moon ranked first?", options: ["Doma", "Akaza", "Kokushibo", "Gyokko"], correct: 2 },
  { text: "Which JoJo Stand has contradictory stats according to Araki?", options: ["Star Platinum", "Killer Queen", "GER", "Tusk Act 4"], correct: 2 },
  { text: "Which Attack on Titan character improved ODM technology?", options: ["Hange", "Levi", "Angel Aaltonen", "Erwin"], correct: 2 },
  { text: "Which Hunter x Hunter character becomes a Specialist under Emperor Time?", options: ["Gon", "Kurapika", "Killua", "Leorio"], correct: 1 },
  { text: "Which One Piece Emperor stopped the Marineford war?", options: ["Kaido", "Big Mom", "Shanks", "Blackbeard"], correct: 2 },
  { text: "Which Bleach villain controlled complete hypnosis?", options: ["Yhwach", "Ulquiorra", "Aizen", "Gin"], correct: 2 },
  { text: "Which Naruto eye technique trapped the world in illusion?", options: ["Izanagi", "Tsukuyomi", "Infinite Tsukuyomi", "Kamui"], correct: 2 },
  { text: "Which anime features Anti-Spirals?", options: ["Evangelion", "FLCL", "Gurren Lagann", "Akira"], correct: 2 },
  { text: "Which JoJo villain used King Crimson?", options: ["Dio", "Kira", "Pucci", "Diavolo"], correct: 3 },
  { text: "Which One Piece character first mentioned Nika directly?", options: ["Kaido", "Vegapunk", "Shanks", "Who’s-Who"], correct: 3 },
  { text: "Which Bleach character used Kamishini no Yari?", options: ["Renji", "Aizen", "Gin", "Tosen"], correct: 2 },
  { text: "Which Naruto character used all five chakra natures naturally?", options: ["Naruto", "Kakashi", "Hiruzen", "Sasuke"], correct: 2 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Election Arc", "Yorknew Arc", "Chimera Ant Arc", "Greed Island Arc"], correct: 2 },
  { text: "Which JoJo part introduced the Arrow?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which anime movie won Studio Ghibli an Oscar?", options: ["Ponyo", "Spirited Away", "Mononoke", "Howl’s Moving Castle"], correct: 1 },
  { text: "Which Bleach arc introduced Yhwach?", options: ["Soul Society Arc", "Arrancar Arc", "TYBW Arc", "Lost Agent Arc"], correct: 2 },
  { text: "Which JoJo protagonist used the Spin technique?", options: ["Giorno", "Josuke", "Johnny Joestar", "Jonathan"], correct: 2 },
  { text: "Which Attack on Titan Titan is Annie?", options: ["Jaw Titan", "Female Titan", "Cart Titan", "Beast Titan"], correct: 1 },
  { text: "Which Naruto clan does Hinata belong to?", options: ["Senju", "Uchiha", "Hyuga", "Uzumaki"], correct: 2 },
  { text: "Which Demon Slayer Hashira uses Sound Breathing?", options: ["Obanai", "Sanemi", "Tengen", "Gyomei"], correct: 2 },
  { text: "Which One Piece character is called the “Strongest Creature”?", options: ["Whitebeard", "Kaido", "Blackbeard", "Roger"], correct: 1 },
  { text: "Which Bleach Espada was Ulquiorra?", options: ["2nd", "3rd", "4th", "5th"], correct: 2 },
  { text: "Which JoJo Stand belongs to Weather Report?", options: ["Stone Free", "Whitesnake", "Weather Report", "Soft & Wet"], correct: 2 },
  { text: "Which anime features the Eclipse event?", options: ["Berserk", "Claymore", "Hellsing", "Vinland Saga"], correct: 0 },
  { text: "Which Hunter x Hunter character uses Bungee Gum?", options: ["Chrollo", "Illumi", "Hisoka", "Feitan"], correct: 2 },
  { text: "Which Naruto villain led the Akatsuki publicly?", options: ["Obito", "Madara", "Pain", "Zetsu"], correct: 2 }
];