export default [
  { level: 5, silhouette: '🎭', hints: ['The nameless monster', 'Blonde German boy', 'Perfect psychopath'], answer: 'Johan Liebert', anime: 'Monster' },
  { level: 5, silhouette: '🔬', hints: ['Japanese doctor in Germany', 'Saved a boy who became a killer', 'Hunts his former patient'], answer: 'Kenzo Tenma', anime: 'Monster' },
  { level: 5, silhouette: '🌐', hints: ['Connected to the Wired', 'Young girl with technology', 'Blurs reality and internet'], answer: 'Lain Iwakura', anime: 'Serial Experiments Lain' },
  { level: 5, silhouette: '🎬', hints: ['Pop idol turned actress', 'Stalked by a fan', 'Questions her own reality'], answer: 'Mima Kirigoe', anime: 'Perfect Blue' },
  { level: 5, silhouette: '🦾', hints: ['Full cyborg body', 'Section 9 leader', 'Philosopher of consciousness'], answer: 'Major Motoko Kusanagi', anime: 'Ghost in the Shell' },
  { level: 5, silhouette: '🤖', hints: ['Think tank AI', 'Spider-like robot', 'Develops individuality'], answer: 'Tachikoma', anime: 'Ghost in the Shell' },
  { level: 5, silhouette: '🌪️', hints: ['Princess of the Valley', 'Rides a glider', 'Communicates with giant insects'], answer: 'Nausicaa', anime: 'Nausicaa of the Valley of the Wind' },
  { level: 5, silhouette: '🐺', hints: ['Raised by wolves', 'Forest spirit protector', 'Hates humans'], answer: 'San', anime: 'Princess Mononoke' },
  { level: 5, silhouette: '✈️', hints: ['Pilot turned pig', 'Italian bounty hunter', 'Refuses to join fascists'], answer: 'Porco Rosso', anime: 'Porco Rosso' },
  { level: 5, silhouette: '🧙', hints: ['Moving castle wizard', 'Vain about appearance', 'Fire demon contract'], answer: 'Howl', anime: "Howl's Moving Castle" },
  { level: 5, silhouette: '🔥', hints: ['Fire demon', 'Powers the castle', 'Contract with a wizard'], answer: 'Calcifer', anime: "Howl's Moving Castle" },
  { level: 5, silhouette: '👵', hints: ['Cursed to be old', 'Cleaning lady in castle', 'Young girl transformed'], answer: 'Sophie Hatter', anime: "Howl's Moving Castle" },

  { level: 5, silhouette: '🚂', hints: ['Bathhouse worker', 'Parents turned to pigs', 'Befriended a river spirit'], answer: 'Chihiro/Sen', anime: 'Spirited Away' },
  { level: 5, silhouette: '🐉', hints: ['River spirit in human form', 'Forgot his real name', 'Serves a witch'], answer: 'Haku', anime: 'Spirited Away' },
  { level: 5, silhouette: '👤', hints: ['No-Face spirit', 'Offers gold to people', 'Becomes what he eats'], answer: 'No-Face', anime: 'Spirited Away' },
  { level: 5, silhouette: '🌿', hints: ['Forest spirit', 'Giant fluffy creature', 'Only visible to children'], answer: 'Totoro', anime: 'My Neighbor Totoro' },
  { level: 5, silhouette: '🐈‍⬛', hints: ['Black cat companion', 'Cannot fly temporarily', 'Belongs to a delivery witch'], answer: 'Jiji', anime: "Kiki's Delivery Service" },
  { level: 5, silhouette: '🧹', hints: ['Young witch on her own', 'Delivery service business', 'Loses her flying ability'], answer: 'Kiki', anime: "Kiki's Delivery Service" },
  { level: 5, silhouette: '🎭', hints: ['Paranoia Agent villain', 'Bat-wielding kid on skates', 'Urban legend attacker'], answer: 'Lil Slugger/Shonen Bat', anime: 'Paranoia Agent' },
  { level: 5, silhouette: '🌈', hints: ['Dream detective', 'Enters people\'s dreams', 'Uses a device called DC Mini'], answer: 'Paprika/Dr. Chiba', anime: 'Paprika' },
  { level: 5, silhouette: '🎭', hints: ['Proxy of Romdo', 'Seeks the truth', 'In a post-apocalyptic dome city'], answer: 'Re-l Mayer', anime: 'Ergo Proxy' },
  { level: 5, silhouette: '🤔', hints: ['Immigrant Proxy', 'Searches for memories', 'Vincent Law'], answer: 'Vincent Law', anime: 'Ergo Proxy' },
  { level: 5, silhouette: '⚰️', hints: ['Immortal alchemist', 'On a train in the 1930s', 'Cannot die no matter what'], answer: 'Firo Prochainezo', anime: 'Baccano!' },
  { level: 5, silhouette: '🔪', hints: ['Crazy knife wielder', 'Psychopath on a train', 'Rail Tracer identity'], answer: 'Claire Stanfield', anime: 'Baccano!' },
  { level: 5, silhouette: '🎩', hints: ['Gentleman thief', 'Master of disguise', 'Blue jacket version'], answer: 'Arsene Lupin III', anime: 'Lupin III' },
  { level: 5, silhouette: '🗡️', hints: ['Samurai retainer', 'Goemon style', 'Cuts anything with his blade'], answer: 'Goemon Ishikawa', anime: 'Lupin III' },
  { level: 5, silhouette: '🌙', hints: ['Vampire hunter', 'Dhampir', 'Son of Dracula'], answer: 'D', anime: 'Vampire Hunter D' },
  { level: 5, silhouette: '🎻', hints: ['Counts stars', 'Philosophical robot', 'Post-apocalyptic journey'], answer: 'Casshern', anime: 'Casshern Sins' },
  { level: 5, silhouette: '🏍️', hints: ['Motorcycle traveler', 'Visits one country per episode', 'The world is not beautiful'], answer: 'Kino', anime: "Kino's Journey" },
  { level: 5, silhouette: '🗣️', hints: ['Talking motorcycle', 'Kino\'s partner', 'Named Hermes'], answer: 'Hermes', anime: "Kino's Journey" },
  { level: 5, silhouette: '💎', hints: ['Gem person', 'Breaks easily', 'Phosphophyllite'], answer: 'Phosphophyllite', anime: 'Land of the Lustrous' },
  { level: 5, silhouette: '🌑', hints: ['Buddhist monk on the moon', 'Takes gems away', 'Mysterious antagonist'], answer: 'Lunarians/Sensei', anime: 'Land of the Lustrous' },
  { level: 5, silhouette: '🧸', hints: ['Child soldier', 'Travels with arms dealer', 'From a war-torn country'], answer: 'Jonah', anime: 'Jormungand' },
  { level: 5, silhouette: '💼', hints: ['Arms dealer', 'Always smiling', 'Her world peace plan is extreme'], answer: 'Koko Hekmatyar', anime: 'Jormungand' },
  { level: 5, silhouette: '🔫', hints: ['Two-gun wielding maid', 'From Black Lagoon company', 'Chinese-American gunslinger'], answer: 'Revy', anime: 'Black Lagoon' },
  { level: 5, silhouette: '👔', hints: ['Japanese salaryman turned pirate', 'Negotiator role', 'Rock is his nickname'], answer: 'Rock', anime: 'Black Lagoon' },
  { level: 5, silhouette: '🎭', hints: ['Medicine seller', 'Paints seals on walls', 'Exorcises mononoke spirits'], answer: 'Medicine Seller', anime: 'Mononoke' },
  { level: 5, silhouette: '⚗️', hints: ['Slime reincarnation', 'Names give power', 'Built a monster nation'], answer: 'Rimuru Tempest', anime: 'That Time I Got Reincarnated as a Slime' },
  { level: 5, silhouette: '🧝', hints: ['Elf mage who outlives everyone', 'Collecting spells', 'Traveled with the hero party'], answer: 'Frieren', anime: 'Frieren: Beyond Journey\'s End' },
  { level: 5, silhouette: '🛡️', hints: ['Shield hero', 'Falsely accused', 'Raised a raccoon demi-human'], answer: 'Naofumi Iwatani', anime: 'The Rising of the Shield Hero' },

  { level: 5, silhouette: '🐉', hints: ['Dragon companion', 'Became a maid', 'From another world'], answer: 'Tohru', anime: "Miss Kobayashi's Dragon Maid" },
  { level: 5, silhouette: '👓', hints: ['Office worker', 'Adopted a dragon', 'Programmer'], answer: 'Kobayashi', anime: "Miss Kobayashi's Dragon Maid" },
  { level: 5, silhouette: '🎭', hints: ['Faceless entity', 'Absorbs others abilities', 'Lonely spirit in bathhouse'], answer: 'No-Face', anime: 'Spirited Away' },
  { level: 5, silhouette: '🧙‍♀️', hints: ['Runs the bathhouse', 'Has a giant baby', 'Yubaba is her name'], answer: 'Yubaba', anime: 'Spirited Away' },
  { level: 5, silhouette: '🌊', hints: ['Goldfish wants to be human', 'Loves a boy named Sosuke', 'Studio Ghibli fish girl'], answer: 'Ponyo', anime: 'Ponyo' },
  { level: 5, silhouette: '🎭', hints: ['Contracts with magical girls', 'Cute but sinister', 'Kyubey is the name'], answer: 'Kyubey', anime: 'Madoka Magica' },
  { level: 5, silhouette: '💜', hints: ['Time-looping magical girl', 'Did nothing wrong', 'Saved Madoka countless times'], answer: 'Homura Akemi', anime: 'Madoka Magica' },
  { level: 5, silhouette: '💗', hints: ['Became a god', 'Pink-haired magical girl', 'Wished away all witches'], answer: 'Madoka Kaname', anime: 'Madoka Magica' },
  { level: 5, silhouette: '🎻', hints: ['Plays cello alone', 'From a quiet town', 'Practices on the beach'], answer: 'Gauche', anime: 'Gauche the Cellist' },
  { level: 5, silhouette: '🗡️', hints: ['Claymore warrior', 'Number 47', 'Half-human half-Yoma'], answer: 'Clare', anime: 'Claymore' },
];
