export default [
  { text: "LEOUCLH", answer: "LELOUCH", hint: "Geass user and mastermind" },
  { text: "KZUSUA", answer: "SUZAKU", hint: "Knightmare Frame pilot" },
  { text: "NKLEAL", answer: "KALLEN", hint: "Red-haired resistance fighter" },
  { text: "ZLHCZENIES", answer: "SCHNEIZEL", hint: "Royal strategist prince" },
  { text: "HLTIG YAGAMI", answer: "LIGHT YAGAMI", hint: "Owner of the Death Note" },
  { text: "WLWALTEI L", answer: "L LAWLIET", hint: "World-famous detective" },
  { text: "AASNMIA M", answer: "MISA AMANE", hint: "Idol with Shinigami eyes" },
  { text: "ERNA", answer: "NEAR", hint: "White-haired successor detective" },
  { text: "OMLEL", answer: "MELLO", hint: "Chocolate-loving rival detective" },
  { text: "KUYR", answer: "RYUK", hint: "Apple-loving Shinigami" },
  { text: "KSNUE", answer: "SENKU", hint: "Science genius teenager" },
  { text: "HRMOEC", answer: "CHROME", hint: "Apprentice scientist" },
  { text: "NGAE SRAIGAI", answer: "GEN ASAGIRI", hint: "Mentalist from Dr. Stone" },
  { text: "AAKUSTS", answer: "TSUKASA", hint: "Strongest primate high schooler" },
  { text: "KOHUKA", answer: "KOHAKU", hint: "Warrior girl from Stone World" },
  { text: "GYHAO", answer: "HYOGA", hint: "Spear fighter from Dr. Stone" },
  { text: "IANZ OAL OOGWN", answer: "AINZ OOAL GOWN", hint: "Ruler of Nazarick" },
  { text: "OBLAED", answer: "ALBEDO", hint: "Overseer guardian succubus" },
  { text: "LRALHTESA", answer: "SHALLTEAR", hint: "Vampire floor guardian" },
  { text: "ERDEMIUG", answer: "DEMIURGE", hint: "Demon strategist guardian" },
  { text: "OTSCUCY", answer: "COCYTUS", hint: "Frozen insect warrior" },
  { text: "SABSE", answer: "SEBAS", hint: "Butler of Nazarick" },
  { text: "ANYAT", answer: "TANYA", hint: "Child soldier mage" },
  { text: "KORVTI NIFOROKV", answer: "VIKTOR NIKIFOROV", hint: "Legendary figure skater" },
  { text: "IURY KATSUKI", answer: "YURI KATSUKI", hint: "Japanese ice skater" },
  { text: "OITLEV EVRDNAGERE", answer: "VIOLET EVERGARDEN", hint: "Auto Memory Doll" },
  { text: "BGIRETL LIBOGANVEUILLEA", answer: "GILBERT BOUGAINVILLEA", hint: "Violet’s major" },
  { text: "AIADCLU SGDHNOI", answer: "CLAUDIA HODGINS", hint: "Postal company president" },
  { text: "SIAL", answer: "ISLA", hint: "Android girl from Plastic Memories" },
  { text: "IHIC", answer: "CHII", hint: "Persocom girl from Chobits" },
  { text: "OERZ OWT", answer: "ZERO TWO", hint: "Pink-haired pilot girl" },
  { text: "RHOI", answer: "HIRO", hint: "Partner of Zero Two" },
  { text: "OROG", answer: "GORO", hint: "Squad leader pilot" },
  { text: "KAMAEA", answer: "AKAME", hint: "Assassin swordswoman" },
  { text: "ESEDATH", answer: "ESDEATH", hint: "Ice empire general" },
  { text: "TUTMSAI", answer: "TATSUMI", hint: "Main fighter of Night Raid" },
  { text: "ENLEO", answer: "LEONE", hint: "Beast transformation user" },
  { text: "EMIN", answer: "MINE", hint: "Pink-haired sniper" },
  { text: "EESHEL", answer: "SHEELE", hint: "Clumsy assassin with giant scissors" },
  { text: "UBDOU", answer: "BUDOU", hint: "Empire military general" },
  { text: "DNEAJNA", answer: "NAJENDA", hint: "Leader of Night Raid" },
  { text: "SHACEEL", answer: "CHELSEA", hint: "Transformation assassin girl" },
  { text: "AVEW", answer: "WAVE", hint: "Empire soldier with armor" },
  { text: "OEKRUM", answer: "KUROME", hint: "Akame’s younger sister" },
  { text: "AAKM ABRNAL", answer: "MAKA ALBARN", hint: "Meister from Soul Eater" },
  { text: "OLSU EATER", answer: "SOUL EATER", hint: "Demon scythe partner" },
  { text: "EDAHT HTE IDK", answer: "DEATH THE KID", hint: "Symmetry-obsessed fighter" },
  { text: "LBCAK ARTS", answer: "BLACK STAR", hint: "Loud ninja assassin" },
  { text: "NAROC", answer: "CRONA", hint: "Partner of Ragnarok" },
  { text: "SAUMED", answer: "MEDUSA", hint: "Witch scientist villain" }
];