export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/6/232649.jpg", options: ["Muzan Kibutsuji", "Akaza", "Kokushibo", "Doma"], correct: 0, hint: "King of demons created all others", level: 3 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/8/372906.jpg", options: ["Akaza", "Muzan", "Kokushibo", "Doma"], correct: 0, hint: "Upper Moon Three martial artist", level: 3 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/4/378853.jpg", options: ["Kokushibo", "Akaza", "Muzan", "Yoriichi"], correct: 0, hint: "Upper Moon One six-eyed swordsman", level: 3 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/6/378851.jpg", options: ["Doma", "Akaza", "Kokushibo", "Muzan"], correct: 0, hint: "Upper Moon Two rainbow-eyed cult leader", level: 3 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/4/179555.jpg", options: ["Madara Uchiha", "Hashirama", "Obito", "Itachi"], correct: 0, hint: "Legendary Uchiha founder rival to First", level: 3 },

  { id: 6, image: "https://cdn.myanimelist.net/images/characters/6/182159.jpg", options: ["Hashirama Senju", "Madara Uchiha", "Tobirama", "Hiruzen"], correct: 0, hint: "First Hokage God of Shinobi", level: 3 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/16/292447.jpg", options: ["Lelouch Lamperouge", "Suzaku", "C.C.", "Kallen"], correct: 0, hint: "Geass prince who became Zero", level: 3 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/16/264199.jpg", options: ["Kirito", "Asuna", "Klein", "Eugeo"], correct: 0, hint: "Black swordsman trapped in death game", level: 3 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/15/264197.jpg", options: ["Asuna", "Kirito", "Sinon", "Leafa"], correct: 0, hint: "Lightning Flash rapier in SAO", level: 3 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/12/334745.jpg", options: ["Rintaro Okabe", "Kurisu Makise", "Mayuri", "Daru"], correct: 0, hint: "Mad scientist El Psy Kongroo", level: 3 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/3/334747.jpg", options: ["Kurisu Makise", "Okabe", "Mayuri", "Moeka"], correct: 0, hint: "Genius time travel researcher Christina", level: 3 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/8/211413.jpg", options: ["Deidara", "Sasori", "Itachi", "Hidan"], correct: 0, hint: "Art is an explosion! Clay bomber", level: 3 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/11/211415.jpg", options: ["Sasori", "Deidara", "Kakuzu", "Konan"], correct: 0, hint: "Puppet master of the Red Sand", level: 3 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/5/211421.jpg", options: ["Kisame Hoshigaki", "Itachi", "Zetsu", "Pain"], correct: 0, hint: "Shark-skin sword blue swordsman", level: 3 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/7/211419.jpg", options: ["Hidan", "Kakuzu", "Kisame", "Zetsu"], correct: 0, hint: "Immortal Jashin worshipper", level: 3 },

  { id: 16, image: "https://cdn.myanimelist.net/images/characters/14/211417.jpg", options: ["Kakuzu", "Hidan", "Kisame", "Sasori"], correct: 0, hint: "Five hearts Akatsuki bounty hunter", level: 3 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/14/235219.jpg", options: ["Konan", "Pain", "Obito", "Itachi"], correct: 0, hint: "Paper angel of Hidden Rain Village", level: 3 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/10/367475.jpg", options: ["Suguru Geto", "Gojo", "Kenjaku", "Yuta"], correct: 0, hint: "Cursed spirit manipulator turned villain", level: 3 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/3/232417.jpg", options: ["Kaneki Ken", "Touka", "Ayato", "Arima"], correct: 0, hint: "One-eyed ghoul cracking fingers", level: 3 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/15/232421.jpg", options: ["Touka Kirishima", "Kaneki", "Hinami", "Rize"], correct: 0, hint: "Rabbit mask fighting for ghouls", level: 3 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/3/377047.jpg", options: ["Yoriichi Tsugikuni", "Tanjiro", "Kokushibo", "Muzan"], correct: 0, hint: "Legendary Sun Breathing originator", level: 3 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/3/378849.jpg", options: ["Gyutaro", "Daki", "Akaza", "Doma"], correct: 0, hint: "Upper Moon Six sickle-wielding sibling", level: 3 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/9/106527.jpg", options: ["King Bradley", "Father", "Greed", "Pride"], correct: 0, hint: "Wrath homunculus Fuhrer of Amestris", level: 3 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/3/267759.jpg", options: ["Father", "Hohenheim", "King Bradley", "Pride"], correct: 0, hint: "Dwarf in the flask creator of homunculi", level: 3 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/3/232905.jpg", options: ["Greed", "Ling Yao", "Envy", "Lust"], correct: 0, hint: "Ultimate shield homunculus turned ally", level: 3 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/10/252911.jpg", options: ["Envy", "Lust", "Gluttony", "Pride"], correct: 0, hint: "Shape-shifting homunculus started wars", level: 3 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/5/64427.jpg", options: ["Sesshomaru", "Inuyasha", "Naraku", "Koga"], correct: 0, hint: "Full demon lord dog brother", level: 3 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/8/253045.jpg", options: ["Chrollo Lucilfer", "Hisoka", "Feitan", "Illumi"], correct: 0, hint: "Phantom Troupe leader steals abilities", level: 3 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/9/287899.jpg", options: ["Neferpitou", "Meruem", "Pouf", "Youpi"], correct: 0, hint: "Cat-like Royal Guard with healing", level: 3 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/13/289233.jpg", options: ["Donquixote Doflamingo", "Crocodile", "Kaido", "Big Mom"], correct: 0, hint: "String user King of Dressrosa", level: 3 },

  { id: 31, image: "https://cdn.myanimelist.net/images/characters/9/310733.jpg", options: ["Kaido", "Big Mom", "Doflamingo", "Blackbeard"], correct: 0, hint: "Strongest creature dragon emperor", level: 3 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/3/365041.jpg", options: ["Sosuke Aizen", "Ichigo", "Urahara", "Gin"], correct: 0, hint: "Betrayed Soul Society master of illusion", level: 3 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/7/284917.jpg", options: ["Ulquiorra Cifer", "Grimmjow", "Aizen", "Starrk"], correct: 0, hint: "Fourth Espada nihilistic bat", level: 3 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/2/284935.jpg", options: ["Grimmjow Jaegerjaquez", "Ulquiorra", "Nnoitra", "Aizen"], correct: 0, hint: "Sixth Espada panther king", level: 3 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/13/176703.jpg", options: ["Frieza", "Cell", "Buu", "Vegeta"], correct: 0, hint: "Galactic tyrant destroyer of planets", level: 3 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/6/268034.jpg", options: ["Blackbeard", "Luffy", "Shanks", "Akainu"], correct: 0, hint: "Two devil fruits dark pirate emperor", level: 3 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/4/376217.jpg", options: ["Mahito", "Jogo", "Hanami", "Dagon"], correct: 0, hint: "Curse that manipulates souls shape", level: 3 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/13/108459.jpg", options: ["Naraku", "Sesshomaru", "Inuyasha", "Kagura"], correct: 0, hint: "Half-demon shapeshifter Inuyasha villain", level: 3 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/8/251675.jpg", options: ["Garou", "Saitama", "Genos", "Boros"], correct: 0, hint: "Hero hunter who became a monster", level: 3 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/9/297927.jpg", options: ["Overhaul", "Shigaraki", "All For One", "Dabi"], correct: 0, hint: "Plague mask yakuza quirk destroyer", level: 3 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/7/291749.jpg", options: ["Shigaraki Tomura", "All For One", "Dabi", "Overhaul"], correct: 0, hint: "Decay quirk villain successor", level: 3 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/8/366455.jpg", options: ["Dabi", "Shigaraki", "Hawks", "Endeavor"], correct: 0, hint: "Blue flame villain secret identity", level: 3 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/12/226215.jpg", options: ["Lust", "Envy", "Gluttony", "Sloth"], correct: 0, hint: "Ultimate spear seductive homunculus", level: 3 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/4/393891.jpg", options: ["Kenjaku", "Geto", "Gojo", "Sukuna"], correct: 0, hint: "Brain-swapping ancient sorcerer villain", level: 3 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/10/287637.jpg", options: ["Feitan", "Chrollo", "Phinks", "Nobunaga"], correct: 0, hint: "Phantom Troupe torturer with fire", level: 3 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/10/236961.jpg", options: ["Hange Zoe", "Levi", "Erwin", "Mikasa"], correct: 0, hint: "Titan-obsessed scientist commander", level: 3 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/6/113834.jpg", options: ["Scar", "Edward", "Mustang", "Kimblee"], correct: 0, hint: "Ishvalan avenger with destructive arm", level: 3 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/5/71765.jpg", options: ["Kagura", "Naraku", "Kanna", "Kikyo"], correct: 0, hint: "Wind sorceress desires freedom", level: 3 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/5/94965.jpg", options: ["Akainu", "Kizaru", "Aokiji", "Garp"], correct: 0, hint: "Magma fist Fleet Admiral ruthless", level: 3 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/9/269323.jpg", options: ["All For One", "Shigaraki", "Overhaul", "Gigantomachia"], correct: 0, hint: "Steals quirks ultimate evil mastermind", level: 3 },
];
