export default [
  { text: "What is Gojo’s domain expansion?", options: ["Infinite Castle", "Unlimited Void", "Malevolent Shrine", "Coffin of Iron Mountain"], correct: 1 },
  { text: "Which Titan does Armin inherit?", options: ["Female Titan", "Jaw Titan", "Colossal Titan", "Beast Titan"], correct: 2 },
  { text: "What is Edward Elric’s title?", options: ["Flame Alchemist", "Fullmetal Alchemist", "Ice Alchemist", "Steel Alchemist"], correct: 1 },
  { text: "Who killed Akaza?", options: ["Tanjiro", "Giyu", "Muzan", "Akaza killed himself after regaining memories"], correct: 3 },
  { text: "Which One Piece arc introduced Trafalgar Law?", options: ["Marineford", "Wano", "Sabaody", "Dressrosa"], correct: 2 },
  { text: "What is the name of Ichigo’s inner Hollow?", options: ["White", "Black", "Grimmjow", "Ulquiorra"], correct: 0 },
  { text: "Which breathing style does Zenitsu use?", options: ["Water", "Flame", "Thunder", "Mist"], correct: 2 },
  { text: "Who taught Gon Nen?", options: ["Biscuit", "Wing", "Netero", "Hisoka"], correct: 1 },
  { text: "What is the Beast Titan’s human name?", options: ["Reiner", "Bertolt", "Zeke", "Porco"], correct: 2 },
  { text: "Which captain betrayed Soul Society?", options: ["Ukitake", "Aizen", "Byakuya", "Toshiro"], correct: 1 },
  { text: "What is Naruto’s chakra nature?", options: ["Wind", "Fire", "Water", "Earth"], correct: 0 },
  { text: "Which Akatsuki member uses clay bombs?", options: ["Kisame", "Deidara", "Sasori", "Hidan"], correct: 1 },
  { text: "What is Luffy’s Devil Fruit called originally?", options: ["Flame-Flame Fruit", "Gum-Gum Fruit", "Chop-Chop Fruit", "Human-Human Fruit"], correct: 1 },
  { text: "Which Hashira uses Mist Breathing?", options: ["Muichiro", "Obanai", "Sanemi", "Gyomei"], correct: 0 },
  { text: "What is Levi Ackerman’s squad called?", options: ["Survey Team", "Scout Guards", "Special Operations Squad", "Titan Killers"], correct: 2 },
  { text: "Which Espada was Ulquiorra?", options: ["1st", "2nd", "4th", "6th"], correct: 2 },
  { text: "What is the name of Natsu’s dragon foster father?", options: ["Acnologia", "Metalicana", "Igneel", "Grandeeney"], correct: 2 },
  { text: "Which anime features the organization SEELE?", options: ["Evangelion", "Psycho-Pass", "Monster", "Ergo Proxy"], correct: 0 },
  { text: "What is the name of Yuno’s wind spirit?", options: ["Salamander", "Bell", "Undine", "Sylph"], correct: 3 },
  { text: "Who became the No.1 hero after All Might?", options: ["Hawks", "Deku", "Endeavor", "Mirko"], correct: 2 },
  { text: "Which Titan killed Eren’s mother?", options: ["Beast Titan", "Jaw Titan", "Smiling Titan", "Female Titan"], correct: 2 },
  { text: "What is the name of Light Yagami’s Shinigami?", options: ["Rem", "Ryuk", "Gelus", "Sidoh"], correct: 1 },
  { text: "Which JoJo protagonist can stop time?", options: ["Giorno", "Joseph", "Jotaro", "Josuke"], correct: 2 },
  { text: "Which anime has “Plus Ultra”?", options: ["Black Clover", "Naruto", "My Hero Academia", "Blue Lock"], correct: 2 },
  { text: "What is the name of Asta’s rival?", options: ["Magna", "Noelle", "Yuno", "Luck"], correct: 2 },
  { text: "Which One Piece admiral uses ice powers?", options: ["Akainu", "Kizaru", "Fujitora", "Aokiji"], correct: 3 },
  { text: "What is the name of Kirito’s first VR game?", options: ["Gun Gale Online", "Alfheim Online", "Sword Art Online", "Underworld"], correct: 2 },
  { text: "Which Hashira survived the final Demon Slayer battle?", options: ["Rengoku", "Tengen", "Muichiro", "Giyu"], correct: 3 },
  { text: "Which captain uses Senbonzakura?", options: ["Renji", "Gin", "Byakuya", "Aizen"], correct: 2 },
  { text: "What clan is Hinata from?", options: ["Uchiha", "Senju", "Hyuga", "Uzumaki"], correct: 2 },
  { text: "Which Pokémon does Brock mainly use?", options: ["Pikachu", "Gengar", "Onix", "Psyduck"], correct: 2 },
  { text: "Which anime movie features Chihiro?", options: ["Ponyo", "Spirited Away", "Totoro", "Your Name"], correct: 1 },
  { text: "Which Titan is Annie?", options: ["Female Titan", "Jaw Titan", "Beast Titan", "Cart Titan"], correct: 0 },
  { text: "What is Mob’s power linked to?", options: ["Anger meter", "Emotion percentage", "Mana", "Chakra"], correct: 1 },
  { text: "Which JoJo villain used Killer Queen?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 1 },
  { text: "What is the name of Chopper’s Devil Fruit?", options: ["Human-Human Fruit", "Gum-Gum Fruit", "Dog-Dog Fruit", "Flame-Flame Fruit"], correct: 0 },
  { text: "Which anime has the phrase “Dattebayo”?", options: ["Bleach", "Naruto", "One Piece", "Fairy Tail"], correct: 1 },
  { text: "Which demon ranked Upper Moon One?", options: ["Akaza", "Kokushibo", "Doma", "Gyokko"], correct: 1 },
  { text: "Which Fullmetal Alchemist character uses flame alchemy?", options: ["Scar", "Mustang", "Edward", "Alphonse"], correct: 1 },
  { text: "Which anime features Johan Liebert?", options: ["Monster", "Pluto", "Death Note", "Psycho-Pass"], correct: 0 },
  { text: "What is the name of Eren’s Titan?", options: ["Founding Titan", "Attack Titan", "Beast Titan", "Cart Titan"], correct: 1 },
  { text: "Which JoJo part introduced Dio’s Stand?", options: ["Part 2", "Part 3", "Part 4", "Part 5"], correct: 1 },
  { text: "Which anime features Guts?", options: ["Berserk", "Vinland Saga", "Claymore", "Hellsing"], correct: 0 },
  { text: "Which Hashira uses Sound Breathing?", options: ["Obanai", "Tengen", "Sanemi", "Gyomei"], correct: 1 },
  { text: "Which Bleach villain created the Arrancars?", options: ["Gin", "Aizen", "Yhwach", "Grimmjow"], correct: 1 },
  { text: "What is the name of Lelouch’s alter ego?", options: ["Zero", "Emperor", "Black Knight", "Rebellion"], correct: 0 },
  { text: "Which anime features Anti-Magic?", options: ["Fairy Tail", "Naruto", "Black Clover", "Bleach"], correct: 2 },
  { text: "Which Straw Hat uses a slingshot?", options: ["Franky", "Brook", "Usopp", "Chopper"], correct: 2 },
  { text: "What is the name of Tanjiro’s sword?", options: ["Zanpakuto", "Nichirin Blade", "Excalibur", "Demon Blade"], correct: 1 },
  { text: "Which anime has Quirks?", options: ["Black Clover", "Naruto", "My Hero Academia", "Bleach"], correct: 2 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Greed Island", "Yorknew", "Chimera Ant", "Election Arc"], correct: 2 }
];