export default [
  { text: "APIAKRUR", answer: "KURAPIKA", hint: "Chain user from Hunter x Hunter" },
  { text: "AOIKSH", answer: "HISOKA", hint: "Dangerous magician clown" },
  { text: "OCLLROH", answer: "CHROLLO", hint: "Phantom Troupe leader" },
  { text: "HICIORUY", answer: "YORUICHI", hint: "Flash goddess Soul Reaper" },
  { text: "AHIKCPNE", answer: "KENPACHI", hint: "Wild captain from Bleach" },
  { text: "AUABKYYA", answer: "BYAKUYA", hint: "Noble Soul Reaper captain" },
  { text: "RRAQLOIUU", answer: "ULQUIORRA", hint: "Espada with green eyes" },
  { text: "RFIGFTHI", answer: "GRIFFITH", hint: "Hawk leader from Berserk" },
  { text: "SGTU", answer: "GUTS", hint: "Black swordsman" },
  { text: "ACSAC", answer: "CASCA", hint: "Female warrior from Berserk" },
  { text: "NROHTFIN", answer: "THORFINN", hint: "Viking seeking revenge" },
  { text: "DADLEKSLA", answer: "ASKELADD", hint: "Clever Viking leader" },
  { text: "UTANEC", answer: "CANUTE", hint: "Prince turned king" },
  { text: "EREGIN", answer: "REIGEN", hint: "Fake psychic mentor" },
  { text: "BMO", answer: "MOB", hint: "Emotion-powered esper" },
  { text: "KREUTEI", answer: "TERUKI", hint: "Esper rival with blonde hair" },
  { text: "EGOIHS", answer: "SHIGEO", hint: "Mob’s real name" },
  { text: "MPIDEL", answer: "DIMPLE", hint: "Green ghost spirit" },
  { text: "KAMI", answer: "MAKI", hint: "Weapon user from JJK" },
  { text: "EGTO", answer: "TOGE", hint: "Uses cursed speech" },
  { text: "OETG", answer: "GETO", hint: "Former sorcerer turned villain" },
  { text: "NAAIMN", answer: "NANAMI", hint: "Salaryman sorcerer" },
  { text: "OIHMAT", answer: "MAHITO", hint: "Curse who manipulates souls" },
  { text: "ANUSKU", answer: "SUKUNA", hint: "King of curses" },
  { text: "UATY", answer: "YUTA", hint: "Special grade student" },
  { text: "JTOI", answer: "TOJI", hint: "Heavenly restriction assassin" },
  { text: "EJNID", answer: "DENJI", hint: "Chainsaw Devil hunter" },
  { text: "EPOWR", answer: "POWER", hint: "Blood fiend girl" },
  { text: "IAK", answer: "AKI", hint: "Calm devil hunter" },
  { text: "KMIAMA", answer: "MAKIMA", hint: "Mysterious control devil" },
  { text: "IBENKO", answer: "KOBENI", hint: "Nervous devil hunter" },
  { text: "KAZAA", answer: "AKAZA", hint: "Upper Moon demon fighter" },
  { text: "KUGRNOEO", answer: "RENGOKU", hint: "Flame Hashira" },
  { text: "UIGYU", answer: "GIYUU", hint: "Water Hashira" },
  { text: "GNETEN", answer: "TENGEN", hint: "Flashy Sound Hashira" },
  { text: "CHMORIIU", answer: "MUICHIRO", hint: "Mist Hashira" },
  { text: "HNOBUSI", answer: "SHINOBU", hint: "Insect Hashira" },
  { text: "UMRSTII", answer: "MITSURI", hint: "Love Hashira" },
  { text: "IAANBA", answer: "OBANAI", hint: "Snake Hashira" },
  { text: "MGEYOI", answer: "GYOMEI", hint: "Stone Hashira giant" },
  { text: "AMENSI", answer: "SANEMI", hint: "Wind Hashira" },
  { text: "MRUIUR", answer: "RIMURU", hint: "Slime reincarnation king" },
  { text: "ACRSNOE", answer: "ESCANOR", hint: "Lion sin with sunshine power" },
  { text: "NBA", answer: "BAN", hint: "Immortal fox sin" },
  { text: "SDOAMIEL", answer: "MELIODAS", hint: "Dragon sin captain" },
  { text: "NIKG", answer: "KING", hint: "Fairy King Harlequin" },
  { text: "IAEND", answer: "DIANE", hint: "Giant girl from Seven Deadly Sins" },
  { text: "AWHK", answer: "HAWK", hint: "Talking pig companion" },
  { text: "LMERIN", answer: "MERLIN", hint: "Boar sin magician" },
  { text: "TSRSOEA", answer: "ESTAROSSA", hint: "Powerful demon commandment" }
];