export default [
  { text: "Which chapter officially revealed Gear 5?", options: ["1000", "1020", "1044", "1050"], correct: 2 },
  { text: "What is Sukuna’s domain expansion?", options: ["Infinite Void", "Malevolent Shrine", "Chimera Garden", "Self-Embodiment of Perfection"], correct: 1 },
  { text: "Which JoJo part introduced Stands?", options: ["Part 1", "Part 2", "Part 3", "Part 4"], correct: 2 },
  { text: "Which wall was destroyed first in Attack on Titan?", options: ["Wall Rose", "Wall Sina", "Wall Maria", "Trost Wall"], correct: 2 },
  { text: "What is Aizen’s Zanpakuto called?", options: ["Benihime", "Zangetsu", "Kyoka Suigetsu", "Senbonzakura"], correct: 2 },
  { text: "Which Nen category does Kurapika become under Emperor Time?", options: ["Enhancer", "Specialist", "Emitter", "Manipulator"], correct: 1 },
  { text: "What is the name of Johan Liebert’s twin sister?", options: ["Anna", "Nina", "Eva", "Lotte"], correct: 1 },
  { text: "Which One Piece character first used Conqueror’s Haki on‑screen?", options: ["Luffy", "Kaido", "Shanks", "Whitebeard"], correct: 2 },
  { text: "Which Hashira created Love Breathing?", options: ["Mitsuri", "Shinobu", "Kanae", "Kanao"], correct: 0 },
  { text: "What was Near’s real name in Death Note?", options: ["Nate River", "Mihael Keehl", "Teru Mikami", "Beyond Birthday"], correct: 0 },
  { text: "Which Titan power can inherit future memories?", options: ["Beast Titan", "Jaw Titan", "Attack Titan", "Cart Titan"], correct: 2 },
  { text: "Which JoJo villain reset the universe?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 3 },
  { text: "What is the name of Shinji’s EVA unit?", options: ["EVA-00", "EVA-01", "EVA-02", "EVA-03"], correct: 1 },
  { text: "Which Bleach captain used Kamishini no Yari?", options: ["Byakuya", "Gin", "Aizen", "Tosen"], correct: 1 },
  { text: "Which breathing style came directly from Sun Breathing?", options: ["Mist Breathing", "Flame Breathing", "Sound Breathing", "Insect Breathing"], correct: 1 },
  { text: "What was Whitebeard’s official title?", options: ["King of Pirates", "Strongest Creature", "Strongest Man in the World", "Sea Emperor"], correct: 2 },
  { text: "Which anime features the Sibyl System?", options: ["Monster", "Ergo Proxy", "Psycho-Pass", "Serial Experiments Lain"], correct: 2 },
  { text: "Which Espada rank was Grimmjow?", options: ["3rd", "4th", "5th", "6th"], correct: 3 },
  { text: "Which Naruto opening featured “Blue Bird”?", options: ["Opening 2", "Opening 3", "Opening 5", "Opening 7"], correct: 1 },
  { text: "Which Fullmetal Alchemist character created the Homunculi?", options: ["Hohenheim", "Father", "Dante", "Truth"], correct: 1 },
  { text: "Which JoJo protagonist used the Steel Ball technique?", options: ["Giorno", "Josuke", "Johnny Joestar", "Jolyne"], correct: 2 },
  { text: "Which One Piece arc introduced Brook?", options: ["Water 7", "Thriller Bark", "Enies Lobby", "Sabaody"], correct: 1 },
  { text: "What is the name of Yhwach’s elite guard?", options: ["Sternritter", "Schutzstaffel", "Quincy Army", "Wandenreich"], correct: 1 },
  { text: "Which anime features Amestris?", options: ["Monster", "Fullmetal Alchemist", "Bleach", "Fate"], correct: 1 },
  { text: "Which Akatsuki duo captured Yugito?", options: ["Itachi & Kisame", "Hidan & Kakuzu", "Sasori & Deidara", "Pain & Konan"], correct: 1 },
  { text: "What is the name of Guts’ sword?", options: ["Dragonslayer", "Excalibur", "Demon Edge", "Berserker Blade"], correct: 0 },
  { text: "Which anime features SEELE?", options: ["Evangelion", "Psycho-Pass", "Ghost in the Shell", "Pluto"], correct: 0 },
  { text: "Which captain becomes a Visored leader?", options: ["Rose", "Love", "Kensei", "Shinji"], correct: 3 },
  { text: "Which JoJo Stand belongs to Diavolo?", options: ["Killer Queen", "King Crimson", "Made in Heaven", "The World"], correct: 1 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Yorknew", "Greed Island", "Chimera Ant", "Election"], correct: 2 },
  { text: "Which Titan is Reiner?", options: ["Beast Titan", "Armored Titan", "Jaw Titan", "Cart Titan"], correct: 1 },
  { text: "Which anime movie won an Oscar for Studio Ghibli?", options: ["Ponyo", "Spirited Away", "Totoro", "Mononoke"], correct: 1 },
  { text: "Which Naruto character could naturally use all five chakra natures?", options: ["Kakashi", "Naruto", "Hiruzen", "Sasuke"], correct: 2 },
  { text: "What was Lelouch’s alias?", options: ["Black Emperor", "Zero", "Knightmare", "Rebellion"], correct: 1 },
  { text: "Which JoJo part introduced the Arrow?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which One Piece island permanently changes climate?", options: ["Dressrosa", "Little Garden", "Zou", "Punk Hazard"], correct: 1 },
  { text: "Which Bleach arc introduced Fullbringers?", options: ["Arrancar Arc", "TYBW Arc", "Lost Agent Arc", "Soul Society Arc"], correct: 2 },
  { text: "Which Upper Moon was Kokushibo?", options: ["Upper Moon 1", "Upper Moon 2", "Upper Moon 3", "Upper Moon 4"], correct: 0 },
  { text: "Which anime features Beyond Netero?", options: ["Bleach", "Naruto", "Hunter x Hunter", "Black Clover"], correct: 2 },
  { text: "Which JoJo protagonist never defeated the final villain directly?", options: ["Giorno", "Jonathan", "Josuke", "Jolyne"], correct: 1 },
  { text: "Which One Piece chapter revealed Joy Boy?", options: ["628", "700", "800", "1044"], correct: 0 },
  { text: "Which Bleach villain manipulated complete hypnosis?", options: ["Yhwach", "Gin", "Aizen", "Ulquiorra"], correct: 2 },
  { text: "Which anime has Anti-Spirals?", options: ["Evangelion", "Gurren Lagann", "FLCL", "Akira"], correct: 1 },
  { text: "Which Naruto technique trapped the world in illusion?", options: ["Amaterasu", "Infinite Tsukuyomi", "Izanagi", "Kamui"], correct: 1 },
  { text: "Which JoJo Stand manipulates weather?", options: ["Whitesnake", "Weather Report", "Stone Free", "Soft & Wet"], correct: 1 },
  { text: "Which Hunter x Hunter character uses Bungee Gum?", options: ["Gon", "Chrollo", "Hisoka", "Illumi"], correct: 2 },
  { text: "Which One Piece Emperor arrived at Marineford to stop the war?", options: ["Kaido", "Big Mom", "Shanks", "Blackbeard"], correct: 2 },
  { text: "Which anime features the Eclipse?", options: ["Berserk", "Claymore", "Hellsing", "Vinland Saga"], correct: 0 },
  { text: "Which Bleach Espada used Respira?", options: ["Ulquiorra", "Baraggan", "Grimmjow", "Stark"], correct: 1 },
  { text: "Which JoJo villain used Made in Heaven?", options: ["Dio", "Pucci", "Kira", "Diavolo"], correct: 1 },
  { text: "Which Attack on Titan character invented ODM improvements?", options: ["Levi", "Hange", "Angel Aaltonen", "Erwin"], correct: 2 }
];