export default [
  { text: "ESIKMA KRSUIU", answer: "MAKISE KURISU", hint: "Genius tsundere scientist" },
  { text: "SUSEOK AIZEN", answer: "SOSUKE AIZEN", hint: "Bleach mastermind captain" },
  { text: "TOSARU GOJO", answer: "SATURU GOJO", hint: "Six Eyes sorcerer" },
  { text: "GYAKUA SHINOMIYA", answer: "KAGUYA SHINOMIYA", hint: "Love is War heroine" },
  { text: "YKUIMI SHIROGANE", answer: "MIYUKI SHIROGANE", hint: "Student council president" },
  { text: "ACIHC FUJIWARA", answer: "CHIKA FUJIWARA", hint: "Chaotic pink-haired girl" },
  { text: "UY ISHIGAMI", answer: "YU ISHIGAMI", hint: "Gamer boy from Love is War" },
  { text: "IA HAYASAKA", answer: "AI HAYASAKA", hint: "Kaguya’s maid" },
  { text: "KMOI IINO", answer: "MIKO IINO", hint: "Strict discipline committee girl" },
  { text: "WAKOIA OOTORU", answer: "OIKAWA TOORU", hint: "Charismatic volleyball setter" },
  { text: "OBTIO KAGEYAMA", answer: "TOBIO KAGEYAMA", hint: "King of the Court" },
  { text: "YSOHO HINATA", answer: "SHOYO HINATA", hint: "Short orange-haired spiker" },
  { text: "EKI TSUKISHIMA", answer: "KEI TSUKISHIMA", hint: "Tall blocker with glasses" },
  { text: "STTUERO KUROO", answer: "TETSURO KUROO", hint: "Nekoma volleyball captain" },
  { text: "OATKRO BOKUTO", answer: "KOTARO BOKUTO", hint: "Moody ace spiker" },
  { text: "JKEII AKAASHI", answer: "KEIJI AKAASHI", hint: "Calm volleyball setter" },
  { text: "WKAATOSHI USHIJIMA", answer: "WAKATOSHI USHIJIMA", hint: "Left-handed volleyball ace" },
  { text: "UUSKO SAIKI", answer: "KUSUO SAIKI", hint: "Pink-haired psychic" },
  { text: "MOKKIO TERUHASHI", answer: "KOKOMI TERUHASHI", hint: "Perfect beautiful girl" },
  { text: "IRIK NENDOU", answer: "RIKI NENDOU", hint: "Loud ramen-loving friend" },
  { text: "HSUN KAIDOU", answer: "SHUN KAIDOU", hint: "Dark Flame Master" },
  { text: "ANRE KUBOYASU", answer: "AREN KUBOYASU", hint: "Former delinquent boy" },
  { text: "EITAR TORITSUKA", answer: "REITA TORITSUKA", hint: "Spirit medium pervert" },
  { text: "UKSUKE SAIKI", answer: "KUSUKE SAIKI", hint: "Genius older brother" },
  { text: "HRINEDAR VAN ASTREA", answer: "REINHARD VAN ASTREA", hint: "Sword Saint knight" },
  { text: "LETBEGEUSE ROMANEE CONTI", answer: "BETELGEUSE ROMANEE CONTI", hint: "Sin Archbishop of Sloth" },
  { text: "AROWSLAAL MATHERS", answer: "ROSWAAL MATHERS", hint: "Clown-faced mage lord" },
  { text: "DAIHCNE", answer: "ECHIDNA", hint: "Witch of Greed" },
  { text: "TLEALSA", answer: "SATELLA", hint: "Witch of Envy" },
  { text: "TACERIBE", answer: "BEATRICE", hint: "Spirit library girl" },
  { text: "FAGRIEL TINSEL", answer: "GARFIEL TINSEL", hint: "Beast transformation guardian" },
  { text: "TOTO SUWEN", answer: "OTTO SUWEN", hint: "Merchant friend of Subaru" },
  { text: "CSUCRH KARSTEN", answer: "CRUSCH KARSTEN", hint: "Green-haired royal candidate" },
  { text: "ATSANASIA HOSHIN", answer: "ANASTASIA HOSHIN", hint: "Business-minded royal candidate" },
  { text: "CPRISILLA BARIELLE", answer: "PRISCILLA BARIELLE", hint: "Arrogant royal candidate" },
  { text: "LFET", answer: "FELT", hint: "Street thief royal candidate" },
  { text: "RINREE BRAUN", answer: "REINER BRAUN", hint: "Armored Titan holder" },
  { text: "EEKZ YEAGER", answer: "ZEKE YEAGER", hint: "Beast Titan holder" },
  { text: "EPKIC FINGER", answer: "PIECK FINGER", hint: "Cart Titan holder" },
  { text: "RCPOO GALLIARD", answer: "PORCO GALLIARD", hint: "Jaw Titan user" },
  { text: "ACFLO GRICE", answer: "FALCO GRICE", hint: "Warrior candidate boy" },
  { text: "IABG BRAUN", answer: "GABI BRAUN", hint: "Warrior candidate girl" },
  { text: "IMYR FRITZ", answer: "YMIR FRITZ", hint: "Founder of Titans" },
  { text: "ENAEN LEONHART", answer: "ANNIE LEONHART", hint: "Female Titan holder" },
  { text: "RTHBETOLD HOOVER", answer: "BERTHOLDT HOOVER", hint: "Colossal Titan holder" },
  { text: "MRINA ARLERT", answer: "ARMIN ARLERT", hint: "Strategic genius scout" },
  { text: "AJEN KIRSTEIN", answer: "JEAN KIRSTEIN", hint: "Horse-faced scout" },
  { text: "CENNIO SPRINGER", answer: "CONNIE SPRINGER", hint: "Funny scout soldier" },
  { text: "HSSAA BLOUSE", answer: "SASHA BLOUSE", hint: "Potato girl" },
  { text: "HNGAE ZOE", answer: "HANGE ZOE", hint: "Titan researcher commander" }
];