// To switch to local images: change image field to "/shadows/l2_X.jpg"
export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/9/284122.jpg", options: ["Itachi Uchiha", "Sasuke", "Madara", "Obito"], correct: 0, hint: "Massacred his own clan for peace", level: 2 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/2/284125.jpg", options: ["Obito Uchiha", "Itachi", "Madara", "Kakashi"], correct: 0, hint: "Orange spiral mask villain", level: 2 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/5/354443.jpg", options: ["Rem", "Ram", "Emilia", "Beatrice"], correct: 0, hint: "Blue-haired maid twin from Re:Zero", level: 2 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/3/279277.jpg", options: ["Kurapika", "Killua", "Leorio", "Gon"], correct: 0, hint: "Chain user hunting Phantom Troupe", level: 2 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/7/351647.jpg", options: ["Trafalgar Law", "Luffy", "Kid", "Zoro"], correct: 0, hint: "Surgeon of Death with Room ability", level: 2 },
  { id: 6, image: "https://cdn.myanimelist.net/images/characters/7/253405.jpg", options: ["Gintoki Sakata", "Kenshin", "Spike", "Mugen"], correct: 0, hint: "Lazy samurai loves strawberry milk", level: 2 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/9/284130.jpg", options: ["Hinata Hyuga", "Sakura", "Ino", "Temari"], correct: 0, hint: "Shy Byakugan heiress who loved Naruto", level: 2 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/5/96553.jpg", options: ["Portgas D. Ace", "Luffy", "Sabo", "Marco"], correct: 0, hint: "Fire fist brother of Luffy", level: 2 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/2/286649.jpg", options: ["Meruem", "Netero", "Pitou", "Pouf"], correct: 0, hint: "Chimera Ant King who played Gungi", level: 2 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/6/250627.jpg", options: ["Jotaro Kujo", "DIO", "Josuke", "Giorno"], correct: 0, hint: "Star Platinum yare yare daze", level: 2 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/7/335251.jpg", options: ["Reiner Braun", "Eren", "Bertholdt", "Zeke"], correct: 0, hint: "Armored Titan warrior from Marley", level: 2 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/9/230195.jpg", options: ["Erwin Smith", "Levi", "Hange", "Mike"], correct: 0, hint: "Blonde commander who charges forward", level: 2 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/12/258681.jpg", options: ["DIO", "Jotaro", "Kars", "Diavolo"], correct: 0, hint: "Vampire who rejected his humanity", level: 2 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/14/210181.jpg", options: ["Roy Mustang", "Edward", "Hughes", "Hawkeye"], correct: 0, hint: "Flame Alchemist aiming for Fuhrer", level: 2 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/5/309731.jpg", options: ["Giorno Giovanna", "DIO", "Bruno", "Mista"], correct: 0, hint: "Son of DIO wants to be Gang-Star", level: 2 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/11/307605.jpg", options: ["Tengen Uzui", "Rengoku", "Giyu", "Sanemi"], correct: 0, hint: "Sound Hashira flamboyant fighter", level: 2 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/12/380360.jpg", options: ["Toge Inumaki", "Megumi", "Panda", "Maki"], correct: 0, hint: "Cursed speech rice ball words only", level: 2 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/10/238005.jpg", options: ["Sasha Blouse", "Mikasa", "Annie", "Historia"], correct: 0, hint: "Potato girl of the Scout Regiment", level: 2 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/4/260353.jpg", options: ["Annie Leonhart", "Mikasa", "Sasha", "Ymir"], correct: 0, hint: "Female Titan shifter crystal cocoon", level: 2 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/3/294036.jpg", options: ["Rin Okumura", "Yukio", "Mephisto", "Shima"], correct: 0, hint: "Son of Satan with blue flames", level: 2 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/7/86517.jpg", options: ["Lucy Heartfilia", "Erza", "Juvia", "Mirajane"], correct: 0, hint: "Celestial spirit mage with golden keys", level: 2 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/8/227217.jpg", options: ["Riza Hawkeye", "Roy Mustang", "Winry", "Olivier"], correct: 0, hint: "Sharpshooter lieutenant loyal to Mustang", level: 2 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/5/58163.jpg", options: ["Shanks", "Luffy", "Roger", "Rayleigh"], correct: 0, hint: "Red-haired emperor gave hat to Luffy", level: 2 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/12/235217.jpg", options: ["Nagato/Pain", "Obito", "Madara", "Konan"], correct: 0, hint: "Six paths of pain God of Rain village", level: 2 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/6/337081.jpg", options: ["Shinobu Kocho", "Nezuko", "Mitsuri", "Kanao"], correct: 0, hint: "Insect Hashira always smiling poison user", level: 2 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/4/314925.jpg", options: ["Muichiro Tokito", "Tanjiro", "Giyu", "Obanai"], correct: 0, hint: "Youngest Mist Hashira prodigy descendant", level: 2 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/7/120623.jpg", options: ["Orochimaru", "Jiraiya", "Tsunade", "Kabuto"], correct: 0, hint: "Snake Sannin obsessed with immortality", level: 2 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/10/252643.jpg", options: ["Zeke Yeager", "Reiner", "Eren", "Grisha"], correct: 0, hint: "Beast Titan throws rocks with precision", level: 2 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/3/339818.jpg", options: ["Mitsuri Kanroji", "Shinobu", "Nezuko", "Kanao"], correct: 0, hint: "Love Hashira cherry blossom mochi hair", level: 2 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/6/179999.jpg", options: ["Shikamaru Nara", "Choji", "Ino", "Asuma"], correct: 0, hint: "Shadow genius strategist troublesome", level: 2 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/5/352493.jpg", options: ["Dracule Mihawk", "Shanks", "Zoro", "Rayleigh"], correct: 0, hint: "World's greatest swordsman hawk eyes", level: 2 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/14/297729.jpg", options: ["Minato Namikaze", "Naruto", "Kakashi", "Jiraiya"], correct: 0, hint: "Yellow Flash Fourth Hokage", level: 2 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/3/86219.jpg", options: ["Tsunade", "Sakura", "Shizune", "Konan"], correct: 0, hint: "Fifth Hokage legendary medical gambling ninja", level: 2 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/13/367423.jpg", options: ["Toji Fushiguro", "Gojo", "Megumi", "Sukuna"], correct: 0, hint: "Heavenly Restriction assassin Megumi's father", level: 2 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/2/61099.jpg", options: ["Boa Hancock", "Nami", "Robin", "Vivi"], correct: 0, hint: "Pirate empress who loves Luffy", level: 2 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/3/72865.jpg", options: ["Brook", "Chopper", "Franky", "Jinbe"], correct: 0, hint: "Skeleton musician Soul King yohoho", level: 2 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/12/86383.jpg", options: ["Might Guy", "Rock Lee", "Kakashi", "Naruto"], correct: 0, hint: "Youthful taijutsu master eight gates", level: 2 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/5/348987.jpg", options: ["Kanao Tsuyuri", "Shinobu", "Nezuko", "Aoi"], correct: 0, hint: "Flower breathing quiet demon slayer girl", level: 2 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/13/292663.jpg", options: ["Leorio Paradinight", "Gon", "Killua", "Kurapika"], correct: 0, hint: "Doctor hunter with a suitcase punch", level: 2 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/12/77159.jpg", options: ["Neji Hyuga", "Hinata", "Rock Lee", "Tenten"], correct: 0, hint: "Byakugan genius of Hyuga branch family", level: 2 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/8/92785.jpg", options: ["Crocodile", "Doflamingo", "Enel", "Moria"], correct: 0, hint: "Sand warlord who tried to take Alabasta", level: 2 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/14/152067.jpg", options: ["Franky", "Usopp", "Brook", "Jinbe"], correct: 0, hint: "Cola-powered cyborg shipwright SUPER", level: 2 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/3/337078.jpg", options: ["Obanai Iguro", "Giyu", "Sanemi", "Muichiro"], correct: 0, hint: "Serpent Hashira with white snake bandaged", level: 2 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/3/337074.jpg", options: ["Sanemi Shinazugawa", "Obanai", "Giyu", "Tengen"], correct: 0, hint: "Wind Hashira scarred aggressive rare blood", level: 2 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/11/392853.jpg", options: ["Todo Aoi", "Yuji", "Gojo", "Megumi"], correct: 0, hint: "Best friend! Boogie woogie technique big guy", level: 2 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/11/46941.jpg", options: ["Marco", "Ace", "Whitebeard", "Jozu"], correct: 0, hint: "Phoenix fruit first division commander blue flames", level: 2 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/14/384810.jpg", options: ["Panda", "Toge", "Megumi", "Maki"], correct: 0, hint: "Not actually a panda cursed corpse Jujutsu High", level: 2 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/6/281438.jpg", options: ["Death the Kid", "Soul", "Black Star", "Maka"], correct: 0, hint: "Obsessed with symmetry son of Death", level: 2 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/4/280069.jpg", options: ["Maka Albarn", "Soul", "Tsubaki", "Liz"], correct: 0, hint: "Scythe-wielding meister at DWMA", level: 2 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/6/280067.jpg", options: ["Soul Evans", "Maka", "Death the Kid", "Black Star"], correct: 0, hint: "Cool demon scythe weapon musician", level: 2 },
];
