export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/7/204573.jpg", options: ["Spike Spiegel", "Jet Black", "Vicious", "Faye Valentine"], correct: 0, hint: "See you space cowboy bounty hunter", level: 4 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/4/230175.jpg", options: ["Kenshin Himura", "Sanosuke", "Shishio", "Aoshi"], correct: 0, hint: "Wandering reverse-blade swordsman", level: 4 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/8/349451.jpg", options: ["Violet Evergarden", "Saber", "Rei Ayanami", "C.C."], correct: 0, hint: "Auto Memory Doll former soldier", level: 4 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/8/305944.jpg", options: ["Ainz Ooal Gown", "Albedo", "Shalltear", "Demiurge"], correct: 0, hint: "Skeleton overlord of Nazarick", level: 4 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/3/305945.jpg", options: ["Albedo", "Shalltear", "Ainz", "Aura"], correct: 0, hint: "Succubus floor guardian obsessed with master", level: 4 },

  { id: 6, image: "https://cdn.myanimelist.net/images/characters/9/354033.jpg", options: ["Emilia", "Rem", "Ram", "Beatrice"], correct: 0, hint: "Half-elf silver-haired spirit user", level: 4 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/7/354039.jpg", options: ["Subaru Natsuki", "Emilia", "Rem", "Roswaal"], correct: 0, hint: "Return by Death tracksuit boy", level: 4 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/14/278275.jpg", options: ["Sebastian Michaelis", "Ciel Phantomhive", "Grell", "Undertaker"], correct: 0, hint: "Hell of a butler demon servant", level: 4 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/8/278277.jpg", options: ["Ciel Phantomhive", "Sebastian", "Alois", "Snake"], correct: 0, hint: "Eye-patch noble Queen's watchdog", level: 4 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/12/316373.jpg", options: ["Kisuke Urahara", "Ichigo", "Aizen", "Yoruichi"], correct: 0, hint: "Hat and clogs shady shopkeeper genius", level: 4 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/3/316371.jpg", options: ["Yoruichi Shihoin", "Urahara", "Soi Fon", "Rukia"], correct: 0, hint: "Flash goddess cat transformation", level: 4 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/4/312817.jpg", options: ["Toshiro Hitsugaya", "Ichigo", "Byakuya", "Kenpachi"], correct: 0, hint: "Ice dragon youngest captain ever", level: 4 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/5/312819.jpg", options: ["Byakuya Kuchiki", "Hitsugaya", "Aizen", "Gin"], correct: 0, hint: "Cherry blossom noble captain", level: 4 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/12/176673.jpg", options: ["Cell", "Frieza", "Buu", "Android 17"], correct: 0, hint: "Perfect bio-android absorbed others", level: 4 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/3/171167.jpg", options: ["Majin Buu", "Cell", "Frieza", "Kid Buu"], correct: 0, hint: "Pink blob destroyer of worlds", level: 4 },
  { id: 16, image: "https://cdn.myanimelist.net/images/characters/14/310735.jpg", options: ["Big Mom", "Kaido", "Blackbeard", "Shanks"], correct: 0, hint: "Soul-stealing emperor mother pirate", level: 4 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/11/312761.jpg", options: ["Katakuri", "Doflamingo", "Luffy", "King"], correct: 0, hint: "Mochi man sees the future", level: 4 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/14/252077.jpg", options: ["Whitebeard", "Roger", "Kaido", "Shanks"], correct: 0, hint: "Strongest man earthquake powers father", level: 4 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/4/360083.jpg", options: ["Hawks", "Endeavor", "Dabi", "All Might"], correct: 0, hint: "Number two winged hero spy", level: 4 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/16/391367.jpg", options: ["Endeavor", "All Might", "Hawks", "Best Jeanist"], correct: 0, hint: "Flame hero seeking redemption", level: 4 },

  { id: 21, image: "https://cdn.myanimelist.net/images/characters/4/355127.jpg", options: ["Yami Sukehiro", "Asta", "Noelle", "Julius"], correct: 0, hint: "Dark magic captain surpass your limits", level: 4 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/5/299441.jpg", options: ["Yuno", "Asta", "Noelle", "William"], correct: 0, hint: "Wind magic rival four-leaf clover", level: 4 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/8/372455.jpg", options: ["Maki Zenin", "Nobara", "Toge", "Mai Zenin"], correct: 0, hint: "No cursed energy weapons master Zenin", level: 4 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/6/372453.jpg", options: ["Nobara Kugisaki", "Maki", "Mei Mei", "Miwa"], correct: 0, hint: "Hammer and nails curse technique", level: 4 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/5/366039.jpg", options: ["Yuta Okkotsu", "Yuji", "Gojo", "Megumi"], correct: 0, hint: "Special grade with cursed queen Rika", level: 4 },
  { id: 26, image: "https://cdn.myanimelist.net/images/characters/9/251329.jpg", options: ["Netero", "Meruem", "Ging", "Zeno"], correct: 0, hint: "Chairman hundred-hand prayer attack", level: 4 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/6/251981.jpg", options: ["Ging Freecss", "Gon", "Netero", "Pariston"], correct: 0, hint: "Absent father top hunter adventurer", level: 4 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/11/233731.jpg", options: ["Armin Arlert", "Eren", "Erwin", "Levi"], correct: 0, hint: "Coconut head colossal strategist", level: 4 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/13/173449.jpg", options: ["Broly", "Goku", "Vegeta", "Jiren"], correct: 0, hint: "Legendary Super Saiyan berserker", level: 4 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/6/355379.jpg", options: ["Gol D. Roger", "Whitebeard", "Shanks", "Rayleigh"], correct: 0, hint: "Pirate King who started the era", level: 4 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/6/352129.jpg", options: ["Petelgeuse Romanee-Conti", "Subaru", "Regulus", "Roswaal"], correct: 0, hint: "Slothful sin archbishop brain trembles", level: 4 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/11/320653.jpg", options: ["Holo", "Kraft Lawrence", "Myuri", "Eve"], correct: 0, hint: "Wise wolf deity apple lover", level: 4 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/4/377283.jpg", options: ["Power", "Denji", "Makima", "Aki"], correct: 0, hint: "Blood fiend Nobel Prize declaration", level: 4 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/5/377281.jpg", options: ["Denji", "Power", "Aki", "Makima"], correct: 0, hint: "Chainsaw Devil hybrid simple dreams", level: 4 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/3/377285.jpg", options: ["Makima", "Power", "Reze", "Himeno"], correct: 0, hint: "Control Devil manipulator with dogs", level: 4 },

  { id: 36, image: "https://cdn.myanimelist.net/images/characters/2/377279.jpg", options: ["Aki Hayakawa", "Denji", "Angel", "Kishibe"], correct: 0, hint: "Future Devil contract fox and sword", level: 4 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/10/298879.jpg", options: ["Senku Ishigami", "Chrome", "Gen", "Taiju"], correct: 0, hint: "Science genius revives stone world", level: 4 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/2/392185.jpg", options: ["Frieren", "Fern", "Himmel", "Stark"], correct: 0, hint: "Elf mage outliving everyone collecting spells", level: 4 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/14/258709.jpg", options: ["Gilgamesh", "Saber", "Archer", "Lancer"], correct: 0, hint: "King of Heroes golden armor Fate", level: 4 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/3/317899.jpg", options: ["Saber/Artoria", "Gilgamesh", "Rin", "Shirou"], correct: 0, hint: "King Arthur knight of Fate", level: 4 },
  { id: 41, image: "https://cdn.myanimelist.net/images/characters/2/314039.jpg", options: ["Rimuru Tempest", "Veldora", "Milim", "Diablo"], correct: 0, hint: "Slime who built a monster nation", level: 4 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/9/253283.jpg", options: ["Komugi", "Meruem", "Netero", "Palm"], correct: 0, hint: "Blind Gungi champion touched the King", level: 4 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/5/395781.jpg", options: ["Fern", "Frieren", "Ubel", "Serie"], correct: 0, hint: "Apprentice mage raised by an elf", level: 4 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/6/371113.jpg", options: ["Naofumi Iwatani", "Raphtalia", "Motoyasu", "Ren"], correct: 0, hint: "Shield Hero falsely accused isekai", level: 4 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/2/332421.jpg", options: ["Goblin Slayer", "Priestess", "High Elf", "Dwarf"], correct: 0, hint: "Armored adventurer only hunts goblins", level: 4 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/5/324655.jpg", options: ["Raphtalia", "Naofumi", "Filo", "Melty"], correct: 0, hint: "Raccoon demi-human shield companion", level: 4 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/7/349155.jpg", options: ["Shinji Ikari", "Asuka", "Rei", "Kaworu"], correct: 0, hint: "Get in the robot reluctant pilot", level: 4 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/8/349157.jpg", options: ["Asuka Langley", "Rei", "Misato", "Shinji"], correct: 0, hint: "Tsundere redhead Eva pilot", level: 4 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/4/349159.jpg", options: ["Rei Ayanami", "Asuka", "Kaworu", "Misato"], correct: 0, hint: "Mysterious blue-haired clone pilot", level: 4 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/8/82096.jpg", options: ["Kenpachi Zaraki", "Ichigo", "Byakuya", "Yamamoto"], correct: 0, hint: "Battle-crazed captain loves fighting", level: 4 },
];
