export default [
  { id: 1, image: "https://cdn.myanimelist.net/images/characters/11/174515.jpg", options: ["Johan Liebert", "Kenzo Tenma", "Grimmer", "Lunge"], correct: 0, hint: "The nameless monster perfect psychopath", level: 5 },
  { id: 2, image: "https://cdn.myanimelist.net/images/characters/4/174513.jpg", options: ["Kenzo Tenma", "Johan Liebert", "Grimmer", "Eva"], correct: 0, hint: "Doctor who saved a future killer", level: 5 },
  { id: 3, image: "https://cdn.myanimelist.net/images/characters/16/234697.jpg", options: ["Motoko Kusanagi", "Batou", "Togusa", "Laughing Man"], correct: 0, hint: "Full cyborg Section 9 philosopher", level: 5 },
  { id: 4, image: "https://cdn.myanimelist.net/images/characters/12/349923.jpg", options: ["Griffith", "Guts", "Casca", "Femto"], correct: 0, hint: "White hawk who sacrificed everything", level: 5 },
  { id: 5, image: "https://cdn.myanimelist.net/images/characters/3/349921.jpg", options: ["Guts", "Griffith", "Casca", "Skull Knight"], correct: 0, hint: "Black swordsman branded struggler", level: 5 },

  { id: 6, image: "https://cdn.myanimelist.net/images/characters/11/253723.jpg", options: ["Lain Iwakura", "Mima Kirigoe", "Rei Ayanami", "Homura"], correct: 0, hint: "Connected to the Wired digital existence", level: 5 },
  { id: 7, image: "https://cdn.myanimelist.net/images/characters/16/244591.jpg", options: ["Nausicaa", "San", "Kiki", "Chihiro"], correct: 0, hint: "Valley princess who rides a glider", level: 5 },
  { id: 8, image: "https://cdn.myanimelist.net/images/characters/2/244589.jpg", options: ["San", "Nausicaa", "Mononoke", "Ashitaka"], correct: 0, hint: "Wolf princess who hates humans", level: 5 },
  { id: 9, image: "https://cdn.myanimelist.net/images/characters/9/304023.jpg", options: ["Howl", "Calcifer", "Sophie", "Turnip Head"], correct: 0, hint: "Vain wizard of the moving castle", level: 5 },
  { id: 10, image: "https://cdn.myanimelist.net/images/characters/16/304025.jpg", options: ["Sophie Hatter", "Howl", "Witch of Waste", "Calcifer"], correct: 0, hint: "Cursed girl turned old cleaning lady", level: 5 },
  { id: 11, image: "https://cdn.myanimelist.net/images/characters/4/293765.jpg", options: ["Chihiro", "Haku", "No-Face", "Yubaba"], correct: 0, hint: "Bathhouse worker parents turned to pigs", level: 5 },
  { id: 12, image: "https://cdn.myanimelist.net/images/characters/2/293767.jpg", options: ["Haku", "Chihiro", "Yubaba", "Zeniba"], correct: 0, hint: "River spirit dragon who forgot his name", level: 5 },
  { id: 13, image: "https://cdn.myanimelist.net/images/characters/2/293769.jpg", options: ["No-Face", "Haku", "Chihiro", "Radish Spirit"], correct: 0, hint: "Lonely mask spirit offers gold", level: 5 },
  { id: 14, image: "https://cdn.myanimelist.net/images/characters/6/249595.jpg", options: ["Homura Akemi", "Madoka Kaname", "Mami", "Sayaka"], correct: 0, hint: "Time-looping magical girl did nothing wrong", level: 5 },
  { id: 15, image: "https://cdn.myanimelist.net/images/characters/2/249593.jpg", options: ["Madoka Kaname", "Homura", "Sayaka", "Kyoko"], correct: 0, hint: "Pink-haired girl who became a god", level: 5 },

  { id: 16, image: "https://cdn.myanimelist.net/images/characters/7/181955.jpg", options: ["Porco Rosso", "Howl", "Kiki", "Nausicaa"], correct: 0, hint: "Italian pilot turned pig bounty hunter", level: 5 },
  { id: 17, image: "https://cdn.myanimelist.net/images/characters/9/182537.jpg", options: ["Totoro", "Catbus", "Soot Sprites", "Mei"], correct: 0, hint: "Giant forest spirit only children see", level: 5 },
  { id: 18, image: "https://cdn.myanimelist.net/images/characters/14/270089.jpg", options: ["Kiki", "Jiji", "Tombo", "Ursula"], correct: 0, hint: "Young witch with delivery service", level: 5 },
  { id: 19, image: "https://cdn.myanimelist.net/images/characters/12/313545.jpg", options: ["Revy", "Rock", "Dutch", "Balalaika"], correct: 0, hint: "Two-gun wielding pirate woman", level: 5 },
  { id: 20, image: "https://cdn.myanimelist.net/images/characters/4/203437.jpg", options: ["Mugen", "Jin", "Fuu", "Spike"], correct: 0, hint: "Break-dancing sword fighter wanderer", level: 5 },
  { id: 21, image: "https://cdn.myanimelist.net/images/characters/16/373559.jpg", options: ["Phosphophyllite", "Diamond", "Bort", "Cinnabar"], correct: 0, hint: "Gem person who slowly lost themselves", level: 5 },
  { id: 22, image: "https://cdn.myanimelist.net/images/characters/5/318161.jpg", options: ["Mob", "Reigen", "Dimple", "Ritsu"], correct: 0, hint: "Esper boy at 100 percent explosion", level: 5 },
  { id: 23, image: "https://cdn.myanimelist.net/images/characters/8/318163.jpg", options: ["Reigen Arataka", "Mob", "Dimple", "Serizawa"], correct: 0, hint: "Self-proclaimed psychic con man master", level: 5 },
  { id: 24, image: "https://cdn.myanimelist.net/images/characters/6/348835.jpg", options: ["Tohru", "Kobayashi", "Kanna", "Elma"], correct: 0, hint: "Dragon who became a maid", level: 5 },
  { id: 25, image: "https://cdn.myanimelist.net/images/characters/7/348837.jpg", options: ["Kobayashi", "Tohru", "Kanna", "Fafnir"], correct: 0, hint: "Programmer who adopted a dragon", level: 5 },

  { id: 26, image: "https://cdn.myanimelist.net/images/characters/2/325965.jpg", options: ["Kyubey", "Madoka", "Homura", "Charlotte"], correct: 0, hint: "Cute sinister contractor with magical girls", level: 5 },
  { id: 27, image: "https://cdn.myanimelist.net/images/characters/7/297175.jpg", options: ["Vash the Stampede", "Wolfwood", "Knives", "Meryl"], correct: 0, hint: "Humanoid typhoon love and peace", level: 5 },
  { id: 28, image: "https://cdn.myanimelist.net/images/characters/12/265401.jpg", options: ["Okabe Rintaro", "Kurisu", "Mayuri", "Daru"], correct: 0, hint: "Hououin Kyouma mad scientist persona", level: 5 },
  { id: 29, image: "https://cdn.myanimelist.net/images/characters/12/248983.jpg", options: ["Edward Wong", "Spike", "Jet", "Faye"], correct: 0, hint: "Radical hacker kid on the Bebop", level: 5 },
  { id: 30, image: "https://cdn.myanimelist.net/images/characters/4/330983.jpg", options: ["Thorfinn", "Askeladd", "Thors", "Canute"], correct: 0, hint: "Viking seeking Vinland true warrior", level: 5 },
  { id: 31, image: "https://cdn.myanimelist.net/images/characters/11/330981.jpg", options: ["Askeladd", "Thorfinn", "Bjorn", "Canute"], correct: 0, hint: "Cunning leader killed Thors", level: 5 },
  { id: 32, image: "https://cdn.myanimelist.net/images/characters/4/290381.jpg", options: ["Yubaba", "Sophie", "Zeniba", "Chihiro"], correct: 0, hint: "Bathhouse witch with a giant baby", level: 5 },
  { id: 33, image: "https://cdn.myanimelist.net/images/characters/12/399423.jpg", options: ["Anya Forger", "Loid", "Yor", "Bond"], correct: 0, hint: "Telepathic child waku waku spy family", level: 5 },
  { id: 34, image: "https://cdn.myanimelist.net/images/characters/14/399425.jpg", options: ["Yor Forger", "Anya", "Loid", "Fiona"], correct: 0, hint: "Assassin mother Thorn Princess", level: 5 },
  { id: 35, image: "https://cdn.myanimelist.net/images/characters/7/399421.jpg", options: ["Loid Forger", "Yor", "Anya", "Franky"], correct: 0, hint: "Twilight master spy fake family", level: 5 },
  { id: 36, image: "https://cdn.myanimelist.net/images/characters/14/290853.jpg", options: ["Saber Alter", "Saber", "Gilgamesh", "Berserker"], correct: 0, hint: "Dark corrupted version of the king", level: 5 },
  { id: 37, image: "https://cdn.myanimelist.net/images/characters/9/404677.jpg", options: ["Sung Jin-Woo", "Cha Hae-In", "Go Gun-Hee", "Thomas Andre"], correct: 0, hint: "Shadow monarch weakest to strongest", level: 5 },
  { id: 38, image: "https://cdn.myanimelist.net/images/characters/12/250777.jpg", options: ["Archer", "Shirou", "Gilgamesh", "Lancer"], correct: 0, hint: "Counter Guardian future self cynical", level: 5 },
  { id: 39, image: "https://cdn.myanimelist.net/images/characters/11/338755.jpg", options: ["Kaguya Shinomiya", "Miyuki Shirogane", "Chika", "Hayasaka"], correct: 0, hint: "Ice princess love is war genius", level: 5 },
  { id: 40, image: "https://cdn.myanimelist.net/images/characters/3/338757.jpg", options: ["Miyuki Shirogane", "Kaguya", "Ishigami", "Chika"], correct: 0, hint: "Student council president study hard", level: 5 },

  { id: 41, image: "https://cdn.myanimelist.net/images/characters/9/344595.jpg", options: ["Osamu Dazai", "Atsushi", "Chuuya", "Ranpo"], correct: 0, hint: "Suicidal genius detective agency member", level: 5 },
  { id: 42, image: "https://cdn.myanimelist.net/images/characters/4/344593.jpg", options: ["Atsushi Nakajima", "Dazai", "Akutagawa", "Kunikida"], correct: 0, hint: "Tiger ability orphan weretiger boy", level: 5 },
  { id: 43, image: "https://cdn.myanimelist.net/images/characters/16/266459.jpg", options: ["Izaya Orihara", "Shizuo", "Celty", "Mikado"], correct: 0, hint: "Information broker loves humanity chaos", level: 5 },
  { id: 44, image: "https://cdn.myanimelist.net/images/characters/3/266457.jpg", options: ["Shizuo Heiwajima", "Izaya", "Simon", "Kasuka"], correct: 0, hint: "Bartender outfit superhuman strength rage", level: 5 },
  { id: 45, image: "https://cdn.myanimelist.net/images/characters/11/356045.jpg", options: ["Marin Kitagawa", "Gojo Wakana", "Juju", "Shinju"], correct: 0, hint: "Cosplay-loving gyaru my dress-up darling", level: 5 },
  { id: 46, image: "https://cdn.myanimelist.net/images/characters/7/192099.jpg", options: ["C.C.", "Lelouch", "Kallen", "Shirley"], correct: 0, hint: "Immortal pizza-loving green-haired witch", level: 5 },
  { id: 47, image: "https://cdn.myanimelist.net/images/characters/13/389731.jpg", options: ["Pochita", "Denji", "Makima", "Power"], correct: 0, hint: "Chainsaw Devil dog form companion", level: 5 },
  { id: 48, image: "https://cdn.myanimelist.net/images/characters/5/380135.jpg", options: ["Yoruichi (cat form)", "Happy", "Jiji", "Blair"], correct: 0, hint: "Black cat actually powerful Soul Reaper", level: 5 },
  { id: 49, image: "https://cdn.myanimelist.net/images/characters/6/381579.jpg", options: ["Sung Jin-Woo (Shadows)", "Ainz", "Rimuru", "Anos"], correct: 0, hint: "Army of shadow soldiers arise command", level: 5 },
  { id: 50, image: "https://cdn.myanimelist.net/images/characters/2/402391.jpg", options: ["Stark", "Frieren", "Fern", "Himmel"], correct: 0, hint: "Cowardly warrior raised by a hero", level: 5 },
];
