export default [
  {"id":31,"text":"🦋🩸🎨","options":["Monogatari","Elfen Lied","Another","Paranoia Agent"],"correct":0,"hint":"Oddities and dialogue","level":4},
  {"id":32,"text":"🧒📡🤖","options":["Serial Experiments Lain","Psycho-Pass","Ergo Proxy","Texhnolyze"],"correct":0,"hint":"Wired world","level":4},
  {"id":33,"text":"🌻⚔️🎧","options":["Samurai Champloo","Afro Samurai","Gintama","Dororo"],"correct":0,"hint":"Hip-hop samurai","level":4},
  {"id":34,"text":"🕷️📖🕯️","options":["Another","Pandora Hearts","Black Butler","Gosick"],"correct":1,"hint":"Abyss and chains","level":4},
  {"id":35,"text":"🐧🥒👧","options":["Sarazanmai","Mawaru Penguindrum","FLCL","Nichijou"],"correct":1,"hint":"Symbolic penguins","level":4},
  {"id":36,"text":"🧠⚡🌆","options":["Akira","Psycho-Pass","Ergo Proxy","Ghost in the Shell"],"correct":0,"hint":"Neo Tokyo","level":4},
  {"id":37,"text":"📚🧛🌙","options":["Hellsing","Shiki","Call of the Night","Bakemonogatari"],"correct":1,"hint":"Village vampires","level":4},
  {"id":38,"text":"🧵👁️🪆","options":["Another","Higurashi","Puella Magi Madoka Magica","Ghost Hound"],"correct":2,"hint":"Dark magical girls","level":4},
  {"id":39,"text":"⚙️🕊️🤖","options":["Ghost in the Shell","Vivy","Ergo Proxy","Pluto"],"correct":1,"hint":"AI singer","level":4},
  {"id":40,"text":"🎺🚀🌌","options":["Macross","Cowboy Bebop","Space Dandy","Legend of the Galactic Heroes"],"correct":0,"hint":"Mecha and music","level":4},
  {"id":81,"text":"🎨👁️😵","options":["Blue Period","Mononoke","Tatami Galaxy","Ping Pong the Animation"],"correct":1,"hint":"Medicine seller","level":4},
  {"id":82,"text":"🌊📖👧","options":["Nagi no Asukara","Children of the Sea","A Lull in the Sea","Ride Your Wave"],"correct":2,"hint":"Underwater village","level":4},
  {"id":83,"text":"🕰️👧🦋","options":["Erased","Summertime Rendering","Orange","ReLIFE"],"correct":1,"hint":"Island time loops","level":4},
  {"id":84,"text":"🎭📺🔪","options":["Perfect Blue","Odd Taxi","Paranoia Agent","Monster"],"correct":2,"hint":"Roller boy attacks","level":4},
  {"id":85,"text":"⚙️🩸👑","options":["Guilty Crown","86","Aldnoah.Zero","Valvrave"],"correct":0,"hint":"Void powers","level":4},
  {"id":86,"text":"🧠👨‍⚕️🔪","options":["Monster","Death Note","Psycho-Pass","Pluto"],"correct":0,"hint":"Johan Liebert","level":4},
  {"id":87,"text":"🎤🐰🌈","options":["Show by Rock!!","Carole & Tuesday","Zombie Land Saga","Oshi no Ko"],"correct":3,"hint":"Idol revenge story","level":4},
  {"id":88,"text":"🧪👧💣","options":["Elfen Lied","Akira","Wonder Egg Priority","Lycoris Recoil"],"correct":3,"hint":"Cafe assassins","level":4},
  {"id":89,"text":"🌌🧍📺","options":["Sonny Boy","FLCL","Tatami Galaxy","Kaiba"],"correct":0,"hint":"Drifting school","level":4},
  {"id":90,"text":"⚔️👹🪷","options":["Dororo","Shigurui","Blade of the Immortal","Ninja Scroll"],"correct":2,"hint":"Immortal samurai","level":4},
  {"id":131,"text":"📖🦋🕰️","options":["The Tatami Galaxy","Monogatari","Mawaru Penguindrum","Sonny Boy"],"correct":0,"hint":"Endless college timelines","level":4},
  {"id":132,"text":"👧⚡🐰","options":["Bunny Girl Senpai","Wonder Egg Priority","Flip Flappers","Charlotte"],"correct":0,"hint":"Adolescence syndrome","level":4},
  {"id":133,"text":"🧬🌌👶","options":["From the New World","Shinsekai Yori","Ergo Proxy","Noein"],"correct":1,"hint":"Psychic dystopia","level":4},
  {"id":134,"text":"🎪🔪🤡","options":["Deadman Wonderland","Karneval","Dorohedoro","Akudama Drive"],"correct":0,"hint":"Prison amusement park","level":4},
  {"id":135,"text":"🌧️👧📖","options":["Humanity Has Declined","Kino's Journey","Girls' Last Tour","Haibane Renmei"],"correct":2,"hint":"Post-apocalypse slice of life","level":4},
  {"id":136,"text":"🧠🎭📺","options":["Kaiji","One Outs","Akagi","Death Parade"],"correct":0,"hint":"Extreme gambling","level":4},
  {"id":137,"text":"🪞👧🦢","options":["Princess Tutu","Revolutionary Girl Utena","Flip Flappers","Cardcaptor Sakura"],"correct":0,"hint":"Fairy tale ballet","level":4},
  {"id":138,"text":"⚔️🩸🌑","options":["Drifters","Berserk","Hellsing Ultimate","Shigurui"],"correct":0,"hint":"Historical warriors isekai","level":4},
  {"id":139,"text":"🛵🎸⚡","options":["Beck","FLCL","Bocchi the Rock!","Nana"],"correct":0,"hint":"Rock band anime","level":4},
  {"id":140,"text":"👁️🧪🧒","options":["Parasyte","Ajin","Devilman Crybaby","Inuyashiki"],"correct":3,"hint":"Old cyborg hero","level":4},
  {"id":181,"text":"📺🧠⚡","options":["Paranoia Agent","Boogiepop Phantom","Serial Experiments Lain","Texhnolyze"],"correct":2,"hint":"\"Present day, present time\"","level":4},
  {"id":182,"text":"🌊⚰️👧","options":["Black Rock Shooter","Sunday Without God","Haibane Renmei","Humanity Has Declined"],"correct":1,"hint":"World where nobody dies","level":4},
  {"id":183,"text":"🎪🐻🔪","options":["Danganronpa","Deadman Wonderland","Mirai Nikki","Btooom!"],"correct":0,"hint":"Monokuma executions","level":4},
  {"id":184,"text":"🧒⚔️🧟","options":["Kabaneri","Seraph of the End","God Eater","Guilty Crown"],"correct":1,"hint":"Vampire apocalypse","level":4},
  {"id":185,"text":"🎭🪞🌸","options":["Pet Shop of Horrors","xxxHOLiC","Mononoke","Ghost Hunt"],"correct":1,"hint":"Wish-granting shop","level":4},
  {"id":186,"text":"🌑🚇👧","options":["Dark Gathering","Mieruko-chan","Otherside Picnic","Ghost Hunt"],"correct":2,"hint":"Internet horror dimensions","level":4},
  {"id":187,"text":"⚙️🧠🌧️","options":["Ergo Proxy","Casshern Sins","Blame!","Psycho-Pass"],"correct":1,"hint":"Robots and ruin","level":4},
  {"id":188,"text":"📖👧🩸","options":["Gosick","Another","Higurashi","Shiki"],"correct":0,"hint":"Victorian mystery girl","level":4},
  {"id":189,"text":"🧸🩸👧","options":["Shadow Star Narutaru","Elfen Lied","School-Live!","Alien 9"],"correct":0,"hint":"Dark creature companions","level":4},
  {"id":190,"text":"🎨🚲🌤️","options":["Windy Tales","Aria","Tamayura","Yokohama Kaidashi Kikou"],"correct":3,"hint":"Peaceful post-apocalypse","level":4},
  {"id":231,"text":"📖🌌🧠","options":["Kaiba","Sonny Boy","Tatami Galaxy","Noein"],"correct":0,"hint":"Memories as data","level":4},
  {"id":232,"text":"👧⚔️🦢","options":["Princess Tutu","Revolutionary Girl Utena","Magic Knight Rayearth","Cardcaptor Sakura"],"correct":0,"hint":"Duck ballerina","level":4},
  {"id":233,"text":"🧒🧠🌧️","options":["Texhnolyze","Ergo Proxy","Ghost Hound","Serial Experiments Lain"],"correct":2,"hint":"Astral projection horror","level":4},
  {"id":234,"text":"⚙️👩‍🎤🌌","options":["Macross Plus","Vivy","Armitage III","Bubblegum Crisis"],"correct":0,"hint":"Sharon Apple","level":4},
  {"id":235,"text":"👧📺🪞","options":["Boogiepop Phantom","Serial Experiments Lain","Perfect Blue","Another"],"correct":0,"hint":"Urban fear anthology","level":4},
  {"id":236,"text":"🎨🌊👧","options":["Children of the Sea","Ride Your Wave","Lu Over the Wall","Ponyo"],"correct":0,"hint":"Cosmic ocean mystery","level":4},
  {"id":237,"text":"🧠🕳️⚙️","options":["Ergo Proxy","Blame!","Texhnolyze","Psycho-Pass"],"correct":2,"hint":"Underground cyberpunk decay","level":4},
  {"id":238,"text":"⚔️🧟🏯","options":["Shigurui","Basilisk","Ninja Scroll","Drifters"],"correct":0,"hint":"Insane samurai realism","level":4},
  {"id":239,"text":"👧☁️🚲","options":["Yokohama Kaidashi Kikou","Aria","Tamayura","Windy Tales"],"correct":0,"hint":"Quiet café android","level":4},
  {"id":240,"text":"🎪👹📿","options":["Ayakashi","Mononoke","Hell Girl","Mushishi"],"correct":1,"hint":"Medicine seller spirit cases","level":4},
];
