export default [
  { text: "Which Sternritter was known as \"The Visionary\"?", options: ["Jugram", "Lille", "Gremmy", "Askin"], correct: 2 },
  { text: "Which Hashira officially had the fastest running speed?", options: ["Sanemi", "Giyu", "Tengen", "Muichiro"], correct: 2 },
  { text: "Which chapter first mentioned Joy Boy by name?", options: ["628", "700", "800", "1044"], correct: 0 },
  { text: "Which Bleach arc introduced Fullbringers?", options: ["Soul Society Arc", "Arrancar Arc", "Lost Agent Arc", "TYBW Arc"], correct: 2 },
  { text: "Which JoJo Stand manipulates weather unconsciously?", options: ["Whitesnake", "Weather Report", "Made in Heaven", "King Crimson"], correct: 1 },
  { text: "Which chapter revealed Itachi's illness?", options: ["390", "395", "401", "410"], correct: 2 },
  { text: "What is the release command for Kyoka Suigetsu?", options: ["Bloom", "Fly", "Scatter", "Shatter"], correct: 3 },
  { text: "Which One Piece SBS confirmed Zoro's real-world nationality?", options: ["SBS 40", "SBS 56", "SBS 70", "SBS 90"], correct: 1 },
  { text: "Which JoJo arc introduced the Spin power system?", options: ["Stardust Crusaders", "Stone Ocean", "Steel Ball Run", "JoJolion"], correct: 2 },
  { text: "Which Bleach captain used Konjiki Ashisogi Jizo?", options: ["Gin", "Byakuya", "Mayuri", "Komamura"], correct: 2 },
  { text: "Which Demon Slayer Hashira had the weakest physical strength officially?", options: ["Shinobu", "Mitsuri", "Muichiro", "Obanai"], correct: 0 },
  { text: "Which Naruto databook confirmed Minato's mission totals?", options: ["Databook 1", "Databook 2", "Databook 3", "Databook 4"], correct: 3 },
  { text: "Which Hunter x Hunter volume introduced Beyond Netero?", options: ["Volume 30", "Volume 31", "Volume 32", "Volume 33"], correct: 2 },
  { text: "Which One Piece island changes climate every season?", options: ["Zou", "Punk Hazard", "Little Garden", "Elbaf"], correct: 2 },
  { text: "Which JoJo protagonist never directly defeated the final villain?", options: ["Jotaro", "Jonathan", "Giorno", "Josuke"], correct: 1 },
  { text: "Which Bleach Espada used Respira?", options: ["Grimmjow", "Ulquiorra", "Baraggan", "Starrk"], correct: 2 },
  { text: "Which Naruto opening featured the song \"Sign\"?", options: ["Opening 4", "Opening 5", "Opening 6", "Opening 7"], correct: 2 },
  { text: "Which JoJo Stand evolved into C-Moon?", options: ["Star Platinum", "Whitesnake", "Killer Queen", "Stone Free"], correct: 1 },
  { text: "Which Titan can inherit future memories?", options: ["Founding Titan", "Attack Titan", "Jaw Titan", "Beast Titan"], correct: 1 },
  { text: "Which anime features the Sibyl System?", options: ["Ergo Proxy", "Monster", "Psycho-Pass", "Pluto"], correct: 2 },
  { text: "Which Fullmetal Alchemist opening was performed by L'Arc-en-Ciel?", options: ["Again", "Rewrite", "Ready Steady Go", "Rain"], correct: 2 },
  { text: "Which JoJo villain reset the universe?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 3 },
  { text: "Which One Piece chapter officially revealed Gear 5?", options: ["1040", "1042", "1044", "1046"], correct: 2 },
  { text: "Which Naruto character naturally awakened the Rinnegan?", options: ["Sasuke", "Obito", "Madara", "Nagato"], correct: 2 },
  { text: "Which Bleach captain became a Visored leader?", options: ["Rose", "Kensei", "Love", "Shinji"], correct: 3 },
  { text: "Which Demon Slayer Upper Moon ranked first?", options: ["Doma", "Akaza", "Kokushibo", "Gyokko"], correct: 2 },
  { text: "Which JoJo Stand has contradictory stats according to Araki interviews?", options: ["Star Platinum", "Killer Queen", "Gold Experience Requiem", "Tusk Act 4"], correct: 2 },
  { text: "Which Attack on Titan character improved ODM technology?", options: ["Hange", "Levi", "Angel Aaltonen", "Erwin"], correct: 2 },
  { text: "Which Hunter x Hunter character becomes a Specialist under Emperor Time?", options: ["Gon", "Kurapika", "Killua", "Leorio"], correct: 1 },
  { text: "Which One Piece Emperor stopped the Marineford war?", options: ["Kaido", "Big Mom", "Shanks", "Blackbeard"], correct: 2 },
  { text: "Which Bleach villain controlled complete hypnosis?", options: ["Yhwach", "Ulquiorra", "Aizen", "Gin"], correct: 2 },
  { text: "Which Naruto eye technique trapped the world in illusion?", options: ["Izanagi", "Tsukuyomi", "Infinite Tsukuyomi", "Kamui"], correct: 2 },
  { text: "Which anime features the Anti-Spirals?", options: ["Evangelion", "FLCL", "Gurren Lagann", "Akira"], correct: 2 },
  { text: "Which JoJo villain used King Crimson?", options: ["Dio", "Kira", "Pucci", "Diavolo"], correct: 3 },
  { text: "Which One Piece character first directly mentioned Nika?", options: ["Kaido", "Vegapunk", "Shanks", "Who's-Who"], correct: 3 },
  { text: "Which Bleach character used Kamishini no Yari?", options: ["Renji", "Aizen", "Gin", "Tosen"], correct: 2 },
  { text: "Which Naruto character naturally used all five chakra natures?", options: ["Naruto", "Kakashi", "Hiruzen", "Sasuke"], correct: 2 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Election Arc", "Yorknew Arc", "Chimera Ant Arc", "Greed Island Arc"], correct: 2 },
  { text: "Which JoJo part introduced the Arrow?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which anime movie won Studio Ghibli an Oscar?", options: ["Ponyo", "Spirited Away", "Mononoke", "Howl's Moving Castle"], correct: 1 },
  { text: "Which Bleach arc introduced Yhwach?", options: ["Soul Society Arc", "Arrancar Arc", "TYBW Arc", "Lost Agent Arc"], correct: 2 },
  { text: "Which JoJo protagonist used the Spin technique?", options: ["Giorno", "Josuke", "Johnny Joestar", "Jonathan"], correct: 2 },
  { text: "Which Attack on Titan Titan is Annie Leonhart?", options: ["Jaw Titan", "Female Titan", "Cart Titan", "Beast Titan"], correct: 1 },
  { text: "Which Naruto clan does Hinata belong to?", options: ["Senju", "Uchiha", "Hyuga", "Uzumaki"], correct: 2 },
  { text: "Which Demon Slayer Hashira uses Sound Breathing?", options: ["Obanai", "Sanemi", "Tengen", "Gyomei"], correct: 2 },
  { text: "Which One Piece character is called the \"Strongest Creature\"?", options: ["Whitebeard", "Kaido", "Blackbeard", "Roger"], correct: 1 },
  { text: "Which Bleach Espada ranked fourth?", options: ["Grimmjow", "Nnoitra", "Ulquiorra", "Starrk"], correct: 2 },
  { text: "Which JoJo Stand belongs to Weather Report?", options: ["Stone Free", "Whitesnake", "Weather Report", "Soft & Wet"], correct: 2 },
  { text: "Which anime features the Eclipse event?", options: ["Berserk", "Claymore", "Hellsing", "Vinland Saga"], correct: 0 },
  { text: "Which Hunter x Hunter character uses Bungee Gum?", options: ["Chrollo", "Illumi", "Hisoka", "Feitan"], correct: 2 },
  { text: "Which Bleach Quincy possessed the Schrift \"The Balance\"?", options: ["Askin", "Jugram Haschwalth", "Bazz-B", "Lille Barro"], correct: 1 },
  { text: "Which Naruto character used the Truth-Seeking Balls most prominently?", options: ["Obito", "Naruto", "Madara", "Hagoromo"], correct: 0 },
  { text: "Which One Piece character possesses the Ope Ope no Mi?", options: ["Kidd", "Law", "Doflamingo", "Marco"], correct: 1 },
  { text: "Which JoJo Stand belongs to Enrico Pucci before Made in Heaven?", options: ["Whitesnake", "Killer Queen", "The World", "King Crimson"], correct: 0 },
  { text: "Which Hunter x Hunter character became the King of the Chimera Ants?", options: ["Pitou", "Pouf", "Meruem", "Youpi"], correct: 2 },
  { text: "Which Demon Slayer Upper Moon used Emotion Clones?", options: ["Gyokko", "Hantengu", "Doma", "Kaigaku"], correct: 1 },
  { text: "Which anime features the \"Gate of Babylon\"?", options: ["Fate Stay Night", "Bleach", "Noragami", "Black Clover"], correct: 0 },
  { text: "Which Naruto clan specialized in mind transfer jutsu?", options: ["Nara Clan", "Yamanaka Clan", "Aburame Clan", "Akimichi Clan"], correct: 1 },
  { text: "Which Bleach captain had the Bankai Katen Kyokotsu Karamatsu Shinju?", options: ["Urahara", "Yamamoto", "Shunsui", "Ukitake"], correct: 2 },
  { text: "Which One Piece arc introduced the Worst Generation together?", options: ["Marineford", "Alabasta", "Sabaody Archipelago", "Dressrosa"], correct: 2 },
  { text: "Which JoJo protagonist had four testicles according to canon?", options: ["Josuke Higashikata (Part 8)", "Giorno", "Johnny", "Jotaro"], correct: 0 },
  { text: "Which Attack on Titan character inherited the Beast Titan after Zeke?", options: ["Falco", "Reiner", "Colt", "Pieck"], correct: 0 },
  { text: "Which Hunter x Hunter Phantom Troupe member could read memories?", options: ["Pakunoda", "Machi", "Kortopi", "Bonolenov"], correct: 0 },
  { text: "Which Naruto villain summoned the Gedo Statue first?", options: ["Madara", "Pain", "Obito", "Kabuto"], correct: 1 },
  { text: "Which Bleach Espada had the aspect of death \"Solitude\"?", options: ["Ulquiorra", "Starrk", "Nnoitra", "Baraggan"], correct: 1 },
  { text: "Which Demon Slayer character turned into a demon temporarily in the finale?", options: ["Zenitsu", "Tanjiro", "Inosuke", "Giyu"], correct: 1 },
  { text: "Which One Piece character awakened Mochi powers?", options: ["Cracker", "Smoothie", "Katakuri", "Perospero"], correct: 2 },
  { text: "Which JoJo villain used D4C?", options: ["Funny Valentine", "Pucci", "Kira", "Diavolo"], correct: 0 },
  { text: "Which anime features the Holy Britannian Empire?", options: ["Akame ga Kill", "Code Geass", "Psycho-Pass", "86"], correct: 1 },
  { text: "Which Naruto character possessed the Kotoamatsukami eye?", options: ["Itachi", "Madara", "Shisui", "Sasuke"], correct: 2 },
  { text: "Which Bleach character became a temporary Soul Reaper substitute badge holder?", options: ["Chad", "Uryu", "Ichigo", "Orihime"], correct: 2 },
  { text: "Which One Piece character first used Future Sight against Luffy?", options: ["Kaido", "Katakuri", "Doflamingo", "Rayleigh"], correct: 1 },
  { text: "Which Hunter x Hunter Royal Guard used scales to manipulate people emotionally?", options: ["Pouf", "Pitou", "Youpi", "Meruem"], correct: 0 },
  { text: "Which Demon Slayer Hashira survived with one arm after the final battle?", options: ["Muichiro", "Obanai", "Giyu", "Gyomei"], correct: 2 },
  { text: "Which JoJo Stand belonged to Rohan Kishibe?", options: ["Heaven's Door", "Stone Free", "Crazy Diamond", "Echoes"], correct: 0 },
  { text: "Which Naruto villain manipulated Kabuto during the war?", options: ["Orochimaru", "Madara", "Obito", "Black Zetsu"], correct: 2 },
  { text: "Which Bleach captain had dual Zanpakuto spirits?", options: ["Kyoraku", "Ukitake", "Yamamoto", "Hitsugaya"], correct: 0 },
  { text: "Which One Piece scientist created the Pacifistas?", options: ["Caesar", "Judge", "Vegapunk", "Queen"], correct: 2 },
  { text: "Which Hunter x Hunter character fought Netero in the final Chimera Ant battle?", options: ["Youpi", "Pouf", "Meruem", "Pitou"], correct: 2 },
  { text: "Which anime features \"Equivalent Exchange\"?", options: ["Fate Zero", "Fullmetal Alchemist", "Noragami", "D.Gray-man"], correct: 1 },
  { text: "Which Naruto tailed beast belonged to Killer B?", options: ["Kurama", "Son Goku", "Gyuki", "Isobu"], correct: 2 },
  { text: "Which Bleach villain absorbed the Soul King?", options: ["Aizen", "Yhwach", "Ichibei", "Jugram"], correct: 1 },
  { text: "Which One Piece arc introduced Gear Second?", options: ["Enies Lobby", "Alabasta", "Marineford", "Thriller Bark"], correct: 0 },
  { text: "Which JoJo protagonist used Tusk Act 4?", options: ["Jolyne", "Josuke", "Johnny", "Giorno"], correct: 2 },
  { text: "Which Demon Slayer Upper Moon replaced Daki and Gyutaro after their deaths?", options: ["Kaigaku", "Nakime", "Hantengu", "Gyokko"], correct: 1 },
  { text: "Which Naruto character used Flying Thunder God most efficiently?", options: ["Tobirama", "Minato", "Naruto", "Sasuke"], correct: 1 },
  { text: "Which Bleach captain lost his Bankai to the Quincy first?", options: ["Byakuya", "Komamura", "Hitsugaya", "Soi Fon"], correct: 0 },
  { text: "Which Hunter x Hunter character used APR during combat?", options: ["Knuckle", "Shoot", "Morel", "Kite"], correct: 0 },
  { text: "Which One Piece character carried the title \"Heavenly Yaksha\"?", options: ["Kaido", "Doflamingo", "Crocodile", "Enel"], correct: 1 },
  { text: "Which JoJo villain fused with the Green Baby?", options: ["Pucci", "Dio", "Valentine", "Kira"], correct: 0 },
  { text: "Which Naruto member of the Sannin became Hokage?", options: ["Orochimaru", "Jiraiya", "Tsunade", "None"], correct: 2 },
  { text: "Which Bleach Arrancar used wolves as explosive weapons?", options: ["Grimmjow", "Starrk", "Ulquiorra", "Nnoitra"], correct: 1 },
  { text: "Which One Piece race can naturally produce electricity?", options: ["Lunarians", "Mink Tribe", "Giants", "Fish-Men"], correct: 1 },
  { text: "Which Hunter x Hunter character used \"Godspeed\"?", options: ["Gon", "Killua", "Hisoka", "Illumi"], correct: 1 },
  { text: "Which Demon Slayer Hashira created Flower Breathing from Water Breathing?", options: ["Shinobu", "Kanae", "Mitsuri", "Kanao"], correct: 1 },
  { text: "Which JoJo Stand can revert actions to zero?", options: ["King Crimson", "GER", "Made in Heaven", "Killer Queen"], correct: 1 },
  { text: "Which Naruto character sealed Kaguya alongside Naruto?", options: ["Sakura", "Kakashi", "Sasuke", "Obito"], correct: 2 },
  { text: "Which Bleach captain possessed the oldest fire-type Zanpakuto?", options: ["Kyoraku", "Yamamoto", "Hitsugaya", "Ukitake"], correct: 1 },
  { text: "Which One Piece arc introduced Silvers Rayleigh?", options: ["Marineford", "Sabaody Archipelago", "Water 7", "Punk Hazard"], correct: 1 },
  { text: "Which Hunter x Hunter character could use Deep Purple smoke constructs?", options: ["Morel", "Knov", "Shoot", "Knuckle"], correct: 0 },
];
