export default [
  { text: "Which animator corrected the Naruto vs Sasuke rooftop clash sequence?", options: ["Yutaka Nakamura", "Norio Matsumoto", "Naoko Yamada", "Tite Kubo"], correct: 1 },
  { text: "What hidden phrase appears inside some Fullmetal Alchemist transmutation circles?", options: ["Deus Ex Machina", "Aleph", "V.I.T.R.I.O.L.", "Ouroboros"], correct: 2 },
  { text: "Which JoJo Stand stat page intentionally contradicts itself according to Araki?", options: ["Star Platinum", "Killer Queen", "Gold Experience Requiem", "Tusk Act 4"], correct: 2 },
  { text: "What was the exact publication date of Dragon Ball chapter 1?", options: ["November 20, 1984", "December 1, 1984", "January 5, 1985", "October 10, 1984"], correct: 0 },
  { text: "Which Hunter x Hunter chapter fully displayed the Dark Continent map?", options: ["320", "338", "350", "400"], correct: 1 },
  { text: "Which One Piece databook confirmed Shanks became a Yonko 6 years before the story?", options: ["Blue Deep", "Green", "Vivre Card", "Red Grand Characters"], correct: 2 },
  { text: "Which Evangelion pilot recorded the highest sync ratio?", options: ["Asuka", "Rei", "Kaworu", "Shinji"], correct: 3 },
  { text: "Which Naruto opening featured the song “Sign”?", options: ["Opening 4", "Opening 5", "Opening 6", "Opening 7"], correct: 2 },
  { text: "Which Bleach Espada used Respira?", options: ["Stark", "Ulquiorra", "Baraggan", "Nnoitra"], correct: 2 },
  { text: "Which JoJo protagonist used the Spin technique?", options: ["Josuke", "Giorno", "Jonathan", "Johnny Joestar"], correct: 3 },
  { text: "Which Attack on Titan character invented modern ODM gear improvements?", options: ["Hange", "Erwin", "Angel Aaltonen", "Levi"], correct: 2 },
  { text: "Which Demon Slayer Hashira officially had the weakest physical strength?", options: ["Shinobu", "Mitsuri", "Muichiro", "Obanai"], correct: 0 },
  { text: "Which chapter contains Ace’s death in One Piece?", options: ["570", "572", "574", "580"], correct: 2 },
  { text: "Which JoJo villain reset the universe?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 3 },
  { text: "Which Akatsuki member never wore a scratched headband?", options: ["Kisame", "Itachi", "Zetsu", "Kakuzu"], correct: 2 },
  { text: "Which Fullmetal Alchemist opening was performed by L’Arc-en-Ciel?", options: ["Again", "Rewrite", "Ready Steady Go", "Period"], correct: 2 },
  { text: "Which JoJo part introduced the Stand Arrow?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which One Piece island permanently changes climate every season?", options: ["Punk Hazard", "Zou", "Little Garden", "Drum Island"], correct: 2 },
  { text: "Which Naruto character naturally used all five chakra natures?", options: ["Kakashi", "Hiruzen", "Naruto", "Madara"], correct: 1 },
  { text: "Which Bleach captain used Konjiki Ashisogi Jizo?", options: ["Byakuya", "Mayuri", "Kenpachi", "Gin"], correct: 1 },
  { text: "Which anime movie won Studio Ghibli an Oscar?", options: ["Howl’s Moving Castle", "Ponyo", "Spirited Away", "Mononoke"], correct: 2 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Yorknew", "Greed Island", "Election Arc", "Chimera Ant Arc"], correct: 3 },
  { text: "Which One Piece character first directly mentioned Nika?", options: ["Kaido", "Shanks", "Who’s-Who", "Vegapunk"], correct: 2 },
  { text: "Which JoJo Stand evolved into C-Moon?", options: ["Whitesnake", "Star Platinum", "King Crimson", "Stone Free"], correct: 0 },
  { text: "Which Naruto character officially completed over 1000 missions?", options: ["Guy", "Kakashi", "Hiruzen", "Jiraiya"], correct: 1 },
  { text: "Which Bleach arc introduced Yhwach?", options: ["Arrancar Arc", "Soul Society Arc", "TYBW Arc", "Lost Agent Arc"], correct: 2 },
  { text: "Which Fullmetal Alchemist character burned a tattoo off his back?", options: ["Scar", "Roy Mustang", "Edward", "Kimblee"], correct: 1 },
  { text: "Which Attack on Titan Titan can inherit future memories?", options: ["Founding Titan", "Beast Titan", "Jaw Titan", "Attack Titan"], correct: 3 },
  { text: "Which One Piece SBS revealed Zoro’s real-world nationality?", options: ["SBS 20", "SBS 40", "SBS 56", "SBS 99"], correct: 2 },
  { text: "Which Dragon Ball form first gave Goku silver hair?", options: ["Super Saiyan Blue", "Ultra Instinct", "Super Saiyan 4", "Kaioken"], correct: 1 },
  { text: "Which JoJo protagonist never directly defeated the final villain?", options: ["Giorno", "Jonathan", "Josuke", "Jolyne"], correct: 1 },
  { text: "Which Naruto databook confirmed Minato’s mission totals?", options: ["Databook 1", "Databook 2", "Databook 3", "Databook 4"], correct: 3 },
  { text: "Which Bleach character used Kamishini no Yari?", options: ["Aizen", "Gin Ichimaru", "Tosen", "Renji"], correct: 1 },
  { text: "Which One Piece chapter officially revealed Gear 5?", options: ["1040", "1042", "1044", "1046"], correct: 2 },
  { text: "Which Demon Slayer Upper Moon ranked first?", options: ["Akaza", "Doma", "Kokushibo", "Gyutaro"], correct: 2 },
  { text: "Which JoJo arc introduced the Spin power system?", options: ["Battle Tendency", "Stone Ocean", "Steel Ball Run", "JoJolion"], correct: 2 },
  { text: "Which anime features the organization SEELE?", options: ["Monster", "Evangelion", "Psycho-Pass", "Ergo Proxy"], correct: 1 },
  { text: "Which Hunter x Hunter character becomes a Specialist under Emperor Time?", options: ["Gon", "Killua", "Kurapika", "Leorio"], correct: 2 },
  { text: "Which Bleach captain became a Visored leader?", options: ["Kensei", "Shinji", "Rose", "Love"], correct: 1 },
  { text: "Which Naruto character naturally awakened the Rinnegan?", options: ["Sasuke", "Obito", "Madara", "Nagato"], correct: 2 },
  { text: "Which One Piece character is called the “Strongest Creature”?", options: ["Whitebeard", "Kaido", "Big Mom", "Shanks"], correct: 1 },
  { text: "Which JoJo villain used King Crimson?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 2 },
  { text: "Which Demon Slayer character created Flower Breathing?", options: ["Kanae", "Shinobu", "Mitsuri", "Kanao"], correct: 0 },
  { text: "Which Bleach Espada was ranked Fourth?", options: ["Grimmjow", "Nnoitra", "Ulquiorra", "Stark"], correct: 2 },
  { text: "Which Hunter x Hunter volume introduced Beyond Netero?", options: ["30", "31", "32", "33"], correct: 2 },
  { text: "Which JoJo Stand has contradictory stats according to Araki?", options: ["Star Platinum", "GER", "Killer Queen", "Tusk Act 4"], correct: 1 },
  { text: "Which One Piece Emperor stopped the Marineford war?", options: ["Kaido", "Blackbeard", "Shanks", "Big Mom"], correct: 2 },
  { text: "Which Naruto technique trapped the world in illusion?", options: ["Kotoamatsukami", "Tsukuyomi", "Infinite Tsukuyomi", "Izanagi"], correct: 2 },
  { text: "Which anime contains the phrase “The human whose name is written in this note shall die”?", options: ["Another", "Tokyo Ghoul", "Death Note", "Parasyte"], correct: 2 },
  { text: "Which JoJo Stand manipulates weather unconsciously?", options: ["Whitesnake", "Weather Report", "Made in Heaven", "King Crimson"], correct: 1 },
  { text: "Which Attack on Titan wall was destroyed first?", options: ["Wall Rose", "Wall Sina", "Wall Maria", "Trost Wall"], correct: 2 }
];