export default [
  { text: "Who is the protagonist of Naruto?", options: ["Sasuke", "Naruto", "Kakashi", "Gaara"], correct: 1 },
  { text: "What is Luffy's dream?", options: ["Become Hokage", "Become Pirate King", "Become Wizard King", "Become Hero"], correct: 1 },
  { text: "Which anime features Titans?", options: ["Bleach", "Attack on Titan", "Fairy Tail", "Blue Lock"], correct: 1 },
  { text: "What is Goku's race?", options: ["Human", "Saiyan", "Namekian", "Android"], correct: 1 },
  { text: "Who is Tanjiro's sister?", options: ["Mitsuri", "Shinobu", "Nezuko", "Kanao"], correct: 2 },
  { text: "Which anime is about volleyball?", options: ["Slam Dunk", "Blue Lock", "Haikyuu", "Kuroko no Basket"], correct: 2 },
  { text: "Who owns the Death Note first in the anime?", options: ["Ryuk", "L", "Light Yagami", "Near"], correct: 2 },
  { text: "What village is Naruto from?", options: ["Sand Village", "Mist Village", "Leaf Village", "Stone Village"], correct: 2 },
  { text: "Who is the captain of the Straw Hat Pirates?", options: ["Zoro", "Sanji", "Luffy", "Ace"], correct: 2 },
  { text: "What color is Pikachu?", options: ["Red", "Yellow", "Blue", "Green"], correct: 1 },
  { text: "Which anime features Soul Reapers?", options: ["Naruto", "Bleach", "Fairy Tail", "Dragon Ball"], correct: 1 },
  { text: "Who is Naruto's rival?", options: ["Kakashi", "Sasuke", "Shikamaru", "Lee"], correct: 1 },
  { text: "Which anime features Dragon Balls?", options: ["Bleach", "Dragon Ball", "One Piece", "Fairy Tail"], correct: 1 },
  { text: "What is the name of Luffy's crew?", options: ["Red Hair Pirates", "Straw Hat Pirates", "Blackbeard Pirates", "Heart Pirates"], correct: 1 },
  { text: "Who trained Tanjiro?", options: ["Giyu", "Urokodaki", "Rengoku", "Tengen"], correct: 1 },
  { text: "Which anime features Quirks?", options: ["Bleach", "Naruto", "My Hero Academia", "Black Clover"], correct: 2 },
  { text: "What is Ichigo's hair color?", options: ["Black", "Brown", "Orange", "White"], correct: 2 },
  { text: "Who is Goku's strongest rival?", options: ["Yamcha", "Krillin", "Vegeta", "Piccolo"], correct: 2 },
  { text: "Which anime features ninjas?", options: ["One Piece", "Naruto", "Bleach", "Fairy Tail"], correct: 1 },
  { text: "What is Ash's main Pokémon?", options: ["Charizard", "Bulbasaur", "Pikachu", "Squirtle"], correct: 2 },
  { text: "Which anime features Demon Slayers?", options: ["Jujutsu Kaisen", "Demon Slayer", "Bleach", "Blue Exorcist"], correct: 1 },
  { text: "What is Naruto's favorite food?", options: ["Sushi", "Curry", "Ramen", "Rice Balls"], correct: 2 },
  { text: "Who wears a straw hat?", options: ["Ichigo", "Deku", "Luffy", "Gon"], correct: 2 },
  { text: "Which anime features alchemy?", options: ["Bleach", "Fullmetal Alchemist", "Fairy Tail", "Attack on Titan"], correct: 1 },
  { text: "Who is the Flame Hashira?", options: ["Tengen", "Giyu", "Rengoku", "Sanemi"], correct: 2 },
  { text: "Which anime features cursed spirits?", options: ["One Piece", "Naruto", "Jujutsu Kaisen", "Fairy Tail"], correct: 2 },
  { text: "What animal is Tony Tony Chopper?", options: ["Cat", "Dog", "Reindeer", "Rabbit"], correct: 2 },
  { text: "Which anime features giant walls?", options: ["Attack on Titan", "Bleach", "Fairy Tail", "Naruto"], correct: 0 },
  { text: "Who is Deku's idol?", options: ["Hawks", "Endeavor", "Bakugo", "All Might"], correct: 3 },
  { text: "Which anime features magic guilds?", options: ["Fairy Tail", "Naruto", "Bleach", "One Piece"], correct: 0 },
  { text: "What is Luffy's Devil Fruit power?", options: ["Ice", "Fire", "Rubber", "Smoke"], correct: 2 },
  { text: "Which anime features the Survey Corps?", options: ["Demon Slayer", "Attack on Titan", "Black Clover", "JoJo"], correct: 1 },
  { text: "Who uses Bankai?", options: ["Naruto", "Goku", "Ichigo", "Luffy"], correct: 2 },
  { text: "Which anime features psychic powers?", options: ["Blue Lock", "Haikyuu", "Mob Psycho 100", "Slam Dunk"], correct: 2 },
  { text: "What is the name of Naruto's fox?", options: ["Shukaku", "Kurama", "Gyuki", "Matatabi"], correct: 1 },
  { text: "Which anime features basketball?", options: ["Haikyuu", "Blue Lock", "Kuroko no Basket", "Yuri on Ice"], correct: 2 },
  { text: "Who is Luffy's brother?", options: ["Law", "Zoro", "Ace", "Sabo"], correct: 2 },
  { text: "Which anime features hollows?", options: ["Bleach", "Naruto", "Dragon Ball", "One Piece"], correct: 0 },
  { text: "What color is Nezuko's bamboo muzzle?", options: ["Red", "Blue", "Green", "Black"], correct: 2 },
  { text: "Which anime features the Akatsuki?", options: ["Bleach", "Naruto", "Fairy Tail", "One Piece"], correct: 1 },
  { text: "Who is the captain of the Black Bulls?", options: ["Julius", "Yuno", "Yami", "Nozel"], correct: 2 },
  { text: "Which anime features Saiyans?", options: ["Naruto", "Bleach", "Dragon Ball", "Fairy Tail"], correct: 2 },
  { text: "What is Inosuke known for wearing?", options: ["Fox Mask", "Cat Mask", "Boar Mask", "Bird Mask"], correct: 2 },
  { text: "Which anime features pirates searching for treasure?", options: ["Bleach", "Naruto", "One Piece", "Haikyuu"], correct: 2 },
  { text: "Who is Goku's oldest son?", options: ["Trunks", "Goten", "Gohan", "Broly"], correct: 2 },
  { text: "Which anime features the Hokages?", options: ["Naruto", "Bleach", "One Piece", "Fairy Tail"], correct: 0 },
  { text: "What is Zenitsu's breathing style?", options: ["Water", "Thunder", "Flame", "Mist"], correct: 1 },
  { text: "Which anime features wizards?", options: ["Fairy Tail", "Haikyuu", "Blue Lock", "Slam Dunk"], correct: 0 },
  { text: "Who is Eren's adoptive sister?", options: ["Annie", "Sasha", "Historia", "Mikasa"], correct: 3 },
  { text: "Which anime features Gojo Satoru?", options: ["Bleach", "Naruto", "Jujutsu Kaisen", "Fairy Tail"], correct: 2 },
  { text: "What is the name of Sasuke's brother?", options: ["Madara", "Obito", "Itachi", "Shisui"], correct: 2 },
  { text: "Which anime features treasure hunters called pirates?", options: ["One Piece", "Bleach", "Naruto", "Demon Slayer"], correct: 0 },
  { text: "What is Goku's signature attack?", options: ["Rasengan", "Kamehameha", "Getsuga Tensho", "Spirit Gun"], correct: 1 },
  { text: "Which anime features breathing techniques?", options: ["Bleach", "Demon Slayer", "Fairy Tail", "One Piece"], correct: 1 },
  { text: "What is the name of Naruto's son?", options: ["Boruto", "Kawaki", "Menma", "Konohamaru"], correct: 0 },
  { text: "Which anime features Soul Society?", options: ["Bleach", "Naruto", "Dragon Ball", "Haikyuu"], correct: 0 },
  { text: "Who is the cook of the Straw Hat Pirates?", options: ["Zoro", "Usopp", "Sanji", "Brook"], correct: 2 },
  { text: "Which anime features heroes and villains?", options: ["My Hero Academia", "Bleach", "One Piece", "Fairy Tail"], correct: 0 },
  { text: "What color are Naruto's eyes?", options: ["Red", "Green", "Blue", "Black"], correct: 2 },
  { text: "Which anime features the Colossal Titan?", options: ["Attack on Titan", "Bleach", "Naruto", "Black Clover"], correct: 0 },
  { text: "Who is the captain of Squad 6 in Bleach?", options: ["Renji", "Aizen", "Byakuya", "Kenpachi"], correct: 2 },
  { text: "Which anime features Devil Fruits?", options: ["Naruto", "Fairy Tail", "One Piece", "Bleach"], correct: 2 },
  { text: "What is Tanjiro's last name?", options: ["Kamado", "Agatsuma", "Hashibira", "Rengoku"], correct: 0 },
  { text: "Which anime features magic knights?", options: ["Black Clover", "Bleach", "Naruto", "Dragon Ball"], correct: 0 },
  { text: "Who is Naruto's teacher at the academy?", options: ["Kakashi", "Guy", "Iruka", "Asuma"], correct: 2 },
  { text: "Which anime features a notebook from a Shinigami?", options: ["Death Note", "Bleach", "Blue Exorcist", "JoJo"], correct: 0 },
  { text: "What weapon does Zoro mainly use?", options: ["Guns", "Spears", "Swords", "Axe"], correct: 2 },
  { text: "Which anime features Titans eating humans?", options: ["Attack on Titan", "Naruto", "Fairy Tail", "Blue Lock"], correct: 0 },
  { text: "Who is the electric-type Pokémon mascot?", options: ["Charmander", "Pikachu", "Eevee", "Snorlax"], correct: 1 },
  { text: "Which anime features exorcists fighting curses?", options: ["Jujutsu Kaisen", "Haikyuu", "One Piece", "Fairy Tail"], correct: 0 },
  { text: "What is Goku's wife's name?", options: ["Bulma", "Chi-Chi", "Android 18", "Videl"], correct: 1 },
  { text: "Which anime features the Espada?", options: ["Bleach", "Naruto", "Fairy Tail", "Black Clover"], correct: 0 },
  { text: "Who is the navigator of the Straw Hats?", options: ["Robin", "Nami", "Vivi", "Hancock"], correct: 1 },
  { text: "Which anime features Hero Killer Stain?", options: ["Black Clover", "Bleach", "My Hero Academia", "Fairy Tail"], correct: 2 },
  { text: "What color is Tanjiro's uniform?", options: ["Blue", "Green", "Black", "White"], correct: 2 },
  { text: "Which anime features giant humanoid monsters?", options: ["Attack on Titan", "Death Note", "Haikyuu", "Blue Lock"], correct: 0 },
  { text: "Who is Naruto's mother?", options: ["Tsunade", "Sakura", "Kushina", "Hinata"], correct: 2 },
  { text: "Which anime features Spirit Pressure?", options: ["Bleach", "Naruto", "Fairy Tail", "One Piece"], correct: 0 },
  { text: "What is Luffy's full name?", options: ["Portgas D. Luffy", "Monkey D. Luffy", "Gol D. Luffy", "Rocks D. Luffy"], correct: 1 },
  { text: "Which anime features Clover Kingdom?", options: ["Fairy Tail", "Bleach", "Black Clover", "Naruto"], correct: 2 },
  { text: "Who is the insect Hashira?", options: ["Mitsuri", "Shinobu", "Kanao", "Kanae"], correct: 1 },
  { text: "Which anime features Ryuk?", options: ["Bleach", "Death Note", "One Piece", "Naruto"], correct: 1 },
  { text: "What is Vegeta's title?", options: ["Prince of Saiyans", "Hokage", "Hero King", "Wizard King"], correct: 0 },
  { text: "Which anime features anti-magic swords?", options: ["Bleach", "Black Clover", "Fairy Tail", "Dragon Ball"], correct: 1 },
  { text: "Who is the doctor of the Straw Hat Pirates?", options: ["Franky", "Brook", "Chopper", "Jinbe"], correct: 2 },
  { text: "Which anime features ODM gear?", options: ["Attack on Titan", "Naruto", "Bleach", "One Piece"], correct: 0 },
  { text: "What is the name of Gojo's student with pink hair?", options: ["Megumi", "Yuta", "Yuji", "Toge"], correct: 2 },
  { text: "Which anime features the Gotei 13?", options: ["Fairy Tail", "Bleach", "Naruto", "Dragon Ball"], correct: 1 },
  { text: "Who is the first Hokage?", options: ["Tobirama", "Minato", "Hashirama", "Hiruzen"], correct: 2 },
  { text: "Which anime features Dragon Slayers?", options: ["Fairy Tail", "Bleach", "Naruto", "Haikyuu"], correct: 0 },
  { text: "What is the name of Eren's Titan form?", options: ["Attack Titan", "Beast Titan", "Jaw Titan", "Cart Titan"], correct: 0 },
  { text: "Which anime features Nen abilities?", options: ["Naruto", "Hunter x Hunter", "Bleach", "One Piece"], correct: 1 },
  { text: "Who is the strongest hero in One Punch Man?", options: ["Genos", "Garou", "Saitama", "King"], correct: 2 },
  { text: "Which anime features spirit detectives?", options: ["Yu Yu Hakusho", "Bleach", "Naruto", "JoJo"], correct: 0 },
  { text: "What is the name of Sasuke's clan?", options: ["Hyuga", "Senju", "Uzumaki", "Uchiha"], correct: 3 },
  { text: "Which anime features Phantom Troupe?", options: ["Bleach", "Hunter x Hunter", "Naruto", "Fairy Tail"], correct: 1 },
  { text: "Who is the strongest known Saiyan rival of Goku?", options: ["Yamcha", "Vegeta", "Krillin", "Tien"], correct: 1 },
  { text: "Which anime features cursed fingers of Sukuna?", options: ["Bleach", "Jujutsu Kaisen", "Fairy Tail", "Black Clover"], correct: 1 },
  { text: "What is the name of the Female Titan's user?", options: ["Mikasa", "Annie", "Historia", "Pieck"], correct: 1 },
  { text: "Which anime features the Straw Hat Pirates?", options: ["Naruto", "Bleach", "One Piece", "Fairy Tail"], correct: 2 },
];
