export default [
  { text: "What is Gojo Satoru's Domain Expansion called?", options: ["Malevolent Shrine", "Unlimited Void", "Coffin of the Iron Mountain", "Chimera Shadow Garden"], correct: 1 },
  { text: "Which Titan does Armin inherit?", options: ["Beast Titan", "Colossal Titan", "Jaw Titan", "Cart Titan"], correct: 1 },
  { text: "What is Edward Elric's State Alchemist title?", options: ["Flame Alchemist", "Steel Alchemist", "Fullmetal Alchemist", "Ice Alchemist"], correct: 2 },
  { text: "Which One Piece arc introduced Trafalgar Law?", options: ["Marineford", "Dressrosa", "Sabaody Archipelago", "Wano"], correct: 2 },
  { text: "What is Ichigo's inner Hollow called?", options: ["White", "Hollow King", "Grimm", "Vasto"], correct: 0 },
  { text: "Which breathing style does Zenitsu use?", options: ["Mist Breathing", "Water Breathing", "Flame Breathing", "Thunder Breathing"], correct: 3 },
  { text: "Who taught Gon Nen?", options: ["Netero", "Biscuit", "Wing", "Hisoka"], correct: 2 },
  { text: "What is the Beast Titan's human name?", options: ["Reiner", "Zeke", "Porco", "Bertolt"], correct: 1 },
  { text: "Which captain betrayed Soul Society?", options: ["Byakuya", "Gin", "Aizen", "Kenpachi"], correct: 2 },
  { text: "What is Naruto's chakra nature?", options: ["Water", "Fire", "Wind", "Earth"], correct: 2 },
  { text: "Which Akatsuki member uses clay bombs?", options: ["Sasori", "Hidan", "Deidara", "Kisame"], correct: 2 },
  { text: "What is Luffy's Devil Fruit publicly called before the truth was revealed?", options: ["Flame-Flame Fruit", "Gum-Gum Fruit", "Human-Human Fruit", "Chop-Chop Fruit"], correct: 1 },
  { text: "Which Hashira uses Mist Breathing?", options: ["Obanai", "Muichiro", "Sanemi", "Gyomei"], correct: 1 },
  { text: "What is Levi Ackerman's squad called?", options: ["Scout Squad", "Titan Hunters", "Special Operations Squad", "Elite Corps"], correct: 2 },
  { text: "Which Espada was Ulquiorra?", options: ["2nd", "3rd", "4th", "5th"], correct: 2 },
  { text: "What is the name of Natsu's dragon foster father?", options: ["Acnologia", "Metalicana", "Igneel", "Atlas Flame"], correct: 2 },
  { text: "Which anime features the organization SEELE?", options: ["Monster", "Psycho-Pass", "Evangelion", "Ergo Proxy"], correct: 2 },
  { text: "What is the name of Yuno's wind spirit?", options: ["Salamander", "Bell", "Sylph", "Undine"], correct: 2 },
  { text: "Who became the No.1 Hero after All Might?", options: ["Hawks", "Deku", "Endeavor", "Best Jeanist"], correct: 2 },
  { text: "Which Titan killed Eren's mother?", options: ["Beast Titan", "Female Titan", "Smiling Titan", "Jaw Titan"], correct: 2 },
  { text: "What is the name of Light Yagami's Shinigami?", options: ["Rem", "Ryuk", "Gelus", "Sidoh"], correct: 1 },
  { text: "Which JoJo protagonist can stop time?", options: ["Joseph", "Josuke", "Jotaro", "Giorno"], correct: 2 },
  { text: "Which anime uses the phrase \"Plus Ultra\"?", options: ["Black Clover", "Naruto", "My Hero Academia", "Blue Lock"], correct: 2 },
  { text: "What is the name of Asta's rival?", options: ["Magna", "Luck", "Yuno", "Noelle"], correct: 2 },
  { text: "Which One Piece admiral uses ice powers?", options: ["Akainu", "Kizaru", "Fujitora", "Aokiji"], correct: 3 },
  { text: "What is the name of Kirito's first VR game?", options: ["Gun Gale Online", "Alfheim Online", "Sword Art Online", "Underworld"], correct: 2 },
  { text: "Which Hashira survived the final Demon Slayer battle?", options: ["Rengoku", "Muichiro", "Giyu", "Gyomei"], correct: 2 },
  { text: "Which captain uses Senbonzakura?", options: ["Renji", "Byakuya", "Gin", "Toshiro"], correct: 1 },
  { text: "What clan is Hinata from?", options: ["Senju", "Uchiha", "Hyuga", "Uzumaki"], correct: 2 },
  { text: "Which Pokémon does Brock mainly use?", options: ["Gengar", "Psyduck", "Onix", "Pikachu"], correct: 2 },
  { text: "Which anime movie features Chihiro?", options: ["Ponyo", "Spirited Away", "Your Name", "Totoro"], correct: 1 },
  { text: "Which Titan is Annie?", options: ["Jaw Titan", "Female Titan", "Beast Titan", "Cart Titan"], correct: 1 },
  { text: "What is Mob's power linked to?", options: ["Chakra", "Mana", "Emotion percentage", "Stamina"], correct: 2 },
  { text: "Which JoJo villain used Killer Queen?", options: ["Dio", "Kira", "Pucci", "Diavolo"], correct: 1 },
  { text: "What is the name of Chopper's Devil Fruit?", options: ["Human-Human Fruit", "Dog-Dog Fruit", "Flame-Flame Fruit", "Bird-Bird Fruit"], correct: 0 },
  { text: "Which anime uses the phrase \"Dattebayo\"?", options: ["Bleach", "Naruto", "Fairy Tail", "One Piece"], correct: 1 },
  { text: "Which demon ranked Upper Moon One?", options: ["Doma", "Akaza", "Kokushibo", "Gyutaro"], correct: 2 },
  { text: "Which Fullmetal Alchemist character uses Flame Alchemy?", options: ["Edward", "Scar", "Mustang", "Kimblee"], correct: 2 },
  { text: "Which anime features Johan Liebert?", options: ["Pluto", "Death Note", "Monster", "Psycho-Pass"], correct: 2 },
  { text: "What is the name of Eren's Titan?", options: ["Jaw Titan", "Founding Titan", "Attack Titan", "Beast Titan"], correct: 2 },
  { text: "Which JoJo part introduced Dio's Stand?", options: ["Part 2", "Part 3", "Part 4", "Part 5"], correct: 1 },
  { text: "Which anime features Guts?", options: ["Claymore", "Berserk", "Hellsing", "Vinland Saga"], correct: 1 },
  { text: "Which Hashira uses Sound Breathing?", options: ["Obanai", "Tengen", "Sanemi", "Gyomei"], correct: 1 },
  { text: "Which Bleach villain created the Arrancars?", options: ["Gin", "Ulquiorra", "Aizen", "Yhwach"], correct: 2 },
  { text: "What is Lelouch's alter ego called?", options: ["Emperor", "Zero", "Black Knight", "Britannia"], correct: 1 },
  { text: "Which anime features Anti-Magic?", options: ["Bleach", "Fairy Tail", "Black Clover", "Dragon Ball"], correct: 2 },
  { text: "Which Straw Hat uses a slingshot?", options: ["Brook", "Franky", "Usopp", "Jinbe"], correct: 2 },
  { text: "What is Tanjiro's sword called?", options: ["Excalibur", "Nichirin Blade", "Zanpakuto", "Demon Edge"], correct: 1 },
  { text: "Which anime features the UA Sports Festival?", options: ["Blue Lock", "Naruto", "My Hero Academia", "Black Clover"], correct: 2 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Yorknew Arc", "Election Arc", "Chimera Ant Arc", "Greed Island Arc"], correct: 2 },
  { text: "Which Akatsuki member is immortal?", options: ["Kisame", "Deidara", "Hidan", "Sasori"], correct: 2 },
  { text: "What is the name of Zoro's strongest sword in Wano?", options: ["Sandai Kitetsu", "Wado Ichimonji", "Enma", "Shusui"], correct: 2 },
  { text: "Which Hashira uses Serpent Breathing?", options: ["Muichiro", "Obanai", "Sanemi", "Mitsuri"], correct: 1 },
  { text: "Which Bleach captain uses ice powers?", options: ["Byakuya", "Toshiro", "Kenpachi", "Mayuri"], correct: 1 },
  { text: "What is Killua's family famous for?", options: ["Magic", "Assassination", "Swordsmanship", "Alchemy"], correct: 1 },
  { text: "Which anime features the Dark Tournament?", options: ["Yu Yu Hakusho", "Naruto", "Bleach", "Fairy Tail"], correct: 0 },
  { text: "Which Devil Fruit belongs to Ace?", options: ["Gum-Gum Fruit", "Flame-Flame Fruit", "Ice-Ice Fruit", "Smoke-Smoke Fruit"], correct: 1 },
  { text: "What is Gaara the Jinchuriki of?", options: ["Kurama", "Shukaku", "Gyuki", "Matatabi"], correct: 1 },
  { text: "Which Titan is Pieck?", options: ["Cart Titan", "Jaw Titan", "Female Titan", "Beast Titan"], correct: 0 },
  { text: "Which anime features Spirit Energy?", options: ["One Piece", "Yu Yu Hakusho", "Haikyuu", "Blue Lock"], correct: 1 },
  { text: "What is the name of Aizen's sword?", options: ["Senbonzakura", "Zangetsu", "Kyoka Suigetsu", "Benihime"], correct: 2 },
  { text: "Which Demon Slayer Upper Moon uses ice powers?", options: ["Akaza", "Kokushibo", "Gyutaro", "Doma"], correct: 3 },
  { text: "Which anime features Alucard?", options: ["Berserk", "Hellsing", "Claymore", "Black Butler"], correct: 1 },
  { text: "What is the name of Luffy's grandfather?", options: ["Dragon", "Roger", "Garp", "Rayleigh"], correct: 2 },
  { text: "Which JoJo villain uses The World?", options: ["Kira", "Pucci", "Dio", "Diavolo"], correct: 2 },
  { text: "Which anime features the Seven Deadly Sins?", options: ["Fairy Tail", "Bleach", "Black Clover", "Seven Deadly Sins"], correct: 3 },
  { text: "Which breathing style does Inosuke use?", options: ["Beast Breathing", "Wind Breathing", "Stone Breathing", "Mist Breathing"], correct: 0 },
  { text: "Which Naruto character uses the Eight Gates most?", options: ["Kakashi", "Lee", "Guy", "Naruto"], correct: 2 },
  { text: "Which anime features the Quincy?", options: ["Bleach", "Naruto", "One Piece", "Fairy Tail"], correct: 0 },
  { text: "What is the name of Yuji Itadori's curse inside him?", options: ["Mahito", "Sukuna", "Jogo", "Kenjaku"], correct: 1 },
  { text: "Which Straw Hat is a cyborg?", options: ["Brook", "Franky", "Jinbe", "Usopp"], correct: 1 },
  { text: "Which anime features the Survey Corps commander Erwin?", options: ["Bleach", "Attack on Titan", "Vinland Saga", "Black Clover"], correct: 1 },
  { text: "Which Pokémon trainer uses water-type Pokémon and closes his eyes often?", options: ["Brock", "Misty", "Ash", "Squirtle"], correct: 0 },
  { text: "Which anime features the Black Swordsman?", options: ["Claymore", "Berserk", "Hellsing", "Akame ga Kill"], correct: 1 },
  { text: "Which Hashira uses Love Breathing?", options: ["Mitsuri", "Shinobu", "Kanae", "Kanao"], correct: 0 },
  { text: "Which Naruto villain controlled the Nine Tails during the attack on Konoha?", options: ["Pain", "Orochimaru", "Obito", "Madara"], correct: 2 },
  { text: "Which anime features Devil Hunters?", options: ["Chainsaw Man", "Jujutsu Kaisen", "Bleach", "Blue Exorcist"], correct: 0 },
  { text: "What is the name of Gon's father?", options: ["Ging", "Silva", "Kite", "Razor"], correct: 0 },
  { text: "Which One Piece Emperor controls Totto Land?", options: ["Kaido", "Whitebeard", "Big Mom", "Shanks"], correct: 2 },
  { text: "Which JoJo protagonist is a marine biologist?", options: ["Joseph", "Josuke", "Jotaro", "Giorno"], correct: 2 },
  { text: "Which anime features anti-spirals?", options: ["Gurren Lagann", "Evangelion", "FLCL", "Akira"], correct: 0 },
  { text: "Which Bleach captain uses flower petals in battle?", options: ["Kenpachi", "Gin", "Byakuya", "Komamura"], correct: 2 },
  { text: "Which Naruto clan specializes in shadow possession?", options: ["Nara Clan", "Akimichi Clan", "Yamanaka Clan", "Hyuga Clan"], correct: 0 },
  { text: "Which anime features vampires called nobles?", options: ["Hellsing", "Vampire Knight", "Black Butler", "Seraph of the End"], correct: 1 },
  { text: "Which One Piece character uses three swords?", options: ["Mihawk", "Law", "Zoro", "Shanks"], correct: 2 },
  { text: "Which Hashira uses Wind Breathing?", options: ["Gyomei", "Obanai", "Sanemi", "Muichiro"], correct: 2 },
  { text: "Which anime features Devil Fruits and Haki together?", options: ["Naruto", "Bleach", "One Piece", "Fairy Tail"], correct: 2 },
  { text: "What is the name of Deku's Quirk?", options: ["Explosion", "Half-Cold Half-Hot", "One For All", "Engine"], correct: 2 },
  { text: "Which anime features the Holy Grail War?", options: ["Fate Stay Night", "Bleach", "Black Clover", "Noragami"], correct: 0 },
  { text: "Which Bleach race are Uryu Ishida and Yhwach from?", options: ["Hollow", "Quincy", "Arrancar", "Visored"], correct: 1 },
  { text: "Which Naruto character became the Kazekage?", options: ["Kankuro", "Gaara", "Temari", "Sasori"], correct: 1 },
  { text: "Which anime features Denji?", options: ["Blue Lock", "Chainsaw Man", "Jujutsu Kaisen", "Mob Psycho 100"], correct: 1 },
  { text: "Which One Piece character is known as \"Surgeon of Death\"?", options: ["Kidd", "Law", "Doflamingo", "Crocodile"], correct: 1 },
  { text: "Which JoJo protagonist becomes a mafia boss?", options: ["Jotaro", "Joseph", "Giorno", "Josuke"], correct: 2 },
  { text: "Which anime features the Homunculi?", options: ["Fullmetal Alchemist", "Bleach", "Naruto", "Fairy Tail"], correct: 0 },
  { text: "Which Demon Slayer Hashira uses Stone Breathing?", options: ["Gyomei", "Sanemi", "Tengen", "Obanai"], correct: 0 },
  { text: "Which Naruto character uses puppet techniques?", options: ["Gaara", "Sasori", "Deidara", "Kakuzu"], correct: 1 },
  { text: "Which anime features Parasites taking over humans?", options: ["Tokyo Ghoul", "Another", "Parasyte", "Ajin"], correct: 2 },
  { text: "Which One Piece arc focuses heavily on samurai and Wano Country?", options: ["Dressrosa", "Wano", "Alabasta", "Skypiea"], correct: 1 },
  { text: "Which anime features the Phantom Troupe?", options: ["Naruto", "Bleach", "Hunter x Hunter", "Fairy Tail"], correct: 2 },
];
