export default [
  { text: "Which chapter officially revealed Gear 5 in One Piece?", options: ["1035", "1040", "1044", "1050"], correct: 2 },
  { text: "What is Sukuna's Domain Expansion called?", options: ["Infinite Void", "Malevolent Shrine", "Chimera Shadow Garden", "Coffin of the Iron Mountain"], correct: 1 },
  { text: "Which JoJo part introduced Stands?", options: ["Part 1", "Part 2", "Part 3", "Part 4"], correct: 2 },
  { text: "Which wall was destroyed first in Attack on Titan?", options: ["Wall Rose", "Wall Sina", "Wall Maria", "Trost Wall"], correct: 2 },
  { text: "What is Aizen's Zanpakuto called?", options: ["Zangetsu", "Kyoka Suigetsu", "Benihime", "Senbonzakura"], correct: 1 },
  { text: "Which Nen category does Kurapika become under Emperor Time?", options: ["Enhancer", "Manipulator", "Specialist", "Conjurer"], correct: 2 },
  { text: "What is the name of Johan Liebert's twin sister?", options: ["Nina", "Eva", "Anna", "Vera"], correct: 0 },
  { text: "Which One Piece character first used Conqueror's Haki on-screen?", options: ["Kaido", "Whitebeard", "Shanks", "Luffy"], correct: 2 },
  { text: "Which Hashira created Love Breathing?", options: ["Kanae", "Mitsuri", "Shinobu", "Kanao"], correct: 1 },
  { text: "What was Near's real name in Death Note?", options: ["Nate River", "Mihael Keehl", "Teru Mikami", "Beyond Birthday"], correct: 0 },
  { text: "Which Titan power can inherit future memories?", options: ["Jaw Titan", "Attack Titan", "Beast Titan", "Cart Titan"], correct: 1 },
  { text: "Which JoJo villain reset the universe?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 3 },
  { text: "What is the name of Shinji Ikari's EVA unit?", options: ["EVA-00", "EVA-01", "EVA-02", "EVA-03"], correct: 1 },
  { text: "Which Bleach captain used Kamishini no Yari?", options: ["Gin", "Byakuya", "Aizen", "Tosen"], correct: 0 },
  { text: "Which breathing style came directly from Sun Breathing?", options: ["Flame Breathing", "Mist Breathing", "Beast Breathing", "Sound Breathing"], correct: 0 },
  { text: "What was Whitebeard's official title?", options: ["Pirate King", "Strongest Creature", "Strongest Man in the World", "Sea Emperor"], correct: 2 },
  { text: "Which anime features the Sibyl System?", options: ["Ergo Proxy", "Monster", "Psycho-Pass", "Serial Experiments Lain"], correct: 2 },
  { text: "Which Espada rank was Grimmjow?", options: ["3rd", "4th", "5th", "6th"], correct: 3 },
  { text: "Which Naruto opening featured \"Blue Bird\"?", options: ["Opening 2", "Opening 3", "Opening 5", "Opening 7"], correct: 1 },
  { text: "Which Fullmetal Alchemist character created the Homunculi?", options: ["Hohenheim", "Father", "Dante", "Truth"], correct: 1 },
  { text: "Which JoJo protagonist used the Steel Ball technique?", options: ["Giorno", "Jolyne", "Johnny Joestar", "Josuke"], correct: 2 },
  { text: "Which One Piece arc introduced Brook?", options: ["Water 7", "Thriller Bark", "Enies Lobby", "Sabaody"], correct: 1 },
  { text: "What is the name of Yhwach's elite guard?", options: ["Quincy Army", "Sternritter", "Schutzstaffel", "Royal Guard"], correct: 2 },
  { text: "Which anime features Amestris?", options: ["Bleach", "Monster", "Fullmetal Alchemist", "Fate Stay Night"], correct: 2 },
  { text: "Which Akatsuki duo captured Yugito Nii?", options: ["Sasori & Deidara", "Pain & Konan", "Itachi & Kisame", "Hidan & Kakuzu"], correct: 3 },
  { text: "What is the name of Guts' sword?", options: ["Excalibur", "Dragonslayer", "Demon Edge", "Berserker Blade"], correct: 1 },
  { text: "Which anime features SEELE?", options: ["Evangelion", "Psycho-Pass", "Akira", "Ergo Proxy"], correct: 0 },
  { text: "Which Bleach captain became a Visored leader?", options: ["Rose", "Love", "Shinji", "Kensei"], correct: 2 },
  { text: "Which JoJo villain used King Crimson?", options: ["Kira", "Dio", "Pucci", "Diavolo"], correct: 3 },
  { text: "Which Hunter x Hunter character is known as the 'Chain User'?", options: ["Gon", "Killua", "Kurapika", "Leorio"], correct: 2 },
  { text: "Which Titan is Reiner Braun?", options: ["Beast Titan", "Cart Titan", "Jaw Titan", "Armored Titan"], correct: 3 },
  { text: "Which Studio Ghibli movie won an Oscar?", options: ["Ponyo", "Spirited Away", "Princess Mononoke", "Howl's Moving Castle"], correct: 1 },
  { text: "Which Naruto character could naturally use all five chakra natures?", options: ["Kakashi", "Naruto", "Hiruzen", "Sasuke"], correct: 2 },
  { text: "What was Lelouch's alias?", options: ["Black Emperor", "Zero", "Britannia King", "Knightmare"], correct: 1 },
  { text: "Which JoJo part introduced the Arrow?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which One Piece island changes climate every season?", options: ["Punk Hazard", "Little Garden", "Zou", "Fish-Man Island"], correct: 1 },
  { text: "Which Bleach arc introduced Fullbringers?", options: ["Soul Society Arc", "Arrancar Arc", "TYBW Arc", "Lost Agent Arc"], correct: 3 },
  { text: "Which Upper Moon was Kokushibo?", options: ["Upper Moon 1", "Upper Moon 2", "Upper Moon 3", "Upper Moon 4"], correct: 0 },
  { text: "Which anime features Beyond Netero?", options: ["Bleach", "Naruto", "Hunter x Hunter", "Black Clover"], correct: 2 },
  { text: "Which JoJo protagonist never directly defeated the final villain?", options: ["Josuke", "Giorno", "Jonathan", "Jolyne"], correct: 2 },
  { text: "Which One Piece chapter first named Joy Boy directly?", options: ["500", "628", "700", "800"], correct: 1 },
  { text: "Which Bleach villain manipulated complete hypnosis?", options: ["Ulquiorra", "Gin", "Yhwach", "Aizen"], correct: 3 },
  { text: "Which anime features the Anti-Spirals?", options: ["Evangelion", "Akira", "FLCL", "Gurren Lagann"], correct: 3 },
  { text: "Which Naruto technique trapped the world in illusion?", options: ["Kamui", "Amaterasu", "Infinite Tsukuyomi", "Izanagi"], correct: 2 },
  { text: "Which JoJo Stand manipulates weather?", options: ["Weather Report", "Whitesnake", "Stone Free", "Soft & Wet"], correct: 0 },
  { text: "Which Hunter x Hunter character uses Bungee Gum?", options: ["Gon", "Chrollo", "Hisoka", "Illumi"], correct: 2 },
  { text: "Which One Piece Emperor arrived at Marineford to stop the war?", options: ["Big Mom", "Kaido", "Blackbeard", "Shanks"], correct: 3 },
  { text: "Which anime features the Eclipse event?", options: ["Hellsing", "Berserk", "Claymore", "Vinland Saga"], correct: 1 },
  { text: "Which Bleach Espada used Respira?", options: ["Grimmjow", "Stark", "Baraggan", "Ulquiorra"], correct: 2 },
  { text: "Which Attack on Titan character invented ODM gear improvements?", options: ["Levi", "Hange", "Erwin", "Angel Aaltonen"], correct: 3 },
  { text: "Which One Piece character was the first known user of Advanced Conqueror's Haki shown in battle?", options: ["Luffy", "Kaido", "Roger", "Whitebeard"], correct: 1 },
  { text: "Which Naruto character awakened the Mangekyo Sharingan after Rin's death?", options: ["Sasuke", "Itachi", "Obito", "Madara"], correct: 2 },
  { text: "Which Bleach captain used the Bankai Daiguren Hyorinmaru?", options: ["Hitsugaya", "Byakuya", "Gin", "Mayuri"], correct: 0 },
  { text: "Which Demon Slayer Upper Moon used poison and sickles?", options: ["Gyokko", "Akaza", "Gyutaro", "Doma"], correct: 2 },
  { text: "Which JoJo Stand belongs to Yoshikage Kira?", options: ["King Crimson", "Killer Queen", "The World", "Made in Heaven"], correct: 1 },
  { text: "Which Hunter x Hunter Phantom Troupe member uses vacuum abilities?", options: ["Machi", "Pakunoda", "Shizuku", "Feitan"], correct: 2 },
  { text: "Which anime features Geass powers?", options: ["Steins Gate", "Code Geass", "Psycho-Pass", "Ergo Proxy"], correct: 1 },
  { text: "Which Naruto character was known as the \"God of Shinobi\"?", options: ["Madara", "Hiruzen", "Hashirama", "Minato"], correct: 2 },
  { text: "Which One Piece warlord used the String-String Fruit?", options: ["Kuma", "Crocodile", "Doflamingo", "Moria"], correct: 2 },
  { text: "Which Bleach race can absorb spiritual particles from surroundings?", options: ["Arrancar", "Quincy", "Fullbringer", "Visored"], correct: 1 },
  { text: "Which JoJo protagonist has the Stand Stone Free?", options: ["Jolyne", "Giorno", "Josuke", "Johnny"], correct: 0 },
  { text: "Which Attack on Titan character inherited the Jaw Titan from Ymir?", options: ["Porco", "Falco", "Reiner", "Pieck"], correct: 0 },
  { text: "Which Fullmetal Alchemist character is called the \"Flame Alchemist\"?", options: ["Scar", "Mustang", "Edward", "Kimblee"], correct: 1 },
  { text: "Which anime features a notebook called the Future Diary?", options: ["Erased", "Another", "Mirai Nikki", "Death Parade"], correct: 2 },
  { text: "Which Naruto character became the Sixth Hokage?", options: ["Kakashi", "Naruto", "Tsunade", "Danzo"], correct: 0 },
  { text: "Which Demon Slayer Hashira uses Snake Breathing?", options: ["Obanai", "Muichiro", "Sanemi", "Tengen"], correct: 0 },
  { text: "Which One Piece arc introduced Gear Fourth?", options: ["Marineford", "Dressrosa", "Whole Cake Island", "Punk Hazard"], correct: 1 },
  { text: "Which Bleach captain wears bells in his hair?", options: ["Kenpachi", "Byakuya", "Komamura", "Kensei"], correct: 0 },
  { text: "Which Hunter x Hunter character trained Killua in assassination?", options: ["Silva", "Zeno", "Illumi", "Biscuit"], correct: 0 },
  { text: "Which JoJo villain possessed two personalities and two souls?", options: ["Kira", "Pucci", "Diavolo", "Dio"], correct: 2 },
  { text: "Which anime features the Gate of Truth?", options: ["Evangelion", "Fullmetal Alchemist", "Fate Zero", "Berserk"], correct: 1 },
  { text: "Which Naruto member of Team 7 specialized in medical ninjutsu?", options: ["Sakura", "Sai", "Sasuke", "Naruto"], correct: 0 },
  { text: "Which One Piece Emperor possesses the Soul-Soul Fruit?", options: ["Big Mom", "Kaido", "Shanks", "Blackbeard"], correct: 0 },
  { text: "Which Bleach character is known as the \"Black Ant\"?", options: ["Aizen", "Ichibei", "Yhwach", "Jugram"], correct: 2 },
  { text: "Which Demon Slayer character created Beast Breathing?", options: ["Zenitsu", "Inosuke", "Genya", "Muichiro"], correct: 1 },
  { text: "Which Hunter x Hunter arc introduced the Phantom Troupe heavily?", options: ["Greed Island", "Yorknew City", "Election Arc", "Heaven's Arena"], correct: 1 },
  { text: "Which anime features Servants summoned for battle?", options: ["Fate Stay Night", "Black Clover", "Noragami", "Bleach"], correct: 0 },
  { text: "Which Naruto villain founded the Akatsuki originally?", options: ["Obito", "Yahiko", "Madara", "Nagato"], correct: 1 },
  { text: "Which One Piece character can transform into a phoenix?", options: ["Marco", "King", "Kaido", "Pell"], correct: 0 },
  { text: "Which Bleach Espada ranked number 1?", options: ["Ulquiorra", "Starrk", "Nnoitra", "Grimmjow"], correct: 1 },
  { text: "Which JoJo protagonist uses Golden Experience?", options: ["Josuke", "Giorno", "Jolyne", "Joseph"], correct: 1 },
  { text: "Which Attack on Titan Titan is known for throwing projectiles accurately?", options: ["Beast Titan", "Cart Titan", "Female Titan", "Jaw Titan"], correct: 0 },
  { text: "Which anime features the organization Akatsuki?", options: ["Naruto", "Bleach", "Black Clover", "Fairy Tail"], correct: 0 },
  { text: "Which Demon Slayer Upper Moon used soundwave attacks with drums?", options: ["Hantengu", "Nakime", "Kyogai", "Daki"], correct: 2 },
  { text: "Which Hunter x Hunter character became chairman after Netero?", options: ["Pariston", "Ging", "Cheadle", "Beyond"], correct: 2 },
  { text: "Which One Piece character first used Observation Haki extensively in Skypiea?", options: ["Enel", "Luffy", "Wyper", "Gan Fall"], correct: 0 },
  { text: "Which Bleach arc introduced the Visoreds?", options: ["Soul Society Arc", "Arrancar Arc", "Fullbring Arc", "TYBW Arc"], correct: 1 },
  { text: "Which JoJo Stand can erase time?", options: ["Star Platinum", "King Crimson", "Killer Queen", "Tusk Act 4"], correct: 1 },
  { text: "Which Naruto clan specializes in bug techniques?", options: ["Aburame Clan", "Nara Clan", "Yamanaka Clan", "Akimichi Clan"], correct: 0 },
  { text: "Which anime features the Black Knights?", options: ["Code Geass", "Psycho-Pass", "Akira", "Hellsing"], correct: 0 },
  { text: "Which One Piece arc introduced Nico Robin officially into the crew?", options: ["Alabasta", "Enies Lobby", "Water 7", "Thriller Bark"], correct: 0 },
  { text: "Which Bleach character uses the technique Getsuga Tensho?", options: ["Renji", "Ichigo", "Byakuya", "Aizen"], correct: 1 },
  { text: "Which Hunter x Hunter character can steal Nen abilities?", options: ["Chrollo", "Hisoka", "Illumi", "Kite"], correct: 0 },
  { text: "Which JoJo part features horse racing across America?", options: ["Part 4", "Part 5", "Part 6", "Part 7"], correct: 3 },
  { text: "Which Naruto villain manipulated Pain secretly?", options: ["Obito", "Madara", "Black Zetsu", "Kabuto"], correct: 0 },
  { text: "Which Demon Slayer character uses Sun Breathing?", options: ["Rengoku", "Tanjiro", "Yoriichi", "Muichiro"], correct: 1 },
  { text: "Which One Piece character is known as the \"Dark King\"?", options: ["Roger", "Rayleigh", "Garp", "Sengoku"], correct: 1 },
  { text: "Which Bleach captain has the Bankai Senbonzakura Kageyoshi?", options: ["Gin", "Byakuya", "Hitsugaya", "Komamura"], correct: 1 },
  { text: "Which anime features the Berserker Armor?", options: ["Claymore", "Berserk", "Vinland Saga", "Hellsing"], correct: 1 },
  { text: "Which Hunter x Hunter character uses electricity as Nen?", options: ["Gon", "Kurapika", "Killua", "Leorio"], correct: 2 },
];
