export default [
  { text: "Which animator corrected the Naruto vs Sasuke rooftop clash cuts in Naruto Part 1?", options: ["Naoko Yamada", "Norio Matsumoto", "Yutaka Nakamura", "Hiroyuki Yamashita"], correct: 1 },
  { text: "What hidden Latin phrase appears in Fullmetal Alchemist transmutation circles?", options: ["Deus Ex Machina", "Aleph Null", "V.I.T.R.I.O.L.", "Prima Materia"], correct: 2 },
  { text: "Which JoJo Stand stat page intentionally contradicts itself according to Araki interviews?", options: ["Killer Queen", "Star Platinum", "Gold Experience Requiem", "Made in Heaven"], correct: 2 },
  { text: "What was the exact publication date of the first Dragon Ball chapter?", options: ["November 20 1984", "December 1 1984", "January 5 1985", "October 10 1984"], correct: 0 },
  { text: "Which Hunter x Hunter chapter fully displayed the Dark Continent map?", options: ["320", "338", "350", "400"], correct: 1 },
  { text: "Which One Piece databook confirmed Shanks became a Yonko 6 years before the main story?", options: ["Green Databook", "Blue Deep", "Vivre Card Databook", "Red Grand Characters"], correct: 2 },
  { text: "Which Evangelion pilot recorded the highest sync ratio ever shown?", options: ["Rei", "Asuka", "Kaworu", "Shinji"], correct: 3 },
  { text: "Which Naruto opening featured the song \"Sign\" by FLOW?", options: ["Opening 4", "Opening 5", "Opening 6", "Opening 7"], correct: 2 },
  { text: "Which Bleach Espada used the ability Respira?", options: ["Starrk", "Ulquiorra", "Baraggan", "Nnoitra"], correct: 2 },
  { text: "Which JoJo protagonist mastered the Spin technique?", options: ["Jotaro", "Giorno", "Johnny Joestar", "Josuke"], correct: 2 },
  { text: "Which Attack on Titan engineer modernized ODM gear technology?", options: ["Hange Zoe", "Angel Aaltonen", "Erwin Smith", "Dot Pixis"], correct: 1 },
  { text: "Which Demon Slayer Hashira officially ranked lowest in physical strength?", options: ["Mitsuri", "Shinobu", "Obanai", "Muichiro"], correct: 1 },
  { text: "In which One Piece chapter did Ace die?", options: ["570", "572", "574", "580"], correct: 2 },
  { text: "Which JoJo villain reset the entire universe?", options: ["Dio", "Kira", "Diavolo", "Enrico Pucci"], correct: 3 },
  { text: "Which Akatsuki member never wore a scratched forehead protector?", options: ["Kisame", "Itachi", "Kakuzu", "Zetsu"], correct: 3 },
  { text: "Which Fullmetal Alchemist opening song was performed by L'Arc-en-Ciel?", options: ["Again", "Rewrite", "Ready Steady Go", "Rain"], correct: 2 },
  { text: "Which JoJo part first introduced the Stand Arrow concept?", options: ["Part 3", "Part 4", "Part 5", "Part 6"], correct: 1 },
  { text: "Which One Piece island changes climate every season naturally?", options: ["Zou", "Little Garden", "Punk Hazard", "Elbaf"], correct: 1 },
  { text: "Which Naruto character naturally mastered all five chakra natures?", options: ["Kakashi", "Hiruzen", "Sasuke", "Naruto"], correct: 1 },
  { text: "Which Bleach captain used the Bankai Konjiki Ashisogi Jizo?", options: ["Byakuya", "Gin", "Kenpachi", "Mayuri"], correct: 3 },
  { text: "Which Studio Ghibli movie won the Academy Award for Best Animated Feature?", options: ["Ponyo", "Spirited Away", "Mononoke", "Nausicaa"], correct: 1 },
  { text: "Which Hunter x Hunter arc introduced Meruem?", options: ["Yorknew City Arc", "Election Arc", "Chimera Ant Arc", "Greed Island Arc"], correct: 2 },
  { text: "Which One Piece character first directly mentioned \"Nika\"?", options: ["Kaido", "Vegapunk", "Who's-Who", "Shanks"], correct: 2 },
  { text: "Which JoJo Stand evolved into C-Moon?", options: ["Whitesnake", "Star Platinum", "Killer Queen", "Stone Free"], correct: 0 },
  { text: "Which Naruto character officially completed over 1000 missions?", options: ["Guy", "Hiruzen", "Kakashi", "Jiraiya"], correct: 2 },
  { text: "Which Bleach arc introduced Yhwach?", options: ["Soul Society Arc", "Arrancar Arc", "TYBW Arc", "Lost Agent Arc"], correct: 2 },
  { text: "Which Fullmetal Alchemist character burned a transmutation tattoo off his own back?", options: ["Edward", "Scar", "Roy Mustang", "Kimblee"], correct: 2 },
  { text: "Which Attack on Titan Titan could inherit future users' memories?", options: ["Beast Titan", "Jaw Titan", "Attack Titan", "Cart Titan"], correct: 2 },
  { text: "Which One Piece SBS revealed Zoro's real-world nationality?", options: ["SBS 40", "SBS 56", "SBS 77", "SBS 90"], correct: 1 },
  { text: "Which Dragon Ball form first gave Goku silver hair?", options: ["Super Saiyan Blue", "Ultra Instinct", "Super Saiyan 4", "Kaioken"], correct: 1 },
  { text: "Which JoJo protagonist never directly defeated the main villain?", options: ["Giorno", "Jonathan", "Josuke", "Jolyne"], correct: 1 },
  { text: "Which Naruto databook confirmed Minato's mission totals?", options: ["Databook 1", "Databook 2", "Databook 3", "Databook 4"], correct: 3 },
  { text: "Which Bleach character used the Zanpakuto Kamishini no Yari?", options: ["Aizen", "Gin Ichimaru", "Renji", "Tosen"], correct: 1 },
  { text: "Which One Piece chapter officially revealed Gear 5?", options: ["1040", "1042", "1044", "1046"], correct: 2 },
  { text: "Which Demon Slayer Upper Moon ranked first among the Twelve Kizuki?", options: ["Doma", "Akaza", "Kokushibo", "Hantengu"], correct: 2 },
  { text: "Which JoJo part introduced the Spin power system?", options: ["Battle Tendency", "Stone Ocean", "Steel Ball Run", "JoJolion"], correct: 2 },
  { text: "Which anime featured the organization SEELE?", options: ["Monster", "Evangelion", "Ergo Proxy", "Psycho-Pass"], correct: 1 },
  { text: "Which Hunter x Hunter character becomes a Specialist only during Emperor Time?", options: ["Gon", "Killua", "Kurapika", "Leorio"], correct: 2 },
  { text: "Which Bleach captain later led the Visoreds?", options: ["Rose", "Love", "Shinji", "Kensei"], correct: 2 },
  { text: "Which Naruto character awakened the Rinnegan naturally through chakra evolution?", options: ["Sasuke", "Obito", "Madara", "Nagato"], correct: 2 },
  { text: "Which One Piece character was called the \"Strongest Creature\"?", options: ["Whitebeard", "Kaido", "Blackbeard", "Roger"], correct: 1 },
  { text: "Which JoJo villain wielded King Crimson?", options: ["Dio", "Kira", "Diavolo", "Pucci"], correct: 2 },
  { text: "Which Demon Slayer character originally created Flower Breathing?", options: ["Kanae", "Shinobu", "Mitsuri", "Kanao"], correct: 0 },
  { text: "Which Bleach Espada held the rank of Fourth Espada?", options: ["Grimmjow", "Nnoitra", "Ulquiorra", "Starrk"], correct: 2 },
  { text: "Which Hunter x Hunter volume introduced Beyond Netero?", options: ["Volume 30", "Volume 31", "Volume 32", "Volume 33"], correct: 2 },
  { text: "Which JoJo Stand possessed contradictory stats according to Araki?", options: ["Killer Queen", "GER", "Star Platinum", "Tusk Act 4"], correct: 1 },
  { text: "Which One Piece Emperor stopped the Marineford War?", options: ["Kaido", "Big Mom", "Blackbeard", "Shanks"], correct: 3 },
  { text: "Which Naruto genjutsu trapped the entire world in illusion?", options: ["Izanami", "Tsukuyomi", "Infinite Tsukuyomi", "Kotoamatsukami"], correct: 2 },
  { text: "Which JoJo Stand manipulates weather patterns automatically?", options: ["Whitesnake", "Weather Report", "Made in Heaven", "King Crimson"], correct: 1 },
  { text: "Which anime director created Cowboy Bebop?", options: ["Hayao Miyazaki", "Shinichiro Watanabe", "Satoshi Kon", "Mamoru Oshii"], correct: 1 },
  { text: "Which Bleach Sternritter possessed the Schrift \"The Miracle\"?", options: ["Lille Barro", "Gerard Valkyrie", "Askin Nakk Le Vaar", "Pernida"], correct: 1 },
  { text: "Which Naruto character first used Sage Mode on-screen?", options: ["Naruto", "Jiraiya", "Hashirama", "Kabuto"], correct: 1 },
  { text: "Which One Piece character possesses the Mythical Zoan \"Model: Seiryu\"?", options: ["Marco", "Kaido", "Yamato", "Sengoku"], correct: 1 },
  { text: "Which JoJo Stand can infinitely rotate targets using the Golden Rectangle principle?", options: ["Tusk Act 4", "D4C", "Made in Heaven", "Soft & Wet"], correct: 0 },
  { text: "Which Hunter x Hunter character invented the ability \"Bungee Gum\"?", options: ["Chrollo", "Killua", "Hisoka", "Biscuit"], correct: 2 },
  { text: "Which Demon Slayer character was turned into a demon by Kokushibo?", options: ["Kaigaku", "Zenitsu", "Genya", "Muichiro"], correct: 0 },
  { text: "Which anime featured the \"Human Instrumentality Project\"?", options: ["Ergo Proxy", "Evangelion", "Serial Experiments Lain", "Akira"], correct: 1 },
  { text: "Which Naruto clan member specialized in Expansion Jutsu?", options: ["Nara Clan", "Akimichi Clan", "Yamanaka Clan", "Aburame Clan"], correct: 1 },
  { text: "Which Bleach captain used the Bankai Zanka no Tachi?", options: ["Kyoraku", "Yamamoto", "Hitsugaya", "Komamura"], correct: 1 },
  { text: "Which One Piece race was King revealed to belong to?", options: ["Giant", "Mink", "Lunarian", "Buccaneer"], correct: 2 },
  { text: "Which JoJo villain used the Stand Dirty Deeds Done Dirt Cheap?", options: ["Pucci", "Funny Valentine", "Dio", "Tooru"], correct: 1 },
  { text: "Which Hunter x Hunter Royal Guard manipulated aura through scales?", options: ["Pitou", "Pouf", "Youpi", "Meruem"], correct: 1 },
  { text: "Which Naruto villain secretly manipulated Madara Uchiha?", options: ["Kabuto", "Black Zetsu", "Obito", "Orochimaru"], correct: 1 },
  { text: "Which Bleach Quincy was revealed to be the Soul King's left arm?", options: ["Gerard", "Pernida", "Lille", "Jugram"], correct: 1 },
  { text: "Which One Piece character awakened Future Sight first chronologically in the story?", options: ["Luffy", "Katakuri", "Enel", "Shanks"], correct: 1 },
  { text: "Which JoJo protagonist used Soft & Wet?", options: ["Josuke Higashikata (Part 8)", "Giorno", "Johnny", "Jolyne"], correct: 0 },
  { text: "Which Demon Slayer Upper Moon controlled Infinity Castle rooms?", options: ["Nakime", "Doma", "Gyokko", "Hantengu"], correct: 0 },
  { text: "Which anime features the \"Deadly Sins\" called Wrath, Lust, and Envy as Homunculi?", options: ["Blue Exorcist", "Fullmetal Alchemist", "Soul Eater", "D.Gray-man"], correct: 1 },
  { text: "Which Naruto character used Wood Release without being a Senju?", options: ["Yamato", "Sasuke", "Kakashi", "Minato"], correct: 0 },
  { text: "Which Bleach Espada represented the aspect of death \"Despair\"?", options: ["Ulquiorra", "Baraggan", "Starrk", "Nnoitra"], correct: 1 },
  { text: "Which One Piece scientist modified Kuma into a Pacifista prototype?", options: ["Caesar Clown", "Judge", "Vegapunk", "Queen"], correct: 2 },
  { text: "Which Hunter x Hunter character used \"APR\" to bankrupt opponents' aura?", options: ["Knuckle", "Morel", "Shoot", "Knov"], correct: 0 },
  { text: "Which JoJo Stand could reset actions and willpower to zero?", options: ["Made in Heaven", "GER", "King Crimson", "Wonder of U"], correct: 1 },
  { text: "Which Naruto tailed beast was known as the Three-Tails?", options: ["Kurama", "Son Goku", "Isobu", "Gyuki"], correct: 2 },
  { text: "Which Bleach captain wielded dual Zanpakuto spirits named Katen and Kyokotsu?", options: ["Yamamoto", "Ukitake", "Kyoraku", "Byakuya"], correct: 2 },
  { text: "Which One Piece character carried the title \"Heavenly Yaksha\"?", options: ["Kaido", "Doflamingo", "Crocodile", "Enel"], correct: 1 },
  { text: "Which Hunter x Hunter ability allowed Chrollo to steal Nen techniques?", options: ["Skill Hunter", "Deep Purple", "Godspeed", "Crazy Slots"], correct: 0 },
  { text: "Which JoJo villain fused with the Green Baby?", options: ["Pucci", "Dio", "Valentine", "Tooru"], correct: 0 },
  { text: "Which Naruto character created the Rasenshuriken?", options: ["Minato", "Kakashi", "Naruto", "Tobirama"], correct: 2 },
  { text: "Which Bleach Arrancar used wolves as explosive spirit weapons?", options: ["Ulquiorra", "Grimmjow", "Starrk", "Nnoitra"], correct: 2 },
  { text: "Which One Piece arc introduced Silvers Rayleigh?", options: ["Marineford", "Water 7", "Sabaody Archipelago", "Punk Hazard"], correct: 2 },
  { text: "Which Hunter x Hunter character used smoke aura constructs called Deep Purple?", options: ["Morel", "Knuckle", "Shoot", "Knov"], correct: 0 },
  { text: "Which JoJo Stand belonged to Rohan Kishibe?", options: ["Heaven's Door", "Crazy Diamond", "Stone Free", "Echoes"], correct: 0 },
  { text: "Which Naruto character possessed the Mangekyo ability Kotoamatsukami?", options: ["Itachi", "Sasuke", "Shisui", "Obito"], correct: 2 },
  { text: "Which Bleach villain absorbed the Soul King?", options: ["Aizen", "Yhwach", "Gerard", "Ichibei"], correct: 1 },
  { text: "Which One Piece race can naturally generate electricity?", options: ["Giants", "Fish-Men", "Minks", "Lunarians"], correct: 2 },
  { text: "Which Hunter x Hunter chairman election candidate constantly smiled manipulatively?", options: ["Ging", "Cheadle", "Pariston", "Botobai"], correct: 2 },
  { text: "Which JoJo Stand manipulated calamity itself?", options: ["Wonder of U", "Soft & Wet", "D4C", "Tusk Act 4"], correct: 0 },
  { text: "Which Naruto summon animal was associated with Jiraiya?", options: ["Snakes", "Slugs", "Frogs", "Hawks"], correct: 2 },
  { text: "Which Bleach captain first lost his Bankai to Quincy theft?", options: ["Hitsugaya", "Komamura", "Byakuya", "Soi Fon"], correct: 2 },
  { text: "Which One Piece Emperor controlled Totto Land?", options: ["Big Mom", "Kaido", "Whitebeard", "Blackbeard"], correct: 0 },
  { text: "Which Hunter x Hunter character used \"Godspeed\"?", options: ["Gon", "Hisoka", "Killua", "Illumi"], correct: 2 },
  { text: "Which JoJo protagonist became a gangster boss in Italy?", options: ["Giorno Giovanna", "Josuke", "Jotaro", "Jonathan"], correct: 0 },
  { text: "Which Naruto member of the Sannin never became Hokage?", options: ["Tsunade", "Orochimaru", "Jiraiya", "Both Orochimaru and Jiraiya"], correct: 3 },
  { text: "Which Bleach Sternritter possessed the Schrift \"The X-Axis\"?", options: ["Lille Barro", "Askin", "Gerard", "Bazz-B"], correct: 0 },
  { text: "Which One Piece character used the attack \"Divine Departure\" first in the series?", options: ["Roger", "Shanks", "Kaido", "Rayleigh"], correct: 0 },
  { text: "Which Hunter x Hunter character used the clown-themed ability Texture Surprise?", options: ["Hisoka", "Chrollo", "Illumi", "Kite"], correct: 0 },
  { text: "Which JoJo part introduced the concept of Rock Humans?", options: ["Part 6", "Part 7", "Part 8", "Part 9"], correct: 2 },
  { text: "Which Naruto character became the Jinchuriki of the Ten Tails first?", options: ["Madara", "Naruto", "Obito", "Hagoromo"], correct: 2 },
  { text: "Which Bleach character was known as \"Monk Who Calls the Real Name\"?", options: ["Ichibe Hyosube", "Yamamoto", "Aizen", "Oetsu Nimaiya"], correct: 0 },
];
