export default [
  {"id":301,"text":"🦋🩸🎨","options":["Monogatari","Elfen Lied","Another","Paranoia Agent"],"correct":0,"hint":"Oddities and dialogue","level":4},
  {"id":302,"text":"🧒📡🤖","options":["Serial Experiments Lain","Psycho-Pass","Ergo Proxy","Texhnolyze"],"correct":0,"hint":"Wired world","level":4},
  {"id":303,"text":"🌻⚔️🎧","options":["Samurai Champloo","Afro Samurai","Gintama","Dororo"],"correct":0,"hint":"Hip-hop samurai","level":4},
  {"id":304,"text":"🕷️📖🕯️","options":["Another","Pandora Hearts","Black Butler","Gosick"],"correct":1,"hint":"Abyss and chains","level":4},
  {"id":305,"text":"🐧🥒👧","options":["Sarazanmai","Mawaru Penguindrum","FLCL","Nichijou"],"correct":1,"hint":"Symbolic penguins","level":4},
  {"id":306,"text":"🧠⚡🌆","options":["Akira","Psycho-Pass","Ergo Proxy","Ghost in the Shell"],"correct":0,"hint":"Neo Tokyo","level":4},
  {"id":307,"text":"📚🧛🌙","options":["Hellsing","Shiki","Call of the Night","Bakemonogatari"],"correct":1,"hint":"Village vampires","level":4},
  {"id":308,"text":"🧵👁️🪆","options":["Another","Higurashi","Puella Magi Madoka Magica","Ghost Hound"],"correct":2,"hint":"Dark magical girls","level":4},
  {"id":309,"text":"⚙️🕊️🤖","options":["Ghost in the Shell","Vivy","Ergo Proxy","Pluto"],"correct":1,"hint":"AI singer","level":4},
  {"id":310,"text":"🎺🚀🌌","options":["Macross","Cowboy Bebop","Space Dandy","Legend of the Galactic Heroes"],"correct":0,"hint":"Mecha and music","level":4},
  {"id":311,"text":"🎨👁️😵","options":["Blue Period","Mononoke","Tatami Galaxy","Ping Pong the Animation"],"correct":1,"hint":"Medicine seller","level":4},
  {"id":312,"text":"🌊📖👧","options":["Nagi no Asukara","Children of the Sea","A Lull in the Sea","Ride Your Wave"],"correct":2,"hint":"Underwater village","level":4},
  {"id":313,"text":"🕰️👧🦋","options":["Erased","Summertime Rendering","Orange","ReLIFE"],"correct":1,"hint":"Island time loops","level":4},
  {"id":314,"text":"🎭📺🔪","options":["Perfect Blue","Odd Taxi","Paranoia Agent","Monster"],"correct":2,"hint":"Roller boy attacks","level":4},
  {"id":315,"text":"⚙️🩸👑","options":["Guilty Crown","86","Aldnoah.Zero","Valvrave"],"correct":0,"hint":"Void powers","level":4},
  {"id":316,"text":"🧠👨‍⚕️🔪","options":["Monster","Death Note","Psycho-Pass","Pluto"],"correct":0,"hint":"Johan Liebert","level":4},
  {"id":317,"text":"🎤🐰🌈","options":["Show by Rock!!","Carole & Tuesday","Zombie Land Saga","Oshi no Ko"],"correct":3,"hint":"Idol revenge story","level":4},
  {"id":318,"text":"🧪👧💣","options":["Elfen Lied","Akira","Wonder Egg Priority","Lycoris Recoil"],"correct":3,"hint":"Cafe assassins","level":4},
  {"id":319,"text":"🌌🧍📺","options":["Sonny Boy","FLCL","Tatami Galaxy","Kaiba"],"correct":0,"hint":"Drifting school","level":4},
  {"id":320,"text":"⚔️👹🪷","options":["Dororo","Shigurui","Blade of the Immortal","Ninja Scroll"],"correct":2,"hint":"Immortal samurai","level":4},
  {"id":321,"text":"📖🦋🕰️","options":["The Tatami Galaxy","Monogatari","Mawaru Penguindrum","Sonny Boy"],"correct":0,"hint":"Endless college timelines","level":4},
  {"id":322,"text":"👧⚡🐰","options":["Bunny Girl Senpai","Wonder Egg Priority","Flip Flappers","Charlotte"],"correct":0,"hint":"Adolescence syndrome","level":4},
  {"id":323,"text":"🧬🌌👶","options":["From the New World","Shinsekai Yori","Ergo Proxy","Noein"],"correct":1,"hint":"Psychic dystopia","level":4},
  {"id":324,"text":"🎪🔪🤡","options":["Deadman Wonderland","Karneval","Dorohedoro","Akudama Drive"],"correct":0,"hint":"Prison amusement park","level":4},
  {"id":325,"text":"🌧️👧📖","options":["Humanity Has Declined","Kino's Journey","Girls' Last Tour","Haibane Renmei"],"correct":2,"hint":"Post-apocalypse slice of life","level":4},
  {"id":326,"text":"🧠🎭📺","options":["Kaiji","One Outs","Akagi","Death Parade"],"correct":0,"hint":"Extreme gambling","level":4},
  {"id":327,"text":"🪞👧🦢","options":["Princess Tutu","Revolutionary Girl Utena","Flip Flappers","Cardcaptor Sakura"],"correct":0,"hint":"Fairy tale ballet","level":4},
  {"id":328,"text":"⚔️🩸🌑","options":["Drifters","Berserk","Hellsing Ultimate","Shigurui"],"correct":0,"hint":"Historical warriors isekai","level":4},
  {"id":329,"text":"🛵🎸⚡","options":["Beck","FLCL","Bocchi the Rock!","Nana"],"correct":0,"hint":"Rock band anime","level":4},
  {"id":330,"text":"👁️🧪🧒","options":["Parasyte","Ajin","Devilman Crybaby","Inuyashiki"],"correct":3,"hint":"Old cyborg hero","level":4},
  {"id":331,"text":"📺🧠⚡","options":["Paranoia Agent","Boogiepop Phantom","Serial Experiments Lain","Texhnolyze"],"correct":2,"hint":"\"Present day, present time\"","level":4},
  {"id":332,"text":"🌊⚰️👧","options":["Black Rock Shooter","Sunday Without God","Haibane Renmei","Humanity Has Declined"],"correct":1,"hint":"World where nobody dies","level":4},
  {"id":333,"text":"🎪🐻🔪","options":["Danganronpa","Deadman Wonderland","Mirai Nikki","Btooom!"],"correct":0,"hint":"Monokuma executions","level":4},
  {"id":334,"text":"🧒⚔️🧟","options":["Kabaneri","Seraph of the End","God Eater","Guilty Crown"],"correct":1,"hint":"Vampire apocalypse","level":4},
  {"id":335,"text":"🎭🪞🌸","options":["Pet Shop of Horrors","xxxHOLiC","Mononoke","Ghost Hunt"],"correct":1,"hint":"Wish-granting shop","level":4},
  {"id":336,"text":"🌑🚇👧","options":["Dark Gathering","Mieruko-chan","Otherside Picnic","Ghost Hunt"],"correct":2,"hint":"Internet horror dimensions","level":4},
  {"id":337,"text":"⚙️🧠🌧️","options":["Ergo Proxy","Casshern Sins","Blame!","Psycho-Pass"],"correct":1,"hint":"Robots and ruin","level":4},
  {"id":338,"text":"📖👧🩸","options":["Gosick","Another","Higurashi","Shiki"],"correct":0,"hint":"Victorian mystery girl","level":4},
  {"id":339,"text":"🧸🩸👧","options":["Shadow Star Narutaru","Elfen Lied","School-Live!","Alien 9"],"correct":0,"hint":"Dark creature companions","level":4},
  {"id":340,"text":"🎨🚲🌤️","options":["Windy Tales","Aria","Tamayura","Yokohama Kaidashi Kikou"],"correct":3,"hint":"Peaceful post-apocalypse","level":4},
  {"id":341,"text":"📖🌌🧠","options":["Kaiba","Sonny Boy","Tatami Galaxy","Noein"],"correct":0,"hint":"Memories as data","level":4},
  {"id":342,"text":"👧⚔️🦢","options":["Princess Tutu","Revolutionary Girl Utena","Magic Knight Rayearth","Cardcaptor Sakura"],"correct":0,"hint":"Duck ballerina","level":4},
  {"id":343,"text":"🧒🧠🌧️","options":["Texhnolyze","Ergo Proxy","Ghost Hound","Serial Experiments Lain"],"correct":2,"hint":"Astral projection horror","level":4},
  {"id":344,"text":"⚙️👩‍🎤🌌","options":["Macross Plus","Vivy","Armitage III","Bubblegum Crisis"],"correct":0,"hint":"Sharon Apple","level":4},
  {"id":345,"text":"👧📺🪞","options":["Boogiepop Phantom","Serial Experiments Lain","Perfect Blue","Another"],"correct":0,"hint":"Urban fear anthology","level":4},
  {"id":346,"text":"🎨🌊👧","options":["Children of the Sea","Ride Your Wave","Lu Over the Wall","Ponyo"],"correct":0,"hint":"Cosmic ocean mystery","level":4},
  {"id":347,"text":"🧠🕳️⚙️","options":["Ergo Proxy","Blame!","Texhnolyze","Psycho-Pass"],"correct":2,"hint":"Underground cyberpunk decay","level":4},
  {"id":348,"text":"⚔️🧟🏯","options":["Shigurui","Basilisk","Ninja Scroll","Drifters"],"correct":0,"hint":"Insane samurai realism","level":4},
  {"id":349,"text":"👧☁️🚲","options":["Yokohama Kaidashi Kikou","Aria","Tamayura","Windy Tales"],"correct":0,"hint":"Quiet café android","level":4},
  {"id":350,"text":"🎪👹📿","options":["Ayakashi","Mononoke","Hell Girl","Mushishi"],"correct":1,"hint":"Medicine seller spirit cases","level":4},
,
  {"id":351,"text":"🌀🧠💻","options":["Serial Experiments Lain","Psycho-Pass","Ghost in Shell","Texhnolyze"],"correct":0,"hint":"Wired identity girl","level":4},
  {"id":352,"text":"🎭🐍📿","options":["Monogatari Series","Xxxholic","Mononoke","Bakemonogatari"],"correct":3,"hint":"Oddity supernatural harem","level":4},
  {"id":353,"text":"🌌🧬👁️","options":["Texhnolyze","Ergo Proxy","Psycho-Pass","Ghost in Shell"],"correct":1,"hint":"Dome city proxy awakening","level":4},
  {"id":354,"text":"🎪👁️🩸","options":["Deadman Wonderland","Kaiji","Mirai Nikki","Danganronpa"],"correct":0,"hint":"Prison amusement park blood","level":4},
  {"id":355,"text":"🏚️🕯️👻","options":["Ghost Hound","Shiki","Another","Mononoke"],"correct":3,"hint":"Medicine seller ayakashi","level":4},
  {"id":356,"text":"🌸💀🎎","options":["Hell Girl","Ghost Hunt","Dusk Maiden","Toilet-Bound Hanako"],"correct":3,"hint":"School ghost seventh mystery","level":4},
  {"id":357,"text":"🎻🌹🧛","options":["Vanitas no Carte","Hellsing","Blood+","Dance in Vampire Bund"],"correct":0,"hint":"Vampire cure grimoire","level":4},
  {"id":358,"text":"🌊🐚🏝️","options":["Nagi no Asukara","Free","Ponyo","Children of Sea"],"correct":0,"hint":"Underwater village fishfolk love","level":4},
  {"id":359,"text":"📺👁️🌀","options":["Paranoia Agent","Perfect Blue","Paprika","Serial Experiments Lain"],"correct":0,"hint":"Bat boy delusion paranoia","level":4},
  {"id":360,"text":"🎭🖤✂️","options":["Kill la Kill","Akame ga Kill","Scissor Seven","Guilty Crown"],"correct":0,"hint":"Scissor blade fiber life","level":4},
  {"id":361,"text":"🚂💀🌫️","options":["Galaxy Express 999","Kabaneri of Iron Fortress","Baccano","Demonslayer Mugen Train"],"correct":1,"hint":"Zombie train fortress","level":4},
  {"id":362,"text":"🏜️🐛🗡️","options":["Nausicaa","Dune","Desert Punk","Dorohedoro"],"correct":0,"hint":"Toxic jungle princess insects","level":4},
  {"id":363,"text":"🌑👶🌌","options":["Kaiba","Space Dandy","Casshern Sins","Sonny Boy"],"correct":0,"hint":"Memory chip body swap","level":4},
  {"id":364,"text":"🔊💀🎸","options":["Detroit Metal City","Beck","Given","Nana"],"correct":0,"hint":"Death metal alter ego","level":4},
  {"id":365,"text":"🌺🏝️🔫","options":["Michiko and Hatchin","Black Lagoon","Jormungand","Gangsta"],"correct":0,"hint":"South American fugitives","level":4},
  {"id":366,"text":"🏰⚙️🌹","options":["Princess Principal","Violet Evergarden","Code Geass","Moriarty"],"correct":0,"hint":"Steampunk spy girls","level":4},
  {"id":367,"text":"🦊👘🏮","options":["Xxxholic","Kamisama Kiss","Inari Kon Kon","Kakuriyo Bed and Breakfast"],"correct":3,"hint":"Ayakashi inn bride debt","level":4},
  {"id":368,"text":"🎵🤖💃","options":["Vivy Fluorite Eye","Macross","Carole and Tuesday","Idol Master"],"correct":0,"hint":"AI singer 100 year mission","level":4},
  {"id":369,"text":"🪖🔫🛩️","options":["86 Eighty-Six","Code Geass","Gundam","Aldnoah Zero"],"correct":0,"hint":"Unmanned war discrimination","level":4},
  {"id":370,"text":"🧟💀🏚️","options":["Shiki","Highschool of Dead","Zombie Land","Gakkou Gurashi"],"correct":0,"hint":"Village vampire epidemic","level":4},
  {"id":371,"text":"🌙🎪🐈","options":["Vanitas no Carte","Pandora Hearts","Black Butler","The Case Study of Vanitas"],"correct":1,"hint":"Abyss chains contractor","level":4},
  {"id":372,"text":"🕊️🔥🌍","options":["Promare","Fire Force","Burning Kabaddi","Gurren Lagann"],"correct":0,"hint":"Burnish flame people","level":4},
  {"id":373,"text":"🏙️🌃🚕","options":["Odd Taxi","Durarara","Baccano","Night Head"],"correct":0,"hint":"Walrus taxi driver mystery","level":4},
  {"id":374,"text":"🎭🩸🌹","options":["Elfen Lied","Claymore","Akame ga Kill","Deadman Wonderland"],"correct":0,"hint":"Diclonius horned girl","level":4},
  {"id":375,"text":"📡🌐💀","options":["Dennou Coil","Ghost in Shell","Psycho-Pass","Serial Experiments Lain"],"correct":0,"hint":"AR glasses kids mystery","level":4},
  {"id":376,"text":"🦋🌸📖","options":["Violet Evergarden","March Comes Like Lion","Hyouka","Sound Euphonium"],"correct":1,"hint":"Shogi depression lion","level":4},
  {"id":377,"text":"🚀👦🌍","options":["Eureka Seven","Darling in Franxx","Captain Earth","Star Driver"],"correct":0,"hint":"Surfing mecha sky boy","level":4},
  {"id":378,"text":"🐺🏙️🌙","options":["Beastars","Wolf Children","BNA","Killing Bites"],"correct":0,"hint":"Animal society carnivore","level":4},
  {"id":379,"text":"🌊👧🐟","options":["Children of the Sea","Ponyo","Nagi no Asukara","Free"],"correct":0,"hint":"Oceanic mystery cosmic","level":4},
  {"id":380,"text":"🎭📚✨","options":["Oshi no Ko","Skip Beat","Glass Mask","Act-Age"],"correct":2,"hint":"Acting genius mask girl","level":4},
  {"id":381,"text":"🌙🐈‍⬛📖","options":["The Cat Returns","Chi Sweet Home","My Roommate Cat","Aria"],"correct":3,"hint":"Gondolier Mars calm water","level":4},
  {"id":382,"text":"🦠🧬👁️","options":["Parasyte","Ajin","Tokyo Ghoul","Devilman Crybaby"],"correct":3,"hint":"Devil merge crybaby tears","level":4},
  {"id":383,"text":"🏔️❄️⛺","options":["Laid-Back Camp","A Place Further","Non Non Biyori","Super Cub"],"correct":0,"hint":"Cozy camping girls Mt. Fuji","level":4},
  {"id":384,"text":"🎭🎪🃏","options":["Karakuri Circus","Black Butler","D.Gray-man","Kuroshitsuji"],"correct":0,"hint":"Puppet automaton revenge","level":4},
  {"id":385,"text":"👦🌾🏡","options":["Barakamon","Silver Spoon","Non Non Biyori","Natsume Book"],"correct":1,"hint":"City boy agriculture school","level":4},
  {"id":386,"text":"🔥🌪️🤖","options":["Gurren Lagann","Promare","Kill la Kill","Darling in Franxx"],"correct":0,"hint":"Drill pierce heavens spiral","level":4},
  {"id":387,"text":"🎵🎤⭐","options":["Oshi no Ko","Love Live","Idol Master","Macross"],"correct":0,"hint":"Reborn idol industry dark","level":4},
  {"id":388,"text":"🌊🏴‍☠️💀","options":["One Piece","Black Lagoon","Bodacious Space Pirates","Fena Pirate Princess"],"correct":3,"hint":"Princess pirate memory quest","level":4},
  {"id":389,"text":"🐛🌿🌙","options":["Mushishi","Mushi-Shi","Kino Journey","Girls Last Tour"],"correct":2,"hint":"Motorrad traveler philosophy","level":4},
  {"id":390,"text":"📱💀🎮","options":["Darwin Game","Mirai Nikki","Btooom","Sword Art Online"],"correct":0,"hint":"Smartphone death game sigils","level":4},
  {"id":391,"text":"🎨🖼️🌊","options":["Blue Period","Barakamon","The Wind Rises","Kakushigoto"],"correct":0,"hint":"Art university blue passion","level":4},
  {"id":392,"text":"🌸🎎👘","options":["Chihayafuru","March Comes Like Lion","Hikaru no Go","Showa Genroku"],"correct":0,"hint":"Karuta competitive passion","level":4},
  {"id":393,"text":"⚡🐲🌌","options":["Dragon Ball Super","Fairy Tail","Slayers","Tenchi Muyo"],"correct":2,"hint":"90s sorcerer comedy fantasy","level":4},
  {"id":394,"text":"🧊👑🦊","options":["The Ancient Magus Bride","Spice and Wolf","Inuyasha","Kamisama Kiss"],"correct":0,"hint":"Bone skull mage bride","level":4},
  {"id":395,"text":"🏴‍☠️🌌⚔️","options":["Space Pirate Captain Harlock","Outlaw Star","Cowboy Bebop","Bodacious Space Pirates"],"correct":0,"hint":"Legendary immortal space pirate","level":4},
  {"id":396,"text":"🌸🗡️🎌","options":["Samurai 7","Sword of Stranger","Afro Samurai","Samurai Champloo"],"correct":1,"hint":"Nameless sword protector boy","level":4},
  {"id":397,"text":"🐉🏔️👧","options":["Dragon Pilot Hisone","Dragon Maid","Fairy Tail","Dragon Drive"],"correct":0,"hint":"Girl swallowed by dragon jet","level":4},
  {"id":398,"text":"🎭🌸🏫","options":["Revue Starlight","Love Live","Bang Dream","Idoly Pride"],"correct":0,"hint":"Stage theater battle girls","level":4},
  {"id":399,"text":"🌍💥🤖","options":["Aldnoah Zero","Valvrave","Cross Ange","Gundam IBO"],"correct":3,"hint":"Iron blooded orphans Mars","level":4},
  {"id":400,"text":"🐧🧊🌊","options":["Penguin Highway","A Place Further","Spy x Family","Odd Taxi"],"correct":0,"hint":"Boy investigates mystery penguins","level":4}
];
