export default [
  {"id":101,"text":"🪚🩸🐶","options":["Chainsaw Man","Tokyo Ghoul","Parasyte","Ajin"],"correct":0,"hint":"Devil hunter","level":2},
  {"id":102,"text":"👁️‍🗨️👹🤌","options":["Naruto","Jujutsu Kaisen","Bleach","Noragami"],"correct":1,"hint":"Cursed energy","level":2},
  {"id":103,"text":"☠️⚔️🌸","options":["Bleach","Samurai Champloo","Dororo","Rurouni Kenshin"],"correct":0,"hint":"Bankai","level":2},
  {"id":104,"text":"🧣⚔️👹","options":["Attack on Titan","Vinland Saga","Claymore","Berserk"],"correct":0,"hint":"Titans outside walls","level":2},
  {"id":105,"text":"🦌⚕️🏴‍☠️","options":["Fairy Tail","One Piece","Naruto","Black Clover"],"correct":1,"hint":"Doctor reindeer","level":2},
  {"id":106,"text":"🧪⚡🧠","options":["Dr. Stone","Steins;Gate","Psycho-Pass","Erased"],"correct":0,"hint":"Science kingdom","level":2},
  {"id":107,"text":"👊🥊📚","options":["Hajime no Ippo","Baki","Kengan Ashura","Megalo Box"],"correct":0,"hint":"Boxing anime","level":2},
  {"id":108,"text":"🎹🎻😭","options":["Your Lie in April","Clannad","Angel Beats","Violet Evergarden"],"correct":0,"hint":"Music and heartbreak","level":2},
  {"id":109,"text":"👺🌊⚔️","options":["Demon Slayer","Bleach","Dororo","Blue Exorcist"],"correct":0,"hint":"Water breathing","level":2},
  {"id":110,"text":"🕰️📱🔬","options":["Dr. Stone","Steins;Gate","Re:Zero","Erased"],"correct":1,"hint":"Time travel microwave","level":2},
  {"id":111,"text":"👻📷👧","options":["Another","Ghost Hunt","Dark Gathering","Mieruko-chan"],"correct":3,"hint":"She sees ghosts","level":2},
  {"id":112,"text":"💀🎻🌌","options":["Your Lie in April","Angel Beats","Plastic Memories","Vivy"],"correct":1,"hint":"Afterlife school","level":2},
  {"id":113,"text":"🪓👹⚫","options":["Black Butler","Dorohedoro","Tokyo Ghoul","Ajin"],"correct":1,"hint":"Lizard-headed man","level":2},
  {"id":114,"text":"🧠📖👦","options":["Bakuman","Death Note","Classroom of the Elite","Tomodachi Game"],"correct":0,"hint":"Manga creators","level":2},
  {"id":115,"text":"⚔️🐺👸","options":["Princess Mononoke","InuYasha","Wolf Children","Dororo"],"correct":0,"hint":"Studio Ghibli forest","level":2},
  {"id":116,"text":"👑💚🍀","options":["Black Clover","Magi","Seven Deadly Sins","Fairy Tail"],"correct":0,"hint":"No magic boy","level":2},
  {"id":117,"text":"🩸👁️📱","options":["Future Diary","Another","Darwin's Game","King's Game"],"correct":0,"hint":"Survival diary game","level":2},
  {"id":118,"text":"🔥🚒👨‍🚒","options":["Fire Force","Soul Eater","Blue Exorcist","Enen no Shouboutai"],"correct":0,"hint":"Human combustion","level":2},
  {"id":119,"text":"🐍⚔️🌸","options":["Basilisk","Naruto","Samurai Deeper Kyo","Hell's Paradise"],"correct":3,"hint":"Criminals on island","level":2},
  {"id":120,"text":"🏹⚡🕷️","options":["Hunter x Hunter","Naruto","Bleach","Jujutsu Kaisen"],"correct":0,"hint":"Phantom Troupe","level":2},
  {"id":121,"text":"🗡️⚡👹","options":["Noragami","Blue Exorcist","Seraph of the End","Bleach"],"correct":0,"hint":"Delivery god","level":2},
  {"id":122,"text":"🐻⚖️🏫","options":["Assassination Classroom","Danganronpa","Classroom of the Elite","Tomodachi Game"],"correct":1,"hint":"Killing game bear","level":2},
  {"id":123,"text":"👑♟️🧠","options":["No Game No Life","Code Geass","Classroom of the Elite","Death Note"],"correct":2,"hint":"Ayanokoji","level":2},
  {"id":124,"text":"🚴💨🏆","options":["Initial D","Yowamushi Pedal","Run with the Wind","Capeta"],"correct":1,"hint":"Cycling anime","level":2},
  {"id":125,"text":"🐟🍣✋","options":["Food Wars","Barakamon","Tsuritama","Campfire Cooking"],"correct":2,"hint":"Fishing aliens","level":2},
  {"id":126,"text":"🎹🎼🌙","options":["Nodame Cantabile","Your Lie in April","Blue Orchestra","Hibike Euphonium"],"correct":0,"hint":"Classical music romance","level":2},
  {"id":127,"text":"⚔️👁️🔥","options":["Blue Exorcist","D.Gray-man","Fire Force","Soul Eater"],"correct":1,"hint":"Akuma exorcists","level":2},
  {"id":128,"text":"🐻🍯👧","options":["Kuma Kuma Kuma Bear","Non Non Biyori","Yuru Camp","Sweetness and Lightning"],"correct":0,"hint":"OP bear suit","level":2},
  {"id":129,"text":"🛡️⚔️👑","options":["Record of Grancrest War","Arslan Senki","Kingdom","Drifters"],"correct":1,"hint":"Young prince","level":2},
  {"id":130,"text":"🧟🎤🎶","options":["Love Live!","Oshi no Ko","Zombie Land Saga","Bocchi the Rock!"],"correct":2,"hint":"Zombie idols","level":2},
  {"id":131,"text":"👹📖🔥","options":["Blue Exorcist","Ao no Exorcist","D.Gray-man","Soul Eater"],"correct":1,"hint":"Satan's son twins","level":2},
  {"id":132,"text":"🧑‍🍳🔪😋","options":["Toriko","Food Wars","Yakitate!! Japan","Restaurant to Another World"],"correct":1,"hint":"Explosive reactions","level":2},
  {"id":133,"text":"🎮👑💀","options":["Overlord","Sword Art Online","Log Horizon","No Game No Life"],"correct":0,"hint":"Skeleton king","level":2},
  {"id":134,"text":"🦊💰🍜","options":["Spice and Wolf","InuYasha","Konohana Kitan","Helpful Fox Senko-san"],"correct":0,"hint":"Wise wolf merchant","level":2},
  {"id":135,"text":"👨‍🏫🔫🐙","options":["Assassination Classroom","Great Teacher Onizuka","Classroom of the Elite","Danganronpa"],"correct":0,"hint":"Yellow tentacle teacher","level":2},
  {"id":136,"text":"⚽👦🔥","options":["Captain Tsubasa","Blue Lock","Inazuma Eleven","Ao Ashi"],"correct":2,"hint":"Special soccer moves","level":2},
  {"id":137,"text":"🛸👧⚡","options":["Urusei Yatsura","To Love Ru","Darling in the Franxx","Lum the Invader Girl"],"correct":0,"hint":"Alien oni girl","level":2},
  {"id":138,"text":"🏹👸🌲","options":["Yona of the Dawn","Snow White with the Red Hair","Princess Mononoke","Fushigi Yuugi"],"correct":0,"hint":"Red-haired princess","level":2},
  {"id":139,"text":"🎤🎸👧","options":["K-On!","Bocchi the Rock!","Beck","Nana"],"correct":0,"hint":"Light music club","level":2},
  {"id":140,"text":"🐉⚔️🩸","options":["Dororo","Rage of Bahamut","Record of Lodoss War","Claymore"],"correct":1,"hint":"Fantasy card game adaptation","level":2},
  {"id":141,"text":"🩸📱🎮","options":["Darwin's Game","Mirai Nikki","Tomodachi Game","King's Game"],"correct":0,"hint":"Smartphone death battles","level":2},
  {"id":142,"text":"🧑‍⚕️💀⚔️","options":["Black Jack","Dororo","Drifters","Hellsing"],"correct":1,"hint":"Body parts stolen by demons","level":2},
  {"id":143,"text":"🏰👑⚔️","options":["Kingdom","Arslan Senki","Vinland Saga","Berserk"],"correct":0,"hint":"Ancient China war","level":2},
  {"id":144,"text":"🎤👻🎸","options":["Angel Beats","Nana","Beck","K-On!"],"correct":0,"hint":"Afterlife band","level":2},
  {"id":145,"text":"⚡🧲👧","options":["A Certain Scientific Railgun","Charlotte","Wonder Egg Priority","Lycoris Recoil"],"correct":0,"hint":"Electromaster girl","level":2},
  {"id":146,"text":"🐺🍎💰","options":["Spice and Wolf","Wolf Children","Beastars","Ookami Kakushi"],"correct":0,"hint":"Merchant journey","level":2},
  {"id":147,"text":"🎮🧙‍♂️💀","options":["Overlord","Log Horizon","SAO","Grimgar"],"correct":0,"hint":"MMORPG undead ruler","level":2},
  {"id":148,"text":"🧛👑🩸","options":["Seraph of the End","Trinity Blood","Hellsing","Vampire Knight"],"correct":0,"hint":"Vampire military","level":2},
  {"id":149,"text":"🪖🤖🌍","options":["Gundam","Code Geass","86","Aldnoah.Zero"],"correct":2,"hint":"Juggernaut mechs","level":2},
  {"id":150,"text":"🎭⚔️🌹","options":["Rose of Versailles","Revolutionary Girl Utena","Princess Tutu","Glass Mask"],"correct":0,"hint":"French Revolution drama","level":2},
,
  {"id":151,"text":"🔗⛓️👁️","options":["Chainsaw Man","Jujutsu Kaisen","Tokyo Ghoul","Berserk"],"correct":1,"hint":"Cursed energy sorcerer","level":2},
  {"id":152,"text":"🎸🎵💔","options":["Given","Your Lie in April","Beck","Nana"],"correct":0,"hint":"Boys love guitar band","level":2},
  {"id":153,"text":"🧊❄️🗡️","options":["Bleach","Fairy Tail","Re:Zero","That Time I Got Reincarnated"],"correct":2,"hint":"Death loop frozen","level":2},
  {"id":154,"text":"🦊🔔⛩️","options":["Inari Kon Kon","Kamisama Kiss","The Helpful Fox Senko","Spice and Wolf"],"correct":1,"hint":"God kissed contract","level":2},
  {"id":155,"text":"🎯🏹👧","options":["Fate/Stay Night","Yona of the Dawn","Akame ga Kill","Claymore"],"correct":1,"hint":"Princess with bow","level":2},
  {"id":156,"text":"📱⏳💀","options":["Mirai Nikki","Steins;Gate","Death Parade","Durarara"],"correct":0,"hint":"Future diary survival","level":2},
  {"id":157,"text":"🧪💊🧠","options":["Dr. Stone","Steins;Gate","Psycho-Pass","Monster"],"correct":2,"hint":"Crime coefficient system","level":2},
  {"id":158,"text":"🌈🦄✨","options":["Madoka Magica","Precure","Sailor Moon","Flip Flappers"],"correct":0,"hint":"Dark magical girls","level":2},
  {"id":159,"text":"🐺🌕🩸","options":["Wolf Rain","Beastars","Spice and Wolf","Wolfs Rain"],"correct":3,"hint":"Wolves seek paradise","level":2},
  {"id":160,"text":"🎭🖤🤡","options":["Tokyo Ghoul","Dorohedoro","Deadman Wonderland","Parasyte"],"correct":1,"hint":"Sorcerer door heads","level":2},
  {"id":161,"text":"🏍️🔥👹","options":["Akira","Durarara","Tokyo Revengers","Yu Yu Hakusho"],"correct":2,"hint":"Time travel gang leader","level":2},
  {"id":162,"text":"🐛🌿🧔","options":["Mushishi","Parasyte","Nausicaa","Made in Abyss"],"correct":0,"hint":"Mushi spirit doctor","level":2},
  {"id":163,"text":"🎩🔮🌙","options":["Sailor Moon","Cardcaptor Sakura","Magic Knight Rayearth","Madoka Magica"],"correct":1,"hint":"Card capturing girl","level":2},
  {"id":164,"text":"💣🏠👨‍👩‍👧","options":["Spy x Family","Assassination Classroom","Reborn","Beelzebub"],"correct":0,"hint":"Fake family spy mission","level":2},
  {"id":165,"text":"🐙👨‍🏫🌙","options":["Assassination Classroom","Mob Psycho","Korosensei Quest","Beelzebub"],"correct":0,"hint":"Kill alien teacher","level":2},
  {"id":166,"text":"🌸🗡️👘","options":["Demon Slayer","Bleach","Rurouni Kenshin","Samurai Champloo"],"correct":3,"hint":"Hip hop samurai journey","level":2},
  {"id":167,"text":"🧲⚡🦾","options":["Fullmetal Alchemist","A Certain Scientific Railgun","My Hero Academia","Soul Eater"],"correct":1,"hint":"Electric esper girl","level":2},
  {"id":168,"text":"🏹🌲🐗","options":["Princess Mononoke","Golden Kamuy","Demon Slayer","Vinland Saga"],"correct":0,"hint":"Forest spirit princess","level":2},
  {"id":169,"text":"👻🔔🏚️","options":["Mob Psycho 100","Noragami","Mieruko-chan","Ghost Hunt"],"correct":1,"hint":"Homeless jersey god","level":2},
  {"id":170,"text":"🎪✨🐰","options":["Magical Girl Site","Madoka Magica","Princess Tutu","Show By Rock"],"correct":2,"hint":"Ballet duck princess","level":2},
  {"id":171,"text":"🗡️👑🐍","options":["Fate/Zero","Seven Deadly Sins","Code Geass","Vinland Saga"],"correct":0,"hint":"Holy Grail War battle","level":2},
  {"id":172,"text":"🏃‍♂️🌀🎭","options":["Naruto","JoJo Bizarre Adventure","Mob Psycho 100","Gintama"],"correct":1,"hint":"Bizarre posing stand","level":2},
  {"id":173,"text":"📓✏️🧒","options":["Bakuman","Death Note","Blue Period","Kakushigoto"],"correct":0,"hint":"Manga artist dream duo","level":2},
  {"id":174,"text":"🌺👧💀","options":["Hell Girl","Another","Shiki","Higurashi"],"correct":0,"hint":"Send to hell request","level":2},
  {"id":175,"text":"🏰👻🌌","options":["Howls Moving Castle","Spirited Away","Castle in the Sky","Ponyo"],"correct":2,"hint":"Floating sky civilization","level":2},
  {"id":176,"text":"🎿⛷️❄️","options":["Free!","Yuri on Ice","SK8 the Infinity","Tsurune"],"correct":1,"hint":"Figure skating duo","level":2},
  {"id":177,"text":"🔩⚙️🦾","options":["Fullmetal Alchemist","86 Eighty-Six","Megalo Box","Vivy"],"correct":2,"hint":"Underground boxing cyborg","level":2},
  {"id":178,"text":"🎨🖌️🌊","options":["Blue Period","Barakamon","Kakushigoto","March Comes Like Lion"],"correct":1,"hint":"Island calligraphy artist","level":2},
  {"id":179,"text":"💀🎭👻","options":["Death Parade","Angel Beats","Death Note","Bleach"],"correct":0,"hint":"Afterlife judgment bar","level":2},
  {"id":180,"text":"🌍🔥👹","options":["Fire Force","Blue Exorcist","Demon Slayer","Black Clover"],"correct":0,"hint":"Infernal fire fighters","level":2},
  {"id":181,"text":"🏫🤖💕","options":["Chobits","Plastic Memories","Vivy","Time of Eve"],"correct":1,"hint":"Android limited lifespan","level":2},
  {"id":182,"text":"🎶🎤🌟","options":["Love Live","Idol Master","Zombieland Saga","Oshi no Ko"],"correct":2,"hint":"Zombie idol comeback","level":2},
  {"id":183,"text":"⚔️🏰🧝","options":["Sword Art Online","Record of Lodoss War","Goblin Slayer","Overlord"],"correct":1,"hint":"Classic fantasy elf war","level":2},
  {"id":184,"text":"🦇🌙🩸","options":["Hellsing","Vampire Hunter D","Castlevania","Rosario Vampire"],"correct":0,"hint":"Vampire hunter organization","level":2},
  {"id":185,"text":"🚗💨🏁","options":["Initial D","Redline","MF Ghost","Wangan Midnight"],"correct":0,"hint":"Mountain drift tofu","level":2},
  {"id":186,"text":"🧸💔😢","options":["Clannad","Anohana","Your Lie in April","Violet Evergarden"],"correct":1,"hint":"Flower name ghost friends","level":2},
  {"id":187,"text":"🎪🔥🤸","options":["Fire Force","Karakuri Circus","Black Butler","D.Gray-man"],"correct":0,"hint":"Spontaneous combustion squad","level":2},
  {"id":188,"text":"👨‍🔬⏰📡","options":["Steins;Gate","Dr. Stone","Erased","Future Diary"],"correct":0,"hint":"Microwave time machine","level":2},
  {"id":189,"text":"🏫📝🧠","options":["Classroom of the Elite","Assassination Classroom","Great Teacher Onizuka","Hyouka"],"correct":0,"hint":"Meritocracy school genius","level":2},
  {"id":190,"text":"🐉⚡🗡️","options":["Dragon Quest Dai","Fairy Tail","Slayers","Record of Grancrest"],"correct":0,"hint":"Dragon quest hero boy","level":2},
  {"id":191,"text":"💎🔨⚗️","options":["Fullmetal Alchemist","Dr. Stone","Land of the Lustrous","Made in Abyss"],"correct":2,"hint":"Gem people shattered","level":2},
  {"id":192,"text":"🌸👫🏫","options":["Clannad","Your Name","Kimi ni Todoke","Toradora"],"correct":2,"hint":"Reaching you shy girl","level":2},
  {"id":193,"text":"🛸👽🔫","options":["Space Dandy","Gintama","Trigun","Cowboy Bebop"],"correct":2,"hint":"Pacifist gunman desert","level":2},
  {"id":194,"text":"🎪🐘🎠","options":["One Piece","Karakuri Circus","Bungou Stray Dogs","Black Butler"],"correct":1,"hint":"Automaton puppet battle","level":2},
  {"id":195,"text":"👑🗡️🏰","options":["Fate/Zero","Overlord","Re:Zero","Shield Hero"],"correct":1,"hint":"Skeleton king supreme","level":2},
  {"id":196,"text":"🌊🐟👧","options":["Ponyo","Free!","Children of the Sea","Nagi no Asukara"],"correct":3,"hint":"Undersea village love","level":2},
  {"id":197,"text":"🎵🎹😭","options":["Your Lie in April","Piano Forest","Nodame Cantabile","Kids on Slope"],"correct":0,"hint":"Dying pianist colorful","level":2},
  {"id":198,"text":"🦸‍♀️🌙💫","options":["Sailor Moon","Madoka Magica","Precure","Cutey Honey"],"correct":0,"hint":"In name of moon","level":2},
  {"id":199,"text":"📺🕹️🌐","options":["Summer Wars","Digimon","Sword Art Online","No Game No Life"],"correct":0,"hint":"Virtual world family","level":2},
  {"id":200,"text":"🧙‍♀️🧹🌊","options":["Mary and the Witch Flower","Kiki Delivery Service","Little Witch Academia","Howls Moving Castle"],"correct":0,"hint":"Stolen witch flower power","level":2}
];
