export default [
  {"id":1,"text":"🍥🦊👦","options":["Bleach","Naruto","One Piece","Dragon Ball"],"correct":1,"hint":"Hidden Leaf ninja","level":1},
  {"id":2,"text":"🏴‍☠️🍖👒","options":["One Piece","Fairy Tail","Black Clover","Bleach"],"correct":0,"hint":"Pirate King dream","level":1},
  {"id":3,"text":"🐉💥🟠","options":["Jujutsu Kaisen","Dragon Ball","Demon Slayer","Attack on Titan"],"correct":1,"hint":"Saiyan warrior","level":1},
  {"id":4,"text":"👹⚔️🎴","options":["Bleach","Demon Slayer","Naruto","Tokyo Ghoul"],"correct":1,"hint":"Breathing styles","level":1},
  {"id":5,"text":"👒⚓🌊","options":["One Piece","Blue Lock","Haikyuu","Black Clover"],"correct":0,"hint":"Grand Line adventure","level":1},
  {"id":6,"text":"⚔️👻🧡","options":["Bleach","Naruto","Death Note","Chainsaw Man"],"correct":0,"hint":"Soul Reapers","level":1},
  {"id":7,"text":"📓🍎💀","options":["Tokyo Ghoul","Death Note","Parasyte","Another"],"correct":1,"hint":"Shinigami notebook","level":1},
  {"id":8,"text":"🏐🧡🖤","options":["Slam Dunk","Blue Lock","Haikyuu","Kuroko no Basket"],"correct":2,"hint":"Volleyball anime","level":1},
  {"id":9,"text":"⚽🔵🔥","options":["Blue Lock","Inazuma Eleven","Captain Tsubasa","Ao Ashi"],"correct":0,"hint":"Ego striker project","level":1},
  {"id":10,"text":"🧹🪄⚫","options":["Black Clover","Mashle","Fairy Tail","Hunter x Hunter"],"correct":1,"hint":"Muscles in magic world","level":1},
  {"id":51,"text":"⚡🍜🟡","options":["One Punch Man","Naruto","Mob Psycho 100","Dragon Ball"],"correct":1,"hint":"Loves ramen","level":1},
  {"id":52,"text":"👊🦸🧑‍🦲","options":["One Punch Man","My Hero Academia","Tiger & Bunny","Mob Psycho 100"],"correct":0,"hint":"Bald hero","level":1},
  {"id":53,"text":"🦸💥🏫","options":["Fire Force","Blue Exorcist","My Hero Academia","Soul Eater"],"correct":2,"hint":"UA High School","level":1},
  {"id":54,"text":"🐉👆🔥","options":["Fairy Tail","Black Clover","Seven Deadly Sins","Magi"],"correct":0,"hint":"Guild wizards","level":1},
  {"id":55,"text":"🍖⚔️🐗","options":["Vinland Saga","Demon Slayer","Dororo","Berserk"],"correct":1,"hint":"Beast breathing","level":1},
  {"id":56,"text":"🐈📦😺","options":["The Cat Returns","Doraemon","Chi's Sweet Home","My Neighbor Totoro"],"correct":1,"hint":"Robotic cat","level":1},
  {"id":57,"text":"👹🔥👶","options":["Blue Exorcist","Beelzebub","Nurarihyon no Mago","Devilman Crybaby"],"correct":1,"hint":"Demon baby","level":1},
  {"id":58,"text":"🏀🟥🟦","options":["Slam Dunk","Kuroko no Basket","Ahiru no Sora","Blue Lock"],"correct":1,"hint":"Phantom sixth man","level":1},
  {"id":59,"text":"🧛🩸🔫","options":["Hellsing","Vampire Knight","Seraph of the End","Trinity Blood"],"correct":0,"hint":"Alucard","level":1},
  {"id":60,"text":"🐯🐉🏫","options":["Toradora","Clannad","Horimiya","Golden Time"],"correct":0,"hint":"Tiger-like tsundere","level":1},
  {"id":101,"text":"🍙⚔️👹","options":["Inuyasha","Naruto","Demon Slayer","Bleach"],"correct":0,"hint":"Feudal Japan demon","level":1},
  {"id":102,"text":"🧙‍♂️🔥🐉","options":["Fairy Tail","Black Clover","Magi","Blue Exorcist"],"correct":0,"hint":"Fire Dragon Slayer","level":1},
  {"id":103,"text":"👊💯👻","options":["Mob Psycho 100","One Punch Man","Bleach","Noragami"],"correct":0,"hint":"Psychic explosion","level":1},
  {"id":104,"text":"⚔️🧛🌹","options":["Vampire Knight","Hellsing","Seraph of the End","Trinity Blood"],"correct":0,"hint":"Vampire school","level":1},
  {"id":105,"text":"🐲⚔️7️⃣","options":["Seven Deadly Sins","Fairy Tail","Black Clover","Dragon Ball"],"correct":0,"hint":"Meliodas","level":1},
  {"id":106,"text":"🎤⭐👶","options":["Oshi no Ko","Love Live!","Idolmaster","Zombieland Saga"],"correct":0,"hint":"Idol twins","level":1},
  {"id":107,"text":"👨‍🍳🍞😋","options":["Food Wars","Yakitate!! Japan","Toriko","Campfire Cooking"],"correct":0,"hint":"Cooking battles","level":1},
  {"id":108,"text":"🏫❤️📚","options":["Horimiya","Kaguya-sama","Toradora","Clannad"],"correct":1,"hint":"Love is war","level":1},
  {"id":109,"text":"🐺👧🌧️","options":["Wolf Children","Spice and Wolf","Princess Mononoke","Beastars"],"correct":0,"hint":"Half-wolf siblings","level":1},
  {"id":110,"text":"🏀🔥👓","options":["Slam Dunk","Ahiru no Sora","Kuroko no Basket","Blue Lock"],"correct":0,"hint":"Red-haired delinquent","level":1},
  {"id":151,"text":"🐱🚌🌳","options":["Kiki's Delivery Service","Spirited Away","My Neighbor Totoro","The Cat Returns"],"correct":2,"hint":"Giant forest spirit","level":1},
  {"id":152,"text":"🧹🐈‍⬛🍞","options":["Little Witch Academia","Kiki's Delivery Service","Flying Witch","Mary and the Witch's Flower"],"correct":1,"hint":"Young delivery witch","level":1},
  {"id":153,"text":"🚂👻🏯","options":["Spirited Away","Howl's Moving Castle","Princess Mononoke","Ponyo"],"correct":0,"hint":"Bathhouse spirits","level":1},
  {"id":154,"text":"🐟👧🌊","options":["Children of the Sea","Ponyo","Lu Over the Wall","Ride Your Wave"],"correct":1,"hint":"Goldfish girl","level":1},
  {"id":155,"text":"⚔️👑🦁","options":["Black Clover","Magi","The Seven Deadly Sins","Arslan Senki"],"correct":1,"hint":"Djinn powers","level":1},
  {"id":156,"text":"👦⚡🐈","options":["Blue Exorcist","Pokémon","Digimon","Beyblade"],"correct":1,"hint":"Electric mouse","level":1},
  {"id":157,"text":"🌀🧿🥷","options":["Naruto","Jujutsu Kaisen","Bleach","Basilisk"],"correct":0,"hint":"Sharingan rivalry","level":1},
  {"id":158,"text":"👧📚✨","options":["Cardcaptor Sakura","Sailor Moon","Madoka Magica","Tokyo Mew Mew"],"correct":0,"hint":"Clow Cards","level":1},
  {"id":159,"text":"🌙👭✨","options":["Pretty Cure","Sailor Moon","Wedding Peach","Magic Knight Rayearth"],"correct":1,"hint":"Moon prism power","level":1},
  {"id":160,"text":"🚗💨⛰️","options":["Initial D","Wangan Midnight","Capeta","Redline"],"correct":0,"hint":"Tofu delivery racer","level":1},
  {"id":201,"text":"🧽⭐🌊","options":["SpongeBob SquarePants","Ponyo","Bubblegum Crisis","Mermaid Melody"],"correct":1,"hint":"Ocean magic girl","level":1},
  {"id":202,"text":"🧑‍🚀🌍🚀","options":["Dr. Stone","Astra Lost in Space","Space Brothers","Edens Zero"],"correct":1,"hint":"Lost in space","level":1},
  {"id":203,"text":"👧🎸😶","options":["K-On!","Nana","Bocchi the Rock!","Beck"],"correct":2,"hint":"Social anxiety guitarist","level":1},
  {"id":204,"text":"⚔️🐉👑","options":["Record of Lodoss War","Fairy Tail","Dragon Quest: Dai","Slayers"],"correct":2,"hint":"Hero from Dragon Quest","level":1},
  {"id":205,"text":"👦🐉💫","options":["Beyblade","Digimon","Bakugan","Yu-Gi-Oh!"],"correct":0,"hint":"Let it rip","level":1},
  {"id":206,"text":"👓📔❤️","options":["Horimiya","My Little Monster","Komi Can't Communicate","Toradora"],"correct":2,"hint":"Communication disorder","level":1},
  {"id":207,"text":"🧹🏫✨","options":["Little Witch Academia","Kiki's Delivery Service","Cardcaptor Sakura","Flying Witch"],"correct":0,"hint":"Magic academy","level":1},
  {"id":208,"text":"⚽🦅🔥","options":["Blue Lock","Captain Tsubasa","Ao Ashi","Inazuma Eleven"],"correct":2,"hint":"Football tactics anime","level":1},
  {"id":209,"text":"🐈🍜😺","options":["Nyan Koi!","The Masterful Cat Is Depressed Again Today","Chi's Sweet Home","Bananya"],"correct":1,"hint":"Giant smart cat","level":1},
  {"id":210,"text":"🛸👽😂","options":["Gintama","Space Dandy","Urusei Yatsura","Dandadan"],"correct":0,"hint":"Alien comedy samurai","level":1},
,
  {"id":51,"text":"🧙‍♂️🪄🏰","options":["Fairy Tail","Black Clover","Magi","Mashle"],"correct":0,"hint":"Magic guild wizards","level":1},
  {"id":52,"text":"🥊👊😤","options":["My Hero Academia","One Punch Man","Baki","Kengan Ashura"],"correct":1,"hint":"One hit KO hero","level":1},
  {"id":53,"text":"🐱🎣🧒","options":["Doraemon","Natsume Book","Pokemon","Yo-kai Watch"],"correct":0,"hint":"Robot cat future","level":1},
  {"id":54,"text":"🏀⚡🔵","options":["Slam Dunk","Haikyuu","Kuroko no Basket","Ahiru no Sora"],"correct":2,"hint":"Phantom sixth man","level":1},
  {"id":55,"text":"👊💎🦸","options":["One Punch Man","My Hero Academia","Mob Psycho 100","Tiger and Bunny"],"correct":1,"hint":"Quirk hero school","level":1},
  {"id":56,"text":"🌸⚔️🎌","options":["Rurouni Kenshin","Gintama","Samurai Champloo","Sword Art Online"],"correct":0,"hint":"Reverse blade samurai","level":1},
  {"id":57,"text":"🤖🔫🚀","options":["Gundam","Evangelion","Code Geass","Macross"],"correct":0,"hint":"Giant mecha wars","level":1},
  {"id":58,"text":"🦸‍♂️💪🏆","options":["Dragon Ball Z","My Hero Academia","One Punch Man","Baki"],"correct":0,"hint":"Super Saiyan power","level":1},
  {"id":59,"text":"🗡️🌐🎮","options":["Sword Art Online",".hack//Sign","Log Horizon","Overlord"],"correct":0,"hint":"Trapped in game","level":1},
  {"id":60,"text":"🍜🐷🛁","options":["Spirited Away","Howls Moving Castle","Ponyo","Princess Mononoke"],"correct":0,"hint":"Bathhouse spirit world","level":1},
  {"id":61,"text":"🏫👻🔍","options":["Another","Ghost Hunt","Hyouka","Dusk Maiden of Amnesia"],"correct":2,"hint":"Curious energy saver","level":1},
  {"id":62,"text":"🎵🎸🤘","options":["K-On!","Beck","Given","Bocchi the Rock"],"correct":0,"hint":"Tea and music club","level":1},
  {"id":63,"text":"🐉🔥🏔️","options":["Fairy Tail","Dragon Ball","Miss Kobayashi Dragon Maid","Fire Force"],"correct":2,"hint":"Dragon becomes maid","level":1},
  {"id":64,"text":"⚾🔥🏟️","options":["Major","Ace of Diamond","Big Windup","Cross Game"],"correct":1,"hint":"Diamond pitcher ace","level":1},
  {"id":65,"text":"🌊🏄‍♂️🐙","options":["Free!","Wave!!","Tsuritama","Ponyo"],"correct":2,"hint":"Fishing alien friend","level":1},
  {"id":66,"text":"🎭🔪🩸","options":["Demon Slayer","Tokyo Ghoul","Parasyte","Deadman Wonderland"],"correct":1,"hint":"Half ghoul masked","level":1},
  {"id":67,"text":"📚✨🧹","options":["Little Witch Academia","Fairy Tail","Black Clover","Mashle"],"correct":0,"hint":"Witch school student","level":1},
  {"id":68,"text":"🏃‍♂️💨🍃","options":["Naruto","Boruto","Black Clover","My Hero Academia"],"correct":1,"hint":"Son of Hokage","level":1},
  {"id":69,"text":"🎲🃏🎰","options":["Kakegurui","Kaiji","No Game No Life","Gambling School"],"correct":0,"hint":"Gambling academy girl","level":1},
  {"id":70,"text":"👸❄️🏰","options":["Frozen","Re:Zero","Yona of the Dawn","Snow White Red Hair"],"correct":3,"hint":"Red-haired herbalist princess","level":1},
  {"id":71,"text":"🌙✨👧","options":["Sailor Moon","Cardcaptor Sakura","Madoka Magica","Pretty Cure"],"correct":0,"hint":"Moon guardian warrior","level":1},
  {"id":72,"text":"🃏🎪🕷️","options":["Hunter x Hunter","JoJo","Karakuri Circus","D.Gray-man"],"correct":2,"hint":"Puppet circus battles","level":1},
  {"id":73,"text":"⭐🚂🌌","options":["Galaxy Express 999","Space Dandy","Cowboy Bebop","Outlaw Star"],"correct":0,"hint":"Space train journey","level":1},
  {"id":74,"text":"🐸🌧️👦","options":["Doraemon","Sergeant Frog","My Hero Academia","Naruto"],"correct":1,"hint":"Alien frog invasion","level":1},
  {"id":75,"text":"🍰☕👧","options":["K-On!","Blend S","Is the Order a Rabbit","Working!!"],"correct":2,"hint":"Cute rabbit cafe","level":1},
  {"id":76,"text":"🥷🌀👁️","options":["Naruto","Boruto","Naruto Shippuden","Rock Lee"],"correct":2,"hint":"Grown up ninja war","level":1},
  {"id":77,"text":"🎯🏹🦌","options":["Demon Slayer","Golden Kamuy","Vinland Saga","Dr. Stone"],"correct":1,"hint":"Gold rush Ainu treasure","level":1},
  {"id":78,"text":"🧬🦠💉","options":["Cells at Work","Dr. Stone","Parasyte","Attack on Titan"],"correct":0,"hint":"Body cell adventures","level":1},
  {"id":79,"text":"🐝🍯🧸","options":["Winnie the Pooh","Beastars","Polar Bear Cafe","Aggressive Retsuko"],"correct":2,"hint":"Animal cafe workers","level":1},
  {"id":80,"text":"🎮🕹️👾","options":["No Game No Life","High Score Girl","Bofuri","Overlord"],"correct":1,"hint":"Retro arcade romance","level":1},
  {"id":81,"text":"🐺🌾👧","options":["Spice and Wolf","Wolf Children","Princess Mononoke","Inuyasha"],"correct":0,"hint":"Wise wolf economics","level":1},
  {"id":82,"text":"🧹✈️👧","options":["Kiki Delivery Service","Little Witch Academia","Howls Moving Castle","Nadia"],"correct":0,"hint":"Flying witch delivery","level":1},
  {"id":83,"text":"🤖💙👦","options":["Astro Boy","Doraemon","Mega Man","Pluto"],"correct":0,"hint":"Classic robot boy hero","level":1},
  {"id":84,"text":"🎪🤡🃏","options":["Hunter x Hunter","Karakuri Circus","Black Butler","D.Gray-man"],"correct":0,"hint":"Clown hunter exam","level":1},
  {"id":85,"text":"🏝️🌺💀","options":["One Piece","Dr. Stone","Btooom","Sounan desu ka"],"correct":2,"hint":"Bomb survival island","level":1},
  {"id":86,"text":"👓📖🔬","options":["Dr. Stone","Steins Gate","Cells at Work","Science Fell in Love"],"correct":0,"hint":"Stone world science","level":1},
  {"id":87,"text":"🐍🔔🧙","options":["Naruto","Black Clover","Fairy Tail","Magi"],"correct":3,"hint":"Aladdin magic labyrinth","level":1},
  {"id":88,"text":"🎻🌹💀","options":["Your Lie in April","Violet Evergarden","Given","Kids on the Slope"],"correct":0,"hint":"Piano and violin","level":1},
  {"id":89,"text":"🦁👑🌍","options":["Seven Deadly Sins","Beastars","Africa Salaryman","Killing Bites"],"correct":0,"hint":"Sin of pride captain","level":1},
  {"id":90,"text":"🌀⏰🔙","options":["Steins;Gate","Re:Zero","Erased","The Girl Who Leapt Through Time"],"correct":2,"hint":"Revival time travel","level":1},
  {"id":91,"text":"👼😈🔥","options":["Blue Exorcist","High School DxD","Devilman Crybaby","Angel Beats"],"correct":0,"hint":"Son of Satan exorcist","level":1},
  {"id":92,"text":"🏋️💪😠","options":["Baki","Kengan Ashura","How Heavy Dumbbells","Hajime no Ippo"],"correct":2,"hint":"Gym girls workout","level":1},
  {"id":93,"text":"🐱👤🌙","options":["Fruits Basket","Cat Returns","Bananya","My Roommate is a Cat"],"correct":0,"hint":"Zodiac curse family","level":1},
  {"id":94,"text":"🏫🔪💀","options":["Another","Danganronpa","Classroom of Elite","Assassination Classroom"],"correct":3,"hint":"Kill the teacher","level":1},
  {"id":95,"text":"🏰⚔️🐴","options":["Vinland Saga","Attack on Titan","Berserk","Kingdom"],"correct":3,"hint":"Chinese warring states","level":1},
  {"id":96,"text":"🎊🥳🏫","options":["Toradora","Love Hina","Clannad","School Rumble"],"correct":0,"hint":"Tiger and dragon love","level":1},
  {"id":97,"text":"🌊⛵🗺️","options":["One Piece","Vinland Saga","Berserk","Black Lagoon"],"correct":1,"hint":"Viking saga revenge","level":1},
  {"id":98,"text":"🐷🔨🔧","options":["Porco Rosso","Silver Spoon","Beastars","Oink Oink"],"correct":0,"hint":"Pig pilot bounty hunter","level":1},
  {"id":99,"text":"🎒🏫💕","options":["Toradora","Kaguya-sama","My Dress-Up Darling","Horimiya"],"correct":3,"hint":"Hidden sides romance","level":1},
  {"id":100,"text":"👨‍🍳🍳🥘","options":["Food Wars","Yakitate Japan","Toriko","Isekai Izakaya"],"correct":0,"hint":"Cooking battle school","level":1}
];
