export default [
  {"id":41,"text":"🍌🔫🗽","options":["Banana Fish","Gangsta","Baccano!","91 Days"],"correct":0,"hint":"New York gangs","level":5},
  {"id":42,"text":"🧼👽🛵","options":["FLCL","Gintama","Space Dandy","Kill la Kill"],"correct":0,"hint":"Crazy coming-of-age","level":5},
  {"id":43,"text":"🚋👻🪙","options":["Noragami","Mob Psycho 100","Dandadan","Mononoke"],"correct":2,"hint":"Aliens and spirits","level":5},
  {"id":44,"text":"🎩🩸🚂","options":["Black Butler","Baccano!","Hellsing","Moriarty the Patriot"],"correct":1,"hint":"Immortal mafia chaos","level":5},
  {"id":45,"text":"🧊📖🧍","options":["Ergo Proxy","Mushishi","Kino's Journey","Haibane Renmei"],"correct":1,"hint":"Ethereal creatures","level":5},
  {"id":46,"text":"👧🪓📞","options":["Another","Higurashi","School Days","Mirai Nikki"],"correct":1,"hint":"Repeating village tragedy","level":5},
  {"id":47,"text":"⚰️🌹👧","options":["Rozen Maiden","Black Butler","Gosick","Vampire Princess Miyu"],"correct":0,"hint":"Living dolls","level":5},
  {"id":48,"text":"🐟🌊🧠","options":["Children of the Sea","Ponyo","Blue Submarine No. 6","Arpeggio of Blue Steel"],"correct":0,"hint":"Philosophical ocean film","level":5},
  {"id":49,"text":"🛰️🧬🌍","options":["Planetes","Knights of Sidonia","Blue Gender","Terra Formars"],"correct":0,"hint":"Space debris workers","level":5},
  {"id":50,"text":"🎭🪞🩸","options":["Perfect Blue","Paprika","Paranoia Agent","Millennium Actress"],"correct":0,"hint":"Psychological idol thriller","level":5},
  {"id":91,"text":"🪐📖🧒","options":["Kaiba","Dennou Coil","Texhnolyze","Noein"],"correct":0,"hint":"Memories and bodies","level":5},
  {"id":92,"text":"🎩🐱🌙","options":["Night on the Galactic Railroad","The Cat Returns","Natsume's Book of Friends","xxxHOLiC"],"correct":0,"hint":"Philosophical cat journey","level":5},
  {"id":93,"text":"🧬⚙️🌃","options":["Texhnolyze","Ergo Proxy","Serial Experiments Lain","Blame!"],"correct":0,"hint":"Underground dystopia","level":5},
  {"id":94,"text":"👧📺⚡","options":["Dennou Coil","FLCL","Digimon Tamers","Boogiepop Phantom"],"correct":0,"hint":"AR glasses world","level":5},
  {"id":95,"text":"🚂🧛🩸","options":["Kabaneri of the Iron Fortress","Vampire Hunter D","Shiki","Hellsing"],"correct":0,"hint":"Zombie train survival","level":5},
  {"id":96,"text":"🕊️⚔️☁️","options":["Haibane Renmei","Angel Beats","Casshern Sins","Kino's Journey"],"correct":0,"hint":"Halo-wing mystery","level":5},
  {"id":97,"text":"🎼🌌💔","options":["Macross Plus","Beck","Nana","Kids on the Slope"],"correct":0,"hint":"AI idol singer","level":5},
  {"id":98,"text":"👹📿🕯️","options":["Mononoke","Ayakashi","Mushishi","Hell Girl"],"correct":1,"hint":"Horror anthology","level":5},
  {"id":99,"text":"🌑👧🪞","options":["Boogiepop Phantom","Another","Wonder Egg Priority","Ghost Hound"],"correct":0,"hint":"Urban legends","level":5},
  {"id":100,"text":"🧠⚫📡","options":["Ergo Proxy","Lain","Pluto","Blame!"],"correct":0,"hint":"Amnesiac android mystery","level":5},
  {"id":141,"text":"🧒📺🌌","options":["Noein","Dennou Coil","Kaiba","Boogiepop Phantom"],"correct":0,"hint":"Quantum dimensions","level":5},
  {"id":142,"text":"⚙️👩‍🚀🌙","options":["Moonlight Mile","Planetes","Rocket Girls","Astra Lost in Space"],"correct":0,"hint":"Realistic space workers","level":5},
  {"id":143,"text":"🧠🎹🕳️","options":["RahXephon","Key the Metal Idol","Serial Experiments Lain","Texhnolyze"],"correct":1,"hint":"Android idol girl","level":5},
  {"id":144,"text":"🩸👧🎀","options":["Alien 9","Elfen Lied","Narutaru","Higurashi"],"correct":0,"hint":"Weird alien school","level":5},
  {"id":145,"text":"🌌🚲👧","options":["Windy Tales","Haibane Renmei","Kino's Journey","NieA Under 7"],"correct":0,"hint":"Wind manipulation","level":5},
  {"id":146,"text":"🎭👹📜","options":["Mononoke","Ayakashi","Mushishi","Hell Girl"],"correct":0,"hint":"Medicine seller exorcist","level":5},
  {"id":147,"text":"🧒🐉⚔️","options":["Brave Story","Dragon Drive","Guin Saga","Legendz"],"correct":0,"hint":"Fantasy parallel world","level":5},
  {"id":148,"text":"📡👧👁️","options":["Ghost Hound","Lain","Dennou Coil","Boogiepop Phantom"],"correct":0,"hint":"Psychological spirit travel","level":5},
  {"id":149,"text":"🌑🪐🧬","options":["Toward the Terra","Terra e...","Blue Gender","Heroic Age"],"correct":1,"hint":"Espers in space","level":5},
  {"id":150,"text":"⚰️🎻🩸","options":["Le Portrait de Petit Cossette","Vampire Princess Miyu","Pet Shop of Horrors","Requiem from the Darkness"],"correct":0,"hint":"Haunted antique glass","level":5},
  {"id":191,"text":"🧠⚙️🌑","options":["Blame!","Texhnolyze","Ergo Proxy","Genocyber"],"correct":0,"hint":"Endless megastructure","level":5},
  {"id":192,"text":"👧📖☁️","options":["Kino's Journey","Haibane Renmei","NieA Under 7","Sketchbook Full Colors"],"correct":2,"hint":"Poor alien roommate","level":5},
  {"id":193,"text":"🎻🩸👧","options":["Le Portrait de Petit Cossette","Vampire Princess Miyu","Shiki","Ghost Hunt"],"correct":0,"hint":"Gothic OVA horror","level":5},
  {"id":194,"text":"📡🌌👁️","options":["Betterman","Argento Soma","Gasaraki","RahXephon"],"correct":3,"hint":"Musical mecha mystery","level":5},
  {"id":195,"text":"⚔️🌸🧠","options":["Shigurui","Basilisk","Samurai Deeper Kyo","Blade of the Immortal"],"correct":0,"hint":"Extremely brutal samurai","level":5},
  {"id":196,"text":"🧒🌍🐉","options":["Fantastic Children","Noein","Guin Saga","Toward the Terra"],"correct":0,"hint":"White-haired wandering kids","level":5},
  {"id":197,"text":"👧📺💀","options":["Boogiepop Phantom","Ghost Hound","Hell Girl","Another"],"correct":2,"hint":"Website revenge service","level":5},
  {"id":198,"text":"🚂⚔️🦇","options":["Night Warriors","Vampire Hunter D: Bloodlust","Castlevania","Hellsing Ultimate"],"correct":1,"hint":"Gorgeous gothic vampire film","level":5},
  {"id":199,"text":"🧠👤📖","options":["Pet","ID: Invaded","Paranoia Agent","Perfect Blue"],"correct":0,"hint":"Memory manipulation powers","level":5},
  {"id":200,"text":"🌌🎼👧","options":["Key the Metal Idol","Armitage III","Bubblegum Crisis","Serial Experiments Lain"],"correct":0,"hint":"Robot girl becoming human","level":5},
  {"id":241,"text":"🧠🎭📡","options":["Serial Experiments Lain","Betterman","Boogiepop Phantom","Key the Metal Idol"],"correct":3,"hint":"Idol android philosophy","level":5},
  {"id":242,"text":"⚙️🌌👤","options":["Argento Soma","RahXephon","Gasaraki","Brain Powered"],"correct":0,"hint":"Alien reconstruction mecha","level":5},
  {"id":243,"text":"🧒👻📖","options":["Mokke","Natsume's Book of Friends","Mushishi","Ghost Hound"],"correct":0,"hint":"Spirit-seeing sisters","level":5},
  {"id":244,"text":"🌌🚂🐱","options":["Night on the Galactic Railroad","Galaxy Express 999","Cat Soup","The Cat Returns"],"correct":1,"hint":"Space train classic","level":5},
  {"id":245,"text":"👧🪐⚡","options":["Alien 9","NieA Under 7","Dennou Coil","Figure 17"],"correct":3,"hint":"Alien clone twin","level":5},
  {"id":246,"text":"⚔️🌑🧠","options":["Blade of the Immortal","Shigurui","Basilisk","Ninja Resurrection"],"correct":3,"hint":"Dark ninja OVA","level":5},
  {"id":247,"text":"🧠💀🌆","options":["Genocyber","MD Geist","Violence Jack","Cyber City Oedo 808"],"correct":0,"hint":"Brutal psychic cyberpunk","level":5},
  {"id":248,"text":"📖⚙️👧","options":["NieA Under 7","Haibane Renmei","Windy Tales","Yokohama Kaidashi Kikou"],"correct":0,"hint":"Poor alien roommate comedy","level":5},
  {"id":249,"text":"🧬🌌🧒","options":["Toward the Terra","Heroic Age","Fantastic Children","Noein"],"correct":0,"hint":"Psychic humans in space","level":5},
  {"id":250,"text":"🩸🎨👧","options":["Belladonna of Sadness","Angel's Egg","Perfect Blue","Vampire Hunter D"],"correct":0,"hint":"Experimental psychedelic film","level":5},
];
