export default [
  {"id":401,"text":"🍌🔫🗽","options":["Banana Fish","Gangsta","Baccano!","91 Days"],"correct":0,"hint":"New York gangs","level":5},
  {"id":402,"text":"🧼👽🛵","options":["FLCL","Gintama","Space Dandy","Kill la Kill"],"correct":0,"hint":"Crazy coming-of-age","level":5},
  {"id":403,"text":"🚋👻🪙","options":["Noragami","Mob Psycho 100","Dandadan","Mononoke"],"correct":2,"hint":"Aliens and spirits","level":5},
  {"id":404,"text":"🎩🩸🚂","options":["Black Butler","Baccano!","Hellsing","Moriarty the Patriot"],"correct":1,"hint":"Immortal mafia chaos","level":5},
  {"id":405,"text":"🧊📖🧍","options":["Ergo Proxy","Mushishi","Kino's Journey","Haibane Renmei"],"correct":1,"hint":"Ethereal creatures","level":5},
  {"id":406,"text":"👧🪓📞","options":["Another","Higurashi","School Days","Mirai Nikki"],"correct":1,"hint":"Repeating village tragedy","level":5},
  {"id":407,"text":"⚰️🌹👧","options":["Rozen Maiden","Black Butler","Gosick","Vampire Princess Miyu"],"correct":0,"hint":"Living dolls","level":5},
  {"id":408,"text":"🐟🌊🧠","options":["Children of the Sea","Ponyo","Blue Submarine No. 6","Arpeggio of Blue Steel"],"correct":0,"hint":"Philosophical ocean film","level":5},
  {"id":409,"text":"🛰️🧬🌍","options":["Planetes","Knights of Sidonia","Blue Gender","Terra Formars"],"correct":0,"hint":"Space debris workers","level":5},
  {"id":410,"text":"🎭🪞🩸","options":["Perfect Blue","Paprika","Paranoia Agent","Millennium Actress"],"correct":0,"hint":"Psychological idol thriller","level":5},
  {"id":411,"text":"🪐📖🧒","options":["Kaiba","Dennou Coil","Texhnolyze","Noein"],"correct":0,"hint":"Memories and bodies","level":5},
  {"id":412,"text":"🎩🐱🌙","options":["Night on the Galactic Railroad","The Cat Returns","Natsume's Book of Friends","xxxHOLiC"],"correct":0,"hint":"Philosophical cat journey","level":5},
  {"id":413,"text":"🧬⚙️🌃","options":["Texhnolyze","Ergo Proxy","Serial Experiments Lain","Blame!"],"correct":0,"hint":"Underground dystopia","level":5},
  {"id":414,"text":"👧📺⚡","options":["Dennou Coil","FLCL","Digimon Tamers","Boogiepop Phantom"],"correct":0,"hint":"AR glasses world","level":5},
  {"id":415,"text":"🚂🧛🩸","options":["Kabaneri of the Iron Fortress","Vampire Hunter D","Shiki","Hellsing"],"correct":0,"hint":"Zombie train survival","level":5},
  {"id":416,"text":"🕊️⚔️☁️","options":["Haibane Renmei","Angel Beats","Casshern Sins","Kino's Journey"],"correct":0,"hint":"Halo-wing mystery","level":5},
  {"id":417,"text":"🎼🌌💔","options":["Macross Plus","Beck","Nana","Kids on the Slope"],"correct":0,"hint":"AI idol singer","level":5},
  {"id":418,"text":"👹📿🕯️","options":["Mononoke","Ayakashi","Mushishi","Hell Girl"],"correct":1,"hint":"Horror anthology","level":5},
  {"id":419,"text":"🌑👧🪞","options":["Boogiepop Phantom","Another","Wonder Egg Priority","Ghost Hound"],"correct":0,"hint":"Urban legends","level":5},
  {"id":420,"text":"🧠⚫📡","options":["Ergo Proxy","Lain","Pluto","Blame!"],"correct":0,"hint":"Amnesiac android mystery","level":5},
  {"id":421,"text":"🧒📺🌌","options":["Noein","Dennou Coil","Kaiba","Boogiepop Phantom"],"correct":0,"hint":"Quantum dimensions","level":5},
  {"id":422,"text":"⚙️👩‍🚀🌙","options":["Moonlight Mile","Planetes","Rocket Girls","Astra Lost in Space"],"correct":0,"hint":"Realistic space workers","level":5},
  {"id":423,"text":"🧠🎹🕳️","options":["RahXephon","Key the Metal Idol","Serial Experiments Lain","Texhnolyze"],"correct":1,"hint":"Android idol girl","level":5},
  {"id":424,"text":"🩸👧🎀","options":["Alien 9","Elfen Lied","Narutaru","Higurashi"],"correct":0,"hint":"Weird alien school","level":5},
  {"id":425,"text":"🌌🚲👧","options":["Windy Tales","Haibane Renmei","Kino's Journey","NieA Under 7"],"correct":0,"hint":"Wind manipulation","level":5},
  {"id":426,"text":"🎭👹📜","options":["Mononoke","Ayakashi","Mushishi","Hell Girl"],"correct":0,"hint":"Medicine seller exorcist","level":5},
  {"id":427,"text":"🧒🐉⚔️","options":["Brave Story","Dragon Drive","Guin Saga","Legendz"],"correct":0,"hint":"Fantasy parallel world","level":5},
  {"id":428,"text":"📡👧👁️","options":["Ghost Hound","Lain","Dennou Coil","Boogiepop Phantom"],"correct":0,"hint":"Psychological spirit travel","level":5},
  {"id":429,"text":"🌑🪐🧬","options":["Toward the Terra","Terra e...","Blue Gender","Heroic Age"],"correct":1,"hint":"Espers in space","level":5},
  {"id":430,"text":"⚰️🎻🩸","options":["Le Portrait de Petit Cossette","Vampire Princess Miyu","Pet Shop of Horrors","Requiem from the Darkness"],"correct":0,"hint":"Haunted antique glass","level":5},
  {"id":431,"text":"🧠⚙️🌑","options":["Blame!","Texhnolyze","Ergo Proxy","Genocyber"],"correct":0,"hint":"Endless megastructure","level":5},
  {"id":432,"text":"👧📖☁️","options":["Kino's Journey","Haibane Renmei","NieA Under 7","Sketchbook Full Colors"],"correct":2,"hint":"Poor alien roommate","level":5},
  {"id":433,"text":"🎻🩸👧","options":["Le Portrait de Petit Cossette","Vampire Princess Miyu","Shiki","Ghost Hunt"],"correct":0,"hint":"Gothic OVA horror","level":5},
  {"id":434,"text":"📡🌌👁️","options":["Betterman","Argento Soma","Gasaraki","RahXephon"],"correct":3,"hint":"Musical mecha mystery","level":5},
  {"id":435,"text":"⚔️🌸🧠","options":["Shigurui","Basilisk","Samurai Deeper Kyo","Blade of the Immortal"],"correct":0,"hint":"Extremely brutal samurai","level":5},
  {"id":436,"text":"🧒🌍🐉","options":["Fantastic Children","Noein","Guin Saga","Toward the Terra"],"correct":0,"hint":"White-haired wandering kids","level":5},
  {"id":437,"text":"👧📺💀","options":["Boogiepop Phantom","Ghost Hound","Hell Girl","Another"],"correct":2,"hint":"Website revenge service","level":5},
  {"id":438,"text":"🚂⚔️🦇","options":["Night Warriors","Vampire Hunter D: Bloodlust","Castlevania","Hellsing Ultimate"],"correct":1,"hint":"Gorgeous gothic vampire film","level":5},
  {"id":439,"text":"🧠👤📖","options":["Pet","ID: Invaded","Paranoia Agent","Perfect Blue"],"correct":0,"hint":"Memory manipulation powers","level":5},
  {"id":440,"text":"🌌🎼👧","options":["Key the Metal Idol","Armitage III","Bubblegum Crisis","Serial Experiments Lain"],"correct":0,"hint":"Robot girl becoming human","level":5},
  {"id":441,"text":"🧠🎭📡","options":["Serial Experiments Lain","Betterman","Boogiepop Phantom","Key the Metal Idol"],"correct":3,"hint":"Idol android philosophy","level":5},
  {"id":442,"text":"⚙️🌌👤","options":["Argento Soma","RahXephon","Gasaraki","Brain Powered"],"correct":0,"hint":"Alien reconstruction mecha","level":5},
  {"id":443,"text":"🧒👻📖","options":["Mokke","Natsume's Book of Friends","Mushishi","Ghost Hound"],"correct":0,"hint":"Spirit-seeing sisters","level":5},
  {"id":444,"text":"🌌🚂🐱","options":["Night on the Galactic Railroad","Galaxy Express 999","Cat Soup","The Cat Returns"],"correct":1,"hint":"Space train classic","level":5},
  {"id":445,"text":"👧🪐⚡","options":["Alien 9","NieA Under 7","Dennou Coil","Figure 17"],"correct":3,"hint":"Alien clone twin","level":5},
  {"id":446,"text":"⚔️🌑🧠","options":["Blade of the Immortal","Shigurui","Basilisk","Ninja Resurrection"],"correct":3,"hint":"Dark ninja OVA","level":5},
  {"id":447,"text":"🧠💀🌆","options":["Genocyber","MD Geist","Violence Jack","Cyber City Oedo 808"],"correct":0,"hint":"Brutal psychic cyberpunk","level":5},
  {"id":448,"text":"📖⚙️👧","options":["NieA Under 7","Haibane Renmei","Windy Tales","Yokohama Kaidashi Kikou"],"correct":0,"hint":"Poor alien roommate comedy","level":5},
  {"id":449,"text":"🧬🌌🧒","options":["Toward the Terra","Heroic Age","Fantastic Children","Noein"],"correct":0,"hint":"Psychic humans in space","level":5},
  {"id":450,"text":"🩸🎨👧","options":["Belladonna of Sadness","Angel's Egg","Perfect Blue","Vampire Hunter D"],"correct":0,"hint":"Experimental psychedelic film","level":5},
,
  {"id":451,"text":"🌀👁️🖥️","options":["Texhnolyze","Serial Experiments Lain","Ergo Proxy","Boogiepop Phantom"],"correct":3,"hint":"Phantom echo darkness","level":5},
  {"id":452,"text":"🏙️💀🌫️","options":["Casshern Sins","Texhnolyze","Blame!","Ergo Proxy"],"correct":1,"hint":"Underground city decay limbs","level":5},
  {"id":453,"text":"🌌🧬🔬","options":["Legend of Galactic Heroes","Toward the Terra","Terra Formars","Banner of Stars"],"correct":1,"hint":"Esper humans seek Terra","level":5},
  {"id":454,"text":"🎭🕸️🌙","options":["Witch Hunter Robin","Boogiepop Phantom","Paranoia Agent","Petite Cossette"],"correct":3,"hint":"Painting trapped girl ghost","level":5},
  {"id":455,"text":"🏚️🕯️📚","options":["Haibane Renmei","Angel Beats","Death Parade","Kino Journey"],"correct":0,"hint":"Wing halo walled town","level":5},
  {"id":456,"text":"🎵🌌💫","options":["Interstella 5555","Macross","Cowboy Bebop","Space Dandy"],"correct":0,"hint":"Daft Punk anime film","level":5},
  {"id":457,"text":"🐛🌿🔮","options":["Mushishi","Mononoke","Natsume","Kino Journey"],"correct":1,"hint":"Medicine seller painted spirits","level":5},
  {"id":458,"text":"🏙️🔫👤","options":["Phantom Requiem","Noir","Black Cat","Darker Than Black"],"correct":3,"hint":"Contractor star powers dark","level":5},
  {"id":459,"text":"🌊🏴‍☠️⚓","options":["One Piece","Bodacious Space Pirates","Future Boy Conan","Nadia Secret of Blue Water"],"correct":3,"hint":"Nemo submarine Atlantis girl","level":5},
  {"id":460,"text":"🎭🎪💀","options":["Shouwa Genroku Rakugo","Gintama","One Piece","Bakemonogatari"],"correct":0,"hint":"Traditional storytelling art death","level":5},
  {"id":461,"text":"🌙🦋👧","options":["Flip Flappers","Madoka Magica","Paprika","Lain"],"correct":0,"hint":"Pure illusion dimension girls","level":5},
  {"id":462,"text":"🏰⚙️🌍","options":["Last Exile","Laputa Castle in Sky","Steamboy","Howls Moving Castle"],"correct":0,"hint":"Vanship sky race exile","level":5},
  {"id":463,"text":"🎨🌀😱","options":["Uzumaki","Parasyte","Mononoke","Another"],"correct":0,"hint":"Spiral curse horror Junji","level":5},
  {"id":464,"text":"👧🌸💔","options":["Revolutionary Girl Utena","Rose of Versailles","Dear Brother","Oniisama e"],"correct":3,"hint":"Sorority drama sister letter","level":5},
  {"id":465,"text":"🏙️🦾🌃","options":["Ghost in Shell SAC","Psycho-Pass","Akudama Drive","Cyberpunk Edgerunners"],"correct":2,"hint":"Criminal ranked chaos city","level":5},
  {"id":466,"text":"🐟🌊👁️","options":["Gyo","Children of Sea","Blue Submarine","Ponyo"],"correct":0,"hint":"Walking fish Junji horror","level":5},
  {"id":467,"text":"🎭🖤🌹","options":["Le Chevalier DEon","Rose of Versailles","Revolutionary Girl Utena","Romeo x Juliet"],"correct":1,"hint":"French revolution lady Oscar","level":5},
  {"id":468,"text":"🌌🔭💫","options":["Space Brothers","Planetes","Stellvia","Twin Spica"],"correct":3,"hint":"Girl astronaut dream twin star","level":5},
  {"id":469,"text":"🌅⚔️😢","options":["Now and Then Here and There","Grave of Fireflies","Barefoot Gen","Future Boy Conan"],"correct":0,"hint":"Boy dragged brutal war world","level":5},
  {"id":470,"text":"🐈💀🌙","options":["Cat Soup","Bananya","Chi Sweet Home","My Roommate Cat"],"correct":0,"hint":"Surreal cat afterlife journey","level":5},
  {"id":471,"text":"🏔️🐐👧","options":["Heidi Girl of Alps","Wolf Children","Non Non Biyori","Silver Spoon"],"correct":0,"hint":"Swiss Alps grandfather girl","level":5},
  {"id":472,"text":"🎭🌊⛵","options":["Aria the Animation","Amanchu","Nagi no Asukara","Grand Blue"],"correct":0,"hint":"Neo Venezia gondolier peaceful","level":5},
  {"id":473,"text":"👻🎹🏫","options":["Angel Beats","Your Lie in April","Clannad","Little Busters"],"correct":0,"hint":"Afterlife school band rebellion","level":5},
  {"id":474,"text":"🦊🎎🏮","options":["Inari Kon Kon","Gingitsune","Kamisama Kiss","Kakuriyo"],"correct":1,"hint":"Silver fox shrine helper","level":5},
  {"id":475,"text":"🌸🗡️🐉","options":["Dragon Ball","Inuyasha","12 Kingdoms","Fushigi Yuugi"],"correct":2,"hint":"Girl becomes king other world","level":5},
  {"id":476,"text":"🏙️🐀🌃","options":["No. 6","Psycho-Pass","Ergo Proxy","Texhnolyze"],"correct":0,"hint":"Utopia city rat boy rebellion","level":5},
  {"id":477,"text":"🎵🎻🏫","options":["Sound Euphonium","Nodame Cantabile","Your Lie in April","La Corda dOro"],"correct":1,"hint":"Quirky piano girl conductor dream","level":5},
  {"id":478,"text":"🌺👧🏝️","options":["Nana","Paradise Kiss","Wandering Son","Kids on Slope"],"correct":1,"hint":"Fashion design Yazawa gorgeous","level":5},
  {"id":479,"text":"🐺🌙🏙️","options":["Wolf Guy","BNA Brand New Animal","Beastars","Inuyasha"],"correct":1,"hint":"Tanuki girl beast city","level":5},
  {"id":480,"text":"🧪🌍💥","options":["Dr. Stone","Planetes","Steamboy","Patema Inverted"],"correct":2,"hint":"Victorian steam invention boy","level":5},
  {"id":481,"text":"🎭🌙🦇","options":["Hellsing Ultimate","Vampire Hunter D Bloodlust","Blood+","Shiki"],"correct":1,"hint":"D bloodlust vampire hunter","level":5},
  {"id":482,"text":"🏫🧪😈","options":["Welcome to Demon School","Blue Exorcist","Beelzebub","Mairimashita Iruma-kun"],"correct":0,"hint":"Human boy demon school enrolled","level":5},
  {"id":483,"text":"🌸🎎✂️","options":["Rozen Maiden","Unbreakable Machine Doll","Angelic Layer","Busou Shinki"],"correct":0,"hint":"Living dolls n-field battle","level":5},
  {"id":484,"text":"🚂🌫️💀","options":["Night on Galactic Railroad","Galaxy Express","Spirited Away","Angels Egg"],"correct":0,"hint":"Kenji Miyazawa celestial train","level":5},
  {"id":485,"text":"🥚👼🏚️","options":["Angels Egg","Haibane Renmei","Casshern Sins","Texhnolyze"],"correct":0,"hint":"Oshii slow surreal egg girl","level":5},
  {"id":486,"text":"🎨🌀🧠","options":["Paprika","Perfect Blue","Paranoia Agent","Mind Game"],"correct":3,"hint":"Masaaki Yuasa wild animation","level":5},
  {"id":487,"text":"🌍🔫🏜️","options":["Desert Punk","Trigun","Fist of North Star","Casshern Sins"],"correct":3,"hint":"Post apocalypse robot sin","level":5},
  {"id":488,"text":"🎵💃🌙","options":["Kids on the Slope","Ballroom e Youkoso","Dance Dance Danseur","Welcome to Ballroom"],"correct":1,"hint":"Competitive ballroom dance passion","level":5},
  {"id":489,"text":"🏰👑🐺","options":["Scrapped Princess","Twelve Kingdoms","Moribito","Kemono no Souja Erin"],"correct":2,"hint":"Spear-wielding bodyguard prince","level":5},
  {"id":490,"text":"🌊🐢🌌","options":["Tsuritama","Ponyo","Aquarion","RahXephon"],"correct":3,"hint":"Mysterious singing time mecha","level":5},
  {"id":491,"text":"📖✨🧙‍♂️","options":["Ascendance of Bookworm","Grimgar","Mushoku Tensei","The Faraway Paladin"],"correct":3,"hint":"Undead raised paladin holy","level":5},
  {"id":492,"text":"🎭🌍⚔️","options":["Berserk","Claymore","Dorohedoro","Drifters"],"correct":3,"hint":"Historical figures isekai war","level":5},
  {"id":493,"text":"🏔️🐐🧒","options":["Kemono no Souja Erin","Moribito","Seirei no Moribito","Beast Player Erin"],"correct":0,"hint":"Beast handler girl kingdom","level":5},
  {"id":494,"text":"🌌🎭🕊️","options":["Haibane Renmei","Angel Beats","Sora no Woto","So Ra No Wo To"],"correct":3,"hint":"Military girls trumpet post-war","level":5},
  {"id":495,"text":"🐛🌿🌺","options":["Mushishi Zoku","Natsume Roku","Mushi-Shi Next","Mushishi Next Passage"],"correct":0,"hint":"Second season mushi continuation","level":5},
  {"id":496,"text":"🏙️🔫💀","options":["Gangsta","91 Days","Banana Fish","Noir"],"correct":2,"hint":"NYC gang ash lynx revenge","level":5},
  {"id":497,"text":"🌙🎭🖤","options":["Boogiepop Others","Paranoia Agent","Mononoke","Petite Cossette"],"correct":0,"hint":"Death personification school urban","level":5},
  {"id":498,"text":"🦋💀🌸","options":["Jigoku Shoujo","Hell Girl Mitsuganae","Hells Girl","Hell Girl Two Mirrors"],"correct":0,"hint":"Send them to hell flower","level":5},
  {"id":499,"text":"🏰🐉📜","options":["Record of Lodoss War","Slayers","Grancrest War","Rage of Bahamut"],"correct":0,"hint":"Classic fantasy RPG OVA","level":5},
  {"id":500,"text":"🌌🧬👽","options":["Toward the Terra","Space Runaway Ideon","Blue Gender","Infinite Ryvius"],"correct":1,"hint":"Legendary mecha total destruction","level":5}
];
