export default [
  {"id":21,"text":"🧥💀🔫","options":["Black Lagoon","Cowboy Bebop","Trigun","Gungrave"],"correct":1,"hint":"Space bounty hunters","level":3},
  {"id":22,"text":"🐺🌕⚔️","options":["Wolf's Rain","Princess Mononoke","InuYasha","Spice and Wolf"],"correct":2,"hint":"Half demon","level":3},
  {"id":23,"text":"🧠🪲👦","options":["Parasyte","Ajin","Tokyo Ghoul","Elfen Lied"],"correct":0,"hint":"Alien hand","level":3},
  {"id":24,"text":"👓📖🔥","options":["Bungou Stray Dogs","Blue Exorcist","Fire Force","D.Gray-man"],"correct":0,"hint":"Authors with powers","level":3},
  {"id":25,"text":"🪖⚙️🩸","options":["Attack on Titan","86","Code Geass","Gundam"],"correct":1,"hint":"War and discrimination","level":3},
  {"id":26,"text":"🎭👑🤖","options":["Guilty Crown","Code Geass","Evangelion","Aldnoah.Zero"],"correct":1,"hint":"Geass power","level":3},
  {"id":27,"text":"🎻🩸🌹","options":["Violet Evergarden","Black Butler","Rose of Versailles","Nana"],"correct":0,"hint":"Auto memory doll","level":3},
  {"id":28,"text":"👹🔵🔥","options":["Blue Exorcist","Bleach","Noragami","Devilman Crybaby"],"correct":0,"hint":"Satan's son","level":3},
  {"id":29,"text":"🛡️🦝📖","options":["Rising of the Shield Hero","Re:Zero","Konosuba","Overlord"],"correct":0,"hint":"Shield weapon","level":3},
  {"id":30,"text":"🎮💀🕹️","options":["No Game No Life","Sword Art Online","Overlord","Log Horizon"],"correct":1,"hint":"Trapped in VR game","level":3},
  {"id":71,"text":"🧊🔥❄️","options":["Fire Force","K Project","Katanagatari","K"],"correct":3,"hint":"Color kings","level":3},
  {"id":72,"text":"👁️🧠🤖","options":["Ghost in the Shell","Psycho-Pass","Ergo Proxy","Akudama Drive"],"correct":1,"hint":"Crime coefficient","level":3},
  {"id":73,"text":"⚔️🩸🐺","options":["Berserk","Claymore","Vinland Saga","Dororo"],"correct":1,"hint":"Half-monster warriors","level":3},
  {"id":74,"text":"🌌🚀😂","options":["Space Brothers","Space Dandy","Cowboy Bebop","Astra Lost in Space"],"correct":1,"hint":"Boobies restaurant","level":3},
  {"id":75,"text":"🧛⚔️🌙","options":["Vampire Hunter D","Hellsing","Trinity Blood","Blood+"],"correct":0,"hint":"Classic vampire hunter","level":3},
  {"id":76,"text":"🧒💥👻","options":["Mob Psycho 100","Noragami","Bleach","Blue Exorcist"],"correct":0,"hint":"Esper boy","level":3},
  {"id":77,"text":"🦾⚙️👬","options":["Fullmetal Alchemist","Soul Eater","Blue Exorcist","D.Gray-man"],"correct":0,"hint":"Equivalent exchange","level":3},
  {"id":78,"text":"🎭🗡️🇯🇵","options":["Rurouni Kenshin","Gintama","Samurai Champloo","Drifters"],"correct":1,"hint":"Comedy samurai","level":3},
  {"id":79,"text":"🚢⚔️🇻🇳","options":["Black Lagoon","Vinland Saga","Kingdom","Golden Kamuy"],"correct":1,"hint":"Vikings","level":3},
  {"id":80,"text":"🎮♟️👫","options":["Sword Art Online","No Game No Life","Log Horizon","Overlord"],"correct":1,"hint":"Sibling gamers","level":3},
  {"id":121,"text":"🎨🏓🔥","options":["Ping Pong the Animation","Blue Period","Run with the Wind","Bakuman"],"correct":0,"hint":"Unique art style","level":3},
  {"id":122,"text":"🧠👓📓","options":["Death Parade","Pet","ID: Invaded","Psycho-Pass"],"correct":2,"hint":"Detective mind worlds","level":3},
  {"id":123,"text":"⚔️🌸🩸","options":["Basilisk","Ninja Scroll","Samurai Deeper Kyo","Shigurui"],"correct":0,"hint":"Ninja clans","level":3},
  {"id":124,"text":"🚬🔫🌆","options":["Gangsta.","Black Lagoon","Banana Fish","Jormungand"],"correct":0,"hint":"Handymen mafia city","level":3},
  {"id":125,"text":"🧊🌌👧","options":["Plastic Memories","Vivy","Planetarian","Charlotte"],"correct":2,"hint":"Robot planetarium girl","level":3},
  {"id":126,"text":"🧛⚔️👑","options":["Trinity Blood","Vampire Hunter D","Castlevania","Hellsing"],"correct":0,"hint":"Priest vampire","level":3},
  {"id":127,"text":"🎮🃏⚔️","options":["Darwin's Game","Btooom!","Sword Art Online","C: The Money of Soul"],"correct":0,"hint":"Deadly mobile game","level":3},
  {"id":128,"text":"🐧🎩🌈","options":["Sarazanmai","Mawaru Penguindrum","Uramichi Oniisan","FLCL"],"correct":0,"hint":"Kappa transformation","level":3},
  {"id":129,"text":"🌑⚔️👹","options":["Dororo","Shiki","Blood-C","Ninja Scroll"],"correct":2,"hint":"Schoolgirl monster hunter","level":3},
  {"id":130,"text":"🚂☁️⚔️","options":["Last Exile","Kabaneri","Violet Evergarden","Princess Principal"],"correct":0,"hint":"Steampunk air battles","level":3},
  {"id":171,"text":"💰🧠⚔️","options":["Kaiji","One Outs","Akagi","Tomodachi Game"],"correct":1,"hint":"Psychological baseball","level":3},
  {"id":172,"text":"🎧🌆💛","options":["Durarara!!","Hamatora","Bungo Stray Dogs","K"],"correct":0,"hint":"Headless rider","level":3},
  {"id":173,"text":"👹📿⚔️","options":["Ushio and Tora","Nurarihyon no Mago","Blue Exorcist","GeGeGe no Kitaro"],"correct":0,"hint":"Spear beast duo","level":3},
  {"id":174,"text":"🚬💣🌍","options":["Jormungand","Black Lagoon","Gangsta.","Phantom: Requiem"],"correct":0,"hint":"Arms dealer crew","level":3},
  {"id":175,"text":"🎭👑🌹","options":["Revolutionary Girl Utena","Princess Tutu","Rose of Versailles","Glass Mask"],"correct":0,"hint":"Duel arena","level":3},
  {"id":176,"text":"⚔️👹🏯","options":["Ninja Scroll","Basilisk","Dororo","Samurai 7"],"correct":0,"hint":"Classic ninja movie","level":3},
  {"id":177,"text":"🧪⚡👧","options":["Wonder Egg Priority","Flip Flappers","Charlotte","Brynhildr in the Darkness"],"correct":3,"hint":"Escaped witches","level":3},
  {"id":178,"text":"🌌🚀🪖","options":["Legend of the Galactic Heroes","Space Battleship Yamato","Macross","Gundam"],"correct":0,"hint":"Galactic war politics","level":3},
  {"id":179,"text":"👨‍⚕️🧠🩸","options":["Black Jack","Monster","Young Black Jack","Parasyte"],"correct":0,"hint":"Unlicensed genius surgeon","level":3},
  {"id":180,"text":"🐺🔫🌕","options":["Wolf's Rain","Gungrave","Darker than Black","Ergo Proxy"],"correct":0,"hint":"Paradise flowers","level":3},
  {"id":221,"text":"🧠🪐👧","options":["Noein","Dennou Coil","Flip Flappers","Sonny Boy"],"correct":2,"hint":"Surreal magical dimensions","level":3},
  {"id":222,"text":"⚔️🩸🧛","options":["Blood+","Hellsing","Shiki","Vampire Hunter D"],"correct":0,"hint":"Saya and chiropterans","level":3},
  {"id":223,"text":"🚬🕶️🔫","options":["Black Lagoon","Gangsta.","Jormungand","Banana Fish"],"correct":0,"hint":"Lagoon Company","level":3},
  {"id":224,"text":"🧠🎲💰","options":["Kaiji","Akagi","One Outs","Kakegurui"],"correct":1,"hint":"Mahjong genius","level":3},
  {"id":225,"text":"🛸🎸👧","options":["FLCL","Beck","Bocchi the Rock!","Space Dandy"],"correct":0,"hint":"Vespa and guitars","level":3},
  {"id":226,"text":"⚔️🌌👹","options":["Blue Exorcist","Noragami","Kekkai Sensen","D.Gray-man"],"correct":2,"hint":"Chaos New York","level":3},
  {"id":227,"text":"🧬👦⚡","options":["Ajin","Parasyte","Inuyashiki","Elfen Lied"],"correct":0,"hint":"Immortal humans","level":3},
  {"id":228,"text":"🎭📚👦","options":["The Tatami Galaxy","Welcome to the NHK","Blue Period","Bakuman"],"correct":1,"hint":"Hikikomori life","level":3},
  {"id":229,"text":"⚔️🧛🚂","options":["Kabaneri of the Iron Fortress","Vampire Hunter D","Hellsing","Seraph of the End"],"correct":0,"hint":"Steam zombie train","level":3},
  {"id":230,"text":"🌊🧒📖","options":["Barakamon","Tsuritama","Natsume's Book of Friends","Mushishi"],"correct":2,"hint":"Yokai names book","level":3},
,
  {"id":151,"text":"🎸🏍️💀","options":["FLCL","Akira","Redline","Promare"],"correct":0,"hint":"Guitar robot forehead","level":3},
  {"id":152,"text":"🧊🐧🌊","options":["A Place Further Than Universe","Penguin Highway","March Comes Like Lion","Odd Taxi"],"correct":0,"hint":"Antarctic girls journey","level":3},
  {"id":153,"text":"🦊🎶🌾","options":["Spice and Wolf","Kamisama Kiss","The Helpful Fox Senko","Natsume Book of Friends"],"correct":3,"hint":"Spirit name returning","level":3},
  {"id":154,"text":"🔫🚬🌕","options":["Cowboy Bebop","Black Lagoon","Trigun","Jormungand"],"correct":1,"hint":"Pirate mercenary crew","level":3},
  {"id":155,"text":"🕸️🧠💉","options":["Parasyte","Tokyo Ghoul","Ajin","Terra Formars"],"correct":0,"hint":"Right hand alien creature","level":3},
  {"id":156,"text":"🎰💀🃏","options":["Kaiji","Kakegurui","No Game No Life","Death Parade"],"correct":0,"hint":"Desperate gambler tears","level":3},
  {"id":157,"text":"🌌🛰️🗑️","options":["Planetes","Space Brothers","Dr. Stone","Astra Lost in Space"],"correct":0,"hint":"Space debris collectors","level":3},
  {"id":158,"text":"📿⛪🔫","options":["Trigun","Hellsing","Blue Exorcist","D.Gray-man"],"correct":0,"hint":"Love and peace gunman","level":3},
  {"id":159,"text":"🦑🎮🧒","options":["Splatoon","Squid Girl","No Game No Life","Assassination Classroom"],"correct":1,"hint":"Invading squid girl","level":3},
  {"id":160,"text":"📖🐛🧔","options":["Mushishi","Kino Journey","Natsume Book","Mononoke"],"correct":0,"hint":"Mushi master traveler","level":3},
  {"id":161,"text":"🏚️👁️🕯️","options":["Mononoke","Mushishi","Xxxholic","Ghost Hunt"],"correct":0,"hint":"Medicine seller spirits","level":3},
  {"id":162,"text":"🎎👘🌸","options":["Xxxholic","Natsume Book","Bungo Stray Dogs","The Eccentric Family"],"correct":3,"hint":"Tanuki family Kyoto","level":3},
  {"id":163,"text":"🌙🐈‍⬛🧹","options":["Soul Eater","Black Cat","Kiki Delivery","The Witch from Mercury"],"correct":0,"hint":"Death weapon meister","level":3},
  {"id":164,"text":"🎪🎭🔪","options":["Black Butler","Moriarty the Patriot","Vanitas no Carte","Bungou Stray Dogs"],"correct":3,"hint":"Literary power detectives","level":3},
  {"id":165,"text":"🐝🌺🦋","options":["Land of the Lustrous","Mushishi","Girl Last Tour","Made in Abyss"],"correct":0,"hint":"Gem beings fighting moon","level":3},
  {"id":166,"text":"🏙️🚗🔫","options":["Durarara","Baccano","Banana Fish","91 Days"],"correct":0,"hint":"Ikebukuro headless rider","level":3},
  {"id":167,"text":"🎻🩰🦢","options":["Princess Tutu","Yuri on Ice","Your Lie in April","Carole and Tuesday"],"correct":0,"hint":"Duck becomes ballerina","level":3},
  {"id":168,"text":"🧸🏠👻","options":["Another","Shiki","Ghost Hound","Higurashi"],"correct":2,"hint":"Brain science spirits","level":3},
  {"id":169,"text":"🌊🔱👑","options":["Free!","Aria","Amanchu","Nagi no Asukara"],"correct":3,"hint":"Sea village surface world","level":3},
  {"id":170,"text":"📦📮👧","options":["Violet Evergarden","March Comes Like Lion","A Silent Voice","Josee Tiger Fish"],"correct":0,"hint":"Letter writing soldier girl","level":3},
  {"id":171,"text":"🤖🌐💀","options":["Ghost in the Shell","Psycho-Pass","Ergo Proxy","Vivy"],"correct":0,"hint":"Cyborg major Section 9","level":3},
  {"id":172,"text":"🎲⚔️🏰","options":["No Game No Life","Log Horizon","Overlord","Danmachi"],"correct":0,"hint":"Sibling gamers isekai","level":3},
  {"id":173,"text":"🐕🔫🚀","options":["Cowboy Bebop","Trigun","Outlaw Star","Space Dandy"],"correct":0,"hint":"See you space cowboy","level":3},
  {"id":174,"text":"🍄🌳🧒","options":["My Neighbor Totoro","Mushishi","Ponyo","Spirited Away"],"correct":0,"hint":"Forest spirit umbrella","level":3},
  {"id":175,"text":"🦑🌊👧","options":["Made in Abyss","Ponyo","Children of Sea","Land of Lustrous"],"correct":0,"hint":"Abyss cave descent girl","level":3},
  {"id":176,"text":"🎪🐻🏴‍☠️","options":["One Piece","Fairy Tail","Golden Kamuy","Shaman King"],"correct":3,"hint":"Spirit medium tournament","level":3},
  {"id":177,"text":"🏙️🌃🦇","options":["Durarara","Blood+","Hellsing","Blood Blockade Battlefront"],"correct":3,"hint":"NYC barrier supernatural","level":3},
  {"id":178,"text":"⚗️📜✨","options":["Fullmetal Alchemist","Dr. Stone","Ascendance of Bookworm","Atelier Ryza"],"correct":2,"hint":"Reborn book lover girl","level":3},
  {"id":179,"text":"🎵🌍🚀","options":["Macross","Cowboy Bebop","Carole and Tuesday","Interstella 5555"],"correct":2,"hint":"Mars music duo girls","level":3},
  {"id":180,"text":"🏔️⛏️🧒","options":["Made in Abyss","Dr. Stone","Promised Neverland","From the New World"],"correct":0,"hint":"Curse of the abyss","level":3},
  {"id":181,"text":"👩‍🦰🔪🏫","options":["Mirai Nikki","Happy Sugar Life","Higurashi","School Days"],"correct":1,"hint":"Yandere happy obsession","level":3},
  {"id":182,"text":"🌸⚡🐱","options":["A Certain Magical Index","Shakugan no Shana","Toradora","Fate/Stay Night"],"correct":1,"hint":"Flame-haired flame haze","level":3},
  {"id":183,"text":"🏴‍☠️🦜🗡️","options":["One Piece","Black Lagoon","Bodacious Space Pirates","Vinland Saga"],"correct":2,"hint":"High school girl pirate","level":3},
  {"id":184,"text":"🐉👧🏔️","options":["Dragon Maid","Fairy Tail","Dragonaut","Dragon Drive"],"correct":0,"hint":"Dragon maid comedy","level":3},
  {"id":185,"text":"🌌👨‍🚀🛸","options":["Space Brothers","Planetes","Legend of Galactic Heroes","Astra Lost in Space"],"correct":0,"hint":"Brothers astronaut dream","level":3},
  {"id":186,"text":"🔥⚽👿","options":["Blue Lock","Inazuma Eleven","Captain Tsubasa","Ao Ashi"],"correct":1,"hint":"Super powered soccer","level":3},
  {"id":187,"text":"🏯⚔️🐍","options":["Basilisk","Ninja Scroll","Naruto","Dororo"],"correct":0,"hint":"Ninja clan deadly battle","level":3},
  {"id":188,"text":"🧟‍♂️🏫🩸","options":["High School of the Dead","School-Live","Zombie Land Saga","Gakkou Gurashi"],"correct":0,"hint":"Zombie school survival","level":3},
  {"id":189,"text":"🎭🌹💀","options":["Requiem of the Rose King","Moriarty Patriot","Vanitas no Carte","Black Butler"],"correct":2,"hint":"Vampire grimoire blue moon","level":3},
  {"id":190,"text":"🐈🐟🏠","options":["My Roommate is a Cat","Bananya","Chi Sweet Home","She and Her Cat"],"correct":0,"hint":"Author adopts stray cat","level":3},
  {"id":191,"text":"👸🗡️🌹","options":["Revolutionary Girl Utena","Rose of Versailles","Yona of the Dawn","Claymore"],"correct":0,"hint":"Duel for rose bride","level":3},
  {"id":192,"text":"🏎️💨🏁","options":["Initial D","Redline","MF Ghost","Appare-Ranman"],"correct":1,"hint":"Insane race animation","level":3},
  {"id":193,"text":"💊🧪🩺","options":["Monster","Black Jack","Dr. Stone","Cells at Work"],"correct":1,"hint":"Unlicensed genius surgeon","level":3},
  {"id":194,"text":"🌙🐇✨","options":["Sailor Moon","Tsuki ga Kirei","Bunny Girl Senpai","Puella Magi Madoka"],"correct":2,"hint":"Adolescence syndrome bunny","level":3},
  {"id":195,"text":"🎓👔🧠","options":["Classroom of Elite","Great Teacher Onizuka","Assassination Classroom","Food Wars"],"correct":1,"hint":"Delinquent becomes teacher","level":3},
  {"id":196,"text":"🐀🍳🇫🇷","options":["Yakitate Japan","Food Wars","Isekai Izakaya","Restaurant to Another World"],"correct":3,"hint":"Fantasy customers Japanese bar","level":3},
  {"id":197,"text":"🪐⚔️🏴","options":["Legend of Galactic Heroes","Space Battleship Yamato","Gundam","Captain Harlock"],"correct":3,"hint":"Space pirate skull flag","level":3},
  {"id":198,"text":"🎺🎶🌙","options":["Kids on the Slope","Your Lie in April","Sound Euphonium","Beck"],"correct":2,"hint":"Band competition concert","level":3},
  {"id":199,"text":"🕷️🧵👧","options":["Kumo desu ga","Land of Lustrous","Spider Riders","So Im a Spider"],"correct":3,"hint":"Reborn as spider dungeon","level":3},
  {"id":200,"text":"🐺❄️🌲","options":["Wolf Children","Wolfs Rain","Spice and Wolf","Silver Fang"],"correct":0,"hint":"Mother raises wolf kids","level":3}
];
