export default [
  {"id":11,"text":"🪚🩸🐶","options":["Chainsaw Man","Tokyo Ghoul","Parasyte","Ajin"],"correct":0,"hint":"Devil hunter","level":2},
  {"id":12,"text":"👁️‍🗨️👹🤌","options":["Naruto","Jujutsu Kaisen","Bleach","Noragami"],"correct":1,"hint":"Cursed energy","level":2},
  {"id":13,"text":"☠️⚔️🌸","options":["Bleach","Samurai Champloo","Dororo","Rurouni Kenshin"],"correct":0,"hint":"Bankai","level":2},
  {"id":14,"text":"🧣⚔️👹","options":["Attack on Titan","Vinland Saga","Claymore","Berserk"],"correct":0,"hint":"Titans outside walls","level":2},
  {"id":15,"text":"🦌⚕️🏴‍☠️","options":["Fairy Tail","One Piece","Naruto","Black Clover"],"correct":1,"hint":"Doctor reindeer","level":2},
  {"id":16,"text":"🧪⚡🧠","options":["Dr. Stone","Steins;Gate","Psycho-Pass","Erased"],"correct":0,"hint":"Science kingdom","level":2},
  {"id":17,"text":"👊🥊📚","options":["Hajime no Ippo","Baki","Kengan Ashura","Megalo Box"],"correct":0,"hint":"Boxing anime","level":2},
  {"id":18,"text":"🎹🎻😭","options":["Your Lie in April","Clannad","Angel Beats","Violet Evergarden"],"correct":0,"hint":"Music and heartbreak","level":2},
  {"id":19,"text":"👺🌊⚔️","options":["Demon Slayer","Bleach","Dororo","Blue Exorcist"],"correct":0,"hint":"Water breathing","level":2},
  {"id":20,"text":"🕰️📱🔬","options":["Dr. Stone","Steins;Gate","Re:Zero","Erased"],"correct":1,"hint":"Time travel microwave","level":2},
  {"id":61,"text":"👻📷👧","options":["Another","Ghost Hunt","Dark Gathering","Mieruko-chan"],"correct":3,"hint":"She sees ghosts","level":2},
  {"id":62,"text":"💀🎻🌌","options":["Your Lie in April","Angel Beats","Plastic Memories","Vivy"],"correct":1,"hint":"Afterlife school","level":2},
  {"id":63,"text":"🪓👹⚫","options":["Black Butler","Dorohedoro","Tokyo Ghoul","Ajin"],"correct":1,"hint":"Lizard-headed man","level":2},
  {"id":64,"text":"🧠📖👦","options":["Bakuman","Death Note","Classroom of the Elite","Tomodachi Game"],"correct":0,"hint":"Manga creators","level":2},
  {"id":65,"text":"⚔️🐺👸","options":["Princess Mononoke","InuYasha","Wolf Children","Dororo"],"correct":0,"hint":"Studio Ghibli forest","level":2},
  {"id":66,"text":"👑💚🍀","options":["Black Clover","Magi","Seven Deadly Sins","Fairy Tail"],"correct":0,"hint":"No magic boy","level":2},
  {"id":67,"text":"🩸👁️📱","options":["Future Diary","Another","Darwin's Game","King's Game"],"correct":0,"hint":"Survival diary game","level":2},
  {"id":68,"text":"🔥🚒👨‍🚒","options":["Fire Force","Soul Eater","Blue Exorcist","Enen no Shouboutai"],"correct":0,"hint":"Human combustion","level":2},
  {"id":69,"text":"🐍⚔️🌸","options":["Basilisk","Naruto","Samurai Deeper Kyo","Hell's Paradise"],"correct":3,"hint":"Criminals on island","level":2},
  {"id":70,"text":"🏹⚡🕷️","options":["Hunter x Hunter","Naruto","Bleach","Jujutsu Kaisen"],"correct":0,"hint":"Phantom Troupe","level":2},
  {"id":111,"text":"🗡️⚡👹","options":["Noragami","Blue Exorcist","Seraph of the End","Bleach"],"correct":0,"hint":"Delivery god","level":2},
  {"id":112,"text":"🐻⚖️🏫","options":["Assassination Classroom","Danganronpa","Classroom of the Elite","Tomodachi Game"],"correct":1,"hint":"Killing game bear","level":2},
  {"id":113,"text":"👑♟️🧠","options":["No Game No Life","Code Geass","Classroom of the Elite","Death Note"],"correct":2,"hint":"Ayanokoji","level":2},
  {"id":114,"text":"🚴💨🏆","options":["Initial D","Yowamushi Pedal","Run with the Wind","Capeta"],"correct":1,"hint":"Cycling anime","level":2},
  {"id":115,"text":"🐟🍣✋","options":["Food Wars","Barakamon","Tsuritama","Campfire Cooking"],"correct":2,"hint":"Fishing aliens","level":2},
  {"id":116,"text":"🎹🎼🌙","options":["Nodame Cantabile","Your Lie in April","Blue Orchestra","Hibike Euphonium"],"correct":0,"hint":"Classical music romance","level":2},
  {"id":117,"text":"⚔️👁️🔥","options":["Blue Exorcist","D.Gray-man","Fire Force","Soul Eater"],"correct":1,"hint":"Akuma exorcists","level":2},
  {"id":118,"text":"🐻🍯👧","options":["Kuma Kuma Kuma Bear","Non Non Biyori","Yuru Camp","Sweetness and Lightning"],"correct":0,"hint":"OP bear suit","level":2},
  {"id":119,"text":"🛡️⚔️👑","options":["Record of Grancrest War","Arslan Senki","Kingdom","Drifters"],"correct":1,"hint":"Young prince","level":2},
  {"id":120,"text":"🧟🎤🎶","options":["Love Live!","Oshi no Ko","Zombie Land Saga","Bocchi the Rock!"],"correct":2,"hint":"Zombie idols","level":2},
  {"id":161,"text":"👹📖🔥","options":["Blue Exorcist","Ao no Exorcist","D.Gray-man","Soul Eater"],"correct":1,"hint":"Satan's son twins","level":2},
  {"id":162,"text":"🧑‍🍳🔪😋","options":["Toriko","Food Wars","Yakitate!! Japan","Restaurant to Another World"],"correct":1,"hint":"Explosive reactions","level":2},
  {"id":163,"text":"🎮👑💀","options":["Overlord","Sword Art Online","Log Horizon","No Game No Life"],"correct":0,"hint":"Skeleton king","level":2},
  {"id":164,"text":"🦊💰🍜","options":["Spice and Wolf","InuYasha","Konohana Kitan","Helpful Fox Senko-san"],"correct":0,"hint":"Wise wolf merchant","level":2},
  {"id":165,"text":"👨‍🏫🔫🐙","options":["Assassination Classroom","Great Teacher Onizuka","Classroom of the Elite","Danganronpa"],"correct":0,"hint":"Yellow tentacle teacher","level":2},
  {"id":166,"text":"⚽👦🔥","options":["Captain Tsubasa","Blue Lock","Inazuma Eleven","Ao Ashi"],"correct":2,"hint":"Special soccer moves","level":2},
  {"id":167,"text":"🛸👧⚡","options":["Urusei Yatsura","To Love Ru","Darling in the Franxx","Lum the Invader Girl"],"correct":0,"hint":"Alien oni girl","level":2},
  {"id":168,"text":"🏹👸🌲","options":["Yona of the Dawn","Snow White with the Red Hair","Princess Mononoke","Fushigi Yuugi"],"correct":0,"hint":"Red-haired princess","level":2},
  {"id":169,"text":"🎤🎸👧","options":["K-On!","Bocchi the Rock!","Beck","Nana"],"correct":0,"hint":"Light music club","level":2},
  {"id":170,"text":"🐉⚔️🩸","options":["Dororo","Rage of Bahamut","Record of Lodoss War","Claymore"],"correct":1,"hint":"Fantasy card game adaptation","level":2},
  {"id":211,"text":"🩸📱🎮","options":["Darwin's Game","Mirai Nikki","Tomodachi Game","King's Game"],"correct":0,"hint":"Smartphone death battles","level":2},
  {"id":212,"text":"🧑‍⚕️💀⚔️","options":["Black Jack","Dororo","Drifters","Hellsing"],"correct":1,"hint":"Body parts stolen by demons","level":2},
  {"id":213,"text":"🏰👑⚔️","options":["Kingdom","Arslan Senki","Vinland Saga","Berserk"],"correct":0,"hint":"Ancient China war","level":2},
  {"id":214,"text":"🎤👻🎸","options":["Angel Beats","Nana","Beck","K-On!"],"correct":0,"hint":"Afterlife band","level":2},
  {"id":215,"text":"⚡🧲👧","options":["A Certain Scientific Railgun","Charlotte","Wonder Egg Priority","Lycoris Recoil"],"correct":0,"hint":"Electromaster girl","level":2},
  {"id":216,"text":"🐺🍎💰","options":["Spice and Wolf","Wolf Children","Beastars","Ookami Kakushi"],"correct":0,"hint":"Merchant journey","level":2},
  {"id":217,"text":"🎮🧙‍♂️💀","options":["Overlord","Log Horizon","SAO","Grimgar"],"correct":0,"hint":"MMORPG undead ruler","level":2},
  {"id":218,"text":"🧛👑🩸","options":["Seraph of the End","Trinity Blood","Hellsing","Vampire Knight"],"correct":0,"hint":"Vampire military","level":2},
  {"id":219,"text":"🪖🤖🌍","options":["Gundam","Code Geass","86","Aldnoah.Zero"],"correct":2,"hint":"Juggernaut mechs","level":2},
  {"id":220,"text":"🎭⚔️🌹","options":["Rose of Versailles","Revolutionary Girl Utena","Princess Tutu","Glass Mask"],"correct":0,"hint":"French Revolution drama","level":2},
];
