export default [
  { text: "ANUROT", answer: "NARUTO", hint: "Future Hokage of the Leaf" },
  { text: "YFFUL", answer: "LUFFY", hint: "Straw Hat captain" },
  { text: "OROZ", answer: "ZORO", hint: "Three sword style user" },
  { text: "KUGO", answer: "GOKU", hint: "Famous Saiyan warrior" },
  { text: "IEVL", answer: "LEVI", hint: "Humanity's strongest soldier" },
  { text: "OGJO", answer: "GOJO", hint: "Strongest Jujutsu sorcerer" },
  { text: "EUKED", answer: "DEKU", hint: "Hero student with One For All" },
  { text: "RNEE", answer: "EREN", hint: "Titan shifter seeking freedom" },
  { text: "MAIN", answer: "NAMI", hint: "Navigator of the Straw Hats" },
  { text: "ARAAG", answer: "GAARA", hint: "Sand user from Naruto" },
  { text: "AEKSUSS", answer: "SASUKE", hint: "Naruto’s rival" },
  { text: "IAKHTAC", answer: "ITACHI", hint: "Uchiha clan prodigy" },
  { text: "KIHASAK", answer: "KAKASHI", hint: "Copy Ninja of the Leaf" },
  { text: "YIRAJAI", answer: "JIRAIYA", hint: "Legendary sannin mentor" },
  { text: "UTSNEDA", answer: "TSUNADE", hint: "Fifth Hokage healer" },
  { text: "AACTHIH", answer: "HINATA", hint: "Byakugan princess" },
  { text: "LKLIAUL", answer: "KILLUA", hint: "Assassin from Hunter x Hunter" },
  { text: "NGO", answer: "GON", hint: "Young Hunter protagonist" },
  { text: "ORJTIAN", answer: "TANJIRO", hint: "Demon Slayer swordsman" },
  { text: "KNEZUO", answer: "NEZUKO", hint: "Demon girl in a box" },
  { text: "KSIONUE", answer: "INOSUKE", hint: "Boar mask Demon Slayer" },
  { text: "UZNIETS", answer: "ZENITSU", hint: "Thunder breathing coward" },
  { text: "KGOBAU", answer: "BAKUGO", hint: "Explosion quirk rival" },
  { text: "RTOODKIO", answer: "TODOROKI", hint: "Half fire half ice hero" },
  { text: "AIZWAA", answer: "AIZAWA", hint: "Teacher who erases quirks" },
  { text: "TLALMHGI", answer: "ALL MIGHT", hint: "Symbol of Peace hero" },
  { text: "ERM", answer: "REM", hint: "Blue-haired maid from Re:Zero" },
  { text: "MRA", answer: "RAM", hint: "Pink-haired twin maid" },
  { text: "IAEMLI", answer: "EMILIA", hint: "Silver-haired half elf" },
  { text: "BRSUAU", answer: "SUBARU", hint: "Returns by death" },
  { text: "OIKGTNI", answer: "GINTOKI", hint: "Silver-haired samurai" },
  { text: "ICIHGO", answer: "ICHIGO", hint: "Orange-haired Soul Reaper" },
  { text: "AKIRU", answer: "RUKIA", hint: "Female Soul Reaper captain" },
  { text: "NAEZI", answer: "AIZEN", hint: "Mastermind villain from Bleach" },
  { text: "DAARMA", answer: "MADARA", hint: "Legendary Uchiha warrior" },
  { text: "OBTIO", answer: "OBITO", hint: "Masked Akatsuki member" },
  { text: "EAC", answer: "ACE", hint: "Fire fist pirate brother" },
  { text: "OABS", answer: "SABO", hint: "Revolutionary chief of staff" },
  { text: "KHANSS", answer: "SHANKS", hint: "Red-haired Yonko captain" },
  { text: "OPPUS", answer: "USOPP", hint: "Straw Hat sniper liar" },
  { text: "KOOBR", answer: "BROOK", hint: "Skeleton musician pirate" },
  { text: "PREPHOC", answer: "CHOPPER", hint: "Reindeer doctor pirate" },
  { text: "NKRFYA", answer: "FRANKY", hint: "Cyborg Straw Hat shipwright" },
  { text: "NIBRO", answer: "ROBIN", hint: "Archaeologist Straw Hat member" },
  { text: "JNISA", answer: "SANJI", hint: "Kicking cook pirate" },
  { text: "VTAEGE", answer: "VEGETA", hint: "Prince of Saiyans" },
  { text: "OCOLPIC", answer: "PICCOLO", hint: "Green Namekian warrior" },
  { text: "ILKRLIN", answer: "KRILLIN", hint: "Goku’s bald best friend" },
  { text: "MABUL", answer: "BULMA", hint: "Genius Capsule Corp inventor" },
  { text: "KCOHNAH DBOA", answer: "BOA HANCOCK", hint: "Pirate empress in love with Luffy" },
  { text: "ETRUM", answer: "MERUEM", hint: "Chimera Ant King" }
];