export default [
  { text: "AQAU HSOHINO", answer: "AQUA HOSHINO", hint: "Son of Ai Hoshino" },
  { text: "YBRU HSOHINO", answer: "RUBY HOSHINO", hint: "Idol fan reincarnated girl" },
  { text: "NAKA AMIAR", answer: "KANA ARIMA", hint: "Former child actress" },
  { text: "EAKAN KUROKAWA", answer: "AKANE KUROKAWA", hint: "Genius actress and analyst" },
  { text: "HMEMOC", answer: "MEMCHO", hint: "Streamer idol girl" },
  { text: "HHACIMAN HIGIKAYA", answer: "HACHIMAN HIKIGAYA", hint: "Cynical high school boy" },
  { text: "NIKUYNO YUKINOSHITA", answer: "YUKINO YUKINOSHITA", hint: "Ice queen student" },
  { text: "UYI YUIGAHAMA", answer: "YUI YUIGAHAMA", hint: "Cheerful club member" },
  { text: "KCOAHMI HIKIGAYA", answer: "KOMACHI HIKIGAYA", hint: "Little sister with brocon energy" },
  { text: "OKEIR HOUTAROU", answer: "OREKI HOUTAROU", hint: "Energy-saving detective boy" },
  { text: "DCHITANA ERU", answer: "CHITANDA ERU", hint: "Curious rich girl" },
  { text: "OTTHISSA FUKUBE", answer: "SATOSHI FUKUBE", hint: "Database boy from Hyouka" },
  { text: "AAMYKA IBARA", answer: "MAYAKA IBARA", hint: "Manga-loving schoolgirl" },
  { text: "YOATMO OKAZAKI", answer: "TOMOYA OKAZAKI", hint: "Delinquent from Clannad" },
  { text: "SAGNIA FURUKAWA", answer: "NAGISA FURUKAWA", hint: "Weak but kind heroine" },
  { text: "MIKOTO ICHINOSE", answer: "KOTOMI ICHINOSE", hint: "Violin genius girl" },
  { text: "MOYTOO SAKAGAMI", answer: "TOMOYO SAKAGAMI", hint: "Strong student council girl" },
  { text: "UKFO IBUKI", answer: "FUKO IBUKI", hint: "Starfish-loving ghost girl" },
  { text: "HSUOIO OKAZAKI", answer: "USHIO OKAZAKI", hint: "Daughter from Clannad After Story" },
  { text: "EOKEB RINTAROU", answer: "OKABE RINTAROU", hint: "Mad scientist Hououin Kyouma" },
  { text: "ARUD", answer: "DARU", hint: "Hacker otaku friend" },
  { text: "YRMIAU SHIINA", answer: "MAYURI SHIINA", hint: "Tuturu girl" },
  { text: "AFRIS NYANNYAN", answer: "FARIS NYANNYAN", hint: "Cat maid café girl" },
  { text: "UAZSUH AMANE", answer: "SUZUHA AMANE", hint: "Time traveler cyclist" },
  { text: "EOKMA KIRYU", answer: "MOEKA KIRYU", hint: "Silent phone-loving girl" },
  { text: "TIKIRSGUU EMIYA", answer: "KIRITSUGU EMIYA", hint: "Mage killer father" },
  { text: "EKRII KOTOMINE", answer: "KIREI KOTOMINE", hint: "Priest from Fate series" },
  { text: "GHAESMLIG", answer: "GILGAMESH", hint: "King of Heroes" },
  { text: "RBESA", answer: "SABER", hint: "Blonde knight servant" },
  { text: "INR TOHSAKA", answer: "RIN TOHSAKA", hint: "Twin-tail mage girl" },
  { text: "RHACRE", answer: "ARCHER", hint: "Red servant with dual blades" },
  { text: "YLLASVEIL", answer: "ILLYASVIEL", hint: "White-haired magical girl" },
  { text: "RUOSHI EMIYA", answer: "SHIROU EMIYA", hint: "Hero of justice boy" },
  { text: "HSNIJI IKARI", answer: "SHINJI IKARI", hint: "Eva pilot with daddy issues" },
  { text: "SAUKA LANGLEY", answer: "ASUKA LANGLEY", hint: "Red-haired Eva pilot" },
  { text: "IER AYANAMI", answer: "REI AYANAMI", hint: "Quiet blue-haired pilot" },
  { text: "RKUOAW NAGISA", answer: "KAWORU NAGISA", hint: "Angelic piano boy" },
  { text: "TAOSMI KATSURAGI", answer: "MISATO KATSURAGI", hint: "Beer-loving guardian" },
  { text: "DOGEN IKARI", answer: "GENDO IKARI", hint: "Commander of NERV" },
  { text: "UYJI ITADORI", answer: "YUJI ITADORI", hint: "Vessel of Sukuna" },
  { text: "UMGEMI FUSHIGURO", answer: "MEGUMI FUSHIGURO", hint: "Ten Shadows user" },
  { text: "BRNOAA KUGISAKI", answer: "NOBARA KUGISAKI", hint: "Hammer and nails sorcerer" },
  { text: "OYROZU", answer: "YOROZU", hint: "Ancient sorcerer woman" },
  { text: "MUREUA", answer: "URAUME", hint: "Sukuna loyalist" },
  { text: "OCSHO", answer: "CHOSO", hint: "Blood manipulation brother" },
  { text: "OJGO", answer: "JOGO", hint: "Volcano-headed curse" },
  { text: "MHNAIA", answer: "HANAMI", hint: "Nature curse spirit" },
  { text: "OGADN", answer: "DAGON", hint: "Ocean curse spirit" },
  { text: "KUYI TSUKUMO", answer: "YUKI TSUKUMO", hint: "Special grade sorcerer woman" },
  { text: "EMI EMI", answer: "MEI MEI", hint: "Crow-controlling sorcerer" }
];