// 500+ Anime Character Birthdays
const CHARACTER_BIRTHDAYS = [
  // JANUARY
  { name: "Sukuna", anime: "Jujutsu Kaisen", month: 1, day: 1 },
  { name: "Portgas D. Ace", anime: "One Piece", month: 1, day: 1 },
  { name: "Trafalgar Law", anime: "One Piece", month: 1, day: 2 },
  { name: "Senku Ishigami", anime: "Dr. Stone", month: 1, day: 4 },
  { name: "Shikamaru Nara", anime: "Naruto", month: 1, day: 5 },
  { name: "Rukia Kuchiki", anime: "Bleach", month: 1, day: 14 },
  { name: "Roronoa Zoro", anime: "One Piece", month: 1, day: 11 },
  { name: "Todoroki Shoto", anime: "My Hero Academia", month: 1, day: 11 },
  { name: "Boa Hancock", anime: "One Piece", month: 1, day: 15 },
  { name: "Gaara", anime: "Naruto", month: 1, day: 19 },
  { name: "Hisoka Morow", anime: "Hunter x Hunter", month: 1, day: 6 },
  { name: "Grimmjow Jaegerjaquez", anime: "Bleach", month: 1, day: 31 },
  { name: "Kaguya Shinomiya", anime: "Kaguya-sama", month: 1, day: 1 },
  { name: "Koro-sensei", anime: "Assassination Classroom", month: 1, day: 1 },
  { name: "Tobio Kageyama", anime: "Haikyuu!!", month: 1, day: 22 },
  { name: "Sinon (Shino Asada)", anime: "Sword Art Online", month: 1, day: 21 },
  { name: "Rin Okumura", anime: "Blue Exorcist", month: 1, day: 27 },
  { name: "Yukio Okumura", anime: "Blue Exorcist", month: 1, day: 27 },
  { name: "Ging Freecss", anime: "Hunter x Hunter", month: 1, day: 5 },
  { name: "Minato Namikaze", anime: "Naruto", month: 1, day: 25 },
  { name: "Saber (Artoria)", anime: "Fate/Stay Night", month: 1, day: 2 },
  { name: "Mashiro Shiina", anime: "Sakurasou", month: 1, day: 6 },
  { name: "Mirajane Strauss", anime: "Fairy Tail", month: 1, day: 3 },
  { name: "Jellal Fernandes", anime: "Fairy Tail", month: 1, day: 29 },
  { name: "Shoyo Hinata", anime: "Haikyuu!!", month: 1, day: 21 },

  { name: "Mitsuki", anime: "Boruto", month: 1, day: 25 },
  { name: "Ryuk", anime: "Death Note", month: 1, day: 11 },
  { name: "Dabi (Toya Todoroki)", anime: "My Hero Academia", month: 1, day: 18 },
  { name: "Aoi Todo", anime: "Jujutsu Kaisen", month: 1, day: 10 },
  { name: "Kyojuro Rengoku", anime: "Demon Slayer", month: 1, day: 20 },
  { name: "Shinobu Kocho", anime: "Demon Slayer", month: 1, day: 24 },
  { name: "Maki Zenin", anime: "Jujutsu Kaisen", month: 1, day: 20 },
  { name: "Yuri Plisetsky", anime: "Yuri on Ice", month: 1, day: 3 },
  { name: "Toge Inumaki", anime: "Jujutsu Kaisen", month: 1, day: 23 },
  { name: "All Might (Toshinori Yagi)", anime: "My Hero Academia", month: 1, day: 10 },
  { name: "Ken Kaneki", anime: "Tokyo Ghoul", month: 1, day: 20 },
  { name: "Touka Kirishima", anime: "Tokyo Ghoul", month: 1, day: 1 },
  { name: "Howl", anime: "Howl's Moving Castle", month: 1, day: 12 },
  { name: "Tatsumaki", anime: "One Punch Man", month: 1, day: 16 },
  { name: "Kenpachi Zaraki", anime: "Bleach", month: 1, day: 19 },
  { name: "Takeshi Yamamoto", anime: "Hitman Reborn", month: 1, day: 24 },
  { name: "Giyu Tomioka", anime: "Demon Slayer", month: 1, day: 29 },

  // FEBRUARY
  { name: "Edward Elric", anime: "Fullmetal Alchemist", month: 2, day: 3 },
  { name: "Rem", anime: "Re:Zero", month: 2, day: 2 },
  { name: "Ram", anime: "Re:Zero", month: 2, day: 2 },
  { name: "Robin Nico", anime: "One Piece", month: 2, day: 6 },
  { name: "Mikasa Ackerman", anime: "Attack on Titan", month: 2, day: 10 },
  { name: "Obito Uchiha", anime: "Naruto", month: 2, day: 10 },
  { name: "Licht", anime: "Plunderer", month: 2, day: 14 },
  { name: "Rin Tohsaka", anime: "Fate/Stay Night", month: 2, day: 3 },
  { name: "Light Yagami", anime: "Death Note", month: 2, day: 28 },
  { name: "Nagisa Shiota", anime: "Assassination Classroom", month: 2, day: 20 },
  { name: "Orihime Inoue", anime: "Bleach", month: 2, day: 6 },

  { name: "Usopp", anime: "One Piece", month: 2, day: 1 },
  { name: "Konan", anime: "Naruto", month: 2, day: 20 },
  { name: "Gilgamesh", anime: "Fate Series", month: 2, day: 14 },
  { name: "Asuna Yuuki", anime: "Sword Art Online", month: 2, day: 22 },
  { name: "Kanao Tsuyuri", anime: "Demon Slayer", month: 2, day: 24 },
  { name: "Chika Fujiwara", anime: "Kaguya-sama", month: 2, day: 3 },
  { name: "Neji Hyuga", anime: "Naruto", month: 2, day: 8 },
  { name: "Hayato Gokudera", anime: "Hitman Reborn", month: 2, day: 9 },
  { name: "Rangiku Matsumoto", anime: "Bleach", month: 2, day: 14 },
  { name: "Kamina", anime: "Gurren Lagann", month: 2, day: 2 },
  { name: "Krillin", anime: "Dragon Ball", month: 2, day: 15 },
  { name: "Kurapika", anime: "Hunter x Hunter", month: 2, day: 4 },
  { name: "Rias Gremory", anime: "High School DxD", month: 2, day: 5 },
  { name: "Raphtalia", anime: "Shield Hero", month: 2, day: 12 },
  { name: "Tanjiro Kamado", anime: "Demon Slayer", month: 2, day: 21 },
  { name: "Yato", anime: "Noragami", month: 2, day: 18 },
  { name: "Hinata Hyuga", anime: "Naruto", month: 2, day: 27 },
  { name: "Emilia", anime: "Re:Zero", month: 2, day: 15 },
  { name: "Shinya Kogami", anime: "Psycho-Pass", month: 2, day: 7 },
  { name: "Sasha Braus", anime: "Attack on Titan", month: 2, day: 26 },
  { name: "Wendy Marvell", anime: "Fairy Tail", month: 2, day: 17 },
  { name: "Ayato Kirishima", anime: "Tokyo Ghoul", month: 2, day: 1 },
  { name: "Tamaki Amajiki", anime: "My Hero Academia", month: 2, day: 4 },
  { name: "Kyoka Jiro", anime: "My Hero Academia", month: 2, day: 1 },
  { name: "Zeref Dragneel", anime: "Fairy Tail", month: 2, day: 11 },

  // MARCH
  { name: "Sanji", anime: "One Piece", month: 3, day: 2 },
  { name: "Luffy", anime: "One Piece", month: 3, day: 5 },
  { name: "Sakura Haruno", anime: "Naruto", month: 3, day: 28 },
  { name: "Saitama", anime: "One Punch Man", month: 3, day: 19 },
  { name: "Yuji Itadori", anime: "Jujutsu Kaisen", month: 3, day: 20 },
  { name: "Eren Yeager", anime: "Attack on Titan", month: 3, day: 30 },
  { name: "Rei Ayanami", anime: "Evangelion", month: 3, day: 30 },

  { name: "Tenten", anime: "Naruto", month: 3, day: 9 },
  { name: "Smoker", anime: "One Piece", month: 3, day: 14 },
  { name: "Ino Yamanaka", anime: "Naruto", month: 3, day: 23 },
  { name: "Rock Lee", anime: "Naruto", month: 3, day: 27 },
  { name: "Karma Akabane", anime: "Assassination Classroom", month: 3, day: 25 },
  { name: "Kei Tsukishima", anime: "Haikyuu!!", month: 3, day: 27 },
  { name: "Izaya Orihara", anime: "Durarara!!", month: 3, day: 4 },
  { name: "Shizuo Heiwajima", anime: "Durarara!!", month: 3, day: 28 },
  { name: "Hiruzen Sarutobi", anime: "Naruto", month: 3, day: 8 },
  { name: "Misaka Mikoto", anime: "A Certain Scientific Railgun", month: 3, day: 2 },
  { name: "Shikamaru Nara", anime: "Naruto", month: 3, day: 22 },
  { name: "Momo Yaoyorozu", anime: "My Hero Academia", month: 3, day: 23 },
  { name: "Kirito (Kazuto)", anime: "Sword Art Online", month: 3, day: 7 },
  { name: "Kagome Higurashi", anime: "Inuyasha", month: 3, day: 15 },
  { name: "Killua Zoldyck", anime: "Hunter x Hunter", month: 3, day: 3 },
  { name: "Gray Fullbuster", anime: "Fairy Tail", month: 3, day: 17 },
  { name: "Juvia Lockser", anime: "Fairy Tail", month: 3, day: 20 },
  { name: "Might Guy", anime: "Naruto", month: 3, day: 1 },
  { name: "Tsunade", anime: "Naruto", month: 3, day: 2 },
  { name: "Inosuke Hashibira", anime: "Demon Slayer", month: 3, day: 12 },
  { name: "Nanami Kento", anime: "Jujutsu Kaisen", month: 3, day: 7 },
  { name: "Toru Oikawa", anime: "Haikyuu!!", month: 3, day: 20 },
  { name: "Marco", anime: "One Piece", month: 3, day: 21 },
  { name: "Loid Forger", anime: "Spy x Family", month: 3, day: 12 },
  { name: "Denji", anime: "Chainsaw Man", month: 3, day: 10 },
  { name: "Takemichi Hanagaki", anime: "Tokyo Revengers", month: 3, day: 25 },
  { name: "Mikey (Manjiro Sano)", anime: "Tokyo Revengers", month: 3, day: 1 },
  { name: "Aqua", anime: "Konosuba", month: 3, day: 22 },
  { name: "Sebastian Michaelis", anime: "Black Butler", month: 3, day: 14 },
  { name: "Ciel Phantomhive", anime: "Black Butler", month: 3, day: 14 },
  { name: "Yor Forger", anime: "Spy x Family", month: 3, day: 28 },
  { name: "Nami", anime: "One Piece", month: 3, day: 3 },
  { name: "Hange Zoe", anime: "Attack on Titan", month: 3, day: 5 },
  { name: "Armin Arlert", anime: "Attack on Titan", month: 3, day: 3 },

  // APRIL
  { name: "Goku", anime: "Dragon Ball", month: 4, day: 16 },
  { name: "Bakugo Katsuki", anime: "My Hero Academia", month: 4, day: 20 },
  { name: "Ichigo Kurosaki", anime: "Bleach", month: 4, day: 15 },
  { name: "Nezuko Kamado", anime: "Demon Slayer", month: 4, day: 28 },
  { name: "Meliodas", anime: "Seven Deadly Sins", month: 4, day: 1 },
  { name: "Leorio Paradinight", anime: "Hunter x Hunter", month: 4, day: 3 },

  { name: "Urahara Kisuke", anime: "Bleach", month: 4, day: 1 },
  { name: "Shanks", anime: "One Piece", month: 4, day: 9 },
  { name: "Nagato (Pain)", anime: "Naruto", month: 4, day: 19 },
  { name: "Izuku Midoriya", anime: "My Hero Academia", month: 4, day: 15 },
  { name: "Megumin", anime: "Konosuba", month: 4, day: 2 },
  { name: "Toshiro Hitsugaya", anime: "Bleach", month: 4, day: 10 },
  { name: "Anya Forger", anime: "Spy x Family", month: 4, day: 18 },
  { name: "Violet Evergarden", anime: "Violet Evergarden", month: 4, day: 14 },
  { name: "Shigaraki Tomura", anime: "My Hero Academia", month: 4, day: 4 },
  { name: "Sosuke Aizen", anime: "Bleach", month: 4, day: 29 },
  { name: "Kira Yoshikage", anime: "JoJo Part 4", month: 4, day: 7 },
  { name: "Yuno Gasai", anime: "Future Diary", month: 4, day: 7 },
  { name: "Yoruichi Shihouin", anime: "Bleach", month: 4, day: 1 },
  { name: "Jellal Fernandes", anime: "Fairy Tail", month: 4, day: 29 },
  { name: "Chrollo Lucilfer", anime: "Hunter x Hunter", month: 4, day: 2 },
  { name: "Gildarts Clive", anime: "Fairy Tail", month: 4, day: 11 },
  { name: "Yami Sukehiro", anime: "Black Clover", month: 4, day: 15 },
  { name: "Noelle Silva", anime: "Black Clover", month: 4, day: 15 },
  { name: "Shinji Ikari", anime: "Evangelion", month: 4, day: 6 },
  { name: "Yusuke Urameshi", anime: "Yu Yu Hakusho", month: 4, day: 3 },
  { name: "Osamu Dazai", anime: "Bungo Stray Dogs", month: 4, day: 19 },
  { name: "Atsushi Nakajima", anime: "Bungo Stray Dogs", month: 4, day: 4 },
  { name: "Chuuya Nakahara", anime: "Bungo Stray Dogs", month: 4, day: 29 },
  { name: "Ryomen Sukuna", anime: "Jujutsu Kaisen", month: 4, day: 25 },
  { name: "Hisoka", anime: "Hunter x Hunter", month: 4, day: 6 },
  { name: "Doppo Kunikida", anime: "Bungo Stray Dogs", month: 4, day: 30 },
  { name: "Power", anime: "Chainsaw Man", month: 4, day: 2 },
  { name: "Aki Hayakawa", anime: "Chainsaw Man", month: 4, day: 12 },
  { name: "Draken (Ken Ryuguji)", anime: "Tokyo Revengers", month: 4, day: 12 },
  { name: "Langa Hasegawa", anime: "SK8 the Infinity", month: 4, day: 8 },
  { name: "Sailor Venus (Minako)", anime: "Sailor Moon", month: 4, day: 22 },
  { name: "Jean Kirstein", anime: "Attack on Titan", month: 4, day: 7 },
  { name: "Connie Springer", anime: "Attack on Titan", month: 4, day: 2 },

  // MAY
  { name: "Luffy", anime: "One Piece", month: 5, day: 5 },
  { name: "Gon Freecss", anime: "Hunter x Hunter", month: 5, day: 5 },
  { name: "Inuyasha", anime: "Inuyasha", month: 5, day: 27 },
  { name: "Erza Scarlet", anime: "Fairy Tail", month: 5, day: 15 },
  { name: "Shinya Kogami", anime: "Psycho-Pass", month: 5, day: 5 },

  { name: "Laxus Dreyar", anime: "Fairy Tail", month: 5, day: 2 },
  { name: "Frieza", anime: "Dragon Ball", month: 5, day: 3 },
  { name: "Brook", anime: "One Piece", month: 5, day: 3 },
  { name: "Shoto Todoroki", anime: "My Hero Academia", month: 5, day: 11 },
  { name: "Tenya Iida", anime: "My Hero Academia", month: 5, day: 22 },
  { name: "Himiko Toga", anime: "My Hero Academia", month: 5, day: 7 },
  { name: "Tokoyami Fumikage", anime: "My Hero Academia", month: 5, day: 30 },
  { name: "Byakuya Kuchiki", anime: "Bleach", month: 5, day: 31 },
  { name: "Yamamoto Genryusai", anime: "Bleach", month: 5, day: 15 },
  { name: "Lucy Heartfilia", anime: "Fairy Tail", month: 5, day: 1 },
  { name: "Levy McGarden", anime: "Fairy Tail", month: 5, day: 17 },
  { name: "Jotaro Kujo", anime: "JoJo's Bizarre Adventure", month: 5, day: 2 },
  { name: "DIO Brando", anime: "JoJo's Bizarre Adventure", month: 5, day: 12 },
  { name: "Joseph Joestar", anime: "JoJo's Bizarre Adventure", month: 5, day: 18 },
  { name: "Diane", anime: "Seven Deadly Sins", month: 5, day: 5 },
  { name: "Ban", anime: "Seven Deadly Sins", month: 5, day: 14 },
  { name: "Sailor Jupiter (Makoto)", anime: "Sailor Moon", month: 5, day: 5 },
  { name: "Shino Aburame", anime: "Naruto", month: 5, day: 23 },
  { name: "Kiba Inuzuka", anime: "Naruto", month: 5, day: 15 },
  { name: "Franky", anime: "One Piece", month: 5, day: 9 },
  { name: "Android 18", anime: "Dragon Ball", month: 5, day: 10 },
  { name: "Piccolo", anime: "Dragon Ball", month: 5, day: 9 },
  { name: "Mob (Shigeo Kageyama)", anime: "Mob Psycho 100", month: 5, day: 12 },
  { name: "Reigen Arataka", anime: "Mob Psycho 100", month: 5, day: 17 },
  { name: "Rintaro Okabe", anime: "Steins;Gate", month: 5, day: 14 },
  { name: "Mayuri Shiina", anime: "Steins;Gate", month: 5, day: 2 },
  { name: "Yuno", anime: "Black Clover", month: 5, day: 14 },
  { name: "Asta", anime: "Black Clover", month: 5, day: 14 },
  { name: "Mitsuri Kanroji", anime: "Demon Slayer", month: 5, day: 19 },
  { name: "Tengen Uzui", anime: "Demon Slayer", month: 5, day: 31 },
  { name: "Makima", anime: "Chainsaw Man", month: 5, day: 5 },
  { name: "Pochita", anime: "Chainsaw Man", month: 5, day: 20 },
  { name: "Kazuya Kinoshita", anime: "Rent-a-Girlfriend", month: 5, day: 8 },
  { name: "Chizuru Mizuhara", anime: "Rent-a-Girlfriend", month: 5, day: 19 },
  { name: "Historia Reiss", anime: "Attack on Titan", month: 5, day: 15 },
  { name: "Annie Leonhart", anime: "Attack on Titan", month: 5, day: 22 },
  { name: "Reki Kyan", anime: "SK8 the Infinity", month: 5, day: 21 },

  // JUNE
  { name: "Itachi Uchiha", anime: "Naruto", month: 6, day: 9 },
  { name: "Shinji Ikari", anime: "Evangelion", month: 6, day: 6 },
  { name: "Spike Spiegel", anime: "Cowboy Bebop", month: 6, day: 26 },
  { name: "Sailor Moon (Usagi)", anime: "Sailor Moon", month: 6, day: 30 },
  { name: "Temari", anime: "Naruto", month: 6, day: 23 },

  { name: "Yamato", anime: "Naruto", month: 6, day: 10 },
  { name: "Franky (Cutty Flam)", anime: "One Piece", month: 6, day: 12 },
  { name: "Giorno Giovanna", anime: "JoJo Part 5", month: 6, day: 5 },
  { name: "Kurogiri", anime: "My Hero Academia", month: 6, day: 2 },
  { name: "Endeavor (Enji Todoroki)", anime: "My Hero Academia", month: 6, day: 22 },
  { name: "Present Mic", anime: "My Hero Academia", month: 6, day: 7 },
  { name: "Denki Kaminari", anime: "My Hero Academia", month: 6, day: 29 },
  { name: "Reiner Braun", anime: "Attack on Titan", month: 6, day: 1 },
  { name: "Bertholdt Hoover", anime: "Attack on Titan", month: 6, day: 30 },
  { name: "Bulma", anime: "Dragon Ball", month: 6, day: 16 },
  { name: "Gohan", anime: "Dragon Ball", month: 6, day: 22 },
  { name: "Chi-Chi", anime: "Dragon Ball", month: 6, day: 18 },
  { name: "Shinsou Hitoshi", anime: "My Hero Academia", month: 6, day: 1 },
  { name: "Cana Alberona", anime: "Fairy Tail", month: 6, day: 15 },
  { name: "Freed Justine", anime: "Fairy Tail", month: 6, day: 5 },
  { name: "Jonathan Joestar", anime: "JoJo Part 1", month: 6, day: 4 },
  { name: "Doppio Vinegar", anime: "JoJo Part 5", month: 6, day: 22 },
  { name: "Shouta Aizawa (Eraserhead)", anime: "My Hero Academia", month: 6, day: 8 },
  { name: "Nobara Kugisaki", anime: "Jujutsu Kaisen", month: 6, day: 7 },
  { name: "Kaori Miyazono", anime: "Your Lie in April", month: 6, day: 4 },
  { name: "Kousei Arima", anime: "Your Lie in April", month: 6, day: 28 },
  { name: "Mafuyu Sato", anime: "Given", month: 6, day: 6 },
  { name: "Zenitsu Agatsuma", anime: "Demon Slayer", month: 6, day: 3 },
  { name: "Gyomei Himejima", anime: "Demon Slayer", month: 6, day: 15 },
  { name: "Sanemi Shinazugawa", anime: "Demon Slayer", month: 6, day: 21 },
  { name: "Rize Kamishiro", anime: "Tokyo Ghoul", month: 6, day: 3 },
  { name: "Hide (Hideyoshi Nagachika)", anime: "Tokyo Ghoul", month: 6, day: 10 },
  { name: "Takashi Mitsuya", anime: "Tokyo Revengers", month: 6, day: 12 },
  { name: "Kazutora Hanemiya", anime: "Tokyo Revengers", month: 6, day: 18 },
  { name: "Senku Ishigami", anime: "Dr. Stone", month: 6, day: 4 },
  { name: "Chrome", anime: "Dr. Stone", month: 6, day: 5 },
  { name: "Kuroko Tetsuya", anime: "Kuroko's Basketball", month: 6, day: 31 },
  { name: "Kagami Taiga", anime: "Kuroko's Basketball", month: 6, day: 2 },
  { name: "Sinbad", anime: "Magi", month: 6, day: 14 },
  { name: "Aladdin", anime: "Magi", month: 6, day: 27 },

  // JULY
  { name: "Naruto Uzumaki", anime: "Naruto", month: 7, day: 10 },
  { name: "Ichigo Kurosaki", anime: "Bleach", month: 7, day: 15 },
  { name: "Nami", anime: "One Piece", month: 7, day: 3 },
  { name: "Tanjiro Kamado", anime: "Demon Slayer", month: 7, day: 14 },
  { name: "Killua Zoldyck", anime: "Hunter x Hunter", month: 7, day: 7 },
  { name: "Natsu Dragneel", anime: "Fairy Tail", month: 7, day: 7 },

  { name: "Deku (Izuku Midoriya)", anime: "My Hero Academia", month: 7, day: 15 },
  { name: "Genos", anime: "One Punch Man", month: 7, day: 4 },
  { name: "Sasuke Uchiha", anime: "Naruto", month: 7, day: 23 },
  { name: "Hinata Shoyo", anime: "Haikyuu!!", month: 7, day: 21 },
  { name: "Kaguya Otsutsuki", anime: "Naruto", month: 7, day: 1 },
  { name: "Nico Robin", anime: "One Piece", month: 7, day: 6 },
  { name: "Sai", anime: "Naruto", month: 7, day: 25 },
  { name: "Uryu Ishida", anime: "Bleach", month: 7, day: 22 },
  { name: "Chad (Sado Yasutora)", anime: "Bleach", month: 7, day: 7 },
  { name: "Renji Abarai", anime: "Bleach", month: 7, day: 31 },
  { name: "Eijiro Kirishima", anime: "My Hero Academia", month: 7, day: 16 },
  { name: "Hawks (Keigo Takami)", anime: "My Hero Academia", month: 7, day: 28 },
  { name: "Fumikage Tokoyami", anime: "My Hero Academia", month: 7, day: 30 },
  { name: "Lisanna Strauss", anime: "Fairy Tail", month: 7, day: 8 },
  { name: "Gajeel Redfox", anime: "Fairy Tail", month: 7, day: 21 },
  { name: "King (Harlequin)", anime: "Seven Deadly Sins", month: 7, day: 1 },
  { name: "Elizabeth Liones", anime: "Seven Deadly Sins", month: 7, day: 12 },
  { name: "Sailor Mercury (Ami)", anime: "Sailor Moon", month: 7, day: 10 },
  { name: "Monkey D. Dragon", anime: "One Piece", month: 7, day: 5 },
  { name: "Gotenks", anime: "Dragon Ball", month: 7, day: 20 },
  { name: "Trunks", anime: "Dragon Ball", month: 7, day: 15 },
  { name: "Android 17", anime: "Dragon Ball", month: 7, day: 17 },
  { name: "Muzan Kibutsuji", anime: "Demon Slayer", month: 7, day: 21 },
  { name: "Obanai Iguro", anime: "Demon Slayer", month: 7, day: 15 },
  { name: "Geto Suguru", anime: "Jujutsu Kaisen", month: 7, day: 3 },
  { name: "Panda", anime: "Jujutsu Kaisen", month: 7, day: 5 },
  { name: "Choso", anime: "Jujutsu Kaisen", month: 7, day: 12 },
  { name: "Levi Ackerman", anime: "Attack on Titan", month: 7, day: 25 },
  { name: "Revy", anime: "Black Lagoon", month: 7, day: 6 },
  { name: "Accelerator", anime: "A Certain Magical Index", month: 7, day: 24 },
  { name: "Subaru Natsuki", anime: "Re:Zero", month: 7, day: 18 },
  { name: "Zero Two", anime: "Darling in the Franxx", month: 7, day: 7 },
  { name: "Hiro", anime: "Darling in the Franxx", month: 7, day: 14 },
  { name: "Baji Keisuke", anime: "Tokyo Revengers", month: 7, day: 3 },
  { name: "Chifuyu Matsuno", anime: "Tokyo Revengers", month: 7, day: 15 },

  // AUGUST
  { name: "Vegeta", anime: "Dragon Ball", month: 8, day: 15 },
  { name: "L Lawliet", anime: "Death Note", month: 8, day: 31 },
  { name: "Hinata Hyuga", anime: "Naruto", month: 8, day: 27 },
  { name: "Orochimaru", anime: "Naruto", month: 8, day: 27 },
  { name: "Tony Tony Chopper", anime: "One Piece", month: 8, day: 3 },
  { name: "Trafalgar Law", anime: "One Piece", month: 8, day: 6 },

  { name: "Yamcha", anime: "Dragon Ball", month: 8, day: 20 },
  { name: "Tien Shinhan", anime: "Dragon Ball", month: 8, day: 12 },
  { name: "Master Roshi", anime: "Dragon Ball", month: 8, day: 28 },
  { name: "Jiraiya", anime: "Naruto", month: 8, day: 11 },
  { name: "Tsunade", anime: "Naruto", month: 8, day: 2 },
  { name: "Asuma Sarutobi", anime: "Naruto", month: 8, day: 18 },
  { name: "Shisui Uchiha", anime: "Naruto", month: 8, day: 19 },
  { name: "Konohamaru Sarutobi", anime: "Naruto", month: 8, day: 28 },
  { name: "Inoue Orihime", anime: "Bleach", month: 8, day: 3 },
  { name: "Ulquiorra Cifer", anime: "Bleach", month: 8, day: 1 },
  { name: "Minoru Mineta", anime: "My Hero Academia", month: 8, day: 8 },
  { name: "Overhaul (Chisaki)", anime: "My Hero Academia", month: 8, day: 10 },
  { name: "Nejire Hado", anime: "My Hero Academia", month: 8, day: 6 },
  { name: "Elfman Strauss", anime: "Fairy Tail", month: 8, day: 13 },
  { name: "Happy", anime: "Fairy Tail", month: 8, day: 20 },
  { name: "Bruno Bucciarati", anime: "JoJo Part 5", month: 8, day: 27 },
  { name: "Narancia Ghirga", anime: "JoJo Part 5", month: 8, day: 20 },
  { name: "Sailor Mars (Rei)", anime: "Sailor Moon", month: 8, day: 13 },
  { name: "Gowther", anime: "Seven Deadly Sins", month: 8, day: 8 },
  { name: "Escanor", anime: "Seven Deadly Sins", month: 8, day: 1 },
  { name: "Yami Yugi", anime: "Yu-Gi-Oh!", month: 8, day: 4 },
  { name: "Seto Kaiba", anime: "Yu-Gi-Oh!", month: 8, day: 25 },
  { name: "Sakura Kinomoto", anime: "Cardcaptor Sakura", month: 8, day: 1 },
  { name: "Himawari Uzumaki", anime: "Boruto", month: 8, day: 1 },
  { name: "Boruto Uzumaki", anime: "Boruto", month: 8, day: 27 },
  { name: "Sarada Uchiha", anime: "Boruto", month: 8, day: 31 },
  { name: "Kokushibo", anime: "Demon Slayer", month: 8, day: 7 },
  { name: "Doma", anime: "Demon Slayer", month: 8, day: 22 },
  { name: "Yoriichi Tsugikuni", anime: "Demon Slayer", month: 8, day: 20 },
  { name: "Gon Freecss", anime: "Hunter x Hunter", month: 8, day: 5 },
  { name: "Shalnark", anime: "Hunter x Hunter", month: 8, day: 9 },
  { name: "Illumi Zoldyck", anime: "Hunter x Hunter", month: 8, day: 13 },
  { name: "Isaac Netero", anime: "Hunter x Hunter", month: 8, day: 16 },
  { name: "Kite", anime: "Hunter x Hunter", month: 8, day: 29 },
  { name: "Ken Kaneki", anime: "Tokyo Ghoul", month: 8, day: 20 },
  { name: "Juzo Suzuya", anime: "Tokyo Ghoul", month: 8, day: 8 },
  { name: "Gintoki Sakata", anime: "Gintama", month: 8, day: 10 },
  { name: "Kagura", anime: "Gintama", month: 8, day: 3 },
  { name: "Shinpachi Shimura", anime: "Gintama", month: 8, day: 12 },
  { name: "Takasugi Shinsuke", anime: "Gintama", month: 8, day: 10 },

  // SEPTEMBER
  { name: "Kakashi Hatake", anime: "Naruto", month: 9, day: 15 },
  { name: "Zenitsu Agatsuma", anime: "Demon Slayer", month: 9, day: 3 },
  { name: "Emilia", anime: "Re:Zero", month: 9, day: 23 },
  { name: "Naruto Uzumaki", anime: "Naruto", month: 9, day: 10 },

  { name: "Iruka Umino", anime: "Naruto", month: 9, day: 26 },
  { name: "Suigetsu Hozuki", anime: "Naruto", month: 9, day: 18 },
  { name: "Karin Uzumaki", anime: "Naruto", month: 9, day: 20 },
  { name: "Madara Uchiha", anime: "Naruto", month: 9, day: 24 },
  { name: "Hashirama Senju", anime: "Naruto", month: 9, day: 23 },
  { name: "Tobirama Senju", anime: "Naruto", month: 9, day: 19 },
  { name: "Portgas D. Rouge", anime: "One Piece", month: 9, day: 1 },
  { name: "Sabo", anime: "One Piece", month: 9, day: 20 },
  { name: "Vivi Nefertari", anime: "One Piece", month: 9, day: 18 },
  { name: "Doflamingo", anime: "One Piece", month: 9, day: 23 },
  { name: "Crocodile", anime: "One Piece", month: 9, day: 5 },
  { name: "Mihawk", anime: "One Piece", month: 9, day: 9 },
  { name: "Gin Ichimaru", anime: "Bleach", month: 9, day: 10 },
  { name: "Sosuke Aizen", anime: "Bleach", month: 9, day: 29 },
  { name: "Tatsuki Arisawa", anime: "Bleach", month: 9, day: 17 },
  { name: "All For One", anime: "My Hero Academia", month: 9, day: 1 },
  { name: "Mirko (Rumi Usagiyama)", anime: "My Hero Academia", month: 9, day: 1 },
  { name: "Midnight (Nemuri Kayama)", anime: "My Hero Academia", month: 9, day: 9 },
  { name: "Ryuko Matoi", anime: "Kill la Kill", month: 9, day: 1 },
  { name: "Satsuki Kiryuin", anime: "Kill la Kill", month: 9, day: 3 },
  { name: "Laxus Dreyar", anime: "Fairy Tail", month: 9, day: 12 },
  { name: "Mavis Vermillion", anime: "Fairy Tail", month: 9, day: 22 },
  { name: "Josuke Higashikata", anime: "JoJo Part 4", month: 9, day: 5 },
  { name: "Rohan Kishibe", anime: "JoJo Part 4", month: 9, day: 28 },
  { name: "Sailor Neptune", anime: "Sailor Moon", month: 9, day: 6 },
  { name: "Merlin", anime: "Seven Deadly Sins", month: 9, day: 14 },
  { name: "Shikamaru Nara", anime: "Naruto", month: 9, day: 22 },
  { name: "Estarossa", anime: "Seven Deadly Sins", month: 9, day: 30 },
  { name: "Soma Yukihira", anime: "Food Wars", month: 9, day: 6 },
  { name: "Nishiki Nishio", anime: "Tokyo Ghoul", month: 9, day: 4 },
  { name: "Shu Tsukiyama", anime: "Tokyo Ghoul", month: 9, day: 12 },
  { name: "Nana Shimura", anime: "My Hero Academia", month: 9, day: 22 },
  { name: "Fumikage Tokoyami", anime: "My Hero Academia", month: 9, day: 30 },
  { name: "Kotaro Tatsumi", anime: "Zombie Land Saga", month: 9, day: 5 },
  { name: "Rimuru Tempest", anime: "That Time I Got Reincarnated as a Slime", month: 9, day: 16 },
  { name: "Milim Nava", anime: "That Time I Got Reincarnated as a Slime", month: 9, day: 20 },

  // OCTOBER
  { name: "Naruto Uzumaki", anime: "Naruto", month: 10, day: 10 },
  { name: "Asta", anime: "Black Clover", month: 10, day: 4 },
  { name: "Sanji", anime: "One Piece", month: 10, day: 2 },
  { name: "Levi Ackerman", anime: "Attack on Titan", month: 10, day: 25 },

  { name: "Obito Uchiha", anime: "Naruto", month: 10, day: 10 },
  { name: "Kurenai Yuhi", anime: "Naruto", month: 10, day: 11 },
  { name: "Anko Mitarashi", anime: "Naruto", month: 10, day: 24 },
  { name: "Kabuto Yakushi", anime: "Naruto", month: 10, day: 29 },
  { name: "Hidan", anime: "Naruto", month: 10, day: 4 },
  { name: "Deidara", anime: "Naruto", month: 10, day: 5 },
  { name: "Sasori", anime: "Naruto", month: 10, day: 8 },
  { name: "Boa Hancock", anime: "One Piece", month: 10, day: 2 },
  { name: "Yamato (One Piece)", anime: "One Piece", month: 10, day: 3 },
  { name: "Jinbe", anime: "One Piece", month: 10, day: 2 },
  { name: "Kaido", anime: "One Piece", month: 10, day: 19 },
  { name: "Big Mom", anime: "One Piece", month: 10, day: 15 },
  { name: "Katakuri", anime: "One Piece", month: 10, day: 25 },
  { name: "Uryuu Ishida", anime: "Bleach", month: 10, day: 6 },
  { name: "Kenpachi Zaraki", anime: "Bleach", month: 10, day: 19 },
  { name: "Zaraki", anime: "Bleach", month: 10, day: 19 },
  { name: "Mirio Togata", anime: "My Hero Academia", month: 10, day: 15 },
  { name: "Best Jeanist", anime: "My Hero Academia", month: 10, day: 5 },
  { name: "Twice (Jin Bubaigawara)", anime: "My Hero Academia", month: 10, day: 10 },
  { name: "Freed Justine", anime: "Fairy Tail", month: 10, day: 5 },
  { name: "Beerus", anime: "Dragon Ball Super", month: 10, day: 7 },
  { name: "Whis", anime: "Dragon Ball Super", month: 10, day: 12 },
  { name: "Broly", anime: "Dragon Ball", month: 10, day: 20 },
  { name: "Cell", anime: "Dragon Ball", month: 10, day: 14 },
  { name: "Sailor Pluto (Setsuna)", anime: "Sailor Moon", month: 10, day: 29 },
  { name: "Sakata Gintoki", anime: "Gintama", month: 10, day: 10 },
  { name: "Taiga Aisaka", anime: "Toradora!", month: 10, day: 4 },
  { name: "Ryuuji Takasu", anime: "Toradora!", month: 10, day: 7 },
  { name: "Misato Katsuragi", anime: "Evangelion", month: 10, day: 8 },
  { name: "Mari Makinami", anime: "Evangelion", month: 10, day: 28 },
  { name: "Izumi Miyamura", anime: "Horimiya", month: 10, day: 7 },
  { name: "Kyoko Hori", anime: "Horimiya", month: 10, day: 25 },
  { name: "Osamu Miya", anime: "Haikyuu!!", month: 10, day: 5 },
  { name: "Atsumu Miya", anime: "Haikyuu!!", month: 10, day: 5 },
  { name: "Kenma Kozume", anime: "Haikyuu!!", month: 10, day: 16 },
  { name: "Bokuto Kotaro", anime: "Haikyuu!!", month: 10, day: 21 },
  { name: "Shoto Todoroki", anime: "My Hero Academia", month: 10, day: 11 },

  // NOVEMBER
  { name: "Roronoa Zoro", anime: "One Piece", month: 11, day: 11 },
  { name: "Lelouch Lamperouge", anime: "Code Geass", month: 11, day: 5 },
  { name: "Sakura Haruno", anime: "Naruto", month: 11, day: 28 },

  { name: "Minato Namikaze", anime: "Naruto", month: 11, day: 25 },
  { name: "Kushina Uzumaki", anime: "Naruto", month: 11, day: 10 },
  { name: "Rock Lee", anime: "Naruto", month: 11, day: 27 },
  { name: "Neji Hyuga", anime: "Naruto", month: 11, day: 3 },
  { name: "Choji Akimichi", anime: "Naruto", month: 11, day: 1 },
  { name: "Killer Bee", anime: "Naruto", month: 11, day: 15 },
  { name: "Kakuzu", anime: "Naruto", month: 11, day: 15 },
  { name: "Konan", anime: "Naruto", month: 11, day: 2 },
  { name: "Blackbeard", anime: "One Piece", month: 11, day: 3 },
  { name: "Perona", anime: "One Piece", month: 11, day: 7 },
  { name: "Kuma", anime: "One Piece", month: 11, day: 9 },
  { name: "Aokiji (Kuzan)", anime: "One Piece", month: 11, day: 15 },
  { name: "Akainu (Sakazuki)", anime: "One Piece", month: 11, day: 25 },
  { name: "Kizaru (Borsalino)", anime: "One Piece", month: 11, day: 23 },
  { name: "Mayuri Kurotsuchi", anime: "Bleach", month: 11, day: 11 },
  { name: "Unohana Retsu", anime: "Bleach", month: 11, day: 21 },
  { name: "Shunsui Kyoraku", anime: "Bleach", month: 11, day: 11 },
  { name: "Fumikage Tokoyami", anime: "My Hero Academia", month: 11, day: 30 },
  { name: "Hanta Sero", anime: "My Hero Academia", month: 11, day: 28 },
  { name: "Muscular", anime: "My Hero Academia", month: 11, day: 11 },
  { name: "Gildarts Clive", anime: "Fairy Tail", month: 11, day: 11 },
  { name: "Mystogan", anime: "Fairy Tail", month: 11, day: 11 },
  { name: "Makarov Dreyar", anime: "Fairy Tail", month: 11, day: 3 },
  { name: "Noriaki Kakyoin", anime: "JoJo Part 3", month: 11, day: 1 },
  { name: "Jean Pierre Polnareff", anime: "JoJo Part 3", month: 11, day: 25 },
  { name: "Jolyne Cujoh", anime: "JoJo Part 6", month: 11, day: 7 },
  { name: "Sailor Uranus (Haruka)", anime: "Sailor Moon", month: 11, day: 27 },
  { name: "Merlin (Seven Deadly Sins)", anime: "Seven Deadly Sins", month: 11, day: 14 },
  { name: "Totsuka Tatara", anime: "K Project", month: 11, day: 1 },
  { name: "Yato", anime: "Noragami", month: 11, day: 18 },
  { name: "Bishamon", anime: "Noragami", month: 11, day: 13 },
  { name: "Hinami Fueguchi", anime: "Tokyo Ghoul", month: 11, day: 21 },
  { name: "Eto Yoshimura", anime: "Tokyo Ghoul", month: 11, day: 13 },
  { name: "Takemichi Hanagaki", anime: "Tokyo Revengers", month: 11, day: 25 },
  { name: "Hinata Tachibana", anime: "Tokyo Revengers", month: 11, day: 11 },
  { name: "Naofumi Iwatani", anime: "Shield Hero", month: 11, day: 12 },
  { name: "Filo", anime: "Shield Hero", month: 11, day: 5 },

  // DECEMBER
  { name: "Gojo Satoru", anime: "Jujutsu Kaisen", month: 12, day: 7 },
  { name: "Levi Ackerman", anime: "Attack on Titan", month: 12, day: 25 },
  { name: "Lelouch Lamperouge", anime: "Code Geass", month: 12, day: 5 },
  { name: "Kaneki Ken", anime: "Tokyo Ghoul", month: 12, day: 20 },

  { name: "Misa Amane", anime: "Death Note", month: 12, day: 25 },
  { name: "Nezuko Kamado", anime: "Demon Slayer", month: 12, day: 28 },
  { name: "Ochaco Uraraka", anime: "My Hero Academia", month: 12, day: 27 },
  { name: "Hinata Hyuga", anime: "Naruto", month: 12, day: 27 },
  { name: "Megumi Fushiguro", anime: "Jujutsu Kaisen", month: 12, day: 22 },
  { name: "Asuka Langley", anime: "Evangelion", month: 12, day: 4 },
  { name: "Erwin Smith", anime: "Attack on Titan", month: 12, day: 14 },
  { name: "Historia Reiss", anime: "Attack on Titan", month: 12, day: 15 },
  { name: "Zeke Yeager", anime: "Attack on Titan", month: 12, day: 1 },
  { name: "Pieck Finger", anime: "Attack on Titan", month: 12, day: 5 },
  { name: "Monkey D. Garp", anime: "One Piece", month: 12, day: 2 },
  { name: "Rayleigh", anime: "One Piece", month: 12, day: 13 },
  { name: "Whitebeard (Newgate)", anime: "One Piece", month: 12, day: 6 },
  { name: "Roger (Gol D. Roger)", anime: "One Piece", month: 12, day: 31 },
  { name: "Yamato", anime: "One Piece", month: 12, day: 3 },
  { name: "Ichigo Kurosaki", anime: "Bleach", month: 12, day: 15 },
  { name: "Rukia Kuchiki", anime: "Bleach", month: 12, day: 14 },
  { name: "Kisuke Urahara", anime: "Bleach", month: 12, day: 31 },
  { name: "Nell Tu", anime: "Bleach", month: 12, day: 24 },
  { name: "Endeavor (Enji)", anime: "My Hero Academia", month: 12, day: 22 },
  { name: "Dabi", anime: "My Hero Academia", month: 12, day: 18 },
  { name: "Shigaraki Tomura", anime: "My Hero Academia", month: 12, day: 4 },
  { name: "Mr. Compress", anime: "My Hero Academia", month: 12, day: 8 },
  { name: "Natsu Dragneel", anime: "Fairy Tail", month: 12, day: 7 },
  { name: "Erza Scarlet", anime: "Fairy Tail", month: 12, day: 15 },
  { name: "Wendy Marvell", anime: "Fairy Tail", month: 12, day: 17 },
  { name: "Larcade Dragneel", anime: "Fairy Tail", month: 12, day: 3 },
  { name: "Giorno Giovanna", anime: "JoJo Part 5", month: 12, day: 16 },
  { name: "Pannacotta Fugo", anime: "JoJo Part 5", month: 12, day: 19 },
  { name: "Sailor Saturn (Hotaru)", anime: "Sailor Moon", month: 12, day: 6 },
  { name: "Goku Black", anime: "Dragon Ball Super", month: 12, day: 14 },
  { name: "Hit", anime: "Dragon Ball Super", month: 12, day: 7 },
  { name: "Jiren", anime: "Dragon Ball Super", month: 12, day: 20 },
  { name: "Kefla", anime: "Dragon Ball Super", month: 12, day: 22 },
  { name: "Shuna", anime: "That Time I Got Reincarnated as a Slime", month: 12, day: 1 },
  { name: "Benimaru", anime: "That Time I Got Reincarnated as a Slime", month: 12, day: 9 },
  { name: "Diablo", anime: "That Time I Got Reincarnated as a Slime", month: 12, day: 15 },
  { name: "Rengoku Kyojuro", anime: "Demon Slayer", month: 12, day: 3 },
  { name: "Akaza", anime: "Demon Slayer", month: 12, day: 5 },
  { name: "Enmu", anime: "Demon Slayer", month: 12, day: 18 },
  { name: "Gyutaro", anime: "Demon Slayer", month: 12, day: 30 },
  { name: "Daki", anime: "Demon Slayer", month: 12, day: 30 },
  { name: "Todo Aoi", anime: "Jujutsu Kaisen", month: 12, day: 23 },
  { name: "Mahito", anime: "Jujutsu Kaisen", month: 12, day: 12 },
  { name: "Hanami", anime: "Jujutsu Kaisen", month: 12, day: 5 },
  { name: "Yuta Okkotsu", anime: "Jujutsu Kaisen", month: 12, day: 7 },
  { name: "Gojo Satoru", anime: "Jujutsu Kaisen", month: 12, day: 7 },
  { name: "Toji Fushiguro", anime: "Jujutsu Kaisen", month: 12, day: 31 },
  { name: "Kisuke Urahara", anime: "Bleach", month: 12, day: 31 },
  { name: "Nelliel Tu Odelschwanck", anime: "Bleach", month: 12, day: 24 },
  { name: "Hitsugaya Toshiro", anime: "Bleach", month: 12, day: 20 },
  { name: "Zaraki Kenpachi", anime: "Bleach", month: 12, day: 19 },
  { name: "Hinata Hyuga", anime: "Naruto", month: 12, day: 27 },
  { name: "Kabuto Yakushi", anime: "Naruto", month: 12, day: 29 },
  { name: "Zetsu", anime: "Naruto", month: 12, day: 20 },
];

export default CHARACTER_BIRTHDAYS;
