// ─── Character Birthdays (1000+ characters) ────────────────
const CHARACTER_BIRTHDAYS = [
  // ── Naruto ──
  { name: "Naruto Uzumaki", anime: "Naruto", month: 10, day: 10 },
  { name: "Sasuke Uchiha", anime: "Naruto", month: 7, day: 23 },
  { name: "Sakura Haruno", anime: "Naruto", month: 3, day: 28 },
  { name: "Kakashi Hatake", anime: "Naruto", month: 9, day: 15 },
  { name: "Itachi Uchiha", anime: "Naruto", month: 6, day: 9 },
  { name: "Hinata Hyuga", anime: "Naruto", month: 12, day: 27 },
  { name: "Gaara", anime: "Naruto", month: 1, day: 19 },
  { name: "Rock Lee", anime: "Naruto", month: 11, day: 27 },
  { name: "Neji Hyuga", anime: "Naruto", month: 7, day: 3 },
  { name: "Shikamaru Nara", anime: "Naruto", month: 9, day: 22 },
  { name: "Ino Yamanaka", anime: "Naruto", month: 9, day: 23 },
  { name: "Choji Akimichi", anime: "Naruto", month: 5, day: 1 },
  { name: "Kiba Inuzuka", anime: "Naruto", month: 7, day: 7 },
  { name: "Shino Aburame", anime: "Naruto", month: 1, day: 23 },
  { name: "Temari", anime: "Naruto", month: 8, day: 23 },
  { name: "Kankuro", anime: "Naruto", month: 5, day: 15 },
  { name: "Jiraiya", anime: "Naruto", month: 11, day: 11 },
  { name: "Tsunade", anime: "Naruto", month: 8, day: 2 },
  { name: "Orochimaru", anime: "Naruto", month: 10, day: 27 },
  { name: "Minato Namikaze", anime: "Naruto", month: 1, day: 25 },
  { name: "Kushina Uzumaki", anime: "Naruto", month: 7, day: 10 },
  { name: "Obito Uchiha", anime: "Naruto", month: 2, day: 10 },
  { name: "Madara Uchiha", anime: "Naruto", month: 12, day: 24 },
  { name: "Hashirama Senju", anime: "Naruto", month: 10, day: 23 },
  { name: "Tobirama Senju", anime: "Naruto", month: 2, day: 19 },
  { name: "Hiruzen Sarutobi", anime: "Naruto", month: 2, day: 8 },
  { name: "Might Guy", anime: "Naruto", month: 1, day: 1 },
  { name: "Asuma Sarutobi", anime: "Naruto", month: 10, day: 18 },
  { name: "Kurenai Yuhi", anime: "Naruto", month: 6, day: 11 },
  { name: "Anko Mitarashi", anime: "Naruto", month: 10, day: 24 },
  { name: "Iruka Umino", anime: "Naruto", month: 5, day: 26 },
  { name: "Konohamaru", anime: "Naruto", month: 12, day: 30 },
  { name: "Sai", anime: "Naruto", month: 11, day: 25 },
  { name: "Yamato", anime: "Naruto", month: 8, day: 10 },
  { name: "Pain (Nagato)", anime: "Naruto", month: 9, day: 19 },
  { name: "Konan", anime: "Naruto", month: 2, day: 20 },
  { name: "Deidara", anime: "Naruto", month: 5, day: 5 },
  { name: "Sasori", anime: "Naruto", month: 11, day: 8 },
  { name: "Hidan", anime: "Naruto", month: 4, day: 2 },
  { name: "Kakuzu", anime: "Naruto", month: 8, day: 15 },
  { name: "Kisame Hoshigaki", anime: "Naruto", month: 3, day: 18 },
  { name: "Zetsu", anime: "Naruto", month: 3, day: 20 },
  { name: "Tobi", anime: "Naruto", month: 2, day: 10 },
  { name: "Kabuto Yakushi", anime: "Naruto", month: 2, day: 29 },
  { name: "Suigetsu Hozuki", anime: "Naruto", month: 2, day: 18 },
  { name: "Karin", anime: "Naruto", month: 6, day: 20 },
  { name: "Jugo", anime: "Naruto", month: 10, day: 1 },

  { name: "Boruto Uzumaki", anime: "Boruto", month: 3, day: 27 },
  { name: "Sarada Uchiha", anime: "Boruto", month: 3, day: 31 },
  { name: "Mitsuki", anime: "Boruto", month: 7, day: 25 },

  // ── One Piece ──
  { name: "Monkey D. Luffy", anime: "One Piece", month: 5, day: 5 },
  { name: "Roronoa Zoro", anime: "One Piece", month: 11, day: 11 },
  { name: "Nami", anime: "One Piece", month: 7, day: 3 },
  { name: "Usopp", anime: "One Piece", month: 4, day: 1 },
  { name: "Sanji", anime: "One Piece", month: 3, day: 2 },
  { name: "Tony Tony Chopper", anime: "One Piece", month: 12, day: 24 },
  { name: "Nico Robin", anime: "One Piece", month: 2, day: 6 },
  { name: "Franky", anime: "One Piece", month: 3, day: 9 },
  { name: "Brook", anime: "One Piece", month: 4, day: 3 },
  { name: "Jinbe", anime: "One Piece", month: 4, day: 2 },
  { name: "Portgas D. Ace", anime: "One Piece", month: 1, day: 1 },
  { name: "Sabo", anime: "One Piece", month: 3, day: 20 },
  { name: "Shanks", anime: "One Piece", month: 3, day: 9 },
  { name: "Trafalgar Law", anime: "One Piece", month: 10, day: 6 },
  { name: "Boa Hancock", anime: "One Piece", month: 9, day: 2 },
  { name: "Dracule Mihawk", anime: "One Piece", month: 3, day: 9 },
  { name: "Crocodile", anime: "One Piece", month: 9, day: 5 },
  { name: "Donquixote Doflamingo", anime: "One Piece", month: 10, day: 23 },
  { name: "Monkey D. Garp", anime: "One Piece", month: 5, day: 2 },
  { name: "Monkey D. Dragon", anime: "One Piece", month: 10, day: 5 },
  { name: "Whitebeard", anime: "One Piece", month: 4, day: 6 },
  { name: "Blackbeard", anime: "One Piece", month: 8, day: 3 },
  { name: "Kaido", anime: "One Piece", month: 5, day: 1 },
  { name: "Big Mom", anime: "One Piece", month: 2, day: 15 },
  { name: "Yamato", anime: "One Piece", month: 11, day: 3 },
  { name: "Vivi Nefertari", anime: "One Piece", month: 2, day: 2 },
  { name: "Eustass Kid", anime: "One Piece", month: 1, day: 10 },
  { name: "Killer", anime: "One Piece", month: 2, day: 2 },
  { name: "Bartholomew Kuma", anime: "One Piece", month: 2, day: 9 },
  { name: "Perona", anime: "One Piece", month: 6, day: 7 },
  { name: "Buggy", anime: "One Piece", month: 8, day: 8 },
  { name: "Smoker", anime: "One Piece", month: 3, day: 14 },
  { name: "Tashigi", anime: "One Piece", month: 10, day: 6 },
  { name: "Coby", anime: "One Piece", month: 5, day: 13 },
  { name: "Helmeppo", anime: "One Piece", month: 7, day: 16 },
  { name: "Aokiji (Kuzan)", anime: "One Piece", month: 9, day: 21 },
  { name: "Kizaru (Borsalino)", anime: "One Piece", month: 11, day: 23 },
  { name: "Akainu (Sakazuki)", anime: "One Piece", month: 8, day: 16 },
  { name: "Fujitora (Issho)", anime: "One Piece", month: 8, day: 10 },
  { name: "Carrot", anime: "One Piece", month: 5, day: 24 },


  // ── Dragon Ball ──
  { name: "Goku (Son Goku)", anime: "Dragon Ball", month: 4, day: 16 },
  { name: "Vegeta", anime: "Dragon Ball", month: 8, day: 15 },
  { name: "Gohan", anime: "Dragon Ball", month: 5, day: 18 },
  { name: "Piccolo", anime: "Dragon Ball", month: 5, day: 9 },
  { name: "Krillin", anime: "Dragon Ball", month: 10, day: 29 },
  { name: "Trunks", anime: "Dragon Ball", month: 11, day: 1 },
  { name: "Goten", anime: "Dragon Ball", month: 3, day: 3 },
  { name: "Bulma", anime: "Dragon Ball", month: 8, day: 18 },
  { name: "Chi-Chi", anime: "Dragon Ball", month: 11, day: 5 },
  { name: "Android 18", anime: "Dragon Ball", month: 6, day: 1 },
  { name: "Android 17", anime: "Dragon Ball", month: 6, day: 1 },
  { name: "Frieza", anime: "Dragon Ball", month: 5, day: 3 },
  { name: "Cell", anime: "Dragon Ball", month: 6, day: 12 },
  { name: "Majin Buu", anime: "Dragon Ball", month: 5, day: 8 },
  { name: "Beerus", anime: "Dragon Ball", month: 1, day: 12 },
  { name: "Whis", anime: "Dragon Ball", month: 4, day: 1 },
  { name: "Broly", anime: "Dragon Ball", month: 4, day: 20 },
  { name: "Yamcha", anime: "Dragon Ball", month: 3, day: 20 },
  { name: "Tien Shinhan", anime: "Dragon Ball", month: 5, day: 12 },
  { name: "Master Roshi", anime: "Dragon Ball", month: 5, day: 28 },
  { name: "Mr. Satan (Hercule)", anime: "Dragon Ball", month: 3, day: 7 },
  { name: "Videl", anime: "Dragon Ball", month: 6, day: 14 },
  { name: "Pan", anime: "Dragon Ball", month: 5, day: 12 },
  { name: "Bardock", anime: "Dragon Ball", month: 6, day: 20 },
  { name: "Jiren", anime: "Dragon Ball", month: 2, day: 21 },
  { name: "Hit", anime: "Dragon Ball", month: 4, day: 8 },

  // ── Demon Slayer ──
  { name: "Tanjiro Kamado", anime: "Demon Slayer", month: 7, day: 14 },
  { name: "Nezuko Kamado", anime: "Demon Slayer", month: 12, day: 28 },
  { name: "Zenitsu Agatsuma", anime: "Demon Slayer", month: 9, day: 3 },
  { name: "Inosuke Hashibira", anime: "Demon Slayer", month: 4, day: 22 },
  { name: "Giyu Tomioka", anime: "Demon Slayer", month: 2, day: 8 },
  { name: "Shinobu Kocho", anime: "Demon Slayer", month: 2, day: 24 },
  { name: "Kyojuro Rengoku", anime: "Demon Slayer", month: 5, day: 10 },
  { name: "Tengen Uzui", anime: "Demon Slayer", month: 10, day: 31 },
  { name: "Mitsuri Kanroji", anime: "Demon Slayer", month: 6, day: 1 },
  { name: "Muichiro Tokito", anime: "Demon Slayer", month: 8, day: 8 },
  { name: "Obanai Iguro", anime: "Demon Slayer", month: 9, day: 15 },
  { name: "Sanemi Shinazugawa", anime: "Demon Slayer", month: 11, day: 29 },
  { name: "Gyomei Himejima", anime: "Demon Slayer", month: 8, day: 23 },
  { name: "Kanao Tsuyuri", anime: "Demon Slayer", month: 5, day: 19 },
  { name: "Genya Shinazugawa", anime: "Demon Slayer", month: 1, day: 7 },
  { name: "Muzan Kibutsuji", anime: "Demon Slayer", month: 7, day: 21 },
  { name: "Akaza", anime: "Demon Slayer", month: 4, day: 4 },
  { name: "Doma", anime: "Demon Slayer", month: 11, day: 14 },
  { name: "Kokushibo", anime: "Demon Slayer", month: 1, day: 20 },
  { name: "Tamayo", anime: "Demon Slayer", month: 7, day: 2 },
  { name: "Yushiro", anime: "Demon Slayer", month: 3, day: 29 },


  // ── Attack on Titan ──
  { name: "Eren Yeager", anime: "Attack on Titan", month: 3, day: 30 },
  { name: "Mikasa Ackerman", anime: "Attack on Titan", month: 2, day: 10 },
  { name: "Armin Arlert", anime: "Attack on Titan", month: 11, day: 3 },
  { name: "Levi Ackerman", anime: "Attack on Titan", month: 12, day: 25 },
  { name: "Erwin Smith", anime: "Attack on Titan", month: 10, day: 14 },
  { name: "Hange Zoe", anime: "Attack on Titan", month: 9, day: 5 },
  { name: "Jean Kirstein", anime: "Attack on Titan", month: 4, day: 7 },
  { name: "Connie Springer", anime: "Attack on Titan", month: 5, day: 2 },
  { name: "Sasha Blouse", anime: "Attack on Titan", month: 7, day: 26 },
  { name: "Historia Reiss", anime: "Attack on Titan", month: 1, day: 15 },
  { name: "Reiner Braun", anime: "Attack on Titan", month: 8, day: 1 },
  { name: "Bertholdt Hoover", anime: "Attack on Titan", month: 12, day: 30 },
  { name: "Annie Leonhart", anime: "Attack on Titan", month: 3, day: 22 },
  { name: "Zeke Yeager", anime: "Attack on Titan", month: 8, day: 1 },
  { name: "Gabi Braun", anime: "Attack on Titan", month: 4, day: 14 },
  { name: "Falco Grice", anime: "Attack on Titan", month: 2, day: 10 },
  { name: "Ymir", anime: "Attack on Titan", month: 2, day: 17 },
  { name: "Kenny Ackerman", anime: "Attack on Titan", month: 2, day: 4 },
  { name: "Petra Ral", anime: "Attack on Titan", month: 12, day: 6 },
  { name: "Marco Bott", anime: "Attack on Titan", month: 6, day: 16 },
  { name: "Pieck Finger", anime: "Attack on Titan", month: 8, day: 5 },
  { name: "Porco Galliard", anime: "Attack on Titan", month: 11, day: 11 },
  { name: "Grisha Yeager", anime: "Attack on Titan", month: 1, day: 26 },
  { name: "Floch Forster", anime: "Attack on Titan", month: 10, day: 8 },

  // ── My Hero Academia ──
  { name: "Izuku Midoriya (Deku)", anime: "My Hero Academia", month: 7, day: 15 },
  { name: "Bakugo Katsuki", anime: "My Hero Academia", month: 4, day: 20 },
  { name: "Todoroki Shoto", anime: "My Hero Academia", month: 1, day: 11 },
  { name: "Ochaco Uraraka", anime: "My Hero Academia", month: 12, day: 27 },
  { name: "Tenya Iida", anime: "My Hero Academia", month: 8, day: 22 },
  { name: "Tsuyu Asui", anime: "My Hero Academia", month: 2, day: 12 },
  { name: "Fumikage Tokoyami", anime: "My Hero Academia", month: 10, day: 30 },
  { name: "Eijiro Kirishima", anime: "My Hero Academia", month: 10, day: 16 },
  { name: "Denki Kaminari", anime: "My Hero Academia", month: 6, day: 29 },
  { name: "Momo Yaoyorozu", anime: "My Hero Academia", month: 9, day: 23 },
  { name: "Kyoka Jiro", anime: "My Hero Academia", month: 8, day: 1 },
  { name: "Mina Ashido", anime: "My Hero Academia", month: 7, day: 30 },
  { name: "Minoru Mineta", anime: "My Hero Academia", month: 10, day: 8 },
  { name: "Hanta Sero", anime: "My Hero Academia", month: 7, day: 28 },
  { name: "All Might", anime: "My Hero Academia", month: 6, day: 10 },
  { name: "Endeavor (Enji Todoroki)", anime: "My Hero Academia", month: 8, day: 8 },
  { name: "Hawks (Keigo Takami)", anime: "My Hero Academia", month: 12, day: 28 },
  { name: "Shigaraki Tomura", anime: "My Hero Academia", month: 4, day: 4 },
  { name: "Dabi (Toya Todoroki)", anime: "My Hero Academia", month: 1, day: 18 },
  { name: "Toga Himiko", anime: "My Hero Academia", month: 8, day: 7 },
  { name: "Twice (Jin Bubaigawara)", anime: "My Hero Academia", month: 5, day: 10 },
  { name: "Aizawa Shota", anime: "My Hero Academia", month: 11, day: 8 },
  { name: "Present Mic", anime: "My Hero Academia", month: 7, day: 7 },
  { name: "Mirio Togata", anime: "My Hero Academia", month: 7, day: 15 },
  { name: "Tamaki Amajiki", anime: "My Hero Academia", month: 3, day: 4 },
  { name: "Nejire Hado", anime: "My Hero Academia", month: 10, day: 6 },


  // ── Jujutsu Kaisen ──
  { name: "Gojo Satoru", anime: "Jujutsu Kaisen", month: 12, day: 7 },
  { name: "Yuji Itadori", anime: "Jujutsu Kaisen", month: 3, day: 20 },
  { name: "Megumi Fushiguro", anime: "Jujutsu Kaisen", month: 12, day: 22 },
  { name: "Nobara Kugisaki", anime: "Jujutsu Kaisen", month: 8, day: 7 },
  { name: "Sukuna", anime: "Jujutsu Kaisen", month: 1, day: 1 },
  { name: "Toge Inumaki", anime: "Jujutsu Kaisen", month: 10, day: 23 },
  { name: "Maki Zenin", anime: "Jujutsu Kaisen", month: 1, day: 20 },
  { name: "Panda", anime: "Jujutsu Kaisen", month: 3, day: 5 },
  { name: "Kento Nanami", anime: "Jujutsu Kaisen", month: 7, day: 3 },
  { name: "Todo Aoi", anime: "Jujutsu Kaisen", month: 9, day: 23 },
  { name: "Mai Zenin", anime: "Jujutsu Kaisen", month: 1, day: 20 },
  { name: "Yuta Okkotsu", anime: "Jujutsu Kaisen", month: 3, day: 7 },
  { name: "Suguru Geto", anime: "Jujutsu Kaisen", month: 2, day: 3 },
  { name: "Choso", anime: "Jujutsu Kaisen", month: 5, day: 20 },
  { name: "Toji Fushiguro", anime: "Jujutsu Kaisen", month: 12, day: 31 },
  { name: "Mahito", anime: "Jujutsu Kaisen", month: 7, day: 12 },
  { name: "Jogo", anime: "Jujutsu Kaisen", month: 3, day: 10 },
  { name: "Hanami", anime: "Jujutsu Kaisen", month: 4, day: 3 },
  { name: "Mei Mei", anime: "Jujutsu Kaisen", month: 11, day: 4 },
  { name: "Kasumi Miwa", anime: "Jujutsu Kaisen", month: 4, day: 4 },
  { name: "Hakari Kinji", anime: "Jujutsu Kaisen", month: 9, day: 10 },
  { name: "Momo Nishimiya", anime: "Jujutsu Kaisen", month: 7, day: 7 },

  // ── Death Note ──
  { name: "Light Yagami", anime: "Death Note", month: 2, day: 28 },
  { name: "L Lawliet", anime: "Death Note", month: 10, day: 31 },
  { name: "Misa Amane", anime: "Death Note", month: 12, day: 25 },
  { name: "Near (Nate River)", anime: "Death Note", month: 8, day: 24 },
  { name: "Mello (Mihael Keehl)", anime: "Death Note", month: 12, day: 13 },
  { name: "Ryuk", anime: "Death Note", month: 11, day: 1 },
  { name: "Rem", anime: "Death Note", month: 4, day: 13 },
  { name: "Soichiro Yagami", anime: "Death Note", month: 7, day: 12 },
  { name: "Watari", anime: "Death Note", month: 5, day: 1 },
  { name: "Matsuda Touta", anime: "Death Note", month: 12, day: 14 },

  // ── Fullmetal Alchemist ──
  { name: "Edward Elric", anime: "Fullmetal Alchemist", month: 2, day: 3 },
  { name: "Alphonse Elric", anime: "Fullmetal Alchemist", month: 4, day: 19 },
  { name: "Roy Mustang", anime: "Fullmetal Alchemist", month: 10, day: 11 },
  { name: "Riza Hawkeye", anime: "Fullmetal Alchemist", month: 10, day: 2 },
  { name: "Winry Rockbell", anime: "Fullmetal Alchemist", month: 6, day: 9 },
  { name: "Scar", anime: "Fullmetal Alchemist", month: 3, day: 12 },
  { name: "Maes Hughes", anime: "Fullmetal Alchemist", month: 4, day: 10 },
  { name: "Alex Louis Armstrong", anime: "Fullmetal Alchemist", month: 4, day: 3 },
  { name: "Ling Yao", anime: "Fullmetal Alchemist", month: 5, day: 20 },
  { name: "Greed", anime: "Fullmetal Alchemist", month: 6, day: 22 },
  { name: "King Bradley", anime: "Fullmetal Alchemist", month: 3, day: 14 },
  { name: "Olivier Mira Armstrong", anime: "Fullmetal Alchemist", month: 12, day: 3 },
  { name: "Lan Fan", anime: "Fullmetal Alchemist", month: 8, day: 13 },
  { name: "Izumi Curtis", anime: "Fullmetal Alchemist", month: 7, day: 15 },
  { name: "Van Hohenheim", anime: "Fullmetal Alchemist", month: 1, day: 15 },


  // ── Hunter x Hunter ──
  { name: "Gon Freecss", anime: "Hunter x Hunter", month: 5, day: 5 },
  { name: "Killua Zoldyck", anime: "Hunter x Hunter", month: 7, day: 7 },
  { name: "Kurapika", anime: "Hunter x Hunter", month: 4, day: 4 },
  { name: "Leorio Paradinight", anime: "Hunter x Hunter", month: 3, day: 3 },
  { name: "Hisoka Morow", anime: "Hunter x Hunter", month: 6, day: 6 },
  { name: "Chrollo Lucilfer", anime: "Hunter x Hunter", month: 11, day: 15 },
  { name: "Illumi Zoldyck", anime: "Hunter x Hunter", month: 11, day: 19 },
  { name: "Alluka Zoldyck", anime: "Hunter x Hunter", month: 5, day: 5 },
  { name: "Ging Freecss", anime: "Hunter x Hunter", month: 10, day: 11 },
  { name: "Meruem", anime: "Hunter x Hunter", month: 4, day: 3 },
  { name: "Neferpitou", anime: "Hunter x Hunter", month: 12, day: 8 },
  { name: "Kite", anime: "Hunter x Hunter", month: 3, day: 6 },
  { name: "Bisky", anime: "Hunter x Hunter", month: 6, day: 9 },
  { name: "Netero", anime: "Hunter x Hunter", month: 1, day: 1 },
  { name: "Feitan Portor", anime: "Hunter x Hunter", month: 2, day: 8 },
  { name: "Shalnark", anime: "Hunter x Hunter", month: 9, day: 9 },
  { name: "Machi Komacine", anime: "Hunter x Hunter", month: 6, day: 18 },
  { name: "Nobunaga Hazama", anime: "Hunter x Hunter", month: 9, day: 8 },
  { name: "Komugi", anime: "Hunter x Hunter", month: 1, day: 5 },
  { name: "Palm Siberia", anime: "Hunter x Hunter", month: 8, day: 20 },

  // ── Bleach ──
  { name: "Ichigo Kurosaki", anime: "Bleach", month: 7, day: 15 },
  { name: "Rukia Kuchiki", anime: "Bleach", month: 1, day: 14 },
  { name: "Orihime Inoue", anime: "Bleach", month: 9, day: 3 },
  { name: "Uryu Ishida", anime: "Bleach", month: 11, day: 6 },
  { name: "Renji Abarai", anime: "Bleach", month: 8, day: 31 },
  { name: "Byakuya Kuchiki", anime: "Bleach", month: 1, day: 31 },
  { name: "Toshiro Hitsugaya", anime: "Bleach", month: 12, day: 20 },
  { name: "Kenpachi Zaraki", anime: "Bleach", month: 11, day: 19 },
  { name: "Sosuke Aizen", anime: "Bleach", month: 5, day: 29 },
  { name: "Gin Ichimaru", anime: "Bleach", month: 9, day: 10 },
  { name: "Kisuke Urahara", anime: "Bleach", month: 12, day: 31 },
  { name: "Yoruichi Shihouin", anime: "Bleach", month: 1, day: 1 },
  { name: "Grimmjow Jaegerjaquez", anime: "Bleach", month: 7, day: 31 },
  { name: "Ulquiorra Cifer", anime: "Bleach", month: 12, day: 1 },
  { name: "Neliel Tu Odelschwanck", anime: "Bleach", month: 4, day: 24 },
  { name: "Shunsui Kyoraku", anime: "Bleach", month: 7, day: 11 },
  { name: "Jushiro Ukitake", anime: "Bleach", month: 12, day: 21 },
  { name: "Rangiku Matsumoto", anime: "Bleach", month: 9, day: 29 },
  { name: "Chad (Yasutora Sado)", anime: "Bleach", month: 4, day: 7 },
  { name: "Isshin Kurosaki", anime: "Bleach", month: 12, day: 10 },
  { name: "Mayuri Kurotsuchi", anime: "Bleach", month: 3, day: 30 },
  { name: "Unohana Retsu", anime: "Bleach", month: 4, day: 21 },
  { name: "Yamamoto Genryusai", anime: "Bleach", month: 1, day: 21 },
  { name: "Nemu Kurotsuchi", anime: "Bleach", month: 3, day: 30 },
  { name: "Shinji Hirako", anime: "Bleach", month: 5, day: 10 },


  // ── Fairy Tail ──
  { name: "Natsu Dragneel", anime: "Fairy Tail", month: 7, day: 7 },
  { name: "Lucy Heartfilia", anime: "Fairy Tail", month: 7, day: 1 },
  { name: "Erza Scarlet", anime: "Fairy Tail", month: 5, day: 15 },
  { name: "Gray Fullbuster", anime: "Fairy Tail", month: 2, day: 13 },
  { name: "Happy", anime: "Fairy Tail", month: 6, day: 20 },
  { name: "Wendy Marvell", anime: "Fairy Tail", month: 4, day: 1 },
  { name: "Gajeel Redfox", anime: "Fairy Tail", month: 6, day: 6 },
  { name: "Levy McGarden", anime: "Fairy Tail", month: 5, day: 21 },
  { name: "Juvia Lockser", anime: "Fairy Tail", month: 11, day: 27 },
  { name: "Laxus Dreyar", anime: "Fairy Tail", month: 11, day: 23 },
  { name: "Mirajane Strauss", anime: "Fairy Tail", month: 6, day: 15 },
  { name: "Elfman Strauss", anime: "Fairy Tail", month: 8, day: 22 },
  { name: "Cana Alberona", anime: "Fairy Tail", month: 7, day: 15 },
  { name: "Makarov Dreyar", anime: "Fairy Tail", month: 4, day: 1 },
  { name: "Jellal Fernandes", anime: "Fairy Tail", month: 7, day: 14 },
  { name: "Zeref Dragneel", anime: "Fairy Tail", month: 8, day: 7 },
  { name: "Mavis Vermillion", anime: "Fairy Tail", month: 3, day: 14 },
  { name: "Gildarts Clive", anime: "Fairy Tail", month: 5, day: 2 },

  // ── One Punch Man ──
  { name: "Saitama", anime: "One Punch Man", month: 3, day: 19 },
  { name: "Genos", anime: "One Punch Man", month: 7, day: 4 },
  { name: "Fubuki", anime: "One Punch Man", month: 5, day: 3 },
  { name: "Tatsumaki", anime: "One Punch Man", month: 2, day: 6 },
  { name: "Speed-o'-Sound Sonic", anime: "One Punch Man", month: 12, day: 12 },
  { name: "Garou", anime: "One Punch Man", month: 3, day: 3 },
  { name: "King", anime: "One Punch Man", month: 4, day: 8 },
  { name: "Mumen Rider", anime: "One Punch Man", month: 9, day: 22 },
  { name: "Metal Bat", anime: "One Punch Man", month: 10, day: 10 },
  { name: "Atomic Samurai", anime: "One Punch Man", month: 5, day: 5 },
  { name: "Bang (Silver Fang)", anime: "One Punch Man", month: 3, day: 11 },
  { name: "Blast", anime: "One Punch Man", month: 1, day: 1 },
  { name: "Drive Knight", anime: "One Punch Man", month: 6, day: 15 },
  { name: "Watchdog Man", anime: "One Punch Man", month: 11, day: 11 },

  // ── Black Clover ──
  { name: "Asta", anime: "Black Clover", month: 10, day: 4 },
  { name: "Yuno", anime: "Black Clover", month: 10, day: 4 },
  { name: "Noelle Silva", anime: "Black Clover", month: 11, day: 15 },
  { name: "Yami Sukehiro", anime: "Black Clover", month: 9, day: 17 },
  { name: "Julius Novachrono", anime: "Black Clover", month: 10, day: 15 },
  { name: "Luck Voltia", anime: "Black Clover", month: 10, day: 11 },
  { name: "Magna Swing", anime: "Black Clover", month: 4, day: 7 },
  { name: "Vanessa Enoteca", anime: "Black Clover", month: 4, day: 18 },
  { name: "Charmy Pappitson", anime: "Black Clover", month: 6, day: 2 },
  { name: "William Vangeance", anime: "Black Clover", month: 12, day: 24 },
  { name: "Mereoleona Vermillion", anime: "Black Clover", month: 7, day: 26 },
  { name: "Fuegoleon Vermillion", anime: "Black Clover", month: 8, day: 5 },
  { name: "Charlotte Roselei", anime: "Black Clover", month: 5, day: 31 },
  { name: "Gauche Adlai", anime: "Black Clover", month: 4, day: 14 },
  { name: "Finral Roulacase", anime: "Black Clover", month: 2, day: 6 },
  { name: "Langris Vaude", anime: "Black Clover", month: 2, day: 6 },
  { name: "Zenon Zogratis", anime: "Black Clover", month: 6, day: 18 },
  { name: "Dante Zogratis", anime: "Black Clover", month: 1, day: 9 },
  { name: "Vanica Zogratis", anime: "Black Clover", month: 3, day: 8 },


  // ── Tokyo Ghoul ──
  { name: "Kaneki Ken", anime: "Tokyo Ghoul", month: 12, day: 20 },
  { name: "Touka Kirishima", anime: "Tokyo Ghoul", month: 7, day: 1 },
  { name: "Hideyoshi Nagachika", anime: "Tokyo Ghoul", month: 6, day: 10 },
  { name: "Shuu Tsukiyama", anime: "Tokyo Ghoul", month: 3, day: 3 },
  { name: "Juuzou Suzuya", anime: "Tokyo Ghoul", month: 6, day: 8 },
  { name: "Ayato Kirishima", anime: "Tokyo Ghoul", month: 7, day: 4 },
  { name: "Hinami Fueguchi", anime: "Tokyo Ghoul", month: 5, day: 21 },
  { name: "Akira Mado", anime: "Tokyo Ghoul", month: 6, day: 6 },
  { name: "Eto Yoshimura", anime: "Tokyo Ghoul", month: 10, day: 13 },
  { name: "Arima Kishou", anime: "Tokyo Ghoul", month: 12, day: 20 },
  { name: "Nishiki Nishio", anime: "Tokyo Ghoul", month: 2, day: 4 },
  { name: "Rize Kamishiro", anime: "Tokyo Ghoul", month: 11, day: 8 },

  // ── Sword Art Online ──
  { name: "Kirito (Kazuto Kirigaya)", anime: "Sword Art Online", month: 10, day: 7 },
  { name: "Asuna Yuuki", anime: "Sword Art Online", month: 9, day: 30 },
  { name: "Sinon (Shino Asada)", anime: "Sword Art Online", month: 8, day: 21 },
  { name: "Leafa (Suguha Kirigaya)", anime: "Sword Art Online", month: 4, day: 19 },
  { name: "Klein (Ryotaro Tsuboi)", anime: "Sword Art Online", month: 10, day: 7 },
  { name: "Silica (Keiko Ayano)", anime: "Sword Art Online", month: 10, day: 4 },
  { name: "Lisbeth (Rika Shinozaki)", anime: "Sword Art Online", month: 10, day: 5 },
  { name: "Alice Zuberg", anime: "Sword Art Online", month: 4, day: 18 },
  { name: "Eugeo", anime: "Sword Art Online", month: 10, day: 27 },
  { name: "Heathcliff (Kayaba Akihiko)", anime: "Sword Art Online", month: 11, day: 6 },
  { name: "Yui", anime: "Sword Art Online", month: 10, day: 12 },

  // ── Re:Zero ──
  { name: "Subaru Natsuki", anime: "Re:Zero", month: 4, day: 1 },
  { name: "Emilia", anime: "Re:Zero", month: 9, day: 23 },
  { name: "Rem", anime: "Re:Zero", month: 2, day: 2 },
  { name: "Ram", anime: "Re:Zero", month: 2, day: 2 },
  { name: "Beatrice", anime: "Re:Zero", month: 4, day: 14 },
  { name: "Roswaal L Mathers", anime: "Re:Zero", month: 9, day: 16 },
  { name: "Felt", anime: "Re:Zero", month: 8, day: 8 },
  { name: "Reinhard van Astrea", anime: "Re:Zero", month: 1, day: 1 },
  { name: "Crusch Karsten", anime: "Re:Zero", month: 4, day: 4 },
  { name: "Echidna", anime: "Re:Zero", month: 7, day: 7 },
  { name: "Garfiel Tinsel", anime: "Re:Zero", month: 10, day: 12 },
  { name: "Otto Suwen", anime: "Re:Zero", month: 3, day: 24 },

  // ── Evangelion ──
  { name: "Shinji Ikari", anime: "Evangelion", month: 6, day: 6 },
  { name: "Asuka Langley Soryu", anime: "Evangelion", month: 12, day: 4 },
  { name: "Rei Ayanami", anime: "Evangelion", month: 3, day: 30 },
  { name: "Misato Katsuragi", anime: "Evangelion", month: 12, day: 8 },
  { name: "Kaworu Nagisa", anime: "Evangelion", month: 9, day: 13 },
  { name: "Gendo Ikari", anime: "Evangelion", month: 4, day: 29 },
  { name: "Ritsuko Akagi", anime: "Evangelion", month: 11, day: 21 },
  { name: "Mari Makinami", anime: "Evangelion", month: 3, day: 30 },


  // ── Code Geass ──
  { name: "Lelouch Lamperouge", anime: "Code Geass", month: 12, day: 5 },
  { name: "Suzaku Kururugi", anime: "Code Geass", month: 7, day: 10 },
  { name: "C.C.", anime: "Code Geass", month: 3, day: 14 },
  { name: "Kallen Kozuki", anime: "Code Geass", month: 3, day: 29 },
  { name: "Nunnally Lamperouge", anime: "Code Geass", month: 10, day: 25 },
  { name: "Cornelia li Britannia", anime: "Code Geass", month: 1, day: 13 },
  { name: "Euphemia li Britannia", anime: "Code Geass", month: 10, day: 11 },
  { name: "Shirley Fenette", anime: "Code Geass", month: 7, day: 2 },
  { name: "Jeremiah Gottwald", anime: "Code Geass", month: 5, day: 5 },

  // ── Cowboy Bebop ──
  { name: "Spike Spiegel", anime: "Cowboy Bebop", month: 6, day: 26 },
  { name: "Jet Black", anime: "Cowboy Bebop", month: 12, day: 3 },
  { name: "Faye Valentine", anime: "Cowboy Bebop", month: 8, day: 14 },
  { name: "Edward Wong", anime: "Cowboy Bebop", month: 1, day: 1 },
  { name: "Vicious", anime: "Cowboy Bebop", month: 7, day: 18 },
  { name: "Julia", anime: "Cowboy Bebop", month: 2, day: 5 },

  // ── Chainsaw Man ──
  { name: "Denji", anime: "Chainsaw Man", month: 1, day: 1 },
  { name: "Makima", anime: "Chainsaw Man", month: 1, day: 6 },
  { name: "Power", anime: "Chainsaw Man", month: 5, day: 12 },
  { name: "Aki Hayakawa", anime: "Chainsaw Man", month: 11, day: 5 },
  { name: "Pochita", anime: "Chainsaw Man", month: 1, day: 1 },
  { name: "Himeno", anime: "Chainsaw Man", month: 8, day: 12 },
  { name: "Kobeni Higashiyama", anime: "Chainsaw Man", month: 3, day: 3 },
  { name: "Kishibe", anime: "Chainsaw Man", month: 7, day: 7 },
  { name: "Reze", anime: "Chainsaw Man", month: 6, day: 6 },
  { name: "Quanxi", anime: "Chainsaw Man", month: 12, day: 12 },
  { name: "Angel Devil", anime: "Chainsaw Man", month: 4, day: 15 },
  { name: "Asa Mitaka", anime: "Chainsaw Man", month: 10, day: 10 },
  { name: "Yoru (War Devil)", anime: "Chainsaw Man", month: 4, day: 4 },
  { name: "Nayuta", anime: "Chainsaw Man", month: 5, day: 25 },
  { name: "Yoshida Hirofumi", anime: "Chainsaw Man", month: 9, day: 9 },

  // ── Spy x Family ──
  { name: "Loid Forger (Twilight)", anime: "Spy x Family", month: 10, day: 14 },
  { name: "Yor Forger", anime: "Spy x Family", month: 6, day: 18 },
  { name: "Anya Forger", anime: "Spy x Family", month: 10, day: 2 },
  { name: "Bond Forger", anime: "Spy x Family", month: 10, day: 11 },
  { name: "Damian Desmond", anime: "Spy x Family", month: 10, day: 1 },
  { name: "Becky Blackbell", anime: "Spy x Family", month: 3, day: 6 },
  { name: "Franky Franklin", anime: "Spy x Family", month: 4, day: 2 },
  { name: "Fiona Frost (Nightfall)", anime: "Spy x Family", month: 2, day: 14 },
  { name: "Yuri Briar", anime: "Spy x Family", month: 3, day: 11 },
  { name: "Handler (Sylvia Sherwood)", anime: "Spy x Family", month: 8, day: 25 },

  // ── Mob Psycho 100 ──
  { name: "Mob (Shigeo Kageyama)", anime: "Mob Psycho 100", month: 5, day: 12 },
  { name: "Reigen Arataka", anime: "Mob Psycho 100", month: 10, day: 10 },
  { name: "Dimple", anime: "Mob Psycho 100", month: 9, day: 9 },
  { name: "Ritsu Kageyama", anime: "Mob Psycho 100", month: 7, day: 2 },
  { name: "Teruki Hanazawa", anime: "Mob Psycho 100", month: 11, day: 23 },
  { name: "Sho Suzuki", anime: "Mob Psycho 100", month: 3, day: 15 },
  { name: "Serizawa Katsuya", anime: "Mob Psycho 100", month: 4, day: 29 },


  // ── Dr. Stone ──
  { name: "Senku Ishigami", anime: "Dr. Stone", month: 1, day: 4 },
  { name: "Taiju Oki", anime: "Dr. Stone", month: 4, day: 1 },
  { name: "Yuzuriha Ogawa", anime: "Dr. Stone", month: 8, day: 12 },
  { name: "Chrome", anime: "Dr. Stone", month: 7, day: 27 },
  { name: "Kohaku", anime: "Dr. Stone", month: 8, day: 8 },
  { name: "Gen Asagiri", anime: "Dr. Stone", month: 4, day: 1 },
  { name: "Ryusui Nanami", anime: "Dr. Stone", month: 11, day: 11 },
  { name: "Tsukasa Shishio", anime: "Dr. Stone", month: 1, day: 18 },
  { name: "Suika", anime: "Dr. Stone", month: 5, day: 6 },
  { name: "Kaseki", anime: "Dr. Stone", month: 10, day: 1 },

  // ── Haikyuu ──
  { name: "Hinata Shoyo", anime: "Haikyuu", month: 6, day: 21 },
  { name: "Kageyama Tobio", anime: "Haikyuu", month: 12, day: 22 },
  { name: "Tsukishima Kei", anime: "Haikyuu", month: 9, day: 27 },
  { name: "Yamaguchi Tadashi", anime: "Haikyuu", month: 11, day: 10 },
  { name: "Tanaka Ryunosuke", anime: "Haikyuu", month: 3, day: 3 },
  { name: "Nishinoya Yu", anime: "Haikyuu", month: 10, day: 10 },
  { name: "Sugawara Koushi", anime: "Haikyuu", month: 6, day: 13 },
  { name: "Sawamura Daichi", anime: "Haikyuu", month: 12, day: 31 },
  { name: "Azumane Asahi", anime: "Haikyuu", month: 1, day: 1 },
  { name: "Oikawa Tooru", anime: "Haikyuu", month: 7, day: 20 },
  { name: "Iwaizumi Hajime", anime: "Haikyuu", month: 6, day: 10 },
  { name: "Kuroo Tetsuro", anime: "Haikyuu", month: 11, day: 17 },
  { name: "Kenma Kozume", anime: "Haikyuu", month: 10, day: 16 },
  { name: "Bokuto Koutarou", anime: "Haikyuu", month: 9, day: 20 },
  { name: "Akaashi Keiji", anime: "Haikyuu", month: 12, day: 5 },
  { name: "Ushijima Wakatoshi", anime: "Haikyuu", month: 8, day: 13 },
  { name: "Tendou Satori", anime: "Haikyuu", month: 5, day: 20 },
  { name: "Atsumu Miya", anime: "Haikyuu", month: 10, day: 5 },
  { name: "Osamu Miya", anime: "Haikyuu", month: 10, day: 5 },
  { name: "Sakusa Kiyoomi", anime: "Haikyuu", month: 3, day: 20 },
  { name: "Kita Shinsuke", anime: "Haikyuu", month: 7, day: 5 },

  // ── Sailor Moon ──
  { name: "Usagi Tsukino (Sailor Moon)", anime: "Sailor Moon", month: 6, day: 30 },
  { name: "Ami Mizuno (Sailor Mercury)", anime: "Sailor Moon", month: 9, day: 10 },
  { name: "Rei Hino (Sailor Mars)", anime: "Sailor Moon", month: 4, day: 17 },
  { name: "Makoto Kino (Sailor Jupiter)", anime: "Sailor Moon", month: 12, day: 5 },
  { name: "Minako Aino (Sailor Venus)", anime: "Sailor Moon", month: 10, day: 22 },
  { name: "Chibiusa", anime: "Sailor Moon", month: 6, day: 30 },
  { name: "Haruka Tenoh (Sailor Uranus)", anime: "Sailor Moon", month: 1, day: 27 },
  { name: "Michiru Kaioh (Sailor Neptune)", anime: "Sailor Moon", month: 3, day: 6 },
  { name: "Setsuna Meioh (Sailor Pluto)", anime: "Sailor Moon", month: 10, day: 29 },
  { name: "Hotaru Tomoe (Sailor Saturn)", anime: "Sailor Moon", month: 1, day: 6 },
  { name: "Tuxedo Mask (Mamoru Chiba)", anime: "Sailor Moon", month: 8, day: 3 },
  { name: "Luna", anime: "Sailor Moon", month: 4, day: 15 },


  // ── Tokyo Revengers ──
  { name: "Takemichi Hanagaki", anime: "Tokyo Revengers", month: 6, day: 25 },
  { name: "Mikey (Manjiro Sano)", anime: "Tokyo Revengers", month: 8, day: 20 },
  { name: "Draken (Ken Ryuguji)", anime: "Tokyo Revengers", month: 5, day: 10 },
  { name: "Baji Keisuke", anime: "Tokyo Revengers", month: 11, day: 3 },
  { name: "Chifuyu Matsuno", anime: "Tokyo Revengers", month: 12, day: 19 },
  { name: "Kazutora Hanemiya", anime: "Tokyo Revengers", month: 9, day: 16 },
  { name: "Hinata Tachibana", anime: "Tokyo Revengers", month: 5, day: 21 },
  { name: "Naoto Tachibana", anime: "Tokyo Revengers", month: 4, day: 12 },
  { name: "Izana Kurokawa", anime: "Tokyo Revengers", month: 8, day: 30 },
  { name: "Kakucho", anime: "Tokyo Revengers", month: 4, day: 4 },
  { name: "South Terano", anime: "Tokyo Revengers", month: 3, day: 15 },
  { name: "Senju Kawaragi", anime: "Tokyo Revengers", month: 5, day: 1 },
  { name: "Hanma Shuji", anime: "Tokyo Revengers", month: 10, day: 27 },

  // ── Vinland Saga ──
  { name: "Thorfinn", anime: "Vinland Saga", month: 2, day: 2 },
  { name: "Askeladd", anime: "Vinland Saga", month: 7, day: 1 },
  { name: "Thorkell", anime: "Vinland Saga", month: 11, day: 15 },
  { name: "Canute", anime: "Vinland Saga", month: 7, day: 14 },
  { name: "Einar", anime: "Vinland Saga", month: 3, day: 23 },
  { name: "Gudrid", anime: "Vinland Saga", month: 6, day: 10 },
  { name: "Thors", anime: "Vinland Saga", month: 1, day: 5 },
  { name: "Bjorn", anime: "Vinland Saga", month: 10, day: 28 },
  { name: "Floki", anime: "Vinland Saga", month: 8, day: 17 },
  { name: "Snake", anime: "Vinland Saga", month: 12, day: 12 },

  // ── Steins;Gate ──
  { name: "Rintaro Okabe", anime: "Steins;Gate", month: 12, day: 14 },
  { name: "Kurisu Makise", anime: "Steins;Gate", month: 7, day: 25 },
  { name: "Mayuri Shiina", anime: "Steins;Gate", month: 2, day: 1 },
  { name: "Itaru Hashida (Daru)", anime: "Steins;Gate", month: 5, day: 19 },
  { name: "Moeka Kiryu", anime: "Steins;Gate", month: 6, day: 6 },
  { name: "Suzuha Amane", anime: "Steins;Gate", month: 9, day: 27 },
  { name: "Faris Nyannyan", anime: "Steins;Gate", month: 4, day: 3 },
  { name: "Ruka Urushibara", anime: "Steins;Gate", month: 8, day: 30 },

  // ── Inuyasha ──
  { name: "Inuyasha", anime: "Inuyasha", month: 5, day: 27 },
  { name: "Kagome Higurashi", anime: "Inuyasha", month: 6, day: 18 },
  { name: "Sesshomaru", anime: "Inuyasha", month: 9, day: 16 },
  { name: "Miroku", anime: "Inuyasha", month: 10, day: 15 },
  { name: "Sango", anime: "Inuyasha", month: 3, day: 1 },
  { name: "Shippo", anime: "Inuyasha", month: 1, day: 15 },
  { name: "Kikyo", anime: "Inuyasha", month: 8, day: 18 },
  { name: "Naraku", anime: "Inuyasha", month: 5, day: 25 },
  { name: "Koga", anime: "Inuyasha", month: 2, day: 14 },
  { name: "Rin", anime: "Inuyasha", month: 12, day: 15 },


  // ── Fruits Basket ──
  { name: "Tohru Honda", anime: "Fruits Basket", month: 5, day: 6 },
  { name: "Kyo Sohma", anime: "Fruits Basket", month: 6, day: 2 },
  { name: "Yuki Sohma", anime: "Fruits Basket", month: 9, day: 5 },
  { name: "Shigure Sohma", anime: "Fruits Basket", month: 11, day: 1 },
  { name: "Hatori Sohma", anime: "Fruits Basket", month: 1, day: 1 },
  { name: "Momiji Sohma", anime: "Fruits Basket", month: 6, day: 15 },
  { name: "Hatsuharu Sohma", anime: "Fruits Basket", month: 3, day: 15 },
  { name: "Akito Sohma", anime: "Fruits Basket", month: 6, day: 22 },
  { name: "Rin Sohma", anime: "Fruits Basket", month: 7, day: 23 },
  { name: "Kagura Sohma", anime: "Fruits Basket", month: 11, day: 22 },
  { name: "Ayame Sohma", anime: "Fruits Basket", month: 4, day: 14 },
  { name: "Kisa Sohma", anime: "Fruits Basket", month: 6, day: 8 },

  // ── Violet Evergarden ──
  { name: "Violet Evergarden", anime: "Violet Evergarden", month: 1, day: 1 },
  { name: "Gilbert Bougainvillea", anime: "Violet Evergarden", month: 8, day: 24 },
  { name: "Claudia Hodgins", anime: "Violet Evergarden", month: 5, day: 5 },
  { name: "Cattleya Baudelaire", anime: "Violet Evergarden", month: 7, day: 14 },
  { name: "Erica Brown", anime: "Violet Evergarden", month: 11, day: 3 },
  { name: "Iris Cannary", anime: "Violet Evergarden", month: 6, day: 15 },

  // ── Gintama ──
  { name: "Gintoki Sakata", anime: "Gintama", month: 10, day: 10 },
  { name: "Shinpachi Shimura", anime: "Gintama", month: 8, day: 12 },
  { name: "Kagura", anime: "Gintama", month: 11, day: 3 },
  { name: "Kotaro Katsura", anime: "Gintama", month: 6, day: 26 },
  { name: "Shinsuke Takasugi", anime: "Gintama", month: 8, day: 10 },
  { name: "Toshiro Hijikata", anime: "Gintama", month: 5, day: 5 },
  { name: "Sougo Okita", anime: "Gintama", month: 7, day: 8 },
  { name: "Isao Kondo", anime: "Gintama", month: 9, day: 4 },
  { name: "Tsukuyo", anime: "Gintama", month: 2, day: 9 },
  { name: "Kamui", anime: "Gintama", month: 6, day: 1 },
  { name: "Taizo Hasegawa (Madao)", anime: "Gintama", month: 5, day: 20 },
  { name: "Elizabeth", anime: "Gintama", month: 9, day: 7 },

  // ── Demon Slayer (more) ──
  { name: "Kagaya Ubuyashiki", anime: "Demon Slayer", month: 1, day: 1 },
  { name: "Rui", anime: "Demon Slayer", month: 8, day: 28 },
  { name: "Enmu", anime: "Demon Slayer", month: 11, day: 7 },
  { name: "Gyutaro", anime: "Demon Slayer", month: 3, day: 14 },
  { name: "Daki", anime: "Demon Slayer", month: 3, day: 14 },
  { name: "Hantengu", anime: "Demon Slayer", month: 5, day: 30 },
  { name: "Gyokko", anime: "Demon Slayer", month: 4, day: 26 },

  // ── Jojo's Bizarre Adventure ──
  { name: "Jonathan Joestar", anime: "JoJo's Bizarre Adventure", month: 4, day: 4 },
  { name: "Joseph Joestar", anime: "JoJo's Bizarre Adventure", month: 9, day: 27 },
  { name: "Jotaro Kujo", anime: "JoJo's Bizarre Adventure", month: 1, day: 1 },
  { name: "Josuke Higashikata", anime: "JoJo's Bizarre Adventure", month: 8, day: 13 },
  { name: "Giorno Giovanna", anime: "JoJo's Bizarre Adventure", month: 4, day: 16 },
  { name: "Jolyne Cujoh", anime: "JoJo's Bizarre Adventure", month: 8, day: 11 },
  { name: "Dio Brando", anime: "JoJo's Bizarre Adventure", month: 4, day: 12 },
  { name: "Bruno Bucciarati", anime: "JoJo's Bizarre Adventure", month: 9, day: 27 },
  { name: "Noriaki Kakyoin", anime: "JoJo's Bizarre Adventure", month: 8, day: 5 },
  { name: "Jean Pierre Polnareff", anime: "JoJo's Bizarre Adventure", month: 6, day: 23 },
  { name: "Caesar Zeppeli", anime: "JoJo's Bizarre Adventure", month: 5, day: 13 },
  { name: "Muhammad Avdol", anime: "JoJo's Bizarre Adventure", month: 6, day: 2 },
  { name: "Rohan Kishibe", anime: "JoJo's Bizarre Adventure", month: 11, day: 28 },
  { name: "Koichi Hirose", anime: "JoJo's Bizarre Adventure", month: 3, day: 28 },
  { name: "Trish Una", anime: "JoJo's Bizarre Adventure", month: 7, day: 8 },
  { name: "Guido Mista", anime: "JoJo's Bizarre Adventure", month: 12, day: 3 },
  { name: "Narancia Ghirga", anime: "JoJo's Bizarre Adventure", month: 5, day: 20 },
  { name: "Leone Abbacchio", anime: "JoJo's Bizarre Adventure", month: 3, day: 25 },


  // ── Assassination Classroom ──
  { name: "Koro-sensei", anime: "Assassination Classroom", month: 3, day: 13 },
  { name: "Nagisa Shiota", anime: "Assassination Classroom", month: 7, day: 20 },
  { name: "Karma Akabane", anime: "Assassination Classroom", month: 12, day: 25 },
  { name: "Kaede Kayano", anime: "Assassination Classroom", month: 1, day: 9 },
  { name: "Tadaomi Karasuma", anime: "Assassination Classroom", month: 8, day: 15 },
  { name: "Irina Jelavic", anime: "Assassination Classroom", month: 10, day: 10 },
  { name: "Itona Horibe", anime: "Assassination Classroom", month: 11, day: 8 },
  { name: "Rio Nakamura", anime: "Assassination Classroom", month: 8, day: 24 },
  { name: "Isogai Yuuma", anime: "Assassination Classroom", month: 11, day: 23 },
  { name: "Maehara Hiroto", anime: "Assassination Classroom", month: 12, day: 6 },

  // ── The Promised Neverland ──
  { name: "Emma", anime: "The Promised Neverland", month: 8, day: 22 },
  { name: "Norman", anime: "The Promised Neverland", month: 3, day: 21 },
  { name: "Ray", anime: "The Promised Neverland", month: 1, day: 15 },
  { name: "Isabella (Mama)", anime: "The Promised Neverland", month: 10, day: 5 },
  { name: "Phil", anime: "The Promised Neverland", month: 3, day: 14 },
  { name: "Gilda", anime: "The Promised Neverland", month: 6, day: 28 },
  { name: "Don", anime: "The Promised Neverland", month: 9, day: 16 },
  { name: "Mujika", anime: "The Promised Neverland", month: 11, day: 12 },

  // ── Fire Force ──
  { name: "Shinra Kusakabe", anime: "Fire Force", month: 10, day: 29 },
  { name: "Arthur Boyle", anime: "Fire Force", month: 7, day: 10 },
  { name: "Maki Oze", anime: "Fire Force", month: 9, day: 16 },
  { name: "Tamaki Kotatsu", anime: "Fire Force", month: 2, day: 22 },
  { name: "Akitaru Obi", anime: "Fire Force", month: 3, day: 27 },
  { name: "Takehisa Hinawa", anime: "Fire Force", month: 6, day: 17 },
  { name: "Iris", anime: "Fire Force", month: 4, day: 10 },
  { name: "Benimaru Shinmon", anime: "Fire Force", month: 2, day: 20 },
  { name: "Joker", anime: "Fire Force", month: 12, day: 25 },
  { name: "Sho Kusakabe", anime: "Fire Force", month: 3, day: 5 },

  // ── Noragami ──
  { name: "Yato", anime: "Noragami", month: 1, day: 1 },
  { name: "Hiyori Iki", anime: "Noragami", month: 9, day: 28 },
  { name: "Yukine", anime: "Noragami", month: 6, day: 8 },
  { name: "Bishamon", anime: "Noragami", month: 3, day: 3 },
  { name: "Kazuma", anime: "Noragami", month: 8, day: 7 },
  { name: "Kofuku", anime: "Noragami", month: 4, day: 1 },
  { name: "Daikoku", anime: "Noragami", month: 11, day: 15 },
  { name: "Nora (Hiiro)", anime: "Noragami", month: 7, day: 7 },

  // ── Toradora ──
  { name: "Taiga Aisaka", anime: "Toradora", month: 7, day: 27 },
  { name: "Ryuuji Takasu", anime: "Toradora", month: 4, day: 18 },
  { name: "Minori Kushieda", anime: "Toradora", month: 3, day: 4 },
  { name: "Ami Kawashima", anime: "Toradora", month: 8, day: 18 },
  { name: "Yusaku Kitamura", anime: "Toradora", month: 4, day: 15 },

  // ── Your Lie in April ──
  { name: "Kousei Arima", anime: "Your Lie in April", month: 3, day: 28 },
  { name: "Kaori Miyazono", anime: "Your Lie in April", month: 7, day: 4 },
  { name: "Tsubaki Sawabe", anime: "Your Lie in April", month: 5, day: 19 },
  { name: "Ryota Watari", anime: "Your Lie in April", month: 11, day: 11 },


  // ── Jujutsu Kaisen (more) ──
  { name: "Kenjaku", anime: "Jujutsu Kaisen", month: 6, day: 3 },
  { name: "Yorozu", anime: "Jujutsu Kaisen", month: 8, day: 14 },
  { name: "Hajime Kashimo", anime: "Jujutsu Kaisen", month: 2, day: 15 },
  { name: "Higuruma Hiromi", anime: "Jujutsu Kaisen", month: 6, day: 26 },
  { name: "Takaba Fumihiko", anime: "Jujutsu Kaisen", month: 11, day: 20 },

  // ── Neon Genesis ──
  { name: "Ryoji Kaji", anime: "Evangelion", month: 6, day: 17 },
  { name: "Toji Suzuhara", anime: "Evangelion", month: 12, day: 26 },
  { name: "Kensuke Aida", anime: "Evangelion", month: 9, day: 12 },
  { name: "Hikari Horaki", anime: "Evangelion", month: 2, day: 18 },

  // ── Trigun ──
  { name: "Vash the Stampede", anime: "Trigun", month: 7, day: 21 },
  { name: "Nicholas D. Wolfwood", anime: "Trigun", month: 11, day: 7 },
  { name: "Rem Saverem", anime: "Trigun", month: 3, day: 10 },
  { name: "Meryl Stryfe", anime: "Trigun", month: 1, day: 18 },
  { name: "Milly Thompson", anime: "Trigun", month: 12, day: 9 },
  { name: "Knives Millions", anime: "Trigun", month: 7, day: 21 },

  // ── Blue Lock ──
  { name: "Isagi Yoichi", anime: "Blue Lock", month: 4, day: 1 },
  { name: "Bachira Meguru", anime: "Blue Lock", month: 8, day: 8 },
  { name: "Chigiri Hyoma", anime: "Blue Lock", month: 6, day: 20 },
  { name: "Kunigami Rensuke", anime: "Blue Lock", month: 11, day: 5 },
  { name: "Nagi Seishiro", anime: "Blue Lock", month: 7, day: 7 },
  { name: "Mikage Reo", anime: "Blue Lock", month: 7, day: 7 },
  { name: "Barou Shouei", anime: "Blue Lock", month: 6, day: 18 },
  { name: "Itoshi Rin", anime: "Blue Lock", month: 12, day: 3 },
  { name: "Itoshi Sae", anime: "Blue Lock", month: 3, day: 30 },
  { name: "Michael Kaiser", anime: "Blue Lock", month: 5, day: 8 },
  { name: "Alexis Ness", anime: "Blue Lock", month: 10, day: 1 },
  { name: "Tokimitsu Aoshi", anime: "Blue Lock", month: 9, day: 9 },
  { name: "Ego Jinpachi", anime: "Blue Lock", month: 1, day: 1 },
  { name: "Anri Teieri", anime: "Blue Lock", month: 3, day: 3 },

  // ── Kuroko no Basket ──
  { name: "Kuroko Tetsuya", anime: "Kuroko no Basket", month: 1, day: 31 },
  { name: "Kagami Taiga", anime: "Kuroko no Basket", month: 8, day: 2 },
  { name: "Kise Ryota", anime: "Kuroko no Basket", month: 6, day: 18 },
  { name: "Midorima Shintaro", anime: "Kuroko no Basket", month: 7, day: 7 },
  { name: "Aomine Daiki", anime: "Kuroko no Basket", month: 8, day: 31 },
  { name: "Murasakibara Atsushi", anime: "Kuroko no Basket", month: 10, day: 9 },
  { name: "Akashi Seijuro", anime: "Kuroko no Basket", month: 12, day: 20 },
  { name: "Momoi Satsuki", anime: "Kuroko no Basket", month: 5, day: 4 },
  { name: "Hyuga Junpei", anime: "Kuroko no Basket", month: 5, day: 16 },
  { name: "Kiyoshi Teppei", anime: "Kuroko no Basket", month: 6, day: 10 },
  { name: "Takao Kazunari", anime: "Kuroko no Basket", month: 11, day: 21 },
  { name: "Himuro Tatsuya", anime: "Kuroko no Basket", month: 10, day: 30 },
  { name: "Aida Riko", anime: "Kuroko no Basket", month: 2, day: 5 },


  // ── Demon Slayer (Hashira extras) ──
  { name: "Sakonji Urokodaki", anime: "Demon Slayer", month: 1, day: 10 },
  { name: "Makomo", anime: "Demon Slayer", month: 4, day: 18 },
  { name: "Sabito", anime: "Demon Slayer", month: 5, day: 14 },
  { name: "Mitsuri's Snake (Kaburamaru)", anime: "Demon Slayer", month: 9, day: 15 },

  // ── Dororo ──
  { name: "Hyakkimaru", anime: "Dororo", month: 11, day: 1 },
  { name: "Dororo", anime: "Dororo", month: 4, day: 5 },
  { name: "Daigo Kagemitsu", anime: "Dororo", month: 8, day: 12 },
  { name: "Mio", anime: "Dororo", month: 6, day: 6 },

  // ── Death Parade ──
  { name: "Decim", anime: "Death Parade", month: 12, day: 3 },
  { name: "Chiyuki", anime: "Death Parade", month: 5, day: 15 },
  { name: "Nona", anime: "Death Parade", month: 9, day: 9 },
  { name: "Ginti", anime: "Death Parade", month: 2, day: 8 },

  // ── Parasyte ──
  { name: "Shinichi Izumi", anime: "Parasyte", month: 7, day: 18 },
  { name: "Migi", anime: "Parasyte", month: 7, day: 18 },
  { name: "Satomi Murano", anime: "Parasyte", month: 4, day: 22 },
  { name: "Tamura Reiko", anime: "Parasyte", month: 12, day: 1 },
  { name: "Gotou", anime: "Parasyte", month: 8, day: 27 },

  // ── Mushoku Tensei ──
  { name: "Rudeus Greyrat", anime: "Mushoku Tensei", month: 2, day: 24 },
  { name: "Eris Boreas Greyrat", anime: "Mushoku Tensei", month: 8, day: 12 },
  { name: "Roxy Migurdia", anime: "Mushoku Tensei", month: 4, day: 24 },
  { name: "Sylphiette", anime: "Mushoku Tensei", month: 1, day: 29 },
  { name: "Paul Greyrat", anime: "Mushoku Tensei", month: 7, day: 1 },
  { name: "Zenith Greyrat", anime: "Mushoku Tensei", month: 3, day: 30 },
  { name: "Ruijerd Superdia", anime: "Mushoku Tensei", month: 5, day: 18 },
  { name: "Ghislaine Dedoldia", anime: "Mushoku Tensei", month: 10, day: 20 },
  { name: "Orsted", anime: "Mushoku Tensei", month: 12, day: 30 },
  { name: "Kishirika Kishirisu", anime: "Mushoku Tensei", month: 6, day: 14 },

  // ── Konosuba ──
  { name: "Kazuma Satou", anime: "Konosuba", month: 6, day: 7 },
  { name: "Aqua", anime: "Konosuba", month: 8, day: 1 },
  { name: "Megumin", anime: "Konosuba", month: 12, day: 4 },
  { name: "Darkness (Lalatina)", anime: "Konosuba", month: 7, day: 6 },
  { name: "Wiz", anime: "Konosuba", month: 1, day: 12 },
  { name: "Yunyun", anime: "Konosuba", month: 2, day: 29 },
  { name: "Vanir", anime: "Konosuba", month: 4, day: 1 },
  { name: "Chris", anime: "Konosuba", month: 12, day: 25 },

  // ── Overlord ──
  { name: "Ainz Ooal Gown (Momonga)", anime: "Overlord", month: 5, day: 8 },
  { name: "Albedo", anime: "Overlord", month: 7, day: 23 },
  { name: "Shalltear Bloodfallen", anime: "Overlord", month: 4, day: 1 },
  { name: "Demiurge", anime: "Overlord", month: 12, day: 12 },
  { name: "Cocytus", anime: "Overlord", month: 1, day: 1 },
  { name: "Aura Bella Fiora", anime: "Overlord", month: 8, day: 3 },
  { name: "Mare Bello Fiore", anime: "Overlord", month: 8, day: 3 },
  { name: "Sebas Tian", anime: "Overlord", month: 4, day: 14 },
  { name: "Narberal Gamma", anime: "Overlord", month: 5, day: 9 },
  { name: "Pandora's Actor", anime: "Overlord", month: 7, day: 7 },


  // ── Shield Hero ──
  { name: "Naofumi Iwatani", anime: "The Rising of the Shield Hero", month: 12, day: 24 },
  { name: "Raphtalia", anime: "The Rising of the Shield Hero", month: 1, day: 14 },
  { name: "Filo", anime: "The Rising of the Shield Hero", month: 3, day: 25 },
  { name: "Melty Q Melromarc", anime: "The Rising of the Shield Hero", month: 5, day: 8 },
  { name: "Rishia Ivyred", anime: "The Rising of the Shield Hero", month: 7, day: 20 },

  // ── That Time I Got Reincarnated as a Slime ──
  { name: "Rimuru Tempest", anime: "That Time I Got Reincarnated as a Slime", month: 10, day: 8 },
  { name: "Shion", anime: "That Time I Got Reincarnated as a Slime", month: 2, day: 14 },
  { name: "Shuna", anime: "That Time I Got Reincarnated as a Slime", month: 3, day: 3 },
  { name: "Benimaru", anime: "That Time I Got Reincarnated as a Slime", month: 7, day: 28 },
  { name: "Milim Nava", anime: "That Time I Got Reincarnated as a Slime", month: 5, day: 20 },
  { name: "Veldora Tempest", anime: "That Time I Got Reincarnated as a Slime", month: 8, day: 8 },
  { name: "Diablo", anime: "That Time I Got Reincarnated as a Slime", month: 12, day: 25 },
  { name: "Gobta", anime: "That Time I Got Reincarnated as a Slime", month: 4, day: 1 },
  { name: "Hinata Sakaguchi", anime: "That Time I Got Reincarnated as a Slime", month: 6, day: 6 },
  { name: "Guy Crimson", anime: "That Time I Got Reincarnated as a Slime", month: 1, day: 1 },

  // ── Dandadan ──
  { name: "Momo Ayase", anime: "Dandadan", month: 3, day: 7 },
  { name: "Okarun (Ken Takakura)", anime: "Dandadan", month: 9, day: 9 },
  { name: "Aira Shiratori", anime: "Dandadan", month: 6, day: 21 },
  { name: "Jiji", anime: "Dandadan", month: 12, day: 12 },
  { name: "Turbo Granny", anime: "Dandadan", month: 5, day: 5 },

  // ── Solo Leveling ──
  { name: "Sung Jinwoo", anime: "Solo Leveling", month: 7, day: 9 },
  { name: "Cha Hae-In", anime: "Solo Leveling", month: 11, day: 15 },
  { name: "Go Gunhee", anime: "Solo Leveling", month: 3, day: 10 },
  { name: "Baek Yoonho", anime: "Solo Leveling", month: 9, day: 18 },
  { name: "Choi Jongin", anime: "Solo Leveling", month: 4, day: 26 },
  { name: "Yoo Jinho", anime: "Solo Leveling", month: 1, day: 28 },
  { name: "Thomas Andre", anime: "Solo Leveling", month: 5, day: 15 },
  { name: "Liu Zhigang", anime: "Solo Leveling", month: 10, day: 1 },
  { name: "Igris", anime: "Solo Leveling", month: 8, day: 8 },
  { name: "Beru", anime: "Solo Leveling", month: 6, day: 6 },

  // ── Frieren ──
  { name: "Frieren", anime: "Frieren: Beyond Journey's End", month: 1, day: 1 },
  { name: "Fern", anime: "Frieren: Beyond Journey's End", month: 9, day: 20 },
  { name: "Stark", anime: "Frieren: Beyond Journey's End", month: 4, day: 15 },
  { name: "Himmel", anime: "Frieren: Beyond Journey's End", month: 7, day: 14 },
  { name: "Heiter", anime: "Frieren: Beyond Journey's End", month: 3, day: 3 },
  { name: "Eisen", anime: "Frieren: Beyond Journey's End", month: 11, day: 11 },
  { name: "Serie", anime: "Frieren: Beyond Journey's End", month: 12, day: 31 },
  { name: "Ubel", anime: "Frieren: Beyond Journey's End", month: 6, day: 6 },
  { name: "Land", anime: "Frieren: Beyond Journey's End", month: 8, day: 20 },
  { name: "Laufen", anime: "Frieren: Beyond Journey's End", month: 2, day: 14 },

  // ── Oshi no Ko ──
  { name: "Aqua Hoshino", anime: "Oshi no Ko", month: 4, day: 12 },
  { name: "Ruby Hoshino", anime: "Oshi no Ko", month: 4, day: 12 },
  { name: "Ai Hoshino", anime: "Oshi no Ko", month: 1, day: 25 },
  { name: "Kana Arima", anime: "Oshi no Ko", month: 3, day: 17 },
  { name: "Akane Kurokawa", anime: "Oshi no Ko", month: 11, day: 23 },
  { name: "Mem-Cho", anime: "Oshi no Ko", month: 7, day: 7 },
  { name: "Miyako Saitou", anime: "Oshi no Ko", month: 8, day: 28 },
  { name: "Hikaru Kamiki", anime: "Oshi no Ko", month: 6, day: 6 },
  { name: "Gorou Amemiya", anime: "Oshi no Ko", month: 10, day: 3 },
  { name: "Frill Shiranui", anime: "Oshi no Ko", month: 5, day: 19 },


  // ── Berserk ──
  { name: "Guts", anime: "Berserk", month: 6, day: 12 },
  { name: "Griffith", anime: "Berserk", month: 2, day: 3 },
  { name: "Casca", anime: "Berserk", month: 6, day: 14 },
  { name: "Puck", anime: "Berserk", month: 5, day: 1 },
  { name: "Schierke", anime: "Berserk", month: 4, day: 18 },
  { name: "Serpico", anime: "Berserk", month: 9, day: 28 },
  { name: "Farnese", anime: "Berserk", month: 7, day: 6 },
  { name: "Skull Knight", anime: "Berserk", month: 1, day: 1 },
  { name: "Isidro", anime: "Berserk", month: 8, day: 25 },
  { name: "Rickert", anime: "Berserk", month: 3, day: 9 },
  { name: "Zodd", anime: "Berserk", month: 10, day: 31 },

  // ── Made in Abyss ──
  { name: "Riko", anime: "Made in Abyss", month: 9, day: 1 },
  { name: "Reg", anime: "Made in Abyss", month: 3, day: 20 },
  { name: "Nanachi", anime: "Made in Abyss", month: 12, day: 12 },
  { name: "Bondrewd", anime: "Made in Abyss", month: 5, day: 5 },
  { name: "Faputa", anime: "Made in Abyss", month: 8, day: 15 },
  { name: "Ozen", anime: "Made in Abyss", month: 2, day: 2 },

  // ── Mob Psycho (more) ──
  { name: "Tome Kurata", anime: "Mob Psycho 100", month: 12, day: 10 },
  { name: "Musashi Gouda", anime: "Mob Psycho 100", month: 6, day: 20 },

  // ── Kaguya-sama ──
  { name: "Kaguya Shinomiya", anime: "Kaguya-sama", month: 1, day: 1 },
  { name: "Miyuki Shirogane", anime: "Kaguya-sama", month: 9, day: 9 },
  { name: "Chika Fujiwara", anime: "Kaguya-sama", month: 3, day: 3 },
  { name: "Yu Ishigami", anime: "Kaguya-sama", month: 3, day: 3 },
  { name: "Ai Hayasaka", anime: "Kaguya-sama", month: 4, day: 2 },
  { name: "Miko Iino", anime: "Kaguya-sama", month: 2, day: 5 },
  { name: "Nagisa Kashiwagi", anime: "Kaguya-sama", month: 9, day: 17 },
  { name: "Kobachi Osaragi", anime: "Kaguya-sama", month: 8, day: 8 },

  // ── Bocchi the Rock ──
  { name: "Hitori Gotoh (Bocchi)", anime: "Bocchi the Rock", month: 2, day: 21 },
  { name: "Nijika Ijichi", anime: "Bocchi the Rock", month: 5, day: 29 },
  { name: "Ryo Yamada", anime: "Bocchi the Rock", month: 9, day: 18 },
  { name: "Ikuyo Kita", anime: "Bocchi the Rock", month: 4, day: 21 },
  { name: "Seika Ijichi", anime: "Bocchi the Rock", month: 10, day: 14 },
  { name: "Kikuri Hiroi", anime: "Bocchi the Rock", month: 12, day: 18 },

  // ── Rent-a-Girlfriend ──
  { name: "Kazuya Kinoshita", anime: "Rent-a-Girlfriend", month: 5, day: 5 },
  { name: "Chizuru Mizuhara", anime: "Rent-a-Girlfriend", month: 4, day: 19 },
  { name: "Mami Nanami", anime: "Rent-a-Girlfriend", month: 12, day: 16 },
  { name: "Ruka Sarashina", anime: "Rent-a-Girlfriend", month: 8, day: 26 },
  { name: "Sumi Sakurasawa", anime: "Rent-a-Girlfriend", month: 3, day: 20 },
  { name: "Mini Yaemori", anime: "Rent-a-Girlfriend", month: 7, day: 7 },

  // ── Jojo Part 6+ ──
  { name: "Ermes Costello", anime: "JoJo's Bizarre Adventure", month: 5, day: 11 },
  { name: "Weather Report", anime: "JoJo's Bizarre Adventure", month: 7, day: 3 },
  { name: "Foo Fighters", anime: "JoJo's Bizarre Adventure", month: 3, day: 3 },
  { name: "Emporio Alnino", anime: "JoJo's Bizarre Adventure", month: 7, day: 12 },
  { name: "Enrico Pucci", anime: "JoJo's Bizarre Adventure", month: 6, day: 5 },
  { name: "Pannacotta Fugo", anime: "JoJo's Bizarre Adventure", month: 4, day: 13 },

  // ── Classroom of the Elite ──
  { name: "Kiyotaka Ayanokoji", anime: "Classroom of the Elite", month: 10, day: 20 },
  { name: "Suzune Horikita", anime: "Classroom of the Elite", month: 2, day: 15 },
  { name: "Kikyo Kushida", anime: "Classroom of the Elite", month: 1, day: 23 },
  { name: "Kei Karuizawa", anime: "Classroom of the Elite", month: 4, day: 8 },
  { name: "Arisu Sakayanagi", anime: "Classroom of the Elite", month: 3, day: 12 },
  { name: "Kakeru Ryuen", anime: "Classroom of the Elite", month: 10, day: 25 },
  { name: "Honami Ichinose", anime: "Classroom of the Elite", month: 9, day: 13 },
  { name: "Manabu Horikita", anime: "Classroom of the Elite", month: 7, day: 13 },
  { name: "Yosuke Hirata", anime: "Classroom of the Elite", month: 4, day: 15 },
  { name: "Sae Chabashira", anime: "Classroom of the Elite", month: 1, day: 1 },


  // ── Bungo Stray Dogs ──
  { name: "Atsushi Nakajima", anime: "Bungo Stray Dogs", month: 5, day: 5 },
  { name: "Osamu Dazai", anime: "Bungo Stray Dogs", month: 6, day: 19 },
  { name: "Doppo Kunikida", anime: "Bungo Stray Dogs", month: 8, day: 30 },
  { name: "Ranpo Edogawa", anime: "Bungo Stray Dogs", month: 10, day: 21 },
  { name: "Akiko Yosano", anime: "Bungo Stray Dogs", month: 12, day: 7 },
  { name: "Kenji Miyazawa", anime: "Bungo Stray Dogs", month: 8, day: 27 },
  { name: "Chuya Nakahara", anime: "Bungo Stray Dogs", month: 4, day: 29 },
  { name: "Ryunosuke Akutagawa", anime: "Bungo Stray Dogs", month: 3, day: 1 },
  { name: "Kyouka Izumi", anime: "Bungo Stray Dogs", month: 11, day: 4 },
  { name: "Fukuzawa Yukichi", anime: "Bungo Stray Dogs", month: 1, day: 10 },
  { name: "Mori Ougai", anime: "Bungo Stray Dogs", month: 2, day: 17 },
  { name: "Fyodor Dostoevsky", anime: "Bungo Stray Dogs", month: 11, day: 11 },
  { name: "Sigma", anime: "Bungo Stray Dogs", month: 7, day: 7 },
  { name: "Nikolai Gogol", anime: "Bungo Stray Dogs", month: 4, day: 1 },

  // ── Wind Breaker ──
  { name: "Haruka Sakura", anime: "Wind Breaker", month: 4, day: 3 },
  { name: "Akihiko Nirei", anime: "Wind Breaker", month: 8, day: 15 },
  { name: "Hayato Suo", anime: "Wind Breaker", month: 3, day: 3 },
  { name: "Tasuku Kaji", anime: "Wind Breaker", month: 6, day: 20 },
  { name: "Ren Kaji", anime: "Wind Breaker", month: 10, day: 10 },
  { name: "Hiragi Toma", anime: "Wind Breaker", month: 12, day: 1 },
  { name: "Togame Jo", anime: "Wind Breaker", month: 5, day: 15 },
  { name: "Umemiya Hajime", anime: "Wind Breaker", month: 9, day: 9 },

  // ── Mashle ──
  { name: "Mash Burnedead", anime: "Mashle", month: 3, day: 3 },
  { name: "Finn Ames", anime: "Mashle", month: 7, day: 14 },
  { name: "Lance Crown", anime: "Mashle", month: 11, day: 17 },
  { name: "Dot Barrett", anime: "Mashle", month: 5, day: 8 },
  { name: "Lemon Irvine", anime: "Mashle", month: 9, day: 3 },
  { name: "Rayne Ames", anime: "Mashle", month: 12, day: 15 },
  { name: "Abel Walker", anime: "Mashle", month: 2, day: 14 },
  { name: "Innocent Zero", anime: "Mashle", month: 1, day: 1 },

  // ── Spy x Family (more) ──
  { name: "Donovan Desmond", anime: "Spy x Family", month: 1, day: 1 },
  { name: "Sylvia Sherwood", anime: "Spy x Family", month: 8, day: 25 },

  // ── Hell's Paradise ──
  { name: "Gabimaru", anime: "Hell's Paradise", month: 1, day: 5 },
  { name: "Sagiri Yamada Asaemon", anime: "Hell's Paradise", month: 3, day: 7 },
  { name: "Yuzuriha", anime: "Hell's Paradise", month: 6, day: 23 },
  { name: "Chobe", anime: "Hell's Paradise", month: 9, day: 14 },
  { name: "Shion Yamada Asaemon", anime: "Hell's Paradise", month: 11, day: 1 },
  { name: "Nurugai", anime: "Hell's Paradise", month: 4, day: 20 },
  { name: "Tensen (Rien)", anime: "Hell's Paradise", month: 8, day: 8 },

  // ── Undead Unluck ──
  { name: "Fuuko Izumo", anime: "Undead Unluck", month: 11, day: 6 },
  { name: "Andy (Victor)", anime: "Undead Unluck", month: 8, day: 8 },
  { name: "Shen", anime: "Undead Unluck", month: 5, day: 1 },
  { name: "Tatiana", anime: "Undead Unluck", month: 2, day: 22 },
  { name: "Juiz", anime: "Undead Unluck", month: 1, day: 1 },
  { name: "Top", anime: "Undead Unluck", month: 7, day: 4 },

  // ── My Dress-Up Darling ──
  { name: "Marin Kitagawa", anime: "My Dress-Up Darling", month: 3, day: 5 },
  { name: "Wakana Gojo", anime: "My Dress-Up Darling", month: 3, day: 21 },
  { name: "Sajuna Inui", anime: "My Dress-Up Darling", month: 10, day: 10 },
  { name: "Shinju Inui", anime: "My Dress-Up Darling", month: 10, day: 10 },

  // ── Kaiju No. 8 ──
  { name: "Kafka Hibino", anime: "Kaiju No. 8", month: 8, day: 5 },
  { name: "Mina Ashiro", anime: "Kaiju No. 8", month: 12, day: 1 },
  { name: "Reno Ichikawa", anime: "Kaiju No. 8", month: 6, day: 6 },
  { name: "Kikoru Shinomiya", anime: "Kaiju No. 8", month: 3, day: 16 },
  { name: "Soshiro Hoshina", anime: "Kaiju No. 8", month: 10, day: 1 },
  { name: "Gen Narumi", anime: "Kaiju No. 8", month: 4, day: 15 },
  { name: "Leno Ichikawa", anime: "Kaiju No. 8", month: 6, day: 6 },


  // ── Food Wars ──
  { name: "Soma Yukihira", anime: "Food Wars", month: 11, day: 6 },
  { name: "Erina Nakiri", anime: "Food Wars", month: 3, day: 23 },
  { name: "Megumi Tadokoro", anime: "Food Wars", month: 12, day: 19 },
  { name: "Takumi Aldini", anime: "Food Wars", month: 7, day: 10 },
  { name: "Ryo Kurokiba", anime: "Food Wars", month: 1, day: 5 },
  { name: "Alice Nakiri", anime: "Food Wars", month: 4, day: 9 },
  { name: "Akira Hayama", anime: "Food Wars", month: 9, day: 12 },
  { name: "Satoshi Isshiki", anime: "Food Wars", month: 2, day: 2 },

  // ── Eminence in Shadow ──
  { name: "Cid Kagenou (Shadow)", anime: "The Eminence in Shadow", month: 10, day: 10 },
  { name: "Alpha", anime: "The Eminence in Shadow", month: 3, day: 14 },
  { name: "Beta", anime: "The Eminence in Shadow", month: 7, day: 7 },
  { name: "Delta", anime: "The Eminence in Shadow", month: 9, day: 9 },
  { name: "Epsilon", anime: "The Eminence in Shadow", month: 1, day: 1 },
  { name: "Gamma", anime: "The Eminence in Shadow", month: 5, day: 5 },
  { name: "Zeta", anime: "The Eminence in Shadow", month: 11, day: 11 },
  { name: "Claire Kagenou", anime: "The Eminence in Shadow", month: 12, day: 12 },
  { name: "Alexia Midgar", anime: "The Eminence in Shadow", month: 6, day: 14 },
  { name: "Rose Oriana", anime: "The Eminence in Shadow", month: 8, day: 20 },

  // ── Quintessential Quintuplets ──
  { name: "Ichika Nakano", anime: "Quintessential Quintuplets", month: 5, day: 5 },
  { name: "Nino Nakano", anime: "Quintessential Quintuplets", month: 5, day: 5 },
  { name: "Miku Nakano", anime: "Quintessential Quintuplets", month: 5, day: 5 },
  { name: "Yotsuba Nakano", anime: "Quintessential Quintuplets", month: 5, day: 5 },
  { name: "Itsuki Nakano", anime: "Quintessential Quintuplets", month: 5, day: 5 },
  { name: "Futaro Uesugi", anime: "Quintessential Quintuplets", month: 4, day: 15 },

  // ── Horimiya ──
  { name: "Kyoko Hori", anime: "Horimiya", month: 3, day: 25 },
  { name: "Izumi Miyamura", anime: "Horimiya", month: 4, day: 17 },
  { name: "Tooru Ishikawa", anime: "Horimiya", month: 11, day: 28 },
  { name: "Yuki Yoshikawa", anime: "Horimiya", month: 5, day: 22 },
  { name: "Kakeru Sengoku", anime: "Horimiya", month: 8, day: 14 },
  { name: "Remi Ayasaki", anime: "Horimiya", month: 12, day: 24 },
  { name: "Sakura Kouno", anime: "Horimiya", month: 3, day: 30 },
  { name: "Sota Hori", anime: "Horimiya", month: 9, day: 29 },

  // ── Lycoris Recoil ──
  { name: "Chisato Nishikigi", anime: "Lycoris Recoil", month: 9, day: 23 },
  { name: "Takina Inoue", anime: "Lycoris Recoil", month: 7, day: 27 },
  { name: "Kurumi", anime: "Lycoris Recoil", month: 4, day: 10 },
  { name: "Mika", anime: "Lycoris Recoil", month: 1, day: 15 },
  { name: "Majima", anime: "Lycoris Recoil", month: 8, day: 8 },
  { name: "Fuki Harukawa", anime: "Lycoris Recoil", month: 6, day: 2 },

  // ── Darling in the Franxx ──
  { name: "Zero Two", anime: "Darling in the Franxx", month: 2, day: 27 },
  { name: "Hiro (Code 016)", anime: "Darling in the Franxx", month: 10, day: 15 },
  { name: "Ichigo (Code 015)", anime: "Darling in the Franxx", month: 3, day: 15 },
  { name: "Goro (Code 056)", anime: "Darling in the Franxx", month: 9, day: 5 },
  { name: "Miku (Code 390)", anime: "Darling in the Franxx", month: 6, day: 6 },
  { name: "Kokoro (Code 556)", anime: "Darling in the Franxx", month: 11, day: 1 },
  { name: "Mitsuru (Code 326)", anime: "Darling in the Franxx", month: 12, day: 20 },

  // ── Miscellaneous popular characters ──
  { name: "Saber (Artoria Pendragon)", anime: "Fate/Stay Night", month: 8, day: 15 },
  { name: "Emiya Shirou", anime: "Fate/Stay Night", month: 5, day: 12 },
  { name: "Rin Tohsaka", anime: "Fate/Stay Night", month: 2, day: 3 },
  { name: "Archer (EMIYA)", anime: "Fate/Stay Night", month: 5, day: 12 },
  { name: "Gilgamesh", anime: "Fate/Stay Night", month: 4, day: 4 },
  { name: "Sakura Matou", anime: "Fate/Stay Night", month: 3, day: 2 },
  { name: "Lancer (Cu Chulainn)", anime: "Fate/Stay Night", month: 6, day: 6 },
  { name: "Rider (Medusa)", anime: "Fate/Stay Night", month: 1, day: 1 },
  { name: "Waver Velvet", anime: "Fate/Zero", month: 10, day: 3 },
  { name: "Iskandar (Alexander)", anime: "Fate/Zero", month: 7, day: 20 },

  // ── Demon Slayer (Lower Moons) ──
  { name: "Kamanue", anime: "Demon Slayer", month: 2, day: 5 },
  { name: "Mukago", anime: "Demon Slayer", month: 6, day: 19 },
  { name: "Wakuraba", anime: "Demon Slayer", month: 10, day: 22 },

  // ── Mob Psycho 100 (more) ──
  { name: "Body Improvement Club Captain", anime: "Mob Psycho 100", month: 4, day: 10 },
  { name: "Teru's rival Shimazaki", anime: "Mob Psycho 100", month: 8, day: 1 },

  // ── Dororo (more) ──
  { name: "Tahomaru", anime: "Dororo", month: 3, day: 16 },
  { name: "Nui no Kata", anime: "Dororo", month: 7, day: 22 },

  // ── Samurai Champloo ──
  { name: "Mugen", anime: "Samurai Champloo", month: 11, day: 11 },
  { name: "Jin", anime: "Samurai Champloo", month: 6, day: 2 },
  { name: "Fuu", anime: "Samurai Champloo", month: 8, day: 19 },

  // ── Yu Yu Hakusho ──
  { name: "Yusuke Urameshi", anime: "Yu Yu Hakusho", month: 3, day: 26 },
  { name: "Kazuma Kuwabara", anime: "Yu Yu Hakusho", month: 4, day: 21 },
  { name: "Kurama", anime: "Yu Yu Hakusho", month: 3, day: 4 },
  { name: "Hiei", anime: "Yu Yu Hakusho", month: 7, day: 18 },
  { name: "Genkai", anime: "Yu Yu Hakusho", month: 1, day: 23 },
  { name: "Botan", anime: "Yu Yu Hakusho", month: 2, day: 5 },
  { name: "Keiko Yukimura", anime: "Yu Yu Hakusho", month: 1, day: 31 },
  { name: "Toguro (Younger)", anime: "Yu Yu Hakusho", month: 9, day: 13 },
  { name: "Sensui Shinobu", anime: "Yu Yu Hakusho", month: 6, day: 6 },
  { name: "Yukina", anime: "Yu Yu Hakusho", month: 1, day: 20 },
  { name: "Koenma", anime: "Yu Yu Hakusho", month: 4, day: 9 },
  { name: "Shizuru Kuwabara", anime: "Yu Yu Hakusho", month: 12, day: 11 },

  // ── Rurouni Kenshin ──
  { name: "Kenshin Himura", anime: "Rurouni Kenshin", month: 6, day: 20 },
  { name: "Kaoru Kamiya", anime: "Rurouni Kenshin", month: 6, day: 4 },
  { name: "Sanosuke Sagara", anime: "Rurouni Kenshin", month: 2, day: 14 },
  { name: "Yahiko Myojin", anime: "Rurouni Kenshin", month: 3, day: 7 },
  { name: "Makoto Shishio", anime: "Rurouni Kenshin", month: 8, day: 8 },
  { name: "Hajime Saito", anime: "Rurouni Kenshin", month: 1, day: 1 },
  { name: "Aoshi Shinomori", anime: "Rurouni Kenshin", month: 1, day: 17 },
  { name: "Megumi Takani", anime: "Rurouni Kenshin", month: 12, day: 16 },
  { name: "Misao Makimachi", anime: "Rurouni Kenshin", month: 11, day: 2 },
  { name: "Enishi Yukishiro", anime: "Rurouni Kenshin", month: 6, day: 26 },
  { name: "Tomoe Yukishiro", anime: "Rurouni Kenshin", month: 8, day: 28 },

  // ── Soul Eater ──
  { name: "Maka Albarn", anime: "Soul Eater", month: 5, day: 5 },
  { name: "Soul Evans", anime: "Soul Eater", month: 6, day: 1 },
  { name: "Black Star", anime: "Soul Eater", month: 2, day: 22 },
  { name: "Tsubaki Nakatsukasa", anime: "Soul Eater", month: 5, day: 18 },
  { name: "Death the Kid", anime: "Soul Eater", month: 8, day: 8 },
  { name: "Liz Thompson", anime: "Soul Eater", month: 1, day: 10 },
  { name: "Patty Thompson", anime: "Soul Eater", month: 1, day: 10 },
  { name: "Crona", anime: "Soul Eater", month: 11, day: 20 },
  { name: "Spirit Albarn", anime: "Soul Eater", month: 4, day: 13 },
  { name: "Franken Stein", anime: "Soul Eater", month: 9, day: 1 },
  { name: "Excalibur", anime: "Soul Eater", month: 7, day: 7 },
  { name: "Medusa Gorgon", anime: "Soul Eater", month: 3, day: 30 },

  // ── Naruto (more) ──
  { name: "Tenten", anime: "Naruto", month: 3, day: 9 },
  { name: "Danzo Shimura", anime: "Naruto", month: 1, day: 6 },
  { name: "Shisui Uchiha", anime: "Naruto", month: 10, day: 19 },
  { name: "Haku", anime: "Naruto", month: 1, day: 9 },
  { name: "Zabuza Momochi", anime: "Naruto", month: 8, day: 15 },
  { name: "Chiyo", anime: "Naruto", month: 10, day: 15 },
  { name: "Killer Bee", anime: "Naruto", month: 5, day: 15 },
  { name: "A (Fourth Raikage)", anime: "Naruto", month: 6, day: 1 },
  { name: "Mei Terumi", anime: "Naruto", month: 5, day: 21 },
  { name: "Onoki", anime: "Naruto", month: 10, day: 22 },
  { name: "Nagato (Pain)", anime: "Naruto", month: 9, day: 19 },
  { name: "Yahiko", anime: "Naruto", month: 2, day: 20 },
  { name: "Hanabi Hyuga", anime: "Naruto", month: 3, day: 27 },
  { name: "Toneri Otsutsuki", anime: "Naruto", month: 10, day: 10 },
  { name: "Kaguya Otsutsuki", anime: "Naruto", month: 8, day: 15 },

  // ── Tokyo Revengers (more) ──
  { name: "Mitsuya Takashi", anime: "Tokyo Revengers", month: 6, day: 12 },
  { name: "Hakkai Shiba", anime: "Tokyo Revengers", month: 11, day: 11 },
  { name: "Peh-yan", anime: "Tokyo Revengers", month: 4, day: 2 },
  { name: "Pah-chin", anime: "Tokyo Revengers", month: 8, day: 18 },
  { name: "Inui Seishu", anime: "Tokyo Revengers", month: 10, day: 18 },
  { name: "Kokonoi Hajime", anime: "Tokyo Revengers", month: 1, day: 20 },
  { name: "Sanzu Haruchiyo", anime: "Tokyo Revengers", month: 6, day: 8 },
  { name: "Ran Haitani", anime: "Tokyo Revengers", month: 4, day: 25 },
  { name: "Rindo Haitani", anime: "Tokyo Revengers", month: 10, day: 7 },
  { name: "Wakasa Imaushi", anime: "Tokyo Revengers", month: 7, day: 15 },
  { name: "Shinichiro Sano", anime: "Tokyo Revengers", month: 1, day: 28 },
  { name: "Emma Sano", anime: "Tokyo Revengers", month: 11, day: 25 },

  // ── Dragon Ball (more) ──
  { name: "Gotenks", anime: "Dragon Ball", month: 8, day: 1 },
  { name: "Android 21", anime: "Dragon Ball", month: 5, day: 21 },
  { name: "Caulifla", anime: "Dragon Ball", month: 7, day: 16 },
  { name: "Kale", anime: "Dragon Ball", month: 7, day: 16 },
  { name: "Cabba", anime: "Dragon Ball", month: 3, day: 3 },
  { name: "Champa", anime: "Dragon Ball", month: 2, day: 12 },
  { name: "Vados", anime: "Dragon Ball", month: 9, day: 27 },
  { name: "Toppo", anime: "Dragon Ball", month: 6, day: 23 },
  { name: "Goku Black", anime: "Dragon Ball", month: 10, day: 16 },
  { name: "Zamasu", anime: "Dragon Ball", month: 10, day: 16 },
  { name: "Launch", anime: "Dragon Ball", month: 3, day: 19 },
  { name: "Chiaotzu", anime: "Dragon Ball", month: 1, day: 3 },
  { name: "Oolong", anime: "Dragon Ball", month: 4, day: 22 },

  // ── Katekyo Hitman Reborn ──
  { name: "Tsunayoshi Sawada", anime: "Katekyo Hitman Reborn", month: 10, day: 14 },
  { name: "Reborn", anime: "Katekyo Hitman Reborn", month: 10, day: 13 },
  { name: "Hayato Gokudera", anime: "Katekyo Hitman Reborn", month: 9, day: 9 },
  { name: "Takeshi Yamamoto", anime: "Katekyo Hitman Reborn", month: 4, day: 24 },
  { name: "Kyoya Hibari", anime: "Katekyo Hitman Reborn", month: 5, day: 5 },
  { name: "Mukuro Rokudo", anime: "Katekyo Hitman Reborn", month: 6, day: 9 },
  { name: "Chrome Dokuro", anime: "Katekyo Hitman Reborn", month: 12, day: 5 },
  { name: "Lambo", anime: "Katekyo Hitman Reborn", month: 5, day: 28 },
  { name: "Ryohei Sasagawa", anime: "Katekyo Hitman Reborn", month: 8, day: 26 },
  { name: "Xanxus", anime: "Katekyo Hitman Reborn", month: 10, day: 10 },
  { name: "Dino Cavallone", anime: "Katekyo Hitman Reborn", month: 2, day: 4 },
  { name: "Byakuran", anime: "Katekyo Hitman Reborn", month: 11, day: 28 },
];

export default CHARACTER_BIRTHDAYS;
